## 04. scratchpad

### 1. Data Upload

In [567]:
import pandas as pd
import os
from collections import defaultdict, Counter
import re
import time
from tqdm.notebook import tqdm
import copy

In [2]:
def upload_to_dataframe(root, files, num_lines):
    path_eng, path_pol = [root+f for f in files]
    data = defaultdict(list)
    
    with open (path_eng, encoding="utf_8") as f_eng, open (path_pol, encoding="utf_8") as f_pol:
        for _ in range(num_lines):
            data['eng_text'].append(f_eng.readline().strip())
            data['pol_text'].append(f_pol.readline().strip())
    return pd.DataFrame(data)

In [3]:
root = "../data/opus_opensub/en-pl.txt/"
files = ('OpenSubtitles.en-pl.en', '/OpenSubtitles.en-pl.pl')
df = upload_to_dataframe(root, files, 600000)

### 2. EDA & Sanitazation

#### 2.1 English Non-Ascii Sentences

In [4]:
def nonascii_list(df_series, is_pol):
    if is_pol:
        pl_chars = set("ąęćłńóśźżĄĘĆŁŃÓŚŹŻ")
        requir = lambda x: x.isascii() or x in pl_chars
    else:
        requir = lambda x: x.isascii()
        
    text_all = ''.join(df_series)
    unique_dct = {x for x in text_all if not requir(x)}
    return sorted(list(unique_dct))

In [5]:
print(nonascii_list(df['eng_text'], False))

['\x80', '\x81', '\x82', '\x83', '\x84', '\x85', '\x88', '\x8b', '\x8c', '\x8e', '\x8f', '\x91', '\x94', '\x96', '\x98', '\x99', '\x9c', '\x9d', '\xa0', '¡', '¢', '£', '¤', '¥', '¦', '§', '¨', '©', 'ª', '¬', '\xad', '°', '±', '²', '³', '´', 'µ', '¶', '·', '¸', '¹', 'º', '¼', '½', '¾', '¿', 'Á', 'Â', 'Ã', 'Ä', 'Å', 'Ç', 'É', 'Ê', 'Ì', 'Ï', 'Ð', 'Ñ', 'Ô', 'Ö', 'Ø', 'Ü', 'Ý', 'Þ', 'ß', 'à', 'á', 'â', 'ã', 'ä', 'å', 'ç', 'è', 'é', 'ê', 'ì', 'í', 'î', 'ï', 'ð', 'ñ', 'ó', 'ô', 'ö', 'ù', 'ú', 'û', 'ü', 'ý', 'þ', 'Ă', 'ď', 'ę', 'Ł', 'ń', 'ő', 'œ', 'ś', 'Š', 'š', 'Ј', 'С', 'й', '،', 'أ', 'إ', 'ئ', 'ا', 'ب', 'ة', 'ت', 'ح', 'ر', 'س', 'ش', 'ع', 'غ', 'ف', 'ك', 'ل', 'م', 'ن', 'و', 'ي', 'َ', 'ُ', 'ِ', 'ّ', 'ْ', '\u200b', '‒', '–', '—', '‚', '€', '™', '─', '☻', '♥', '♪', '慹', '拢', '檛', '鈥', 'ﬁ', 'ﬂ']

In [6]:
is_ascii = lambda text: text.isascii()
maska = df['eng_text'].apply(is_ascii)
df_non_ascii = df[~maska].copy().reset_index(drop=True)
print(df_non_ascii.shape)
df_non_ascii.head()

(4595, 2)

,eng_text,pol_text
0,¿You had never seen A crab suedes? Them there ...,- Nigdy wcześniej nie widziałaś raków?
1,"He hears ¿, where you live?",Nigdy wcześniej nie byłam w lesie.
2,"Boys ¿, they are there?",Jesteście tam chłopaki?
3,- Te atrapé. - No es gracioso. Your he catches...,- Ale twoje mina była.
4,"Your also ¿, it is not like that?","- Tak, niezła jest"

In [7]:
df_2 = df[maska].reset_index(drop=True)
df_2.shape

(595405, 2)

#### 2.2 Polish Non-Ascii Sentences

In [8]:
pl_chars = set("ąęćłńóśźżĄĘĆŁŃÓŚŹŻ")
requir = lambda let: not let.isascii() and let not in pl_chars
maska = df_2['pol_text'].apply(lambda snt: any([requir(let) for let in snt]))
df_non_ascii = df_2[maska].copy().reset_index(drop=True)
print(df_non_ascii.shape)
df_non_ascii.sample(10)

(1227, 2)

,eng_text,pol_text
170,"We're going back by water, Kali, using Mr. Tho...","Wracamy drogą wodną, Kalí, czółnem pana Thornt..."
1162,"Yes, a walk up the avenue's What we'll take",¶ Więc idziemy sobie ulicą ¶ Aż dotrzemy kiedy...
651,"If you like business, you can pick any job and...","Ješli tak, može pan sobie zajac dowolnie wybra..."
423,He and his little four page paper against that...,Czterostronnicowa broszura przeciwko syndykato...
734,I did not say that Senator Paine was one of th...,"Nie powiedzialem, že jednym z nich byl senator..."
130,""""" Tis a pity that some of our compatriots are...","""Szkoda, że ​​niektórzy z naszych rodaków... s..."
916,She sure made this disappearance act look good.,Z pewnością ​​ten akt zniknięcia wyglądał dobrze.
703,You can't quit now.,Nie možesz teraz odjesc.
1103,The fella with an umbrella,¶ Facetowi z parasolem
1206,And you'll find that you're In the rotogravure,¶ I zobaczysz siebie w gazetach

In [9]:
df_3 = df_2[~maska].reset_index(drop=True)
print(df_3.shape)
df_3.sample(5)

(594178, 2)

,eng_text,pol_text
406669,It was her laugh in the gallery that woke me.,To jej śmiech w galerii mnie obudził.
392337,But you better keep an eye out for rattlers an...,"Ale uważaj na grzechotniki , kojoty i skunksy."
456792,See you tomorrow.,Do jutra.
210340,"Henry Higgins, do you see this?","Henry Higgins, Widzisz?"
214672,"Here, here.","Hej, hej."

In [10]:
print(nonascii_list(df_3['eng_text'], False))
print(nonascii_list(df_3['pol_text'], True))

[]
[]

In [11]:
df_3.iloc[74182]['eng_text']

'The next time I...'

In [12]:
df_3.iloc[74182]['pol_text']

'Następnym razem...'

#### 2.3 Short Or Empty Examples

In [13]:
mask1 = df_3['eng_text'].str.len() >= 3
mask2 = df_3['pol_text'].str.len() >= 3

In [14]:
df_4 = df_3[mask1 & mask2].reset_index(drop=True)
df_4.head()

,eng_text,pol_text
0,"Previously on ""The Blacklist""...",/W poprzednich odcinkach: /
1,- You want to call your daddy?,- Chcesz zadzwonić do taty?
2,"- Yeah, I want to tell him I'm okay.","- Tak, powiem, że wszystko w porządku."
3,Okay.,Dobrze.
4,Lizzy... Be careful of your husband.,"Lizzy, uważaj na męża."

In [15]:
df_4.shape

(593894, 2)

#### 2.4 Dialog like sentences [starts with - ]

In [16]:
is_dialog = lambda snt: bool(re.match(r"^ *- *", snt))
mask = df_4['eng_text'].apply(is_dialog) | df_4['pol_text'].apply(is_dialog)
df_dialogs = df_4[mask].copy().reset_index(drop=True)
df_dialogs.head()

,eng_text,pol_text
0,- You want to call your daddy?,- Chcesz zadzwonić do taty?
1,"- Yeah, I want to tell him I'm okay.","- Tak, powiem, że wszystko w porządku."
2,- 45 seconds.,Szybciej! 45 sekund.
3,It's okay. It's okay. It's okay.,- Już dobrze.
4,It's okay. You're okay. You're okay.,- Odpoczywaj.

In [17]:
def fix_dialog(snt):
    return re.sub(r"^ *- *", "", snt)

df_4['eng_text'] = df_4['eng_text'].apply(fix_dialog).reset_index(drop=True)
df_4['pol_text'] = df_4['pol_text'].apply(fix_dialog).reset_index(drop=True)
df_4.sample(5)

,eng_text,pol_text
377519,"It's that rubber band. Pulaski's, I'd know it ...",Wszędzie poznałbym tę gumkę od Pułaskiej.
274008,What? - You`d better get on the roof.,Wchodźcie obydwaj na dach!
147926,That's awful pretty.,To jest piękne.
345672,"Oh, a little of this, a little of that. Not mu...","Trochę tego, trochę tamtego, ale niewiele czeg..."
420191,Didn't he give you his name?,Nie podał imienia?

#### 2.5 Broken Dialog like sentences [somehwere has -]

# Do naprawy (lepszy re przed tokenziacja)

In [18]:
broken_dialog = lambda snt: bool(re.match(r".* +- +.*", snt))
mask1 = df_4['eng_text'].apply(broken_dialog)
mask2 = df_4['pol_text'].apply(broken_dialog)

In [19]:
df_4[mask1 | mask2].sample(5)

,eng_text,pol_text
508203,Not bad. - With bath?,"Ani tu dobrze, ani źle."
242568,Silly of me - I adore youth!,Głupio z mojej strony - uwielbiam młodość.
532936,"Not a trace of them, sir. - We're searching-","Nie ma po nich śladu, sir."
508437,All he wanted was for me to get his girl out o...,"Chciał, żebym wydostał jego dziewczynę z więzi..."
157689,I've got everything fixed up now for an attack...,Mam wszystko przygotowane do ataku na Floss Va...

In [20]:
df_5 = df_4[~mask1 & ~mask2].reset_index(drop=True)

In [21]:
broken_dialog = lambda snt: bool(re.match(r".*-.*", snt))

In [22]:
df_5.sample(5)

,eng_text,pol_text
61228,You know what men are like on a Saturday.,"Wiesz, jak to jest w soboty z mężczyznami."
432733,Right.,Zgoda.
55580,"Now, let's talk about you.",A teraz pomówmy trochę o tobie.
43646,WE'LL HAVE TO STOP AND GET MY THINGS.,Musimy się zatrzymać i zabrać moje rzeczy.
260663,"Oh, this is something different.","O, to co innego."

#### 2.6 Different Last Case

In [23]:
mask = df_5['eng_text'].str[-1] != df_5['pol_text'].str[-1]
mask.sum()

57558

In [24]:
df_6 = df_5[~mask].reset_index(drop=True)

#### 2.7 Text length difference

In [25]:
mask = df_6['eng_text'].str.split
df_6['len_ratio'] = df_6['eng_text'].str.split().str.len() / df_6['pol_text'].str.split().str.len()
df_6.head()

,eng_text,pol_text,len_ratio
0,You want to call your daddy?,Chcesz zadzwonić do taty?,1.500000
1,"Yeah, I want to tell him I'm okay.","Tak, powiem, że wszystko w porządku.",1.333333
2,Okay.,Dobrze.,1.000000
3,Lizzy... Be careful of your husband.,"Lizzy, uważaj na męża.",1.500000
4,I can only lead you to the truth.,/Mogę naprowadzić cię na prawdę.,1.600000

In [26]:
thres_left = df_6["len_ratio"].quantile(0.05)
thres_right = df_6["len_ratio"].quantile(0.95)
thres_left, thres_right

(0.75, 2.5)

In [27]:
mask = (df_6["len_ratio"] >= thres_left) & (df_6["len_ratio"] <= thres_right)
mask.sum()

472209

In [28]:
df_7 = df_6[mask].reset_index(drop=True)
df_7.sample(5)

,eng_text,pol_text,len_ratio
164175,"In Heaven's name, why?","Na niebiosa, dlaczego?",1.333333
359981,"Sloan, keep out of this.",Nie mieszaj się do tego.,1.000000
197603,You try to ruin my business?,Chcesz zrujnować mój interes?,1.500000
62736,I was going to say it a little further along.,Chciałem to powiedzieć nieco później.,2.000000
215229,"Would you say a few words, Casy?","Może powiesz parę słów, Casy?",1.400000

In [29]:
df_7.sample(5)

,eng_text,pol_text,len_ratio
375375,I have seen it in the newspaper. Who beat Chue...,To pan pokonał pana Chuen w zawodach policji.,1.75
244631,Which way has the slave taken?,Jaką drogę obrał niewolnik?,1.50
311414,"I've heard of you, Monsieur Inspector.","Słyszałem o panu, inspektorze.",1.50
313327,A photographic ship accompanies missions to Ki...,W lotach nad Kiską bombowcom towarzyszy samolo...,0.88
446360,"Well, let's go.",No to jedźmy.,1.00

#### 2.8 Sentences starting with * fix

In [30]:
fix_star = lambda snt: re.sub(r"^ *[*].*", "", snt)
df_7['eng_text'] = df_7['eng_text'].apply(fix_star)
df_7['pol_text'] = df_7['pol_text'].apply(fix_star)

#### 2.9 Action Comments

In [31]:
def mask_distinct(df, col1, col2, chars):
    chars_escaped = "".join(re.escape(c) for c in chars)
    templ = f"[{chars_escaped}]"

    m1 = df[col1].str.contains(templ, regex=True, na=False)
    m2 = df[col2].str.contains(templ, regex=True, na=False)

    return m1 ^ m2

chars = '[]()/\*+#$"️'
mask = mask_distinct(df_7, "eng_text", "pol_text", chars)

df_8 = df_7[~mask].reset_index(drop=True)
df_8.shape

(467550, 3)

In [32]:
df_8.sample(5)

,eng_text,pol_text,len_ratio
324578,"With love, Gloria.","Pozdrowienia, Gloria.",1.500000
318905,It is a school for unfortunate orphans.,To jest szkoła dla nieszczęśliwych sierot.,1.166667
122691,"Van, come home.","Van, wróć do domu.",0.750000
365856,No.,Nie.,1.000000
277049,Go back and wait.,Poczekaj tam na mnie.,1.000000

#### 2.10  " ` " ---> " ' " & del " ~ "

In [33]:
wanted_case = '`'
mask = df_8["eng_text"].apply(lambda x: wanted_case in x)
df_8[mask]

,eng_text,pol_text,len_ratio
214145,"Revolution had broken out, her diplomats sued ...","Rewolucja na tyłach frontu, dąży do zawarcia p...",1.277778
214152,We`ll examine it.,Zbadajmy go.,1.500000
214157,What do you think you`re doing?,Wstawaj! Co ty robisz?,1.500000
214161,Where`s your hand grenade?,Gdzie masz swój granat?,1.000000
214163,Let `em have it!,Niech je poczują!,1.333333
...,...,...,...
214943,We don`t want to hate one another.,Bez nienawiści ani pogardy.,1.750000
214944,There`s room for everyone.,Każdy ma swe miejsce.,1.000000
214947,"Greed has poisoned men`s souls, has barricaded...","Chciwość zatruła nasze dusze, wzniosła mury ni...",1.333333
214963,You don`t hate.,Przestańcie nienawidzieć.,1.500000
214965,"Soldiers, don`t fight for slavery, fight for l...","Nie walczcie o niewolę, lecz o wolność!",1.142857

In [34]:
df_8["eng_text"] = df_8["eng_text"].str.replace("`", "'", regex=False)
df_8["pol_text"] = df_8["pol_text"].str.replace("`", "'", regex=False)

In [35]:
df_8["eng_text"] = df_8["eng_text"].str.replace("~", "", regex=False)
df_8["pol_text"] = df_8["pol_text"].str.replace("~", "", regex=False)

#### 2.11 Del rows with specific case

In [36]:
def del_row_with_char(df, eng_col, pol_col, chars):
    df_proc = df.copy()
    for char in chars:
        mask1 = df_proc[eng_col].apply(lambda x: char in x)
        mask2 = df_proc[pol_col].apply(lambda x: char in x)
        df_proc = df_proc[~(mask1 | mask2)].reset_index(drop=True)
    return df_proc
    

chars = "=+*@#;|_}{"
df_9 = del_row_with_char(df_8, "eng_text", "pol_text", chars)

#### 2.12 Del rows with dialog -

In [37]:
mask1 = df_9["eng_text"].apply(lambda x: bool(re.search(r' +-[^ ]+', x)))
mask2 = df_9["pol_text"].apply(lambda x: bool(re.search(r' +-[^ ]+', x)))
df_data = df_9[~(mask1 | mask2)].reset_index(drop=True)

#### 3. Data Tokenization

In [38]:
uniq_cases = set("".join(df_data["eng_text"].astype(str)))
tab1 = sorted(list(uniq_cases), reverse=True)
print(tab1)

['z', 'y', 'x', 'w', 'v', 'u', 't', 's', 'r', 'q', 'p', 'o', 'n', 'm', 'l', 'k', 'j', 'i', 'h', 'g', 'f', 'e', 'd', 'c', 'b', 'a', ']', '[', 'Z', 'Y', 'X', 'W', 'V', 'U', 'T', 'S', 'R', 'Q', 'P', 'O', 'N', 'M', 'L', 'K', 'J', 'I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'A', '?', ':', '9', '8', '7', '6', '5', '4', '3', '2', '1', '0', '/', '.', '-', ',', ')', '(', "'", '%', '$', '"', '!', ' ']

In [39]:
uniq_cases = set("".join(df_data["pol_text"].astype(str)))
tab2 = sorted(list(uniq_cases), reverse=True)
print(tab2)

['ż', 'Ż', 'ź', 'Ź', 'ś', 'Ś', 'ń', 'Ń', 'ł', 'Ł', 'ę', 'Ę', 'ć', 'Ć', 'ą', 'Ą', 'ó', 'Ó', 'z', 'y', 'x', 'w', 'v', 'u', 't', 's', 'r', 'q', 'p', 'o', 'n', 'm', 'l', 'k', 'j', 'i', 'h', 'g', 'f', 'e', 'd', 'c', 'b', 'a', ']', '[', 'Z', 'Y', 'X', 'W', 'V', 'U', 'T', 'S', 'R', 'Q', 'P', 'O', 'N', 'M', 'L', 'K', 'J', 'I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'A', '?', ':', '9', '8', '7', '6', '5', '4', '3', '2', '1', '0', '/', '.', '-', ',', ')', '(', "'", '%', '$', '"', '!', ' ']

In [40]:
def tokenize_eng(snt):
    snt = snt.lower()
    snt = re.sub("(?<! )'(?! )", r" '", snt)
    snt = re.sub(r"""([\]?:)\[(/\.\-,%\$"!])""", r" \1 ", snt)
    snt = re.sub(r"\s+", " ", snt).strip()
    return re.split(r'\s+', snt.strip())

In [41]:
def tokenize_pol(snt):
    snt = snt.lower()
    snt = re.sub(r"""([\]?:)\[(/\.\-,%\$"!])""", r" \1 ", snt)
    snt = re.sub(r"\s+", " ", snt).strip()
    return re.split(r'\s+', snt.strip())

In [42]:
df_data = df_data.drop(['len_ratio'], axis=1)

#### 3.1 Splitting and trimming on quantile

In [43]:
df_data['eng_split'] = df_data['eng_text'].apply(tokenize_eng)
df_data['pol_split'] = df_data['pol_text'].apply(tokenize_pol)
df_data.sample(10)

,eng_text,pol_text,eng_split,pol_split
322714,I wanted my movements accounted for up to the ...,"Chciałem, aby wszystkie moje kroki były widocz...","[i, wanted, my, movements, accounted, for, up,...","[chciałem, ,, aby, wszystkie, moje, kroki, był..."
301363,One of the things you do not know is that Colo...,"Jedną z rzeczy, których nie wiesz, jest to że ...","[one, of, the, things, you, do, not, know, is,...","[jedną, z, rzeczy, ,, których, nie, wiesz, ,, ..."
402335,You should know better than to give in to your...,Nie powinnaś ulegać swoim impulsom.,"[you, should, know, better, than, to, give, in...","[nie, powinnaś, ulegać, swoim, impulsom, .]"
209673,Thank you.,Dziękuję.,"[thank, you, .]","[dziękuję, .]"
337890,It's not me this time...,Tym razem to nie ja...,"[it, 's, not, me, this, time, ., ., .]","[tym, razem, to, nie, ja, ., ., .]"
151666,"Here you are, Mrs Gilbert.","Tutaj, pani Gilbert.","[here, you, are, ,, mrs, gilbert, .]","[tutaj, ,, pani, gilbert, .]"
216680,Get out of the way.,Zejdźcie z drogi.,"[get, out, of, the, way, .]","[zejdźcie, z, drogi, .]"
2865,"And now, my son, let us assist in carrying you...","A teraz, mój synu, pozwól mi zdjąć z ciebie to...","[and, now, ,, my, son, ,, let, us, assist, in,...","[a, teraz, ,, mój, synu, ,, pozwól, mi, zdjąć,..."
120090,I've been running across that log ever since I...,Biegałem przez ten dziennik odkąd byłem po kol...,"[i, 've, been, running, across, that, log, eve...","[biegałem, przez, ten, dziennik, odkąd, byłem,..."
112881,How do you do? Excuse me.,Generał Pompil o Montezuma .,"[how, do, you, do, ?, excuse, me, .]","[generał, pompil, o, montezuma, .]"

# TODO - zamien lt na It

In [388]:
df_data[df_data['eng_split'].apply(lambda x: 'lt' in x)]

,eng_text,pol_text,eng_split,pol_split
9576,lt was the only thing they had.,"To było jedyne, jakie mieli wolne.","[lt, was, the, only, thing, they, had, .]","[to, było, jedyne, ,, jakie, mieli, wolne, .]"
9606,lt was your fault you put the thing under the ...,"To twoja wina, bo położyłeś go pod łóżko.","[lt, was, your, fault, you, put, the, thing, u...","[to, twoja, wina, ,, bo, położyłeś, go, pod, ł..."
10725,Beat it. lt's a bull!,"Uciekajmy, to gliniarz!","[beat, it, ., lt, 's, a, bull, !]","[uciekajmy, ,, to, gliniarz, !]"
10729,lt went in your pocket.,Wpadł ci do kieszeni.,"[lt, went, in, your, pocket, .]","[wpadł, ci, do, kieszeni, .]"
10753,lt caught in your pocket.,On utknął w kieszeni...,"[lt, caught, in, your, pocket, .]","[on, utknął, w, kieszeni, ., ., .]"
...,...,...,...,...
407392,Okay. lt's your f uneral.,Dobrze. To twój cyrk.,"[okay, ., lt, 's, your, f, uneral, .]","[dobrze, ., to, twój, cyrk, .]"
407396,lt's important.,To ważne.,"[lt, 's, important, .]","[to, ważne, .]"
407469,"Maybe, maybe not. lt's a pretty story.","Może tak, może nie. Niezła historia.","[maybe, ,, maybe, not, ., lt, 's, a, pretty, s...","[może, tak, ,, może, nie, ., niezła, historia, .]"
407484,lt's unlocked.,Jest otwarta.,"[lt, 's, unlocked, .]","[jest, otwarta, .]"
407511,lt's in my pocket.,Jest w mojej kieszeni.,"[lt, 's, in, my, pocket, .]","[jest, w, mojej, kieszeni, .]"

In [44]:
thres1 = df_data['eng_split'].str.len().quantile(0.99)
mask1 = df_data['eng_split'].str.len() > thres1

thres2 = df_data['pol_split'].str.len().quantile(0.99)
mask2 = df_data['pol_split'].str.len() > thres2
print(mask1.sum(), mask2.sum(), (mask1 | mask2).sum())

df_data = df_data[~(mask1 | mask2)].reset_index(drop=True)

4113 3960 5510

#### 3.2 BPE Init. Uniq_freq & Rozklad chars

In [45]:
uniq_freq_eng = Counter(df_data['eng_split'].explode())
uniq_freq_pol = Counter(df_data['pol_split'].explode())

In [46]:
len(uniq_freq_eng), len(uniq_freq_pol)

(40087, 113603)

In [377]:
char_factor = lambda word: [x for x in word] + ['_']
vocab_chars_eng = [[char_factor(k), v] for k, v in uniq_freq_eng.most_common()]
vocab_chars_pol = [[char_factor(k), v] for k, v in uniq_freq_pol.most_common()]
print(len(vocab_chars_eng), vocab_chars_eng[:5], '\n')
print(len(vocab_chars_pol), vocab_chars_pol[:5])

40087 [[['.', '_'], 435802], [[',', '_'], 177291], [['y', 'o', 'u', '_'], 134548], [['i', '_'], 122767], [['t', 'h', 'e', '_'], 89859]]

113603 [[['.', '_'], 413780], [[',', '_'], 183948], [['?', '_'], 83444], [['n', 'i', 'e', '_'], 82694], [['t', 'o', '_'], 53190]]

#### 3.3 BPE Tokenizer most common pairs

In [527]:
class BPETokenizer():
    def __init__(self, vocab_chrs, vocab_size, is_tgt):
        self.vocab_chrs = vocab_chrs
        self.vocab_size = vocab_size
        self.vocab = self.vocab_init(vocab_chrs, is_tgt)
        self.base_size = len(self.vocab)

    def vocab_init(self, vocab_chrs, is_tgt):
        vocab = {'<pad>': 0, '<unk>': 1, '<eos>': 2, '_': 3}
        if is_tgt:
            vocab['<bos>'] = 4
            
        uniq_toks = {tok for toks, _ in vocab_chrs for tok in toks}
        uniq_toks.remove('_')
        for i, tok in enumerate(uniq_toks, len(vocab)):
            vocab[tok] = i
        return vocab                

    def train_bpe(self):
        for i in tqdm(range(self.base_size, self.vocab_size)):
            pair = self.most_common_pair()
            self.vocab[' '.join(pair)] = i
            self.replace_pairs(pair)

    def replace_pairs(self, pair):
        pair_con = f" {pair[0]}{pair[1]} "
        p_1, p_2 = map(re.escape, pair)
        
        for i, (toks, _) in enumerate(self.vocab_chrs):
            if pair in zip(toks, toks[1:]):
                self.vocab_chrs[i][0] = re.sub(rf"\s{p_1}\s{p_2}\s", pair_con, f" {' '.join(toks)} ").split()

    def most_common_pair(self):
        pair_counts = defaultdict(int)
        for toks, freq in self.vocab_chrs:
            for pair in zip(toks, toks[1:]):
                pair_counts[pair] += freq
        return max(pair_counts, key=pair_counts.get)

### 1. tokenizer

In [381]:
tokenizer_eng = BPETokenizer(vocab_chars_eng, 8000, False)
t = time.time()
tokenizer_eng.train_bpe()
print(f"{time.time()-t:.2f} seconds")

  0%|          | 0/7945 [00:00<?, ?it/s]

500.43 seconds

### 4. Testing Pair Count Func.

In [568]:
def replace_test(pair, vocab):
    indices = []
    vocab_chrs = copy.deepcopy(vocab)
    pair_con = f" {pair[0]}{pair[1]} "
    p_1, p_2 = map(re.escape, pair)
        
    for i, (toks, _) in enumerate(vocab_chrs):
        if pair in zip(toks, toks[1:]):
            vocab_chrs[i][0] = re.sub(rf"\s{p_1}\s{p_2}\s", pair_con, f" {' '.join(toks)} ").split()
            indices.append(i)
    return vocab_chrs, indices

#### 4.1 Initial Version

In [437]:
def func_1(vocab):
    pair_counts = defaultdict(int)
    for toks, freq in vocab:
        for pair in zip(toks, toks[1:]):
            pair_counts[pair] += freq
    return max(pair_counts, key=pair_counts.get), pair_counts

In [434]:
test_vocab = [[char_factor(k), v] for k, v in uniq_freq_eng.most_common()]
t = time.time()
for _ in range(100):
    func_1(test_vocab)
    pass
print(f"{time.time()-t:.2f} seconds")

4.82 seconds

In [569]:
test_vocab1 = [[char_factor(k), v] for k, v in uniq_freq_eng.most_common()]
pair1, dct_c1 = func_1(test_vocab1)
dct_c1 = dict(sorted(dct_c1.items(), key=lambda x: x[1], reverse=True))
print(f"Pair 1: {pair1}")

test_vocab2, ids = replace_test(pair1, test_vocab1)
pair2, dct_c2 = func_1(test_vocab2)
dct_c2 = dict(sorted(dct_c2.items(), key=lambda x: x[1], reverse=True))
print(f"Pair 2: {pair2}")

Pair 1: ('e', '_')
Pair 2: ('.', '_')

In [573]:
kurwa_1 = [test_vocab1[i] for i in ids]
kurwa_2 = [test_vocab2[i] for i in ids]

In [626]:
kurwa_1[:10]

[[['t', 'h', 'e', '_'], 89859],
 [['m', 'e', '_'], 29977],
 [['h', 'e', '_'], 26149],
 [['w', 'e', '_'], 23370],
 [['b', 'e', '_'], 20137],
 [['h', 'a', 'v', 'e', '_'], 19830],
 [["'", 'r', 'e', '_'], 15483],
 [['h', 'e', 'r', 'e', '_'], 15059],
 [['a', 'r', 'e', '_'], 14431],
 [['t', 'h', 'e', 'r', 'e', '_'], 14310]]

In [627]:
kurwa_2[:10]

[[['t', 'h', 'e_'], 89859],
 [['m', 'e_'], 29977],
 [['h', 'e_'], 26149],
 [['w', 'e_'], 23370],
 [['b', 'e_'], 20137],
 [['h', 'a', 'v', 'e_'], 19830],
 [["'", 'r', 'e_'], 15483],
 [['h', 'e', 'r', 'e_'], 15059],
 [['a', 'r', 'e_'], 14431],
 [['t', 'h', 'e', 'r', 'e_'], 14310]]

In [606]:
vocab_pair_1 = [[list(zip(tab, tab[1:])), c] for tab, c in test_vocab1]
vocab_pair_1 = [vocab_pair_1[i] for i in ids]
vocab_pair_1

[[[('t', 'h'), ('h', 'e'), ('e', '_')], 89859],
 [[('m', 'e'), ('e', '_')], 29977],
 [[('h', 'e'), ('e', '_')], 26149],
 [[('w', 'e'), ('e', '_')], 23370],
 [[('b', 'e'), ('e', '_')], 20137],
 [[('h', 'a'), ('a', 'v'), ('v', 'e'), ('e', '_')], 19830],
 [[("'", 'r'), ('r', 'e'), ('e', '_')], 15483],
 [[('h', 'e'), ('e', 'r'), ('r', 'e'), ('e', '_')], 15059],
 [[('a', 'r'), ('r', 'e'), ('e', '_')], 14431],
 [[('t', 'h'), ('h', 'e'), ('e', 'r'), ('r', 'e'), ('e', '_')], 14310],
 [[("'", 'v'), ('v', 'e'), ('e', '_')], 11579],
 [[('l', 'i'), ('i', 'k'), ('k', 'e'), ('e', '_')], 11372],
 [[('s', 'h'), ('h', 'e'), ('e', '_')], 10741],
 [[('c', 'o'), ('o', 'm'), ('m', 'e'), ('e', '_')], 10653],
 [[('s', 'e'), ('e', 'e'), ('e', '_')], 9619],
 [[('o', 'n'), ('n', 'e'), ('e', '_')], 8831],
 [[('t', 'a'), ('a', 'k'), ('k', 'e'), ('e', '_')], 6657],
 [[('w', 'h'), ('h', 'e'), ('e', 'r'), ('r', 'e'), ('e', '_')], 6175],
 [[('t', 'i'), ('i', 'm'), ('m', 'e'), ('e', '_')], 5538],
 [[('w', 'e'), ('e', 'r'), ('r', 'e'), ('e', '_')], 4912],
 [[('l', 'i'), ('i', 't'), ('t', 't'), ('t', 'l'), ('l', 'e'), ('e', '_')],
  4764],
 [[('s', 'o'), ('o', 'm'), ('m', 'e'), ('e', '_')], 4544],
 [[('m', 'a'), ('a', 'k'), ('k', 'e'), ('e', '_')], 4312],
 [[('m', 'o'), ('o', 'r'), ('r', 'e'), ('e', '_')], 4078],
 [[('g', 'i'), ('i', 'v'), ('v', 'e'), ('e', '_')], 3923],
 [[('s', 'u'), ('u', 'r'), ('r', 'e'), ('e', '_')], 3682],
 [[('p', 'l'), ('l', 'e'), ('e', 'a'), ('a', 's'), ('s', 'e'), ('e', '_')],
  3634],
 [[('l', 'o'), ('o', 'v'), ('v', 'e'), ('e', '_')], 3028],
 [[('b', 'e'), ('e', 'f'), ('f', 'o'), ('o', 'r'), ('r', 'e'), ('e', '_')],
  2916],
 [[('h', 'o'), ('o', 'm'), ('m', 'e'), ('e', '_')], 2550],
 [[('p', 'e'), ('e', 'o'), ('o', 'p'), ('p', 'l'), ('l', 'e'), ('e', '_')],
  2514],
 [[('t', 'h'), ('h', 'o'), ('o', 's'), ('s', 'e'), ('e', '_')], 2422],
 [[('m', 'a'), ('a', 'y'), ('y', 'b'), ('b', 'e'), ('e', '_')], 2417],
 [[('b', 'e'),
   ('e', 'c'),
   ('c', 'a'),
   ('a', 'u'),
   ('u', 's'),
   ('s', 'e'),
   ('e', '_')],
  2327],
 [[('l', 'e'), ('e', 'a'), ('a', 'v'), ('v', 'e'), ('e', '_')], 2297],
 [[('t', 'h'), ('h', 'e'), ('e', 's'), ('s', 'e'), ('e', '_')], 2289],
 [[('l', 'i'), ('i', 'f'), ('f', 'e'), ('e', '_')], 2245],
 [[('c', 'o'), ('o', 'u'), ('u', 'r'), ('r', 's'), ('s', 'e'), ('e', '_')],
  2213],
 [[('n', 'a'), ('a', 'm'), ('m', 'e'), ('e', '_')], 2067],
 [[('n', 'i'), ('i', 'c'), ('c', 'e'), ('e', '_')], 2061],
 [[('p', 'l'), ('l', 'a'), ('a', 'c'), ('c', 'e'), ('e', '_')], 1966],
 [[('h', 'o'), ('o', 'u'), ('u', 's'), ('s', 'e'), ('e', '_')], 1787],
 [[('c', 'a'), ('a', 'm'), ('m', 'e'), ('e', '_')], 1777],
 [[('m', 'a'), ('a', 'd'), ('d', 'e'), ('e', '_')], 1681],
 [[('d', 'o'), ('o', 'n'), ('n', 'e'), ('e', '_')], 1673],
 [[('b', 'e'),
   ('e', 'l'),
   ('l', 'i'),
   ('i', 'e'),
   ('e', 'v'),
   ('v', 'e'),
   ('e', '_')],
  1656],
 [[('t', 'h'), ('h', 'r'), ('r', 'e'), ('e', 'e'), ('e', '_')], 1553],
 [[('c', 'a'), ('a', 'r'), ('r', 'e'), ('e', '_')], 1511],
 [[('o', 'n'), ('n', 'c'), ('c', 'e'), ('e', '_')], 1446],
 [[('m', 'i'), ('i', 'n'), ('n', 'u'), ('u', 't'), ('t', 'e'), ('e', '_')],
  1438],
 [[('e', 'l'), ('l', 's'), ('s', 'e'), ('e', '_')], 1430],
 [[('f', 'i'), ('i', 'n'), ('n', 'e'), ('e', '_')], 1394],
 [[('w', 'i'), ('i', 'f'), ('f', 'e'), ('e', '_')], 1361],
 [[('a', 'l'), ('l', 'o'), ('o', 'n'), ('n', 'e'), ('e', '_')], 1343],
 [[('q', 'u'), ('u', 'i'), ('i', 't'), ('t', 'e'), ('e', '_')], 1341],
 [[('h', 'o'), ('o', 'p'), ('p', 'e'), ('e', '_')], 1335],
 [[('s', 'a'), ('a', 'm'), ('m', 'e'), ('e', '_')], 1282],
 [[('l', 'i'), ('i', 'v'), ('v', 'e'), ('e', '_')], 1252],
 [[('s', 'u'),
   ('u', 'p'),
   ('p', 'p'),
   ('p', 'o'),
   ('o', 's'),
   ('s', 'e'),
   ('e', '_')],
  1234],
 [[('w', 'h'), ('h', 'i'), ('i', 'l'), ('l', 'e'), ('e', '_')], 1227],
 [[('t', 'r'),
   ('r', 'o'),
   ('o', 'u'),
   ('u', 'b'),
   ('b', 'l'),
   ('l', 'e'),
   ('e', '_')],
  1153],
 [[('g', 'o'), ('o', 'n'), ('n', 'e'), ('e', '_')], 1138],
 [[('s', 'i'), ('i', 'n'), ('n', 'c'), ('c', 'e'), ('e', '_')], 1104],
 [[('w', 'h'), ('h', 'o'), ('o', 'l'), ('l', 'e'), ('e', '_')], 1083],
 [[('u', 's'), ('s', 'e'), ('e', '_')], 1029],
 [[('m', 'i'), ('i', 'n'), ('n', 'e'), ('e', '_')], 1016],
 [[('p', 'o'), ('o', 'l'), ('l', 'i'), ('i', 'c'), ('c', 'e'), ('e', '_')],
  954],
 [[('c', 'a'), ('a', 's'), ('s', 'e'), ('e', '_')], 944],
 [[('c', 'h'), ('h', 'a'), ('a', 'n'), ('n', 'c'), ('c', 'e'), ('e', '_')],
  918],
 [[('l', 'a'), ('a', 't'), ('t', 'e'), ('e', '_')], 855],
 [[('s', 'o'),
   ('o', 'm'),
   ('m', 'e'),
   ('e', 'o'),
   ('o', 'n'),
   ('n', 'e'),
   ('e', '_')],
  853],
 [[('f', 'i'), ('i', 'v'), ('v', 'e'), ('e', '_')], 852],
 [[('f', 'a'), ('a', 'c'), ('c', 'e'), ('e', '_')], 835],
 [[('e', 'x'), ('x', 'c'), ('c', 'u'), ('u', 's'), ('s', 'e'), ('e', '_')],
  835],
 [[('g', 'a'), ('a', 'v'), ('v', 'e'), ('e', '_')], 790],
 [[('a', 'n'), ('n', 'y'), ('y', 'o'), ('o', 'n'), ('n', 'e'), ('e', '_')],
  765],
 [[('g', 'o'),
   ('o', 'o'),
   ('o', 'd'),
   ('d', 'b'),
   ('b', 'y'),
   ('y', 'e'),
   ('e', '_')],
  752],
 [[('t', 'r'), ('r', 'u'), ('u', 'e'), ('e', '_')], 733],
 [[('d', 'i'), ('i', 'e'), ('e', '_')], 717],
 [[('o', 'f'), ('f', 'f'), ('f', 'i'), ('i', 'c'), ('c', 'e'), ('e', '_')],
  700],
 [[('f', 'i'), ('i', 'r'), ('r', 'e'), ('e', '_')], 685],
 [[('c', 'h'), ('h', 'a'), ('a', 'n'), ('n', 'g'), ('g', 'e'), ('e', '_')],
  681],
 [[('g', 'e'), ('e', 'o'), ('o', 'r'), ('r', 'g'), ('g', 'e'), ('e', '_')],
  670],
 [[('j', 'o'), ('o', 'e'), ('e', '_')], 660],
 [[('h', 'a'), ('a', 't'), ('t', 'e'), ('e', '_')], 603],
 [[('h', 'o'), ('o', 'r'), ('r', 's'), ('s', 'e'), ('e', '_')], 588],
 [[('m', 'o'), ('o', 'v'), ('v', 'e'), ('e', '_')], 584],
 [[('c', 'o'), ('o', 'u'), ('u', 'p'), ('p', 'l'), ('l', 'e'), ('e', '_')],
  578],
 [[('d', 'a'), ('a', 'n'), ('n', 'c'), ('c', 'e'), ('e', '_')], 565],
 [[('f', 'r'), ('r', 'e'), ('e', 'e'), ('e', '_')], 562],
 [[('m', 'a'), ('a', 'd'), ('d', 'a'), ('a', 'm'), ('m', 'e'), ('e', '_')],
  560],
 [[('u', 'n'), ('n', 'c'), ('c', 'l'), ('l', 'e'), ('e', '_')], 556],
 [[('c', 'l'), ('l', 'o'), ('o', 's'), ('s', 'e'), ('e', '_')], 554],
 [[('s', 'i'), ('i', 'd'), ('d', 'e'), ('e', '_')], 538],
 [[('s', 'a'), ('a', 'v'), ('v', 'e'), ('e', '_')], 524],
 [[('w', 'r'), ('r', 'i'), ('i', 't'), ('t', 'e'), ('e', '_')], 522],
 [[('s', 'a'), ('a', 'f'), ('f', 'e'), ('e', '_')], 493],
 [[('a', 'l'), ('l', 'i'), ('i', 'v'), ('v', 'e'), ('e', '_')], 493],
 [[('o', 'u'),
   ('u', 't'),
   ('t', 's'),
   ('s', 'i'),
   ('i', 'd'),
   ('d', 'e'),
   ('e', '_')],
  484],
 [[('a', 'n'),
   ('n', 'y'),
   ('y', 'm'),
   ('m', 'o'),
   ('o', 'r'),
   ('r', 'e'),
   ('e', '_')],
  481],
 [[('l', 'i'), ('i', 'n'), ('n', 'e'), ('e', '_')], 474],
 [[('f', 'o'),
   ('o', 'r'),
   ('r', 'g'),
   ('g', 'i'),
   ('i', 'v'),
   ('v', 'e'),
   ('e', '_')],
  469],
 [[('l', 'o'), ('o', 's'), ('s', 'e'), ('e', '_')], 460],
 [[('s', 't'),
   ('t', 'r'),
   ('r', 'a'),
   ('a', 'n'),
   ('n', 'g'),
   ('g', 'e'),
   ('e', '_')],
  451],
 [[('a', 'b'), ('b', 'l'), ('l', 'e'), ('e', '_')], 450],
 [[('b', 'y'), ('y', 'e'), ('e', '_')], 450],
 [[('w', 'h'), ('h', 'i'), ('i', 't'), ('t', 'e'), ('e', '_')], 445],
 [[('p', 'r'),
   ('r', 'o'),
   ('o', 'm'),
   ('m', 'i'),
   ('i', 's'),
   ('s', 'e'),
   ('e', '_')],
  443],
 [[('p', 'i'),
   ('i', 'c'),
   ('c', 't'),
   ('t', 'u'),
   ('u', 'r'),
   ('r', 'e'),
   ('e', '_')],
  439],
 [[('p', 'h'), ('h', 'o'), ('o', 'n'), ('n', 'e'), ('e', '_')], 434],
 [[('i', 'n'), ('n', 's'), ('s', 'i'), ('i', 'd'), ('d', 'e'), ('e', '_')],
  418],
 [[('c', 'o'), ('o', 'f'), ('f', 'f'), ('f', 'e'), ('e', 'e'), ('e', '_')],
  405],
 [[('l', 'i'), ('i', 'e'), ('e', '_')], 404],
 [[('r', 'i'), ('i', 'd'), ('d', 'e'), ('e', '_')], 402],
 [[('g', 'a'), ('a', 'm'), ('m', 'e'), ('e', '_')], 399],
 [[('d', 'r'), ('r', 'i'), ('i', 'v'), ('v', 'e'), ('e', '_')], 392],
 [[('n', 'o'), ('o', 'n'), ('n', 'e'), ('e', '_')], 391],
 [[('e', 'v'),
   ('v', 'e'),
   ('e', 'r'),
   ('r', 'y'),
   ('y', 'o'),
   ('o', 'n'),
   ('n', 'e'),
   ('e', '_')],
  391],
 [[('m', 'i'),
   ('i', 's'),
   ('s', 't'),
   ('t', 'a'),
   ('a', 'k'),
   ('k', 'e'),
   ('e', '_')],
  387],
 [[('j', 'u'), ('u', 'd'), ('d', 'g'), ('g', 'e'), ('e', '_')], 384],
 [[('s', 'e'), ('e', 'n'), ('n', 's'), ('s', 'e'), ('e', '_')], 378],
 [[('c', 'h'),
   ('h', 'a'),
   ('a', 'r'),
   ('r', 'l'),
   ('l', 'i'),
   ('i', 'e'),
   ('e', '_')],
  375],
 [[('s', 'o'),
   ('o', 'm'),
   ('m', 'e'),
   ('e', 'w'),
   ('w', 'h'),
   ('h', 'e'),
   ('e', 'r'),
   ('r', 'e'),
   ('e', '_')],
  366],
 [[('t', 'a'), ('a', 'b'), ('b', 'l'), ('l', 'e'), ('e', '_')], 360],
 [[('s', 't'), ('t', 'a'), ('a', 't'), ('t', 'e'), ('e', '_')], 354],
 [[('e', 'y'), ('y', 'e'), ('e', '_')], 353],
 [[('p', 'l'),
   ('l', 'e'),
   ('e', 'a'),
   ('a', 's'),
   ('s', 'u'),
   ('u', 'r'),
   ('r', 'e'),
   ('e', '_')],
  350],
 [[('t', 'e'),
   ('e', 'r'),
   ('r', 'r'),
   ('r', 'i'),
   ('i', 'b'),
   ('b', 'l'),
   ('l', 'e'),
   ('e', '_')],
  346],
 [[('e', 'd'), ('d', 'd'), ('d', 'i'), ('i', 'e'), ('e', '_')], 345],
 [[('p', 'o'),
   ('o', 's'),
   ('s', 's'),
   ('s', 'i'),
   ('i', 'b'),
   ('b', 'l'),
   ('l', 'e'),
   ('e', '_')],
  344],
 [[('b', 'e'), ('e', 'c'), ('c', 'o'), ('o', 'm'), ('m', 'e'), ('e', '_')],
  343],
 [[('d', 'e'), ('e', '_')], 334],
 [[('w', 'e'),
   ('e', 'l'),
   ('l', 'c'),
   ('c', 'o'),
   ('o', 'm'),
   ('m', 'e'),
   ('e', '_')],
  330],
 [[('i', 'm'),
   ('m', 'a'),
   ('a', 'g'),
   ('g', 'i'),
   ('i', 'n'),
   ('n', 'e'),
   ('e', '_')],
  327],
 [[('d', 'i'),
   ('i', 'f'),
   ('f', 'f'),
   ('f', 'e'),
   ('e', 'r'),
   ('r', 'e'),
   ('e', 'n'),
   ('n', 'c'),
   ('c', 'e'),
   ('e', '_')],
  323],
 [[('w', 'o'), ('o', 'r'), ('r', 's'), ('s', 'e'), ('e', '_')], 322],
 [[('m', 'a'),
   ('a', 'r'),
   ('r', 'r'),
   ('r', 'i'),
   ('i', 'a'),
   ('a', 'g'),
   ('g', 'e'),
   ('e', '_')],
  316],
 [[('f', 'r'), ('r', 'a'), ('a', 'n'), ('n', 'c'), ('c', 'e'), ('e', '_')],
  313],
 [[('f', 'i'), ('i', 'g'), ('g', 'u'), ('u', 'r'), ('r', 'e'), ('e', '_')],
  309],
 [[('s', 'i'), ('i', 'm'), ('m', 'p'), ('p', 'l'), ('l', 'e'), ('e', '_')],
  308],
 [[('p', 'i'), ('i', 'e'), ('e', 'c'), ('c', 'e'), ('e', '_')], 306],
 [[('p', 'e'), ('e', 'a'), ('a', 'c'), ('c', 'e'), ('e', '_')], 305],
 [[('b', 'r'), ('r', 'o'), ('o', 'k'), ('k', 'e'), ('e', '_')], 299],
 [[('c', 'h'), ('h', 'a'), ('a', 'r'), ('r', 'g'), ('g', 'e'), ('e', '_')],
  296],
 [[('h', 'i'), ('i', 'd'), ('d', 'e'), ('e', '_')], 287],
 [[('t', 'e'),
   ('e', 'l'),
   ('l', 'e'),
   ('e', 'p'),
   ('p', 'h'),
   ('h', 'o'),
   ('o', 'n'),
   ('n', 'e'),
   ('e', '_')],
  280],
 [[('w', 'a'), ('a', 'k'), ('k', 'e'), ('e', '_')], 278],
 [[('s', 'u'),
   ('u', 'r'),
   ('r', 'p'),
   ('p', 'r'),
   ('r', 'i'),
   ('i', 's'),
   ('s', 'e'),
   ('e', '_')],
  276],
 [[('w', 'i'), ('i', 'n'), ('n', 'e'), ('e', '_')], 273],
 [[('p', 'r'), ('r', 'o'), ('o', 'v'), ('v', 'e'), ('e', '_')], 269],
 [[('a', 'y'), ('y', 'e'), ('e', '_')], 269],
 [[('d', 'a'), ('a', 'r'), ('r', 'e'), ('e', '_')], 268],
 [[('s', 'a'), ('a', 'k'), ('k', 'e'), ('e', '_')], 266],
 [[('b', 'l'), ('l', 'a'), ('a', 'm'), ('m', 'e'), ('e', '_')], 264],
 [[('p', 'l'), ('l', 'a'), ('a', 'n'), ('n', 'e'), ('e', '_')], 264],
 [[('r', 'e'),
   ('e', 'a'),
   ('a', 'l'),
   ('l', 'i'),
   ('i', 'z'),
   ('z', 'e'),
   ('e', '_')],
  259],
 [[('d', 'o'), ('o', 'u'), ('u', 'b'), ('b', 'l'), ('l', 'e'), ('e', '_')],
  257],
 [[('h', 'a'), ('a', 'n'), ('n', 'd'), ('d', 'l'), ('l', 'e'), ('e', '_')],
  254],
 [[('n', 'o'),
   ('o', 'n'),
   ('n', 's'),
   ('s', 'e'),
   ('e', 'n'),
   ('n', 's'),
   ('s', 'e'),
   ('e', '_')],
  254],
 [[('b', 'r'), ('r', 'i'), ('i', 'd'), ('d', 'g'), ('g', 'e'), ('e', '_')],
  252],
 [[('s', 'e'),
   ('e', 'r'),
   ('r', 'v'),
   ('v', 'i'),
   ('i', 'c'),
   ('c', 'e'),
   ('e', '_')],
  251],
 [[('a', 'n'),
   ('n', 'y'),
   ('y', 'w'),
   ('w', 'h'),
   ('h', 'e'),
   ('e', 'r'),
   ('r', 'e'),
   ('e', '_')],
  249],
 [[('f', 'u'), ('u', 't'), ('t', 'u'), ('u', 'r'), ('r', 'e'), ('e', '_')],
  248],
 [[('b', 'o'), ('o', 't'), ('t', 't'), ('t', 'l'), ('l', 'e'), ('e', '_')],
  246],
 [[('b', 'l'), ('l', 'u'), ('u', 'e'), ('e', '_')], 245],
 [[('b', 'l'),
   ('l', 'a'),
   ('a', 'c'),
   ('c', 'k'),
   ('k', 'i'),
   ('i', 'e'),
   ('e', '_')],
  243],
 [[('v', 'o'), ('o', 'i'), ('i', 'c'), ('c', 'e'), ('e', '_')], 242],
 [[('n', 'o'), ('o', 's'), ('s', 'e'), ('e', '_')], 239],
 [[('d', 'u'), ('u', 'k'), ('k', 'e'), ('e', '_')], 239],
 [[('m', 'e'),
   ('e', 's'),
   ('s', 's'),
   ('s', 'a'),
   ('a', 'g'),
   ('g', 'e'),
   ('e', '_')],
  238],
 [[('g', 'e'), ('e', 'e'), ('e', '_')], 237],
 [[('i', 'm'),
   ('m', 'p'),
   ('p', 'o'),
   ('o', 's'),
   ('s', 's'),
   ('s', 'i'),
   ('i', 'b'),
   ('b', 'l'),
   ('l', 'e'),
   ('e', '_')],
  232],
 [[('d', 'a'), ('a', 'v'), ('v', 'e'), ('e', '_')], 231],
 [[('p', 'r'),
   ('r', 'i'),
   ('i', 'v'),
   ('v', 'a'),
   ('a', 't'),
   ('t', 'e'),
   ('e', '_')],
  227],
 [[('k', 'n'), ('n', 'i'), ('i', 'f'), ('f', 'e'), ('e', '_')], 217],
 [[('p', 'e'), ('e', 't'), ('t', 'e'), ('e', '_')], 216],
 [[('f', 'o'), ('o', 'r'), ('r', 'c'), ('c', 'e'), ('e', '_')], 212],
 [[('a', 'g'), ('g', 'e'), ('e', '_')], 209],
 [[('w', 'h'), ('h', 'o'), ('o', 's'), ('s', 'e'), ('e', '_')], 208],
 [[('n', 'o'), ('o', 't'), ('t', 'i'), ('i', 'c'), ('c', 'e'), ('e', '_')],
  205],
 [[('o', 'w'), ('w', 'e'), ('e', '_')], 205],
 [[('n', 'o'), ('o', 't'), ('t', 'e'), ('e', '_')], 205],
 [[('s', 'h'), ('h', 'a'), ('a', 'r'), ('r', 'e'), ('e', '_')], 204],
 [[('i', 'c'), ('c', 'e'), ('e', '_')], 201],
 [[('p', 'r'), ('r', 'i'), ('i', 'n'), ('n', 'c'), ('c', 'e'), ('e', '_')],
  201],
 [[('e', 'v'),
   ('v', 'i'),
   ('i', 'd'),
   ('d', 'e'),
   ('e', 'n'),
   ('n', 'c'),
   ('c', 'e'),
   ('e', '_')],
  197],
 [[('a', 'g'), ('g', 'r'), ('r', 'e'), ('e', 'e'), ('e', '_')], 197],
 [[('w', 'r'), ('r', 'o'), ('o', 't'), ('t', 'e'), ('e', '_')], 197],
 [[('r', 'a'), ('a', 'i'), ('i', 's'), ('s', 'e'), ('e', '_')], 190],
 [[('e', 's'), ('s', 'c'), ('c', 'a'), ('a', 'p'), ('p', 'e'), ('e', '_')],
  189],
 [[('s', 't'), ('t', 'o'), ('o', 'r'), ('r', 'e'), ('e', '_')], 187],
 [[('s', 'm'), ('m', 'o'), ('o', 'k'), ('k', 'e'), ('e', '_')], 186],
 [[('v', 'i'),
   ('i', 'l'),
   ('l', 'l'),
   ('l', 'a'),
   ('a', 'g'),
   ('g', 'e'),
   ('e', '_')],
  185],
 [[('j', 'o'), ('o', 'k'), ('k', 'e'), ('e', '_')], 183],
 [[('a', 'd'), ('d', 'v'), ('v', 'i'), ('i', 'c'), ('c', 'e'), ('e', '_')],
  183],
 [[('p', 'r'), ('r', 'i'), ('i', 'c'), ('c', 'e'), ('e', '_')], 181],
 [[('t', 'i'), ('i', 'e'), ('e', '_')], 180],
 [[('d', 'e'),
   ('e', 't'),
   ('t', 'e'),
   ('e', 'c'),
   ('c', 't'),
   ('t', 'i'),
   ('i', 'v'),
   ('v', 'e'),
   ('e', '_')],
  180],
 [[('n', 'i'), ('i', 'n'), ('n', 'e'), ('e', '_')], 180],
 [[('t', 'r'), ('r', 'e'), ('e', 'e'), ('e', '_')], 179],
 [[('c', 'o'),
   ('o', 'u'),
   ('u', 'r'),
   ('r', 'a'),
   ('a', 'g'),
   ('g', 'e'),
   ('e', '_')],
  178],
 [[('m', 'i'), ('i', 'd'), ('d', 'd'), ('d', 'l'), ('l', 'e'), ('e', '_')],
  177],
 [[('t', 'w'), ('w', 'i'), ('i', 'c'), ('c', 'e'), ('e', '_')], 177],
 [[('f', 'o'),
   ('o', 'r'),
   ('r', 't'),
   ('t', 'u'),
   ('u', 'n'),
   ('n', 'e'),
   ('e', '_')],
  176],
 [[('c', 'r'), ('r', 'i'), ('i', 'm'), ('m', 'e'), ('e', '_')], 176],
 [[('a', 'l'), ('l', 'i'), ('i', 'c'), ('c', 'e'), ('e', '_')], 176],
 [[('c', 'h'),
   ('h', 'a'),
   ('a', 'm'),
   ('m', 'p'),
   ('p', 'a'),
   ('a', 'g'),
   ('g', 'n'),
   ('n', 'e'),
   ('e', '_')],
  176],
 [[('s', 't'), ('t', 'a'), ('a', 'g'), ('g', 'e'), ('e', '_')], 174],
 [[('d', 'a'), ('a', 'm'), ('m', 'e'), ('e', '_')], 169],
 [[('s', 't'), ('t', 'o'), ('o', 'n'), ('n', 'e'), ('e', '_')], 168],
 [[('d', 'a'), ('a', 't'), ('t', 'e'), ('e', '_')], 167],
 [[('h', 'o'),
   ('o', 'r'),
   ('r', 'r'),
   ('r', 'i'),
   ('i', 'b'),
   ('b', 'l'),
   ('l', 'e'),
   ('e', '_')],
  167],
 [[('c', 'i'),
   ('i', 'g'),
   ('g', 'a'),
   ('a', 'r'),
   ('r', 'e'),
   ('e', 't'),
   ('t', 't'),
   ('t', 'e'),
   ('e', '_')],
  165],
 [[('t', 'y'), ('y', 'p'), ('p', 'e'), ('e', '_')], 163],
 [[('j', 'u'), ('u', 'l'), ('l', 'i'), ('i', 'e'), ('e', '_')], 163],
 [[('s', 'e'), ('e', 'r'), ('r', 'v'), ('v', 'e'), ('e', '_')], 162],
 [[('s', 'o'),
   ('o', 'm'),
   ('m', 'e'),
   ('e', 't'),
   ('t', 'i'),
   ('i', 'm'),
   ('m', 'e'),
   ('e', '_')],
  162],
 [[('c', 'o'),
   ('o', 'm'),
   ('m', 'f'),
   ('f', 'o'),
   ('o', 'r'),
   ('r', 't'),
   ('t', 'a'),
   ('a', 'b'),
   ('b', 'l'),
   ('l', 'e'),
   ('e', '_')],
  161],
 [[('r', 'e'),
   ('e', 's'),
   ('s', 'p'),
   ('p', 'o'),
   ('o', 'n'),
   ('n', 's'),
   ('s', 'i'),
   ('i', 'b'),
   ('b', 'l'),
   ('l', 'e'),
   ('e', '_')],
  160],
 [[('s', 'e'), ('e', 't'), ('t', 't'), ('t', 'l'), ('l', 'e'), ('e', '_')],
  159],
 [[('w', 'i'), ('i', 's'), ('s', 'e'), ('e', '_')], 158],
 [[('m', 'a'),
   ('a', 'd'),
   ('d', 'e'),
   ('e', 'm'),
   ('m', 'o'),
   ('o', 'i'),
   ('i', 's'),
   ('s', 'e'),
   ('e', 'l'),
   ('l', 'l'),
   ('l', 'e'),
   ('e', '_')],
  158],
 [[('r', 'o'), ('o', 's'), ('s', 'e'), ('e', '_')], 154],
 [[('c', 'a'), ('a', 'u'), ('u', 's'), ('s', 'e'), ('e', '_')], 154],
 [[('a', 'b'), ('b', 'o'), ('o', 'v'), ('v', 'e'), ('e', '_')], 153],
 [[('w', 'i'), ('i', 'r'), ('r', 'e'), ('e', '_')], 153],
 [[('m', 'a'), ('a', 'r'), ('r', 'i'), ('i', 'e'), ('e', '_')], 152],
 [[('n', 'u'), ('u', 'r'), ('r', 's'), ('s', 'e'), ('e', '_')], 152],
 [[('s', 'i'), ('i', 'n'), ('n', 'g'), ('g', 'l'), ('l', 'e'), ('e', '_')],
  151],
 [[('c', 'h'), ('h', 'o'), ('o', 'i'), ('i', 'c'), ('c', 'e'), ('e', '_')],
  151],
 [[('b', 'r'), ('r', 'i'), ('i', 'd'), ('d', 'e'), ('e', '_')], 151],
 [[('w', 'i'), ('i', 'l'), ('l', 'l'), ('l', 'i'), ('i', 'e'), ('e', '_')],
  151],
 [[('d', 'i'),
   ('i', 'v'),
   ('v', 'o'),
   ('o', 'r'),
   ('r', 'c'),
   ('c', 'e'),
   ('e', '_')],
  150],
 [[('s', 'm'), ('m', 'i'), ('i', 'l'), ('l', 'e'), ('e', '_')], 149],
 [[('w', 'a'), ('a', 's'), ('s', 't'), ('t', 'e'), ('e', '_')], 148],
 [[('p', 'a'), ('a', 'l'), ('l', 'a'), ('a', 'c'), ('c', 'e'), ('e', '_')],
  147],
 [[('j', 'u'),
   ('u', 's'),
   ('s', 't'),
   ('t', 'i'),
   ('i', 'c'),
   ('c', 'e'),
   ('e', '_')],
  146],
 [[('c', 'u'), ('u', 't'), ('t', 'e'), ('e', '_')], 146],
 [[('c', 'a'), ('a', 't'), ('t', 't'), ('t', 'l'), ('l', 'e'), ('e', '_')],
  146],
 [[('b', 'r'), ('r', 'a'), ('a', 'v'), ('v', 'e'), ('e', '_')], 144],
 [[('e', 'x'),
   ('x', 'p'),
   ('p', 'e'),
   ('e', 'r'),
   ('r', 'i'),
   ('i', 'e'),
   ('e', 'n'),
   ('n', 'c'),
   ('c', 'e'),
   ('e', '_')],
  144],
 [[('i', 'n'),
   ('n', 's'),
   ('s', 't'),
   ('t', 'a'),
   ('a', 'n'),
   ('n', 'c'),
   ('c', 'e'),
   ('e', '_')],
  144],
 [[('e', 'v'),
   ('v', 'e'),
   ('e', 'r'),
   ('r', 'y'),
   ('y', 'w'),
   ('w', 'h'),
   ('h', 'e'),
   ('e', 'r'),
   ('r', 'e'),
   ('e', '_')],
  143],
 [[('s', 't'), ('t', 'r'), ('r', 'i'), ('i', 'k'), ('k', 'e'), ('e', '_')],
  143],
 [[('a', 'p'),
   ('p', 'o'),
   ('o', 'l'),
   ('l', 'o'),
   ('o', 'g'),
   ('g', 'i'),
   ('i', 'z'),
   ('z', 'e'),
   ('e', '_')],
  142],
 [[('s', 't'), ('t', 'e'), ('e', 'v'), ('v', 'e'), ('e', '_')], 142],
 [[('m', 'a'),
   ('a', 'c'),
   ('c', 'h'),
   ('h', 'i'),
   ('i', 'n'),
   ('n', 'e'),
   ('e', '_')],
  141],
 [[('s', 'o'), ('o', 'r'), ('r', 'e'), ('e', '_')], 140],
 [[('s', 'q'), ('q', 'u'), ('u', 'a'), ('a', 'r'), ('r', 'e'), ('e', '_')],
  137],
 [[('s', 'c'), ('c', 'e'), ('e', 'n'), ('n', 'e'), ('e', '_')], 136],
 [[('e', 'u'), ('u', 'r'), ('r', 'o'), ('o', 'p'), ('p', 'e'), ('e', '_')],
  136],
 [[('r', 'a'), ('a', 'c'), ('c', 'e'), ('e', '_')], 136],
 [[('s', 't'), ('t', 'o'), ('o', 'l'), ('l', 'e'), ('e', '_')], 135],
 [[('i', 'n'),
   ('n', 'v'),
   ('v', 'i'),
   ('i', 's'),
   ('s', 'i'),
   ('i', 'b'),
   ('b', 'l'),

In [607]:
vocab_pair_2 = [[list(zip(tab, tab[1:])), c] for tab, c in test_vocab2]
vocab_pair_2 = [vocab_pair_2[i] for i in ids]
vocab_pair_2

[[[('t', 'h'), ('h', 'e_')], 89859],
 [[('m', 'e_')], 29977],
 [[('h', 'e_')], 26149],
 [[('w', 'e_')], 23370],
 [[('b', 'e_')], 20137],
 [[('h', 'a'), ('a', 'v'), ('v', 'e_')], 19830],
 [[("'", 'r'), ('r', 'e_')], 15483],
 [[('h', 'e'), ('e', 'r'), ('r', 'e_')], 15059],
 [[('a', 'r'), ('r', 'e_')], 14431],
 [[('t', 'h'), ('h', 'e'), ('e', 'r'), ('r', 'e_')], 14310],
 [[("'", 'v'), ('v', 'e_')], 11579],
 [[('l', 'i'), ('i', 'k'), ('k', 'e_')], 11372],
 [[('s', 'h'), ('h', 'e_')], 10741],
 [[('c', 'o'), ('o', 'm'), ('m', 'e_')], 10653],
 [[('s', 'e'), ('e', 'e_')], 9619],
 [[('o', 'n'), ('n', 'e_')], 8831],
 [[('t', 'a'), ('a', 'k'), ('k', 'e_')], 6657],
 [[('w', 'h'), ('h', 'e'), ('e', 'r'), ('r', 'e_')], 6175],
 [[('t', 'i'), ('i', 'm'), ('m', 'e_')], 5538],
 [[('w', 'e'), ('e', 'r'), ('r', 'e_')], 4912],
 [[('l', 'i'), ('i', 't'), ('t', 't'), ('t', 'l'), ('l', 'e_')], 4764],
 [[('s', 'o'), ('o', 'm'), ('m', 'e_')], 4544],
 [[('m', 'a'), ('a', 'k'), ('k', 'e_')], 4312],
 [[('m', 'o'), ('o', 'r'), ('r', 'e_')], 4078],
 [[('g', 'i'), ('i', 'v'), ('v', 'e_')], 3923],
 [[('s', 'u'), ('u', 'r'), ('r', 'e_')], 3682],
 [[('p', 'l'), ('l', 'e'), ('e', 'a'), ('a', 's'), ('s', 'e_')], 3634],
 [[('l', 'o'), ('o', 'v'), ('v', 'e_')], 3028],
 [[('b', 'e'), ('e', 'f'), ('f', 'o'), ('o', 'r'), ('r', 'e_')], 2916],
 [[('h', 'o'), ('o', 'm'), ('m', 'e_')], 2550],
 [[('p', 'e'), ('e', 'o'), ('o', 'p'), ('p', 'l'), ('l', 'e_')], 2514],
 [[('t', 'h'), ('h', 'o'), ('o', 's'), ('s', 'e_')], 2422],
 [[('m', 'a'), ('a', 'y'), ('y', 'b'), ('b', 'e_')], 2417],
 [[('b', 'e'), ('e', 'c'), ('c', 'a'), ('a', 'u'), ('u', 's'), ('s', 'e_')],
  2327],
 [[('l', 'e'), ('e', 'a'), ('a', 'v'), ('v', 'e_')], 2297],
 [[('t', 'h'), ('h', 'e'), ('e', 's'), ('s', 'e_')], 2289],
 [[('l', 'i'), ('i', 'f'), ('f', 'e_')], 2245],
 [[('c', 'o'), ('o', 'u'), ('u', 'r'), ('r', 's'), ('s', 'e_')], 2213],
 [[('n', 'a'), ('a', 'm'), ('m', 'e_')], 2067],
 [[('n', 'i'), ('i', 'c'), ('c', 'e_')], 2061],
 [[('p', 'l'), ('l', 'a'), ('a', 'c'), ('c', 'e_')], 1966],
 [[('h', 'o'), ('o', 'u'), ('u', 's'), ('s', 'e_')], 1787],
 [[('c', 'a'), ('a', 'm'), ('m', 'e_')], 1777],
 [[('m', 'a'), ('a', 'd'), ('d', 'e_')], 1681],
 [[('d', 'o'), ('o', 'n'), ('n', 'e_')], 1673],
 [[('b', 'e'), ('e', 'l'), ('l', 'i'), ('i', 'e'), ('e', 'v'), ('v', 'e_')],
  1656],
 [[('t', 'h'), ('h', 'r'), ('r', 'e'), ('e', 'e_')], 1553],
 [[('c', 'a'), ('a', 'r'), ('r', 'e_')], 1511],
 [[('o', 'n'), ('n', 'c'), ('c', 'e_')], 1446],
 [[('m', 'i'), ('i', 'n'), ('n', 'u'), ('u', 't'), ('t', 'e_')], 1438],
 [[('e', 'l'), ('l', 's'), ('s', 'e_')], 1430],
 [[('f', 'i'), ('i', 'n'), ('n', 'e_')], 1394],
 [[('w', 'i'), ('i', 'f'), ('f', 'e_')], 1361],
 [[('a', 'l'), ('l', 'o'), ('o', 'n'), ('n', 'e_')], 1343],
 [[('q', 'u'), ('u', 'i'), ('i', 't'), ('t', 'e_')], 1341],
 [[('h', 'o'), ('o', 'p'), ('p', 'e_')], 1335],
 [[('s', 'a'), ('a', 'm'), ('m', 'e_')], 1282],
 [[('l', 'i'), ('i', 'v'), ('v', 'e_')], 1252],
 [[('s', 'u'), ('u', 'p'), ('p', 'p'), ('p', 'o'), ('o', 's'), ('s', 'e_')],
  1234],
 [[('w', 'h'), ('h', 'i'), ('i', 'l'), ('l', 'e_')], 1227],
 [[('t', 'r'), ('r', 'o'), ('o', 'u'), ('u', 'b'), ('b', 'l'), ('l', 'e_')],
  1153],
 [[('g', 'o'), ('o', 'n'), ('n', 'e_')], 1138],
 [[('s', 'i'), ('i', 'n'), ('n', 'c'), ('c', 'e_')], 1104],
 [[('w', 'h'), ('h', 'o'), ('o', 'l'), ('l', 'e_')], 1083],
 [[('u', 's'), ('s', 'e_')], 1029],
 [[('m', 'i'), ('i', 'n'), ('n', 'e_')], 1016],
 [[('p', 'o'), ('o', 'l'), ('l', 'i'), ('i', 'c'), ('c', 'e_')], 954],
 [[('c', 'a'), ('a', 's'), ('s', 'e_')], 944],
 [[('c', 'h'), ('h', 'a'), ('a', 'n'), ('n', 'c'), ('c', 'e_')], 918],
 [[('l', 'a'), ('a', 't'), ('t', 'e_')], 855],
 [[('s', 'o'), ('o', 'm'), ('m', 'e'), ('e', 'o'), ('o', 'n'), ('n', 'e_')],
  853],
 [[('f', 'i'), ('i', 'v'), ('v', 'e_')], 852],
 [[('f', 'a'), ('a', 'c'), ('c', 'e_')], 835],
 [[('e', 'x'), ('x', 'c'), ('c', 'u'), ('u', 's'), ('s', 'e_')], 835],
 [[('g', 'a'), ('a', 'v'), ('v', 'e_')], 790],
 [[('a', 'n'), ('n', 'y'), ('y', 'o'), ('o', 'n'), ('n', 'e_')], 765],
 [[('g', 'o'), ('o', 'o'), ('o', 'd'), ('d', 'b'), ('b', 'y'), ('y', 'e_')],
  752],
 [[('t', 'r'), ('r', 'u'), ('u', 'e_')], 733],
 [[('d', 'i'), ('i', 'e_')], 717],
 [[('o', 'f'), ('f', 'f'), ('f', 'i'), ('i', 'c'), ('c', 'e_')], 700],
 [[('f', 'i'), ('i', 'r'), ('r', 'e_')], 685],
 [[('c', 'h'), ('h', 'a'), ('a', 'n'), ('n', 'g'), ('g', 'e_')], 681],
 [[('g', 'e'), ('e', 'o'), ('o', 'r'), ('r', 'g'), ('g', 'e_')], 670],
 [[('j', 'o'), ('o', 'e_')], 660],
 [[('h', 'a'), ('a', 't'), ('t', 'e_')], 603],
 [[('h', 'o'), ('o', 'r'), ('r', 's'), ('s', 'e_')], 588],
 [[('m', 'o'), ('o', 'v'), ('v', 'e_')], 584],
 [[('c', 'o'), ('o', 'u'), ('u', 'p'), ('p', 'l'), ('l', 'e_')], 578],
 [[('d', 'a'), ('a', 'n'), ('n', 'c'), ('c', 'e_')], 565],
 [[('f', 'r'), ('r', 'e'), ('e', 'e_')], 562],
 [[('m', 'a'), ('a', 'd'), ('d', 'a'), ('a', 'm'), ('m', 'e_')], 560],
 [[('u', 'n'), ('n', 'c'), ('c', 'l'), ('l', 'e_')], 556],
 [[('c', 'l'), ('l', 'o'), ('o', 's'), ('s', 'e_')], 554],
 [[('s', 'i'), ('i', 'd'), ('d', 'e_')], 538],
 [[('s', 'a'), ('a', 'v'), ('v', 'e_')], 524],
 [[('w', 'r'), ('r', 'i'), ('i', 't'), ('t', 'e_')], 522],
 [[('s', 'a'), ('a', 'f'), ('f', 'e_')], 493],
 [[('a', 'l'), ('l', 'i'), ('i', 'v'), ('v', 'e_')], 493],
 [[('o', 'u'), ('u', 't'), ('t', 's'), ('s', 'i'), ('i', 'd'), ('d', 'e_')],
  484],
 [[('a', 'n'), ('n', 'y'), ('y', 'm'), ('m', 'o'), ('o', 'r'), ('r', 'e_')],
  481],
 [[('l', 'i'), ('i', 'n'), ('n', 'e_')], 474],
 [[('f', 'o'), ('o', 'r'), ('r', 'g'), ('g', 'i'), ('i', 'v'), ('v', 'e_')],
  469],
 [[('l', 'o'), ('o', 's'), ('s', 'e_')], 460],
 [[('s', 't'), ('t', 'r'), ('r', 'a'), ('a', 'n'), ('n', 'g'), ('g', 'e_')],
  451],
 [[('a', 'b'), ('b', 'l'), ('l', 'e_')], 450],
 [[('b', 'y'), ('y', 'e_')], 450],
 [[('w', 'h'), ('h', 'i'), ('i', 't'), ('t', 'e_')], 445],
 [[('p', 'r'), ('r', 'o'), ('o', 'm'), ('m', 'i'), ('i', 's'), ('s', 'e_')],
  443],
 [[('p', 'i'), ('i', 'c'), ('c', 't'), ('t', 'u'), ('u', 'r'), ('r', 'e_')],
  439],
 [[('p', 'h'), ('h', 'o'), ('o', 'n'), ('n', 'e_')], 434],
 [[('i', 'n'), ('n', 's'), ('s', 'i'), ('i', 'd'), ('d', 'e_')], 418],
 [[('c', 'o'), ('o', 'f'), ('f', 'f'), ('f', 'e'), ('e', 'e_')], 405],
 [[('l', 'i'), ('i', 'e_')], 404],
 [[('r', 'i'), ('i', 'd'), ('d', 'e_')], 402],
 [[('g', 'a'), ('a', 'm'), ('m', 'e_')], 399],
 [[('d', 'r'), ('r', 'i'), ('i', 'v'), ('v', 'e_')], 392],
 [[('n', 'o'), ('o', 'n'), ('n', 'e_')], 391],
 [[('e', 'v'),
   ('v', 'e'),
   ('e', 'r'),
   ('r', 'y'),
   ('y', 'o'),
   ('o', 'n'),
   ('n', 'e_')],
  391],
 [[('m', 'i'), ('i', 's'), ('s', 't'), ('t', 'a'), ('a', 'k'), ('k', 'e_')],
  387],
 [[('j', 'u'), ('u', 'd'), ('d', 'g'), ('g', 'e_')], 384],
 [[('s', 'e'), ('e', 'n'), ('n', 's'), ('s', 'e_')], 378],
 [[('c', 'h'), ('h', 'a'), ('a', 'r'), ('r', 'l'), ('l', 'i'), ('i', 'e_')],
  375],
 [[('s', 'o'),
   ('o', 'm'),
   ('m', 'e'),
   ('e', 'w'),
   ('w', 'h'),
   ('h', 'e'),
   ('e', 'r'),
   ('r', 'e_')],
  366],
 [[('t', 'a'), ('a', 'b'), ('b', 'l'), ('l', 'e_')], 360],
 [[('s', 't'), ('t', 'a'), ('a', 't'), ('t', 'e_')], 354],
 [[('e', 'y'), ('y', 'e_')], 353],
 [[('p', 'l'),
   ('l', 'e'),
   ('e', 'a'),
   ('a', 's'),
   ('s', 'u'),
   ('u', 'r'),
   ('r', 'e_')],
  350],
 [[('t', 'e'),
   ('e', 'r'),
   ('r', 'r'),
   ('r', 'i'),
   ('i', 'b'),
   ('b', 'l'),
   ('l', 'e_')],
  346],
 [[('e', 'd'), ('d', 'd'), ('d', 'i'), ('i', 'e_')], 345],
 [[('p', 'o'),
   ('o', 's'),
   ('s', 's'),
   ('s', 'i'),
   ('i', 'b'),
   ('b', 'l'),
   ('l', 'e_')],
  344],
 [[('b', 'e'), ('e', 'c'), ('c', 'o'), ('o', 'm'), ('m', 'e_')], 343],
 [[('d', 'e_')], 334],
 [[('w', 'e'), ('e', 'l'), ('l', 'c'), ('c', 'o'), ('o', 'm'), ('m', 'e_')],
  330],
 [[('i', 'm'), ('m', 'a'), ('a', 'g'), ('g', 'i'), ('i', 'n'), ('n', 'e_')],
  327],
 [[('d', 'i'),
   ('i', 'f'),
   ('f', 'f'),
   ('f', 'e'),
   ('e', 'r'),
   ('r', 'e'),
   ('e', 'n'),
   ('n', 'c'),
   ('c', 'e_')],
  323],
 [[('w', 'o'), ('o', 'r'), ('r', 's'), ('s', 'e_')], 322],
 [[('m', 'a'),
   ('a', 'r'),
   ('r', 'r'),
   ('r', 'i'),
   ('i', 'a'),
   ('a', 'g'),
   ('g', 'e_')],
  316],
 [[('f', 'r'), ('r', 'a'), ('a', 'n'), ('n', 'c'), ('c', 'e_')], 313],
 [[('f', 'i'), ('i', 'g'), ('g', 'u'), ('u', 'r'), ('r', 'e_')], 309],
 [[('s', 'i'), ('i', 'm'), ('m', 'p'), ('p', 'l'), ('l', 'e_')], 308],
 [[('p', 'i'), ('i', 'e'), ('e', 'c'), ('c', 'e_')], 306],
 [[('p', 'e'), ('e', 'a'), ('a', 'c'), ('c', 'e_')], 305],
 [[('b', 'r'), ('r', 'o'), ('o', 'k'), ('k', 'e_')], 299],
 [[('c', 'h'), ('h', 'a'), ('a', 'r'), ('r', 'g'), ('g', 'e_')], 296],
 [[('h', 'i'), ('i', 'd'), ('d', 'e_')], 287],
 [[('t', 'e'),
   ('e', 'l'),
   ('l', 'e'),
   ('e', 'p'),
   ('p', 'h'),
   ('h', 'o'),
   ('o', 'n'),
   ('n', 'e_')],
  280],
 [[('w', 'a'), ('a', 'k'), ('k', 'e_')], 278],
 [[('s', 'u'),
   ('u', 'r'),
   ('r', 'p'),
   ('p', 'r'),
   ('r', 'i'),
   ('i', 's'),
   ('s', 'e_')],
  276],
 [[('w', 'i'), ('i', 'n'), ('n', 'e_')], 273],
 [[('p', 'r'), ('r', 'o'), ('o', 'v'), ('v', 'e_')], 269],
 [[('a', 'y'), ('y', 'e_')], 269],
 [[('d', 'a'), ('a', 'r'), ('r', 'e_')], 268],
 [[('s', 'a'), ('a', 'k'), ('k', 'e_')], 266],
 [[('b', 'l'), ('l', 'a'), ('a', 'm'), ('m', 'e_')], 264],
 [[('p', 'l'), ('l', 'a'), ('a', 'n'), ('n', 'e_')], 264],
 [[('r', 'e'), ('e', 'a'), ('a', 'l'), ('l', 'i'), ('i', 'z'), ('z', 'e_')],
  259],
 [[('d', 'o'), ('o', 'u'), ('u', 'b'), ('b', 'l'), ('l', 'e_')], 257],
 [[('h', 'a'), ('a', 'n'), ('n', 'd'), ('d', 'l'), ('l', 'e_')], 254],
 [[('n', 'o'),
   ('o', 'n'),
   ('n', 's'),
   ('s', 'e'),
   ('e', 'n'),
   ('n', 's'),
   ('s', 'e_')],
  254],
 [[('b', 'r'), ('r', 'i'), ('i', 'd'), ('d', 'g'), ('g', 'e_')], 252],
 [[('s', 'e'), ('e', 'r'), ('r', 'v'), ('v', 'i'), ('i', 'c'), ('c', 'e_')],
  251],
 [[('a', 'n'),
   ('n', 'y'),
   ('y', 'w'),
   ('w', 'h'),
   ('h', 'e'),
   ('e', 'r'),
   ('r', 'e_')],
  249],
 [[('f', 'u'), ('u', 't'), ('t', 'u'), ('u', 'r'), ('r', 'e_')], 248],
 [[('b', 'o'), ('o', 't'), ('t', 't'), ('t', 'l'), ('l', 'e_')], 246],
 [[('b', 'l'), ('l', 'u'), ('u', 'e_')], 245],
 [[('b', 'l'), ('l', 'a'), ('a', 'c'), ('c', 'k'), ('k', 'i'), ('i', 'e_')],
  243],
 [[('v', 'o'), ('o', 'i'), ('i', 'c'), ('c', 'e_')], 242],
 [[('n', 'o'), ('o', 's'), ('s', 'e_')], 239],
 [[('d', 'u'), ('u', 'k'), ('k', 'e_')], 239],
 [[('m', 'e'), ('e', 's'), ('s', 's'), ('s', 'a'), ('a', 'g'), ('g', 'e_')],
  238],
 [[('g', 'e'), ('e', 'e_')], 237],
 [[('i', 'm'),
   ('m', 'p'),
   ('p', 'o'),
   ('o', 's'),
   ('s', 's'),
   ('s', 'i'),
   ('i', 'b'),
   ('b', 'l'),
   ('l', 'e_')],
  232],
 [[('d', 'a'), ('a', 'v'), ('v', 'e_')], 231],
 [[('p', 'r'), ('r', 'i'), ('i', 'v'), ('v', 'a'), ('a', 't'), ('t', 'e_')],
  227],
 [[('k', 'n'), ('n', 'i'), ('i', 'f'), ('f', 'e_')], 217],
 [[('p', 'e'), ('e', 't'), ('t', 'e_')], 216],
 [[('f', 'o'), ('o', 'r'), ('r', 'c'), ('c', 'e_')], 212],
 [[('a', 'g'), ('g', 'e_')], 209],
 [[('w', 'h'), ('h', 'o'), ('o', 's'), ('s', 'e_')], 208],
 [[('n', 'o'), ('o', 't'), ('t', 'i'), ('i', 'c'), ('c', 'e_')], 205],
 [[('o', 'w'), ('w', 'e_')], 205],
 [[('n', 'o'), ('o', 't'), ('t', 'e_')], 205],
 [[('s', 'h'), ('h', 'a'), ('a', 'r'), ('r', 'e_')], 204],
 [[('i', 'c'), ('c', 'e_')], 201],
 [[('p', 'r'), ('r', 'i'), ('i', 'n'), ('n', 'c'), ('c', 'e_')], 201],
 [[('e', 'v'),
   ('v', 'i'),
   ('i', 'd'),
   ('d', 'e'),
   ('e', 'n'),
   ('n', 'c'),
   ('c', 'e_')],
  197],
 [[('a', 'g'), ('g', 'r'), ('r', 'e'), ('e', 'e_')], 197],
 [[('w', 'r'), ('r', 'o'), ('o', 't'), ('t', 'e_')], 197],
 [[('r', 'a'), ('a', 'i'), ('i', 's'), ('s', 'e_')], 190],
 [[('e', 's'), ('s', 'c'), ('c', 'a'), ('a', 'p'), ('p', 'e_')], 189],
 [[('s', 't'), ('t', 'o'), ('o', 'r'), ('r', 'e_')], 187],
 [[('s', 'm'), ('m', 'o'), ('o', 'k'), ('k', 'e_')], 186],
 [[('v', 'i'), ('i', 'l'), ('l', 'l'), ('l', 'a'), ('a', 'g'), ('g', 'e_')],
  185],
 [[('j', 'o'), ('o', 'k'), ('k', 'e_')], 183],
 [[('a', 'd'), ('d', 'v'), ('v', 'i'), ('i', 'c'), ('c', 'e_')], 183],
 [[('p', 'r'), ('r', 'i'), ('i', 'c'), ('c', 'e_')], 181],
 [[('t', 'i'), ('i', 'e_')], 180],
 [[('d', 'e'),
   ('e', 't'),
   ('t', 'e'),
   ('e', 'c'),
   ('c', 't'),
   ('t', 'i'),
   ('i', 'v'),
   ('v', 'e_')],
  180],
 [[('n', 'i'), ('i', 'n'), ('n', 'e_')], 180],
 [[('t', 'r'), ('r', 'e'), ('e', 'e_')], 179],
 [[('c', 'o'), ('o', 'u'), ('u', 'r'), ('r', 'a'), ('a', 'g'), ('g', 'e_')],
  178],
 [[('m', 'i'), ('i', 'd'), ('d', 'd'), ('d', 'l'), ('l', 'e_')], 177],
 [[('t', 'w'), ('w', 'i'), ('i', 'c'), ('c', 'e_')], 177],
 [[('f', 'o'), ('o', 'r'), ('r', 't'), ('t', 'u'), ('u', 'n'), ('n', 'e_')],
  176],
 [[('c', 'r'), ('r', 'i'), ('i', 'm'), ('m', 'e_')], 176],
 [[('a', 'l'), ('l', 'i'), ('i', 'c'), ('c', 'e_')], 176],
 [[('c', 'h'),
   ('h', 'a'),
   ('a', 'm'),
   ('m', 'p'),
   ('p', 'a'),
   ('a', 'g'),
   ('g', 'n'),
   ('n', 'e_')],
  176],
 [[('s', 't'), ('t', 'a'), ('a', 'g'), ('g', 'e_')], 174],
 [[('d', 'a'), ('a', 'm'), ('m', 'e_')], 169],
 [[('s', 't'), ('t', 'o'), ('o', 'n'), ('n', 'e_')], 168],
 [[('d', 'a'), ('a', 't'), ('t', 'e_')], 167],
 [[('h', 'o'),
   ('o', 'r'),
   ('r', 'r'),
   ('r', 'i'),
   ('i', 'b'),
   ('b', 'l'),
   ('l', 'e_')],
  167],
 [[('c', 'i'),
   ('i', 'g'),
   ('g', 'a'),
   ('a', 'r'),
   ('r', 'e'),
   ('e', 't'),
   ('t', 't'),
   ('t', 'e_')],
  165],
 [[('t', 'y'), ('y', 'p'), ('p', 'e_')], 163],
 [[('j', 'u'), ('u', 'l'), ('l', 'i'), ('i', 'e_')], 163],
 [[('s', 'e'), ('e', 'r'), ('r', 'v'), ('v', 'e_')], 162],
 [[('s', 'o'),
   ('o', 'm'),
   ('m', 'e'),
   ('e', 't'),
   ('t', 'i'),
   ('i', 'm'),
   ('m', 'e_')],
  162],
 [[('c', 'o'),
   ('o', 'm'),
   ('m', 'f'),
   ('f', 'o'),
   ('o', 'r'),
   ('r', 't'),
   ('t', 'a'),
   ('a', 'b'),
   ('b', 'l'),
   ('l', 'e_')],
  161],
 [[('r', 'e'),
   ('e', 's'),
   ('s', 'p'),
   ('p', 'o'),
   ('o', 'n'),
   ('n', 's'),
   ('s', 'i'),
   ('i', 'b'),
   ('b', 'l'),
   ('l', 'e_')],
  160],
 [[('s', 'e'), ('e', 't'), ('t', 't'), ('t', 'l'), ('l', 'e_')], 159],
 [[('w', 'i'), ('i', 's'), ('s', 'e_')], 158],
 [[('m', 'a'),
   ('a', 'd'),
   ('d', 'e'),
   ('e', 'm'),
   ('m', 'o'),
   ('o', 'i'),
   ('i', 's'),
   ('s', 'e'),
   ('e', 'l'),
   ('l', 'l'),
   ('l', 'e_')],
  158],
 [[('r', 'o'), ('o', 's'), ('s', 'e_')], 154],
 [[('c', 'a'), ('a', 'u'), ('u', 's'), ('s', 'e_')], 154],
 [[('a', 'b'), ('b', 'o'), ('o', 'v'), ('v', 'e_')], 153],
 [[('w', 'i'), ('i', 'r'), ('r', 'e_')], 153],
 [[('m', 'a'), ('a', 'r'), ('r', 'i'), ('i', 'e_')], 152],
 [[('n', 'u'), ('u', 'r'), ('r', 's'), ('s', 'e_')], 152],
 [[('s', 'i'), ('i', 'n'), ('n', 'g'), ('g', 'l'), ('l', 'e_')], 151],
 [[('c', 'h'), ('h', 'o'), ('o', 'i'), ('i', 'c'), ('c', 'e_')], 151],
 [[('b', 'r'), ('r', 'i'), ('i', 'd'), ('d', 'e_')], 151],
 [[('w', 'i'), ('i', 'l'), ('l', 'l'), ('l', 'i'), ('i', 'e_')], 151],
 [[('d', 'i'), ('i', 'v'), ('v', 'o'), ('o', 'r'), ('r', 'c'), ('c', 'e_')],
  150],
 [[('s', 'm'), ('m', 'i'), ('i', 'l'), ('l', 'e_')], 149],
 [[('w', 'a'), ('a', 's'), ('s', 't'), ('t', 'e_')], 148],
 [[('p', 'a'), ('a', 'l'), ('l', 'a'), ('a', 'c'), ('c', 'e_')], 147],
 [[('j', 'u'), ('u', 's'), ('s', 't'), ('t', 'i'), ('i', 'c'), ('c', 'e_')],
  146],
 [[('c', 'u'), ('u', 't'), ('t', 'e_')], 146],
 [[('c', 'a'), ('a', 't'), ('t', 't'), ('t', 'l'), ('l', 'e_')], 146],
 [[('b', 'r'), ('r', 'a'), ('a', 'v'), ('v', 'e_')], 144],
 [[('e', 'x'),
   ('x', 'p'),
   ('p', 'e'),
   ('e', 'r'),
   ('r', 'i'),
   ('i', 'e'),
   ('e', 'n'),
   ('n', 'c'),
   ('c', 'e_')],
  144],
 [[('i', 'n'),
   ('n', 's'),
   ('s', 't'),
   ('t', 'a'),
   ('a', 'n'),
   ('n', 'c'),
   ('c', 'e_')],
  144],
 [[('e', 'v'),
   ('v', 'e'),
   ('e', 'r'),
   ('r', 'y'),
   ('y', 'w'),
   ('w', 'h'),
   ('h', 'e'),
   ('e', 'r'),
   ('r', 'e_')],
  143],
 [[('s', 't'), ('t', 'r'), ('r', 'i'), ('i', 'k'), ('k', 'e_')], 143],
 [[('a', 'p'),
   ('p', 'o'),
   ('o', 'l'),
   ('l', 'o'),
   ('o', 'g'),
   ('g', 'i'),
   ('i', 'z'),
   ('z', 'e_')],
  142],
 [[('s', 't'), ('t', 'e'), ('e', 'v'), ('v', 'e_')], 142],
 [[('m', 'a'), ('a', 'c'), ('c', 'h'), ('h', 'i'), ('i', 'n'), ('n', 'e_')],
  141],
 [[('s', 'o'), ('o', 'r'), ('r', 'e_')], 140],
 [[('s', 'q'), ('q', 'u'), ('u', 'a'), ('a', 'r'), ('r', 'e_')], 137],
 [[('s', 'c'), ('c', 'e'), ('e', 'n'), ('n', 'e_')], 136],
 [[('e', 'u'), ('u', 'r'), ('r', 'o'), ('o', 'p'), ('p', 'e_')], 136],
 [[('r', 'a'), ('a', 'c'), ('c', 'e_')], 136],
 [[('s', 't'), ('t', 'o'), ('o', 'l'), ('l', 'e_')], 135],
 [[('i', 'n'),
   ('n', 'v'),
   ('v', 'i'),
   ('i', 's'),
   ('s', 'i'),
   ('i', 'b'),
   ('b', 'l'),
   ('l', 'e_')],
  134],
 [[('s', 'h'), ('h', 'a'), ('a', 'm'), ('m', 'e_')], 134],
 [[('g', 'a'), ('a', 't'), ('t', 'e_')], 134],
 [[('s', 'p'), ('p', 'o'), ('o', 'k'), ('k', 'e_')], 133],
 [[('m', 'e'),
   ('e', 'd'),
   ('d', 'i'),
   ('i', 'c'),
   ('c', 'i'),
   ('i', 'n'),
   ('n', 'e_')],
  133],
 [[("'", 'c'), ('c', 'a'), ('a', 'u'), ('u', 's'), ('s', 'e_')], 132],
 [[('d', 'e'), ('e', 'c'), ('c', 'i'), ('i', 'd'), ('d', 'e_')], 132],
 [[('h', 'o'), ('o', 'l'), ('l', 'e_')], 132],
 [[('m', 'a'), ('a', 'n'), ('n', 'a'), ('a', 'g'), ('g', 'e_')], 131],
 [[('n', 'a'), ('a', 't'), ('t', 'u'), ('u', 'r'), ('r', 'e_')], 130],
 [[('k', 'a'), ('a', 'n'), ('n', 'e_')], 129],
 [[('r', 'o'), ('o', 'p'), ('p', 'e_')], 127],
 [[('s', 'l'), ('l', 'a'), ('a', 'v'), ('v', 'e_')], 127],
 [[('b', 'a'), ('a', 't'), ('t', 't'), ('t', 'l'), ('l', 'e_')], 127],
 [[('l', 'o'), ('o', 'o'), ('o', 's'), ('s', 'e_')], 127],
 [[('p', 'a'), ('a', 'g'), ('g', 'e_')], 126],
 [[('s', 'o'),
   ('o', 'm'),
   ('m', 'e'),
   ('e', 'p'),
   ('p', 'l'),
   ('l', 'a'),
   ('a', 'c'),
   ('c', 'e_')],
  126],
 [[('m', 'i'), ('i', 'k'), ('k', 'e_')], 126],
 [[('i', 'r'), ('r', 'e'), ('e', 'n'), ('n', 'e_')], 125],
 [[('c', 'h'), ('h', 'o'), ('o', 'o'), ('o', 's'), ('s', 'e_')], 123],
 [[('n', 'o'), ('o', 'i'), ('i', 's'), ('s', 'e_')], 123],
 [[('g', 'r'), ('r', 'a'), ('a', 'c'), ('c', 'e_')], 122],
 [[('g', 'r'), ('r', 'a'), ('a', 'v'), ('v', 'e_')], 122],
 [[('a', 'p'),
   ('p', 'p'),
   ('p', 'r'),
   ('r', 'e'),
   ('e', 'c'),
   ('c', 'i'),
   ('i', 'a'),
   ('a', 't'),
   ('t', 'e_')],
  122],
 [[('l', 'a'), ('a', 'r'), ('r', 'g'), ('g', 'e_')], 121],
 [[('s', 'u'), ('u', 'i'), ('i', 'c'), ('c', 'i'), ('i', 'd'), ('d', 'e_')],
  121],
 [[('r', 'e'), ('e', 'f'), ('f', 'u'), ('u', 's'), ('s', 'e_')], 120],
 [[('h', 'o'), ('o', 'r'), ('r', 'a'), ('a', 'c'), ('c', 'e_')], 120],
 [[('c', 'o'),
   ('o', 'n'),
   ('n', 't'),
   ('t', 'i'),
   ('i', 'n'),
   ('n', 'u'),
   ('u', 'e_')],
  119],
 [[('c', 'o'),
   ('o', 'm'),
   ('m', 'p'),
   ('p', 'l'),
   ('l', 'e'),
   ('e', 't'),
   ('t', 'e_')],
  119],
 [[('t', 'a'), ('a', 's'), ('s', 't'), ('t', 'e_')], 117],
 [[('r', 'e'),
   ('e', 'c'),
   ('c', 'o'),
   ('o', 'g'),
   ('g', 'n'),
   ('n', 'i'),
   ('i', 'z'),
   ('z', 'e_')],
  117],
 [[('p', 'i'), ('i', 'p'), ('p', 'e_')], 117],
 [[('n', 'e'), ('e', 'r'), ('r', 'v'), ('v', 'e_')], 117],
 [[('c', 'o'),
   ('o', 'n'),
   ('n', 's'),
   ('s', 'c'),
   ('c', 'i'),
   ('i', 'e'),
   ('e', 'n'),
   ('n', 'c'),
   ('c', 'e_')],
  116],
 [[('t', 'r'), ('r', 'a'), ('a', 'd'), ('d', 'e_')], 116],
 [[('b', 'i'), ('i', 't'), ('t', 'e_')], 116],
 [[('s', 'i'), ('i', 'l'), ('l', 'e'), ('e', 'n'), ('n', 'c'), ('c', 'e_')],
  115],
 [[('d', 'u'), ('u', 'e_')], 114],
 [[('s', 'p'), ('p', 'a'), ('a', 'r'), ('r', 'e_')], 114],
 [[('b', 'e'), ('e', 'c'), ('c', 'a'), ('a', 'm'), ('m', 'e_')], 113],
 [[('j', 'a'), ('a', 'n'), ('n', 'e_')], 112],
 [[('p', 'u'), ('u', 'r'), ('r', 'p'), ('p', 'o'), ('o', 's'), ('s', 'e_')],
  112],
 [[('s', 'h'), ('h', 'a'), ('a', 'k'), ('k', 'e_')], 112],
 [[('b', 'e'), ('e', 'l'), ('l', 'l'), ('l', 'e_')], 112],
 [[('h', 'a'),
   ('a', 'n'),
   ('n', 'd'),
   ('d', 's'),
   ('s', 'o'),
   ('o', 'm'),
   ('m', 'e_')],
  111],
 [[('a', 'r'), ('r', 'r'), ('r', 'a'), ('a', 'n'), ('n', 'g'), ('g', 'e_')],
  109],
 [[('m', 'o'), ('o', 'n'), ('n', 't'), ('t', 'e_')], 109],

In [579]:
kurwa_1[:10]

[[['t', 'h', 'e', '_'], 89859],
 [['m', 'e', '_'], 29977],
 [['h', 'e', '_'], 26149],
 [['w', 'e', '_'], 23370],
 [['b', 'e', '_'], 20137],
 [['h', 'a', 'v', 'e', '_'], 19830],
 [["'", 'r', 'e', '_'], 15483],
 [['h', 'e', 'r', 'e', '_'], 15059],
 [['a', 'r', 'e', '_'], 14431],
 [['t', 'h', 'e', 'r', 'e', '_'], 14310]]

In [580]:
kurwa_2[:10]

[[['t', 'h', 'e_'], 89859],
 [['m', 'e_'], 29977],
 [['h', 'e_'], 26149],
 [['w', 'e_'], 23370],
 [['b', 'e_'], 20137],
 [['h', 'a', 'v', 'e_'], 19830],
 [["'", 'r', 'e_'], 15483],
 [['h', 'e', 'r', 'e_'], 15059],
 [['a', 'r', 'e_'], 14431],
 [['t', 'h', 'e', 'r', 'e_'], 14310]]

In [621]:
dct_c2

{('.', '_'): 435802,
 ('t', '_'): 405188,
 ('t', 'h'): 286912,
 ('s', '_'): 279133,
 ('o', 'u'): 241694,
 ('n', '_'): 224509,
 ('d', '_'): 199163,
 ('i', 'n'): 187051,
 (',', '_'): 177291,
 ('e', 'r'): 171377,
 ('y', '_'): 170823,
 ('r', '_'): 169575,
 ('y', 'o'): 161552,
 ('o', '_'): 158570,
 ('a', 'n'): 156511,
 ('h', 'a'): 141491,
 ('u', '_'): 135623,
 ('h', 'e_'): 127255,
 ('i', '_'): 126232,
 ('h', 'e'): 123261,
 ('o', 'n'): 122342,
 ('a', 't'): 120991,
 ('t', 'o'): 108364,
 ('l', '_'): 107287,
 ('l', 'l'): 104796,
 ('i', 't'): 104719,
 ('n', 'g'): 99478,
 ('r', 'e_'): 92025,
 ('g', '_'): 89713,
 ('o', 'r'): 88425,
 ('h', 'i'): 86574,
 ('n', 'd'): 86449,
 ('i', 's'): 85924,
 ('e', 'n'): 85895,
 ('?', '_'): 84640,
 ('a', 'r'): 82818,
 ('a', '_'): 81686,
 ('s', 't'): 78706,
 ('n', 'o'): 77134,
 ('e', 's'): 71709,
 ('e', 'a'): 68049,
 ('h', '_'): 64617,
 ('f', '_'): 63686,
 ('m', 'e_'): 62434,
 ('a', 'l'): 61623,
 ('w', 'h'): 61169,
 ('m', '_'): 61166,
 ('d', 'o'): 60236,
 ('e', 'l'): 59120,
 ('a', 's'): 58861,
 ('r', 'e'): 58092,
 ('o', 'w'): 57751,
 ("'", 's'): 57136,
 ('t', 'e'): 56628,
 ('e', 'd'): 55544,
 ('u', 'r'): 54896,
 ('h', 'o'): 54478,
 ('u', 't'): 53640,
 ('w', 'a'): 53622,
 ('e', 't'): 53453,
 ('v', 'e_'): 52048,
 ('o', 'm'): 51184,
 ('l', 'i'): 50694,
 ("'", 't'): 50517,
 ('w', '_'): 50017,
 ('k', '_'): 49455,
 ('o', 't'): 49292,
 ('g', 'o'): 47979,
 ('n', 't'): 47700,
 ('r', 'i'): 47625,
 ('m', 'a'): 47126,
 ('o', 'f'): 46999,
 ('c', 'o'): 45898,
 ('l', 'e'): 44031,
 ('v', 'e'): 43560,
 ('u', 's'): 43270,
 ('c', 'a'): 42797,
 ('t', 'i'): 42341,
 ('r', 'o'): 42178,
 ('o', 'o'): 42081,
 ('l', 'o'): 41988,
 ('s', 'o'): 39673,
 ('f', 'o'): 39473,
 ('a', 'y'): 39460,
 ('s', 'e'): 39335,
 ('g', 'h'): 37912,
 ('b', 'e'): 37217,
 ('w', 'i'): 36661,
 ('t', 'a'): 36642,
 ('n', 'e'): 36388,
 ('i', 'l'): 35803,
 ('m', 'e'): 35347,
 ('s', 'h'): 34641,
 ('c', 'h'): 33317,
 ('r', 'a'): 32061,
 ('a', 'v'): 31966,
 ('i', 'g'): 31932,
 ('l', 'a'): 31705,
 ('d', 'e'): 31219,
 ('l', 'd'): 31148,
 ('!', '_'): 30794,
 ('i', 'd'): 30571,
 ('a', 'i'): 30544,
 ('g', 'e'): 30475,
 ('h', 't'): 30254,
 ('e', 'e'): 29902,
 ('a', 'd'): 29892,
 ('d', 'i'): 29680,
 ('i', 'm'): 29610,
 ('r', 's'): 29565,
 ('s', 'e_'): 29113,
 ('s', 'i'): 29060,
 ('r', 'y'): 28834,
 ('w', 'e'): 28681,
 ('w', 'o'): 28647,
 ('u', 'l'): 28528,
 ('u', 'n'): 28361,
 ('b', 'o'): 27687,
 ('k', 'e_'): 26244,
 ('m', 'i'): 25809,
 ('p', '_'): 25600,
 ('i', 'c'): 25428,
 ('m', 'o'): 25424,
 ('a', 'c'): 25292,
 ('p', 'e'): 24925,
 ('n', 'e_'): 24775,
 ('b', 'u'): 24142,
 ('l', 'e_'): 23801,
 ('w', 'e_'): 23706,
 ('t', 't'): 23677,
 ('o', 'l'): 23644,
 ('l', 'y'): 23512,
 ('s', 's'): 23332,
 ('m', 'y'): 23323,
 ('s', 'a'): 23275,
 ('n', 'i'): 23248,
 ('e', 'v'): 23140,
 ('b', 'e_'): 22903,
 ('i', 'r'): 22736,
 ('e', 'y'): 22413,
 ('a', 'm'): 22183,
 ('c', 'k'): 22011,
 ('i', 'f'): 21415,
 ('t', 'r'): 21409,
 ('y', 'e'): 21246,
 ('e', 'm'): 21140,
 ('o', 'd'): 20942,
 ('r', 't'): 20437,
 ('c', 'e_'): 20400,
 ('n', 'k'): 20121,
 ("'", 'l'): 20068,
 ('a', 'k'): 19921,
 ('i', 'e'): 19524,
 ('f', 'i'): 18897,
 ('k', 'n'): 18360,
 ('a', 'b'): 18160,
 ('p', 'l'): 18092,
 ('n', 's'): 17802,
 ('d', 'a'): 17622,
 ('o', 's'): 17389,
 ('b', 'a'): 17346,
 ('k', 'i'): 17251,
 ("'", 'm'): 17037,
 ('f', 'r'): 16526,
 ('p', 'a'): 16518,
 ('r', 'r'): 16403,
 ('e', 'c'): 16181,
 ('r', 'd'): 15941,
 ('n', 'c'): 15796,
 ('n', 'y'): 15582,
 ("'", 'r'): 15562,
 ('i', 'o'): 15354,
 ('u', 'p'): 15265,
 ('n', 'a'): 15244,
 ('s', 'u'): 15192,
 ('p', 'o'): 15182,
 ('i', 'v'): 15138,
 ('k', 'e'): 14879,
 ('p', 'r'): 14867,
 ('a', 'p'): 14004,
 ('o', 'p'): 13928,
 ('o', 'k'): 13890,
 ('u', 'g'): 13794,
 ('e', 'e_'): 13708,
 ('a', 'g'): 13270,
 ('b', 'l'): 13249,
 ('o', 'v'): 13184,
 ('o', 'i'): 12969,
 ('i', 'k'): 12955,
 ('g', 'i'): 12820,
 ('f', 'e'): 12768,
 ('c', 't'): 12719,
 ('j', 'u'): 12313,
 ('m', 'u'): 12152,
 ('f', 'a'): 12075,
 ('t', 's'): 11837,
 ('t', 'e_'): 11801,
 ("'", 'v'): 11583,
 ('o', 'h'): 11402,
 ('g', 'a'): 11225,
 ('t', 'l'): 11083,
 ('n', 'n'): 11083,
 ('d', 'n'): 10734,
 ('r', 'n'): 10594,
 ('c', 'e'): 10391,
 ('d', 'r'): 10366,
 ('v', 'i'): 10260,
 ('e', 'p'): 10242,
 ('u', 'c'): 10232,
 ('p', 'p'): 10213,
 ('b', 'r'): 10186,
 ('f', 'f'): 10034,
 ('m', 'r'): 9956,
 ('a', 'u'): 9823,
 ('d', 'y'): 9791,
 ('t', 'y'): 9687,
 ('w', 'n'): 9593,
 ('g', 'r'): 9588,
 ('t', 'u'): 9527,
 ('r', 'l'): 9430,
 ('y', 's'): 9406,
 ('p', 'i'): 9275,
 ('h', 'y'): 9149,
 ('s', 'p'): 9003,
 ('r', 'u'): 8939,
 ('"', '_'): 8870,
 ('e', 'f'): 8710,
 ('e', 'x'): 8613,
 ('e', 'w'): 8254,
 ('h', 'u'): 8161,
 ('a', 'w'): 8001,
 ('g', 'u'): 7969,
 ('d', 's'): 7933,
 ('f', 'u'): 7915,
 ("'", 'd'): 7898,
 ('-', '_'): 7821,
 ('m', 'p'): 7739,
 ('c', 'i'): 7662,
 ('i', 'a'): 7588,
 ('c', 'r'): 7544,
 ('q', 'u'): 7332,
 ('c', 'l'): 7330,
 ('g', 'e_'): 7157,
 ('e', 'i'): 7150,
 ('s', 'n'): 7136,
 ('b', 'i'): 7069,
 ('d', 'e_'): 7065,
 ('b', 'y'): 6974,
 ('u', 'i'): 6965,
 ('o', 'c'): 6931,
 ('a', 'f'): 6916,
 ('l', 's'): 6748,
 ('k', 's'): 6623,
 ('f', 't'): 6508,
 ('r', 'g'): 6341,
 ('j', 'o'): 6237,
 ('c', 'u'): 6200,
 ('r', 'm'): 6185,
 ('o', 'b'): 6066,
 ('s', 'c'): 6058,
 ('n', 'l'): 6057,
 ('r', 'k'): 6057,
 ('l', 'k'): 5993,
 ('l', 'f'): 5983,
 ('a', 'h'): 5832,
 ('h', 'r'): 5830,
 ('p', 'u'): 5780,
 ('i', 'e_'): 5581,
 ('y', 't'): 5522,
 ('e', 'o'): 5384,
 ('m', 'b'): 5282,
 ('l', 'u'): 5234,
 ('u', 'm'): 5228,
 ('o', 'e'): 5220,
 ('o', 'y'): 5158,
 ('s', 'k'): 5103,
 ('g', 's'): 5063,
 ('o', 'a'): 4839,
 ('u', 'e'): 4621,
 ('e', 'g'): 4467,
 ('t', 'w'): 4438,
 ('f', 'e_'): 4436,
 ('n', 'u'): 4354,
 ('i', 'p'): 4349,
 ('y', 'i'): 4227,
 ('y', 'b'): 4119,
 ('s', 'l'): 4079,
 ('u', 'b'): 4056,
 ('g', 'l'): 4033,
 ('l', 't'): 4031,
 ('t', 'c'): 3994,
 ('p', 's'): 3953,
 ('o', 'g'): 3938,
 ('v', 'a'): 3919,
 ('p', 't'): 3892,
 ('m', 'm'): 3806,
 ('u', 'd'): 3737,
 ('0', '_'): 3734,
 ('p', 'h'): 3699,
 ('d', 'd'): 3650,
 ('d', 'u'): 3641,
 ('c', '_'): 3637,
 ('r', 'c'): 3547,
 ('u', 'a'): 3499,
 ('s', 'w'): 3479,
 ('i', 'b'): 3438,
 ('b', '_'): 3407,
 ('f', 'l'): 3375,
 ('m', 's'): 3341,
 ('l', 'p'): 3328,
 ('w', 'r'): 3090,
 ('k', 'a'): 2976,
 ('s', 'm'): 2963,
 ('j', 'e'): 2930,
 ('p', 'e_'): 2867,
 ("'", '_'): 2865,
 ('w', 's'): 2835,
 ('r', 'v'): 2717,
 ('j', 'a'): 2657,
 ('d', 'l'): 2616,
 ('s', 'y'): 2567,
 ('v', 'o'): 2555,
 ('l', 'w'): 2527,
 ('u', 'y'): 2395,
 ('x', 'p'): 2388,
 ('c', 'c'): 2368,
 ('g', 'n'): 2361,
 ('u', 'e_'): 2326,
 ('g', 'g'): 2311,
 ('x', 'c'): 2298,
 ('x', '_'): 2234,
 ('0', '0'): 2222,
 ('e', 'b'): 2174,
 ('u', 'h'): 2145,
 ('r', 'f'): 2136,
 ('y', 'a'): 2039,
 ('i', 'z'): 2016,
 (':', '_'): 1991,
 ('x', 't'): 1958,
 ('y', 'e_'): 1929,
 ('p', 'y'): 1928,
 ('l', 'm'): 1918,
 ('e', 'h'): 1893,
 ('r', 'p'): 1836,
 ('e', 'u'): 1831,
 ('e', 'k'): 1828,
 ('n', 'f'): 1766,
 ('n', 'v'): 1704,
 ('k', 'y'): 1631,
 ('a', 'z'): 1621,
 ('h', 'n'): 1607,
 ('d', 'g'): 1607,
 ('c', 'y'): 1570,
 ('i', 'x'): 1564,
 ('l', 'r'): 1499,
 ('r', 'h'): 1478,
 ('u', 'f'): 1443,
 ('r', 'b'): 1386,
 ('t', 'm'): 1382,
 ('s', 'b'): 1380,
 ('n', "'"): 1315,
 ('l', 'v'): 1307,
 ('b', 'b'): 1298,
 ('y', 'w'): 1297,
 ('b', 's'): 1198,
 ('x', 'a'): 1193,
 ('y', 'm'): 1090,
 ('z', 'e'): 1084,
 ('t', 'n'): 1062,
 ('k', 'l'): 1053,
 ('z', 'e_'): 1048,
 ('x', 'i'): 966,
 ('o', 'e_'): 965,
 ('h', 'm'): 945,
 ('z', 'y'): 925,
 ('5', '_'): 904,
 ('h', 's'): 897,
 ('z', 'a'): 884,
 ('z', 'i'): 879,
 ('1', '0'): 877,
 ('k', 'o'): 867,
 ('a', 'x'): 843,
 ('d', 'b'): 841,
 ('n', 'r'): 795,
 ('d', 'm'): 795,
 ('j', 'i'): 791,
 ('o', 'x'): 774,
 ("'", 'e'): 745,
 ('x', 'e'): 735,
 ('y', 'l'): 722,
 ('w', 'f'): 712,
 ('2', '_'): 699,
 ('d', 'v'): 697,
 ('y', 'p'): 696,
 ('y', 'n'): 696,
 ('1', '_'): 694,
 ('a', 'j'): 692,
 ('r', 'w'): 660,
 ('z', '_'): 649,
 ('l', 'c'): 623,
 ('s', 'q'): 602,
 ('w', 'l'): 599,
 ('g', 'y'): 597,
 ('a', 'e'): 589,
 ('n', 'j'): 587,
 ("'", 'a'): 584,
 ('n', 'h'): 559,
 ('l', 'b'): 544,
 ('m', 'c'): 542,
 ('2', '0'): 535,
 ('k', 'r'): 534,
 ('w', 'd'): 520,
 ('b', 't'): 514,
 ('d', 'f'): 513,
 ('d', 'w'): 510,
 ('t', 'f'): 498,
 ('i', 'u'): 482,
 ('5', '0'): 476,
 ('u', 'k'): 475,
 ('f', 'y'): 475,
 ('3', '_'): 474,
 ('g', 't'): 470,
 ('4', '_'): 466,
 ('v', 'y'): 464,
 ('h', 'l'): 462,
 ('e', 'q'): 460,
 ('8', '_'): 454,
 ('s', "'"): 453,
 ('3', '0'): 446,
 ('s', 'f'): 429,
 ('7', '_'): 422,
 ('i', 'i'): 418,
 ('n', 'm'): 417,
 ('n', 'b'): 414,
 ('b', 'j'): 413,
 ('m', 'n'): 412,
 ('y', 'c'): 397,
 ('t', 'z'): 394,
 ('6', '_'): 393,
 ('w', 'y'): 392,
 ('o', 'z'): 392,
 ('z', 'z'): 390,
 ('c', 's'): 376,
 ('z', 'o'): 369,
 ('e', 'z'): 366,
 ('v', '_'): 360,
 ('k', 'u'): 349,
 ('y', 'r'): 338,
 ('k', 'f'): 331,
 ('k', 'h'): 328,
 ('s', 'd'): 326,
 ('m', 'f'): 321,
 ('1', '5'): 320,
 ('y', 'd'): 318,
 ("'", 'c'): 313,
 ('h', 'b'): 306,
 ('n', 'w'): 289,
 ('1', '2'): 286,
 ('9', '_'): 286,
 ('l', 'g'): 286,
 ('c', 'q'): 281,
 ('$', '_'): 280,
 ('s', 'g'): 276,
 ('1', '9'): 275,
 ('u', 'z'): 265,
 ('g', "'"): 262,
 ('u', 'o'): 261,
 ("'", 'i'): 257,
 ('h', 'd'): 257,
 ('n', 'q'): 248,
 ('4', '0'): 228,
 ('n', 'p'): 224,
 ('i', 'q'): 223,
 ('h', 'w'): 219,
 ('u', 'v'): 215,
 ('d', 'h'): 196,
 ('t', 'b'): 191,
 ('1', '1'): 190,
 ('a', 'o'): 190,
 ('h', 'h'): 184,
 ('l', 'n'): 179,
 ('g', 'f'): 177,
 ('n', 'z'): 177,
 ('f', 's'): 176,
 ('d', 'p'): 173,
 ('2', '5'): 173,
 ('b', 'v'): 169,
 ('1', '8'): 167,
 ('y', 'f'): 154,
 ('a', 'a'): 154,
 ('n', 'x'): 153,
 ('d', 'c'): 150,
 ('p', 'm'): 149,
 ('w', 'k'): 148,
 ('c', 'g'): 144,
 ('i', 'y'): 142,
 ('e', 'j'): 142,
 ('y', 'h'): 140,
 ('m', 'l'): 136,
 ("'", 'n'): 134,
 ('z', 'l'): 132,
 ('k', 'm'): 127,
 ('g', 'm'): 127,
 ('u', 'x'): 127,
 ('h', 'f'): 126,
 ('w', 'b'): 126,
 ('v', 'l'): 125,
 ('j', '_'): 123,
 ('y', 'g'): 122,
 ('d', 't'): 121,
 ('k', 't'): 120,
 ('g', 'd'): 114,
 ('l', 'h'): 114,
 ('6', '0'): 112,
 ('t', 'p'): 112,
 ('w', 't'): 111,
 ('x', 'h'): 111,
 ('m', 't'): 111,
 ('1', '6'): 109,
 ('t', 'g'): 108,
 ('1', '7'): 107,
 ('h', 'k'): 107,
 ('k', 'w'): 107,
 ('v', 'u'): 106,
 ('s', 'r'): 105,
 ('h', 'c'): 103,
 ('1', '4'): 101,
 ('y', 'u'): 101,
 ('2', '4'): 94,
 ('d', 'q'): 90,
 ("'", 'h'): 90,
 ('i', 'j'): 90,
 ('d', 'j'): 90,
 ('v', 'r'): 89,
 ('1', '3'): 88,
 ('c', 'n'): 86,
 ('g', 'w'): 85,
 ('s', 'v'): 83,
 ('4', '5'): 82,
 ('c', 'f'): 80,
 ('r', 'z'): 78,
 ('m', 'h'): 76,
 ('d', 'k'): 74,
 ('9', '0'): 74,
 ('9', '3'): 73,
 ('c', 'd'): 72,
 ('p', 'k'): 70,
 ('o', 'q'): 69,
 ('l', 'z'): 69,
 ('a', 'q'): 68,
 ('r', 'j'): 68,
 ('z', 'u'): 67,
 ('9', '2'): 65,
 ('3', '5'): 64,
 ('3', '2'): 64,
 ('o', 'j'): 64,
 ('8', '0'): 64,
 ('s', 'z'): 62,
 ('g', 'b'): 62,
 ('x', 'o'): 61,
 ('2', '1'): 60,
 ('7', '0'): 60,
 ('2', '2'): 59,
 ('2', '7'): 59,
 ('k', 'b'): 58,
 ('%', '_'): 57,
 ('p', 'n'): 57,
 ('c', 'z'): 56,
 ('b', 'm'): 55,
 ('3', '1'): 55,
 ('p', 'f'): 54,
 ('c', 'm'): 52,
 ('f', 'w'): 51,
 ('p', 'b'): 50,
 ('2', '6'): 49,
 ('w', 'p'): 48,
 ('u', 'j'): 48,
 ('[', '_'): 47,
 (']', '_'): 47,
 ('u', 'w'): 47,
 ('9', '4'): 46,
 ('r', 'q'): 45,
 ('2', '9'): 45,
 ('x', 'l'): 44,
 ('x', 'u'): 42,
 ('7', '5'): 42,
 ('0', 't'): 42,
 ('i', 'w'): 42,
 ("'", 'y'): 41,
 ('x', 'y'): 41,
 ('2', '8'): 41,
 ('2', '3'): 41,
 ('/', '_'): 40,
 ('4', '8'): 40,
 ('3', '7'): 40,
 ('b', 'd'): 40,
 ('j', 'e_'): 39,
 ('k', 'g'): 39,
 ('p', 'j'): 39,
 ('i', 'h'): 39,
 ('3', '6'): 38,
 ('4', '2'): 38,
 ('a', 'e_'): 37,
 ('5', 't'): 36,
 ('3', '8'): 36,
 ('b', 'w'): 35,
 ('y', 'z'): 35,
 ('p', 'w'): 35,
 ('0', '1'): 35,
 ('t', 'd'): 34,
 ('w', 'u'): 34,
 ('w', 'm'): 34,
 ('9', '1'): 34,
 ('k', 'd'): 33,
 ('6', '5'): 33,
 ("'", 'b'): 33,
 ('4', '1'): 33,
 ('h', 'p'): 33,
 ('f', 'm'): 32,
 ('7', 't'): 32,
 ('k', 'p'): 32,
 ('k', 'k'): 32,
 ('x', 'q'): 31,
 ('w', 'c'): 31,
 ('x', 'f'): 30,
 ('o', "'"): 30,
 ('4', 't'): 30,
 ('t', 'j'): 30,
 ('3', '4'): 30,
 ('8', '8'): 30,
 ('t', "'"): 29,
 ("'", 'w'): 29,
 ('c', 'p'): 28,
 ('2', 'n'): 28,
 ('z', 'k'): 28,
 ('9', '5'): 28,
 ('3', '3'): 28,
 ('j', 'r'): 27,
 ('l', 'j'): 27,
 ('z', 'g'): 27,
 ('q', '_'): 27,
 ('8', 't'): 27,
 ('t', 'k'): 27,
 ('(', '_'): 26,
 (')', '_'): 26,
 ('y', 'k'): 26,
 ('1', 's'): 26,
 ("'", 'o'): 26,
 ('c', 'w'): 25,
 ('4', '3'): 25,
 ('v', 'v'): 25,
 ('5', '1'): 25,
 ('x', 'e_'): 24,
 ('8', '5'): 24,
 ('y', 'j'): 23,
 ('4', '7'): 23,
 ('f', 'h'): 23,
 ('y', 'v'): 22,
 ('9', '8'): 22,
 ('6', 't'): 22,
 ('5', '2'): 22,
 ('0', '5'): 22,
 ('p', 'c'): 22,
 ('9', '6'): 22,
 ('e', "'"): 22,
 ('g', 'k'): 21,
 ('3', '9'): 21,
 ('b', 'c'): 21,
 ('9', 't'): 21,
 ('f', 'j'): 21,
 ('0', '4'): 21,
 ('f', 'c'): 20,
 ('z', 't'): 20,
 ('3', 'r'): 20,
 ('l', "'"): 20,
 ('5', '5'): 20,
 ('9', '9'): 20,
 ('b', 'n'): 20,
 ('7', '1'): 20,
 ('k', 'c'): 19,
 ('4', '4'): 19,
 ('6', '6'): 19,
 ('5', '9'): 19,
 ('x', 'w'): 18,
 ('v', 'g'): 18,
 ('h', 'q'): 18,
 ('h', 'j'): 18,
 ('4', '6'): 18,
 ('u', 'q'): 18,
 ('k', 'v'): 17,
 ('z', 'b'): 17,
 ('0', '8'): 17,
 ('5', '4'): 17,
 ('8', '1'): 17,
 ('y', "'"): 17,
 ('9', '7'): 17,
 ('d', 'z'): 16,
 ('7', '2'): 16,
 ('6', '2'): 16,
 ('7', '3'): 16,
 ('8', '6'): 16,
 ('0', '3'): 16,
 ('z', 'v'): 15,
 ('u', 'u'): 15,
 ('i', "'"): 15,
 ("'", 'u'): 15,
 ('f', 'b'): 15,
 ('4', '9'): 15,
 ('s', 'j'): 15,
 ('7', '7'): 15,
 ('8', '9'): 15,
 ('g', 'p'): 15,
 ('m', 'q'): 14,
 ('3', 't'): 14,
 ('h', 'v'): 14,
 ('c', 'b'): 14,
 ('f', 'n'): 14,
 ('d', "'"): 14,
 ('0', '2'): 14,
 ('0', 's'): 14,
 ('6', '4'): 14,
 ("'", 'p'): 14,
 ('l', 'q'): 13,
 ('t', 'v'): 13,
 ('v', 's'): 13,
 ('5', '6'): 13,
 ('6', '1'): 13,
 ('v', 'n'): 13,
 ('8', '7'): 13,
 ('8', '4'): 13,
 ('5', '7'): 13,
 ('0', '9'): 13,
 ('8', '2'): 13,
 ('w', 'w'): 12,
 ('5', '8'): 12,
 ('5', '3'): 12,
 ('6', '7'): 12,
 ('k', 'j'): 12,
 ('7', '6'): 12,
 ('0', '6'): 11,
 ('m', 'w'): 11,
 ('6', '9'): 11,
 ('7', '4'): 11,
 ('6', '3'): 11,
 ('r', "'"): 11,
 ('u', "'"): 10,
 ('v', 'k'): 10,
 ('b', 'p'): 10,
 ('p', 'g'): 10,
 ('m', 'd'): 10,
 ('z', 'h'): 10,
 ('2', 't'): 9,
 ('m', 'k'): 9,
 ('g', 'c'): 9,
 ('l', '1'): 9,
 ('8', '3'): 9,
 ('b', 'f'): 9,
 ('7', '8'): 9,
 ('6', '8'): 9,
 ('7', '9'): 9,
 ("'", '3'): 9,
 ("'", 'f'): 9,
 ('0', '7'): 8,
 ('b', 'h'): 8,
 ('s', '1'): 7,
 ("'", '2'): 7,
 ('z', 'w'): 7,
 ('p', 'd'): 7,
 ('1', 't'): 6,
 ('r', 'x'): 6,
 ('m', 'g'): 6,
 ('5', 'c'): 6,
 ('w', 'g'): 6,
 ('z', 's'): 6,
 ("'", '1'): 6,
 ('b', 'k'): 5,
 ('r', '1'): 5,
 ('v', 't'): 5,
 ('5', 'o'): 5,
 ('h', "'"): 5,
 ('m', 'z'): 5,
 ('x', 'n'): 5,
 ('m', 'v'): 5,
 ('a', "'"): 5,
 ("'", '4'): 5,
 ('j', 'v'): 4,
 ('2', 'k'): 4,
 ('p', 'z'): 4,
 ('z', 'r'): 4,
 ('x', '4'): 4,
 ("'", 'k'): 4,
 ('k', "'"): 4,
 ('f', 'v'): 4,
 ("'", 'g'): 4,
 ('f', 'g'): 4,
 ('h', 'g'): 3,
 ('6', 'f'): 3,
 ("'", '0'): 3,
 ('0', 'o'): 3,
 ('5', 'p'): 3,
 ('j', 's'): 3,
 ('c', '2'): 3,
 ('2', 'h'): 3,
 ("'", '7'): 3,
 ('x', 'b'): 3,
 ('z', 'p'): 3,
 ('x', 'x'): 3,
 ('p', "'"): 3,
 ('y', 'x'): 3,
 ('y', 'y'): 3,
 ('j', 'p'): 3,
 ('w', "'"): 3,
 ('p', 'v'): 3,
 ('6', 'a'): 2,
 ('m', '4'): 2,
 ('l', 'x'): 2,
 ('x', 'v'): 2,
 ('a', '1'): 2,
 ('w', '9'): 2,
 ('9', 'y'): 2,
 ('2', 'a'): 2,
 ('j', 'm'): 2,
 ('f', 'k'): 2,
 ('g', 'v'): 2,
 ('b', 'z'): 2,
 ('q', 'a'): 2,
 ('v', 'c'): 2,
 ('2', 'o'): 2,
 ('b', 'x'): 2,
 ('z', 'c'): 2,
 ('f', 'p'): 2,
 ('8', 's'): 2,
 ("'", '9'): 2,
 ("'", '5'): 2,
 ('0', 'k'): 2,
 ('4', 'a'): 2,
 ('b', 'g'): 2,
 ("'", 'j'): 2,
 ('h', '2'): 2,
 ('0', 'l'): 2,
 ('j', 'd'): 2,
 ('2', 's'): 2,
 ('j', 'n'): 1,
 ('0', 'r'): 1,
 ('f', "'"): 1,
 ('0', 'm'): 1,
 ('w', 'z'): 1,
 ('g', 'z'): 1,
 ('3', 'o'): 1,
 ('4', 'o'): 1,
 ('6', 'o'): 1,
 ('1', 'c'): 1,
 ('1', 'a'): 1,
 ('g', '9'): 1,
 ('v', 'd'): 1,
 ('m', '2'): 1,
 ('k', '6'): 1,
 ('9', 'a'): 1,
 ('j', 'l'): 1,
 ('z', 'm'): 1,
 ('0', "'"): 1,
 ('l', '2'): 1,
 ('9', 'l'): 1,
 ('l', '5'): 1,
 ('8', 'h'): 1,
 ('4', 'm'): 1,
 ('8', 'p'): 1,
 ('m', '1'): 1,
 ('a', '3'): 1,
 ('q', 'e'): 1,
 ('4', 'x'): 1,
 ('9', 'b'): 1,
 ('5', 'f'): 1,
 ('4', 's'): 1,
 ('5', 's'): 1,
 ('b', '7'): 1,
 ('o', '0'): 1,
 ('2', 'c'): 1,
 ('w', '7'): 1,
 ('7', 'b'): 1,
 ('8', 'x'): 1,
 ('x', '1'): 1,
 ('0', 'n'): 1,
 ("'", '6'): 1,
 ('r', '5'): 1,
 ('s', '5'): 1,
 ('m', '5'): 1,
 ('0', 'c'): 1,
 ('q', 's'): 1,
 ('9', 's'): 1,
 ('z', 'n'): 1,
 ('m', "'"): 1,
 ('b', "'"): 1,
 ('y', '1'): 1,
 ('5', 'h'): 1,
 ("'", '8'): 1,
 ('k', '4'): 1,
 ('z', 'f'): 1,
 ('7', 'p'): 1,
 ('q', 'v'): 1,
 ('v', 'f'): 1,
 ('6', 's'): 1,
 ('3', 'd'): 1,
 ('x', "'"): 1,
 ('7', 'o'): 1,
 ('8', 'o'): 1,
 ('6', 'l'): 1,
 ('c', 'v'): 1,
 ("'", 'e_'): 1,
 ('x', 'm'): 1,
 ('x', '6'): 1,
 ('0', 'f'): 1,
 ("'", 'q'): 1,
 ('i', '8'): 1,
 ('8', 'n'): 1,
 ('x', 'g'): 1,
 ('d', '2'): 1,
 ('5', 'l'): 1,
 ('8', 'b'): 1,
 ('o', '4'): 1,
 ('z', 'd'): 1,
 ('g', '2'): 1,
 ('p', 'x'): 1,
 ('7', 'h'): 1,
 ('h', '3'): 1,
 ('6', 'e_'): 1}

In [529]:
test_vocab2

[[['.', '_'], 435802],
 [[',', '_'], 177291],
 [['y', 'o', 'u', '_'], 134548],
 [['i', '_'], 122767],
 [['t', 'h', 'e_'], 89859],
 [['?', '_'], 84640],
 [['t', 'o', '_'], 73192],
 [['a', '_'], 61661],
 [["'", 's', '_'], 57045],
 [['i', 't', '_'], 55074],
 [["'", 't', '_'], 50411],
 [['t', 'h', 'a', 't', '_'], 43020],
 [['a', 'n', 'd', '_'], 41124],
 [['o', 'f', '_'], 39514],
 [['i', 'n', '_'], 32142],
 [['!', '_'], 30794],
 [['m', 'e_'], 29977],
 [['w', 'h', 'a', 't', '_'], 26868],
 [['i', 's', '_'], 26378],
 [['h', 'e_'], 26149],
 [['f', 'o', 'r', '_'], 23935],
 [['w', 'e_'], 23370],
 [['t', 'h', 'i', 's', '_'], 20366],
 [['y', 'o', 'u', 'r', '_'], 20158],
 [['b', 'e_'], 20137],
 [['m', 'y', '_'], 20105],
 [["'", 'l', 'l', '_'], 20011],
 [['h', 'a', 'v', 'e_'], 19830],
 [['d', 'o', 'n', '_'], 18888],
 [['d', 'o', '_'], 18663],
 [['o', 'n', '_'], 18052],
 [['n', 'o', '_'], 17694],
 [["'", 'm', '_'], 16935],
 [['a', 'l', 'l', '_'], 16776],
 [['b', 'u', 't', '_'], 16067],
 [['w', 'a', 's', '_'], 15781],
 [["'", 'r', 'e_'], 15483],
 [['w', 'i', 't', 'h', '_'], 15435],
 [['c', 'a', 'n', '_'], 15365],
 [['h', 'e', 'r', 'e_'], 15059],
 [['n', 'o', 't', '_'], 14896],
 [['a', 'r', 'e_'], 14431],
 [['k', 'n', 'o', 'w', '_'], 14310],
 [['t', 'h', 'e', 'r', 'e_'], 14310],
 [['h', 'i', 'm', '_'], 14193],
 [['g', 'e', 't', '_'], 13469],
 [['i', 'f', '_'], 12400],
 [['w', 'e', 'l', 'l', '_'], 12155],
 [['t', 'h', 'e', 'y', '_'], 11807],
 [['n', 'o', 'w', '_'], 11736],
 [["'", 'v', 'e_'], 11579],
 [['l', 'i', 'k', 'e_'], 11372],
 [['y', 'e', 's', '_'], 10842],
 [['o', 'u', 't', '_'], 10839],
 [['s', 'h', 'e_'], 10741],
 [['c', 'o', 'm', 'e_'], 10653],
 [['g', 'o', '_'], 10570],
 [['r', 'i', 'g', 'h', 't', '_'], 10414],
 [['s', 'o', '_'], 10352],
 [['a', 'b', 'o', 'u', 't', '_'], 10349],
 [['a', 't', '_'], 10100],
 [['u', 'p', '_'], 9851],
 [['o', 'h', '_'], 9750],
 [['w', 'i', 'l', 'l', '_'], 9685],
 [['j', 'u', 's', 't', '_'], 9650],
 [['s', 'e', 'e_'], 9619],
 [['g', 'o', 'o', 'd', '_'], 9404],
 [['h', 'e', 'r', '_'], 9170],
 [['a', 's', '_'], 9044],
 [['"', '_'], 8870],
 [['o', 'n', 'e_'], 8831],
 [['g', 'o', 't', '_'], 8827],
 [['h', 'o', 'w', '_'], 8698],
 [["'", 'd', '_'], 7878],
 [['-', '_'], 7821],
 [['w', 'a', 'n', 't', '_'], 7783],
 [['t', 'h', 'i', 'n', 'k', '_'], 7743],
 [['w', 'h', 'y', '_'], 7726],
 [['h', 'i', 's', '_'], 7396],
 [['m', 'r', '_'], 7390],
 [['g', 'o', 'i', 'n', 'g', '_'], 7023],
 [['d', 'i', 'd', '_'], 6784],
 [['t', 'a', 'k', 'e_'], 6657],
 [['t', 'h', 'e', 'm', '_'], 6612],
 [['b', 'e', 'e', 'n', '_'], 6579],
 [['w', 'h', 'e', 'n', '_'], 6444],
 [['f', 'r', 'o', 'm', '_'], 6437],
 [['l', 'e', 't', '_'], 6379],
 [['t', 'e', 'l', 'l', '_'], 6330],
 [['w', 'h', 'o', '_'], 6283],
 [['w', 'h', 'e', 'r', 'e_'], 6175],
 [['s', 'a', 'y', '_'], 6142],
 [['v', 'e', 'r', 'y', '_'], 5833],
 [['b', 'a', 'c', 'k', '_'], 5736],
 [['m', 'a', 'n', '_'], 5539],
 [['t', 'i', 'm', 'e_'], 5538],
 [['l', 'o', 'o', 'k', '_'], 5465],
 [['a', 'n', '_'], 5437],
 [['h', 'a', 'd', '_'], 5395],
 [['t', 'o', 'o', '_'], 5297],
 [['u', 's', '_'], 5228],
 [['w', 'o', 'u', 'l', 'd', '_'], 5165],
 [['n', 'e', 'v', 'e', 'r', '_'], 5037],
 [['d', 'i', 'd', 'n', '_'], 4959],
 [['w', 'e', 'r', 'e_'], 4912],
 [['s', 'i', 'r', '_'], 4907],
 [['l', 'i', 't', 't', 'l', 'e_'], 4764],
 [['w', 'a', 'y', '_'], 4572],
 [['o', 'r', '_'], 4571],
 [['t', 'h', 'e', 'n', '_'], 4556],
 [['s', 'o', 'm', 'e_'], 4544],
 [['d', 'o', 'w', 'n', '_'], 4510],
 [['m', 'u', 's', 't', '_'], 4353],
 [['a', 'n', 'y', '_'], 4343],
 [['m', 'a', 'k', 'e_'], 4312],
 [['o', 'n', 'l', 'y', '_'], 4213],
 [['c', 'o', 'u', 'l', 'd', '_'], 4125],
 [['m', 'o', 'r', 'e_'], 4078],
 [['b', 'y', '_'], 4064],
 [['h', 'a', 's', '_'], 4035],
 [['s', 'o', 'm', 'e', 't', 'h', 'i', 'n', 'g', '_'], 4018],
 [['t', 'h', 'a', 'n', 'k', '_'], 3991],
 [['o', 'u', 'r', '_'], 3987],
 [['o', 'v', 'e', 'r', '_'], 3933],
 [['g', 'i', 'v', 'e_'], 3923],
 [['w', 'o', 'n', '_'], 3826],
 [['m', 'u', 'c', 'h', '_'], 3806],
 [['s', 'u', 'r', 'e_'], 3682],
 [['p', 'l', 'e', 'a', 's', 'e_'], 3634],
 [['n', 'i', 'g', 'h', 't', '_'], 3541],
 [['b', 'e', 't', 't', 'e', 'r', '_'], 3447],
 [['y', 'e', 'a', 'h', '_'], 3404],
 [['n', 'o', 't', 'h', 'i', 'n', 'g', '_'], 3379],
 [['a', 'n', 'y', 't', 'h', 'i', 'n', 'g', '_'], 3219],
 [['a', 'w', 'a', 'y', '_'], 3136],
 [['t', 'w', 'o', '_'], 3114],
 [['m', 'e', 'a', 'n', '_'], 3060],
 [['o', 'l', 'd', '_'], 3053],
 [['o', 'f', 'f', '_'], 3035],
 [['l', 'o', 'v', 'e_'], 3028],
 [['h', 'e', 'l', 'l', 'o', '_'], 3018],
 [['a', 'm', '_'], 2934],
 [['m', 'i', 's', 's', '_'], 2929],
 [['b', 'e', 'f', 'o', 'r', 'e_'], 2916],
 [['s', 'a', 'i', 'd', '_'], 2882],
 [['a', 'g', 'a', 'i', 'n', '_'], 2882],
 [['f', 'i', 'n', 'd', '_'], 2839],
 [['s', 'h', 'o', 'u', 'l', 'd', '_'], 2800],
 [['l', 'o', 'n', 'g', '_'], 2767],
 [['i', 's', 'n', '_'], 2738],
 [['t', 'h', 'i', 'n', 'g', '_'], 2720],
 [['s', 'o', 'r', 'r', 'y', '_'], 2676],
 [['h', 'e', 'l', 'p', '_'], 2667],
 [['a', 'f', 't', 'e', 'r', '_'], 2623],
 [['t', 'h', 'o', 'u', 'g', 'h', 't', '_'], 2600],
 [['p', 'u', 't', '_'], 2573],
 [['h', 'o', 'm', 'e_'], 2550],
 [['t', 'h', 'a', 'n', '_'], 2528],
 [['e', 'v', 'e', 'r', '_'], 2525],
 [['f', 'i', 'r', 's', 't', '_'], 2521],
 [['p', 'e', 'o', 'p', 'l', 'e_'], 2514],
 [['f', 'a', 't', 'h', 'e', 'r', '_'], 2502],
 [['t', 'h', 'i', 'n', 'g', 's', '_'], 2447],
 [['a', 'l', 'w', 'a', 'y', 's', '_'], 2424],
 [['t', 'h', 'o', 's', 'e_'], 2422],
 [['m', 'a', 'y', 'b', 'e_'], 2417],
 [['d', 'a', 'y', '_'], 2410],
 [['k', 'e', 'e', 'p', '_'], 2393],
 [['t', 'a', 'l', 'k', '_'], 2389],
 [['i', 'n', 't', 'o', '_'], 2380],
 [['g', 'o', 'n', 'n', 'a', '_'], 2372],
 [['m', 'r', 's', '_'], 2366],
 [['t', 'o', 'l', 'd', '_'], 2360],
 [['w', 'a', 'i', 't', '_'], 2348],
 [['m', 'i', 'n', 'd', '_'], 2339],
 [['a', 'i', 'n', '_'], 2336],
 [['b', 'e', 'c', 'a', 'u', 's', 'e_'], 2327],
 [['l', 'a', 's', 't', '_'], 2314],
 [['m', 'a', 'y', '_'], 2299],
 [['l', 'e', 'a', 'v', 'e_'], 2297],
 [['t', 'h', 'e', 's', 'e_'], 2289],
 [['o', 't', 'h', 'e', 'r', '_'], 2277],
 [['d', 'e', 'a', 'r', '_'], 2255],
 [['a', 'r', 'o', 'u', 'n', 'd', '_'], 2245],
 [['l', 'i', 'f', 'e_'], 2245],
 [['e', 'v', 'e', 'n', '_'], 2242],
 [['c', 'o', 'u', 'r', 's', 'e_'], 2213],
 [['m', 'o', 'n', 'e', 'y', '_'], 2207],
 [['w', 'o', 'u', 'l', 'd', 'n', '_'], 2160],
 [['n', 'e', 'w', '_'], 2154],
 [['m', 'o', 'r', 'n', 'i', 'n', 'g', '_'], 2147],
 [['r', 'e', 'a', 'l', 'l', 'y', '_'], 2098],
 [['n', 'a', 'm', 'e_'], 2067],
 [['n', 'i', 'c', 'e_'], 2061],
 [['m', 'a', 't', 't', 'e', 'r', '_'], 2051],
 [['e', 'v', 'e', 'r', 'y', 't', 'h', 'i', 'n', 'g', '_'], 2034],
 [['m', 'i', 'g', 'h', 't', '_'], 2030],
 [['w', 'o', 'r', 'k', '_'], 2029],
 [['h', 'a', 'v', 'e', 'n', '_'], 2015],
 [['s', 't', 'i', 'l', 'l', '_'], 2010],
 [[':', '_'], 1991],
 [['e', 'n', 'o', 'u', 'g', 'h', '_'], 1989],
 [['p', 'l', 'a', 'c', 'e_'], 1966],
 [['g', 'i', 'r', 'l', '_'], 1956],
 [['m', 'e', 'n', '_'], 1953],
 [['d', 'o', 'i', 'n', 'g', '_'], 1934],
 [['d', 'o', 'e', 's', '_'], 1933],
 [['c', 'a', 'l', 'l', '_'], 1911],
 [['t', 'h', 'a', 'n', 'k', 's', '_'], 1896],
 [['h', 'e', 'y', '_'], 1882],
 [['n', 'e', 'e', 'd', '_'], 1876],
 [['s', 't', 'a', 'y', '_'], 1861],
 [['s', 't', 'o', 'p', '_'], 1823],
 [['h', 'o', 'u', 's', 'e_'], 1787],
 [['c', 'a', 'm', 'e_'], 1777],
 [['r', 'e', 'm', 'e', 'm', 'b', 'e', 'r', '_'], 1771],
 [['y', 'e', 'a', 'r', 's', '_'], 1757],
 [['a', 's', 'k', '_'], 1757],
 [['a', 'n', 'o', 't', 'h', 'e', 'r', '_'], 1757],
 [['r', 'o', 'o', 'm', '_'], 1751],
 [['h', 'e', 'a', 'r', '_'], 1737],
 [['y', 'o', 'u', 'r', 's', 'e', 'l', 'f', '_'], 1734],
 [['t', 'h', 'r', 'o', 'u', 'g', 'h', '_'], 1734],
 [['b', 'o', 'y', '_'], 1733],
 [['a', 'f', 'r', 'a', 'i', 'd', '_'], 1721],
 [['d', 'o', 'e', 's', 'n', '_'], 1714],
 [['u', 'n', 'd', 'e', 'r', 's', 't', 'a', 'n', 'd', '_'], 1690],
 [['m', 'a', 'd', 'e_'], 1681],
 [['d', 'o', 'n', 'e_'], 1673],
 [['t', 'h', 'e', 'i', 'r', '_'], 1670],
 [['b', 'i', 'g', '_'], 1668],
 [['c', 'o', 'm', 'i', 'n', 'g', '_'], 1659],
 [['b', 'e', 'l', 'i', 'e', 'v', 'e_'], 1656],
 [['g', 'r', 'e', 'a', 't', '_'], 1653],
 [['m', 'o', 't', 'h', 'e', 'r', '_'], 1653],
 [['l', 'e', 'f', 't', '_'], 1651],
 [['f', 'e', 'e', 'l', '_'], 1647],
 [['t', 'o', 'n', 'i', 'g', 'h', 't', '_'], 1646],
 [['e', 'v', 'e', 'r', 'y', '_'], 1620],
 [['c', 'o', 'u', 'l', 'd', 'n', '_'], 1609],
 [['s', 'h', 'a', 'l', 'l', '_'], 1607],
 [['b', 'a', 'd', '_'], 1605],
 [['k', 'i', 'n', 'd', '_'], 1582],
 [['o', 'w', 'n', '_'], 1565],
 [['t', 'h', 'r', 'e', 'e_'], 1553],
 [['w', 'o', 'm', 'a', 'n', '_'], 1527],
 [['c', 'a', 'r', 'e_'], 1511],
 [['d', 'a', 'r', 'l', 'i', 'n', 'g', '_'], 1498],
 [['l', 'i', 's', 't', 'e', 'n', '_'], 1496],
 [['d', 'o', 'c', 't', 'o', 'r', '_'], 1493],
 [['w', 'a', 'n', 't', 'e', 'd', '_'], 1492],
 [['m', 'y', 's', 'e', 'l', 'f', '_'], 1484],
 [['f', 'r', 'i', 'e', 'n', 'd', '_'], 1474],
 [['l', 'o', 't', '_'], 1456],
 [['s', 'e', 'e', 'n', '_'], 1455],
 [['o', 'n', 'c', 'e_'], 1446],
 [['m', 'i', 'n', 'u', 't', 'e_'], 1438],
 [['e', 'l', 's', 'e_'], 1430],
 [['w', 'o', 'r', 'l', 'd', '_'], 1412],
 [['b', 'u', 's', 'i', 'n', 'e', 's', 's', '_'], 1411],
 [['h', 'e', 'a', 'r', 'd', '_'], 1410],
 [['s', 'u', 'c', 'h', '_'], 1395],
 [['f', 'i', 'n', 'e_'], 1394],
 [['t', 'o', 'm', 'o', 'r', 'r', 'o', 'w', '_'], 1389],
 [['p', 'r', 'e', 't', 't', 'y', '_'], 1388],
 [['d', 'r', '_'], 1385],
 [['s', 'i', 't', '_'], 1383],
 [['s', 'h', 'o', 'w', '_'], 1372],
 [['l', 'a', 'd', 'y', '_'], 1363],
 [['w', 'i', 'f', 'e_'], 1361],
 [['t', 'r', 'y', '_'], 1354],
 [['a', 'l', 'o', 'n', 'e_'], 1343],
 [['q', 'u', 'i', 't', 'e_'], 1341],
 [['h', 'o', 'p', 'e_'], 1335],
 [['y', 'o', 'u', 'n', 'g', '_'], 1328],
 [['b', 'r', 'i', 'n', 'g', '_'], 1313],
 [['d', 'e', 'a', 'd', '_'], 1312],
 [['w', 'a', 's', 'n', '_'], 1303],
 [['k', 'n', 'e', 'w', '_'], 1299],
 [['y', 'e', 't', '_'], 1295],
 [['w', 'i', 't', 'h', 'o', 'u', 't', '_'], 1287],
 [['g', 'u', 'e', 's', 's', '_'], 1284],
 [['s', 'a', 'm', 'e_'], 1282],
 [['b', 'e', 'i', 'n', 'g', '_'], 1270],
 [['g', 'e', 't', 't', 'i', 'n', 'g', '_'], 1264],
 [['i', 'd', 'e', 'a', '_'], 1260],
 [['l', 'i', 'v', 'e_'], 1252],
 [['l', 'o', 'o', 'k', 'i', 'n', 'g', '_'], 1236],
 [['w', 'r', 'o', 'n', 'g', '_'], 1236],
 [['s', 'u', 'p', 'p', 'o', 's', 'e_'], 1234],
 [['w', 'i', 's', 'h', '_'], 1231],
 [['h', 'a', 'p', 'p', 'e', 'n', 'e', 'd', '_'], 1229],
 [['w', 'h', 'i', 'l', 'e_'], 1227],
 [['h', 'a', 'p', 'p', 'y', '_'], 1224],
 [['s', 'a', 'w', '_'], 1218],
 [['b', 'o', 'y', 's', '_'], 1213],
 [['a', 'l', 'o', 'n', 'g', '_'], 1201],
 [['m', 'o', 's', 't', '_'], 1192],
 [['w', 'e', 'n', 't', '_'], 1188],
 [['s', 'o', 'o', 'n', '_'], 1187],
 [['d', 'r', 'i', 'n', 'k', '_'], 1172],
 [['f', 'o', 'u', 'n', 'd', '_'], 1165],
 [['g', 'u', 'y', '_'], 1156],
 [['t', 'r', 'o', 'u', 'b', 'l', 'e_'], 1153],
 [['n', 'e', 'x', 't', '_'], 1141],
 [['g', 'o', 'n', 'e_'], 1138],
 [['b', 'e', 's', 't', '_'], 1125],
 [['u', 'h', '_'], 1121],
 [['u', 'n', 't', 'i', 'l', '_'], 1115],
 [['g', 'e', 'n', 't', 'l', 'e', 'm', 'e', 'n', '_'], 1115],
 [['t', 'o', 'w', 'n', '_'], 1112],
 [['h', 'e', 'a', 'd', '_'], 1109],
 [['d', 'a', 'y', 's', '_'], 1107],
 [['s', 'i', 'n', 'c', 'e_'], 1104],
 [['f', 'e', 'w', '_'], 1104],
 [['g', 'l', 'a', 'd', '_'], 1102],
 [['t', 'o', 'd', 'a', 'y', '_'], 1097],
 [['j', 'o', 'b', '_'], 1096],
 [['m', 'a', 'n', 'y', '_'], 1095],
 [['m', 'a', 'r', 'r', 'i', 'e', 'd', '_'], 1092],
 [['r', 'e', 'a', 'd', 'y', '_'], 1087],
 [['w', 'h', 'o', 'l', 'e_'], 1083],
 [['t', 'r', 'y', 'i', 'n', 'g', '_'], 1077],
 [['h', 'o', 'l', 'd', '_'], 1076],
 [['t', 'a', 'l', 'k', 'i', 'n', 'g', '_'], 1070],
 [['r', 'u', 'n', '_'], 1068],
 [['f', 'o', 'r', 'g', 'e', 't', '_'], 1041],
 [['p', 'e', 'r', 'h', 'a', 'p', 's', '_'], 1038],
 [['h', 'a', 'n', 'd', '_'], 1033],
 [['w', 'a', 'i', 't', 'i', 'n', 'g', '_'], 1030],
 [['u', 's', 'e_'], 1029],
 [['s', 't', 'a', 'n', 'd', '_'], 1023],
 [['c', 'a', 'p', 't', 'a', 'i', 'n', '_'], 1019],
 [['s', 'a', 'y', 's', '_'], 1018],
 [['m', 'i', 'n', 'e_'], 1016],
 [['k', 'i', 'l', 'l', '_'], 996],
 [['w', 'h', 'i', 'c', 'h', '_'], 994],
 [['o', 'k', 'a', 'y', '_'], 993],
 [['m', 'e', 'e', 't', '_'], 992],
 [['e', 'v', 'e', 'n', 'i', 'n', 'g', '_'], 984],
 [['o', 'p', 'e', 'n', '_'], 981],
 [['u', 's', 'e', 'd', '_'], 973],
 [['t', 'o', 'g', 'e', 't', 'h', 'e', 'r', '_'], 968],
 [['h', 'u', 'h', '_'], 967],
 [['w', 'a', 'n', 't', 's', '_'], 963],
 [['p', 'l', 'a', 'y', '_'], 961],
 [['a', 'g', 'o', '_'], 957],
 [['s', 'o', 'm', 'e', 'b', 'o', 'd', 'y', '_'], 956],
 [['p', 'o', 'l', 'i', 'c', 'e_'], 954],
 [['b', 'e', 'a', 'u', 't', 'i', 'f', 'u', 'l', '_'], 952],
 [['c', 'a', 's', 'e_'], 944],
 [['s', 'e', 'n', 'd', '_'], 944],
 [['a', 'r', 'e', 'n', '_'], 943],
 [['w', 'o', 'r', 'r', 'y', '_'], 927],
 [['h', 'u', 's', 'b', 'a', 'n', 'd', '_'], 924],
 [['t', 'o', 'o', 'k', '_'], 924],
 [['k', 'i', 'l', 'l', 'e', 'd', '_'], 921],
 [['p', 'a', 'y', '_'], 918],
 [['c', 'h', 'a', 'n', 'c', 'e_'], 918],
 [['d', 'o', 'o', 'r', '_'], 913],
 [['n', 'o', 'b', 'o', 'd', 'y', '_'], 906],
 [['p', 'o', 'o', 'r', '_'], 903],
 [['h', 'u', 'r', 'r', 'y', '_'], 898],
 [['w', 'a', 't', 'e', 'r', '_'], 896],
 [['u', 'n', 'd', 'e', 'r', '_'], 892],
 [['s', 'o', 'n', '_'], 890],
 [['f', 'r', 'i', 'e', 'n', 'd', 's', '_'], 883],
 [['l', 'a', 't', 'e', 'r', '_'], 879],
 [['t', 'u', 'r', 'n', '_'], 875],
 [['w', 'o', 'r', 'd', '_'], 871],
 [['s', 'p', 'e', 'a', 'k', '_'], 869],
 [['s', 'l', 'e', 'e', 'p', '_'], 861],
 [['s', 't', 'a', 'r', 't', '_'], 860],
 [['b', 'o', 't', 'h', '_'], 858],
 [['l', 'a', 't', 'e_'], 855],
 [['s', 'o', 'm', 'e', 'o', 'n', 'e_'], 853],
 [['h', 'a', 'n', 'd', 's', '_'], 852],
 [['f', 'i', 'v', 'e_'], 852],
 [['y', 'o', 'u', 'r', 's', '_'], 844],
 [['f', 'a', 'c', 'e_'], 835],
 [['h', 'e', 'a', 'r', 't', '_'], 835],
 [['e', 'x', 'c', 'u', 's', 'e_'], 835],
 [['c', 'o', 'u', 'n', 't', 'r', 'y', '_'], 830],
 [['e', 'v', 'e', 'r', 'y', 'b', 'o', 'd', 'y', '_'], 830],
 [['e', 'a', 's', 'y', '_'], 829],
 [['w', 'o', 'n', 'd', 'e', 'r', 'f', 'u', 'l', '_'], 829],
 [['f', 'a', 'r', '_'], 826],
 [['d', 'e', 'a', 't', 'h', '_'], 822],
 [['r', 'e', 's', 't', '_'], 819],
 [['m', 'o', 'm', 'e', 'n', 't', '_'], 811],
 [['b', 'a', 'b', 'y', '_'], 809],
 [['c', 'a', 'r', '_'], 807],
 [['a', 'g', 'a', 'i', 'n', 's', 't', '_'], 807],
 [['l', 'o', 'o', 'k', 's', '_'], 803],
 [['c', 'o', 'm', 'e', 's', '_'], 803],
 [['t', 'h', 'i', 'n', 'k', 'i', 'n', 'g', '_'], 800],
 [['w', 'a', 'r', '_'], 795],
 [['k', 'n', 'o', 'w', 's', '_'], 793],
 [['r', 'a', 't', 'h', 'e', 'r', '_'], 791],
 [['g', 'a', 'v', 'e_'], 790],
 [['h', 'a', 'r', 'd', '_'], 788],
 [['e', 'y', 'e', 's', '_'], 788],
 [['a', 'n', 'y', 'b', 'o', 'd', 'y', '_'], 787],
 [['r', 'e', 'a', 'd', '_'], 787],
 [['l', 'o', 's', 't', '_'], 783],
 [['w', 'a', 't', 'c', 'h', '_'], 782],
 [['h', 'u', 'r', 't', '_'], 780],
 [['b', 'r', 'o', 't', 'h', 'e', 'r', '_'], 777],
 [['o', 'u', 'g', 'h', 't', '_'], 775],
 [['b', 'e', 'd', '_'], 774],
 [['a', 'n', 'y', 'o', 'n', 'e_'], 765],
 [['c', 'e', 'r', 't', 'a', 'i', 'n', 'l', 'y', '_'], 765],
 [['f', 'i', 'g', 'h', 't', '_'], 763],
 [['b', 'i', 't', '_'], 763],
 [['g', 'o', 'd', '_'], 760],
 [['c', 'h', 'i', 'l', 'd', '_'], 759],
 [['h', 'a', 'l', 'f', '_'], 755],
 [['k', 'i', 'd', '_'], 755],
 [['g', 'o', 'o', 'd', 'b', 'y', 'e_'], 752],
 [['e', 'a', 'c', 'h', '_'], 751],
 [['t', 'i', 'l', 'l', '_'], 750],
 [['h', 'a', 'p', 'p', 'e', 'n', '_'], 743],
 [['y', 'e', 'a', 'r', '_'], 737],
 [['m', 'a', 'r', 'r', 'y', '_'], 734],
 [['t', 'r', 'u', 'e_'], 733],
 [['e', 'a', 't', '_'], 726],
 [["'", 'e', 'm', '_'], 718],
 [['d', 'i', 'e_'], 717],
 [['a', 'n', 'y', 'w', 'a', 'y', '_'], 717],
 [['a', 'h', 'e', 'a', 'd', '_'], 717],
 [['s', 'i', 's', 't', 'e', 'r', '_'], 715],
 [['m', 'a', 'k', 'e', 's', '_'], 713],
 [['g', 'u', 'n', '_'], 712],
 [['b', 'r', 'o', 'u', 'g', 'h', 't', '_'], 706],
 [['s', 'e', 'e', 'm', 's', '_'], 705],
 [['e', 'n', 'd', '_'], 700],
 [['o', 'f', 'f', 'i', 'c', 'e_'], 700],
 [['m', 'i', 'n', 'u', 't', 'e', 's', '_'], 700],
 [['l', '_'], 699],
 [['f', 'o', 'u', 'r', '_'], 695],
 [['t', 'a', 'k', 'i', 'n', 'g', '_'], 692],
 [['d', 'i', 'n', 'n', 'e', 'r', '_'], 691],
 [['t', 'r', 'a', 'i', 'n', '_'], 690],
 [['m', 'a', '_'], 688],
 [['w', 'o', 'm', 'e', 'n', '_'], 687],
 [['f', 'u', 'n', 'n', 'y', '_'], 685],
 [['f', 'i', 'r', 'e_'], 685],
 [['m', 'o', 'n', 's', 'i', 'e', 'u', 'r', '_'], 683],
 [['f', 'o', 'o', 'l', '_'], 681],
 [['c', 'h', 'a', 'n', 'g', 'e_'], 681],
 [['g', 'o', 'e', 's', '_'], 679],
 [['a', 'l', 'r', 'e', 'a', 'd', 'y', '_'], 678],
 [['c', 'r', 'a', 'z', 'y', '_'], 676],
 [['a', 's', 'k', 'e', 'd', '_'], 672],
 [['g', 'e', 'o', 'r', 'g', 'e_'], 670],
 [['i', 'm', 'p', 'o', 'r', 't', 'a', 'n', 't', '_'], 668],
 [['q', 'u', 'i', 'e', 't', '_'], 667],
 [['g', 'o', 't', 't', 'a', '_'], 662],
 [['f', 'e', 'l', 'l', 'o', 'w', '_'], 660],
 [['j', 'o', 'e_'], 660],
 [['b', 'e', 't', '_'], 659],
 [['c', 'a', 'l', 'l', 'e', 'd', '_'], 645],
 [['l', 'u', 'c', 'k', '_'], 642],
 [["'", '_'], 642],
 [['s', 't', 'o', 'r', 'y', '_'], 641],
 [['b', 'r', 'e', 'a', 'k', '_'], 637],
 [['h', 'o', 'u', 'r', '_'], 636],
 [['b', 'u', 'y', '_'], 635],
 [['h', 'a', 'v', 'i', 'n', 'g', '_'], 633],
 [['l', 'a', 'w', '_'], 631],
 [['o', '_'], 629],
 [['s', 'e', 'n', 't', '_'], 629],
 [['c', 'h', 'i', 'l', 'd', 'r', 'e', 'n', '_'], 627],
 [['m', 'e', 't', '_'], 626],
 [['1', '0', '_'], 626],
 [['s', 'h', 'o', 't', '_'], 626],
 [['a', 'n', 's', 'w', 'e', 'r', '_'], 624],
 [['w', 'e', 'e', 'k', '_'], 622],
 [['s', 'o', 'r', 't', '_'], 621],
 [['w', 'a', 'l', 'k', '_'], 619],
 [['k', 'i', 'n', 'g', '_'], 618],
 [['m', 'e', 'a', 'n', 's', '_'], 617],
 [['r', 'e', 'a', 'l', '_'], 615],
 [['t', 'r', 'i', 'e', 'd', '_'], 609],
 [['h', 'a', 't', 'e_'], 603],
 [['g', 'e', 't', 's', '_'], 600],
 [['l', 'e', 'a', 'v', 'i', 'n', 'g', '_'], 600],
 [['d', 'a', 'u', 'g', 'h', 't', 'e', 'r', '_'], 598],
 [['b', 'i', 'l', 'l', '_'], 598],
 [['t', 'i', 'm', 'e', 's', '_'], 597],
 [['a', 'l', 'm', 'o', 's', 't', '_'], 594],
 [['a', 'h', '_'], 594],
 [['r', 'e', 'a', 's', 'o', 'n', '_'], 592],
 [['f', 'a', 'm', 'i', 'l', 'y', '_'], 590],
 [['h', 'o', 'r', 's', 'e_'], 588],
 [['m', 'o', 'v', 'e_'], 584],
 [['s', 'h', 'o', 'u', 'l', 'd', 'n', '_'], 583],
 [['p', 'r', 'o', 'b', 'a', 'b', 'l', 'y', '_'], 582],
 [['s', 'h', 'u', 't', '_'], 582],
 [['y', 'a', '_'], 582],
 [['h', 'i', 'm', 's', 'e', 'l', 'f', '_'], 579],
 [['c', 'o', 'u', 'p', 'l', 'e_'], 578],
 [['l', 'e', 't', 't', 'e', 'r', '_'], 577],
 [['t', 'i', 'r', 'e', 'd', '_'], 576],
 [['p', 'r', 'o', 'f', 'e', 's', 's', 'o', 'r', '_'], 572],
 [['e', 'x', 'a', 'c', 't', 'l', 'y', '_'], 570],
 [['w', 'o', 'n', 'd', 'e', 'r', '_'], 570],
 [['p', 'a', 'r', 't', '_'], 569],
 [['w', 'a', 'n', 'n', 'a', '_'], 569],
 [['l', 'o', 'r', 'd', '_'], 568],
 [['e', 'i', 't', 'h', 'e', 'r', '_'], 567],
 [['b', 'o', 'a', 't', '_'], 566],
 [['d', 'a', 'n', 'c', 'e_'], 565],
 [['m', 'a', 'k', 'i', 'n', 'g', '_'], 562],
 [['k', 'n', 'o', 'w', 'n', '_'], 562],
 [['j', 'o', 'h', 'n', '_'], 562],
 [['f', 'r', 'e', 'e_'], 562],
 [['s', 'e', 't', '_'], 560],
 [['m', 'a', 'd', 'a', 'm', 'e_'], 560],
 [['h', 'o', 't', 'e', 'l', '_'], 560],
 [['f', 'u', 'l', 'l', '_'], 558],
 [['c', 'u', 't', '_'], 558],
 [['p', 'a', 'r', 't', 'y', '_'], 558],
 [['c', 'o', 'l', 'd', '_'], 557],
 [['l', 'o', 'v', 'e', 'l', 'y', '_'], 557],
 [['u', 'n', 'c', 'l', 'e_'], 556],
 [['c', 'l', 'o', 's', 'e_'], 554],
 [['s', 'h', 'i', 'p', '_'], 554],
 [['a', 'f', 't', 'e', 'r', 'n', 'o', 'o', 'n', '_'], 549],
 [['t', 'e', 'l', 'l', 'i', 'n', 'g', '_'], 548],
 [['t', 'r', 'u', 't', 'h', '_'], 548],
 [['c', 'i', 't', 'y', '_'], 542],
 [['s', 'e', 'e', 'm', '_'], 540],
 [['s', 'i', 'd', 'e_'], 538],
 [['s', 'i', 'x', '_'], 536],
 [['n', 'u', 'm', 'b', 'e', 'r', '_'], 534],

In [553]:
tabset = {'e', 'e_'}
tabset.isdisjoint(['t', 'h', 'e', '_'])

False

In [552]:
tab_test = ['t', 'h', 'e', '_']
list(zip(tab_test, tab_test[1:]))

[('t', 'h'), ('h', 'e'), ('e', '_')]

In [545]:
def func_2(vocab, tab):
    pair_counts = defaultdict(int)
    for toks, freq in vocab:
        if not tab.isdisjoint(toks):
            for pair in zip(toks, toks[1:]):
                pair_counts[pair] += freq
    return max(pair_counts, key=pair_counts.get), pair_counts

In [548]:
test_chuj = func_2(test_vocab2, tabset)

In [550]:
test_chuj

(('e', 'r'),
 defaultdict(int,
             {('t', 'h'): 162311,
              ('h', 'e_'): 127255,
              ('m', 'e_'): 62434,
              ('w', 'e_'): 23706,
              ('b', 'e_'): 22903,
              ('h', 'a'): 36549,
              ('a', 'v'): 29656,
              ('v', 'e_'): 52048,
              ("'", 'r'): 15549,
              ('r', 'e_'): 92025,
              ('h', 'e'): 123261,
              ('e', 'r'): 171377,
              ('a', 'r'): 51514,
              ('g', 'e'): 30475,
              ('e', 't'): 53453,
              ('t', '_'): 63504,
              ('w', 'e'): 28681,
              ('e', 'l'): 59120,
              ('l', 'l'): 38015,
              ('l', '_'): 34786,
              ('e', 'y'): 22413,
              ('y', '_'): 55128,
              ("'", 'v'): 11582,
              ('l', 'i'): 38107,
              ('i', 'k'): 12661,
              ('k', 'e_'): 26244,
              ('y', 'e'): 21246,
              ('e', 's'): 71709,
              ('s', '_'): 76876,
              ('s', 'h'): 17483,
              ('c', 'o'): 26690,
              ('o', 'm'): 33071,
              ('s', 'e'): 39335,
              ('e', 'e_'): 13708,
              ('r', '_'): 88318,
              ('o', 'n'): 44764,
              ('n', 'e_'): 24775,
              ('t', 'a'): 18049,
              ('a', 'k'): 18088,
              ('e', 'm'): 21140,
              ('m', '_'): 10293,
              ('b', 'e'): 37217,
              ('e', 'e'): 29902,
              ('e', 'n'): 85895,
              ('n', '_'): 61073,
              ('w', 'h'): 18590,
              ('l', 'e'): 44031,
              ('t', 'e'): 56628,
              ('v', 'e'): 43560,
              ('r', 'y'): 14425,
              ('t', 'i'): 25407,
              ('i', 'm'): 11543,
              ('n', 'e'): 36388,
              ('e', 'v'): 23140,
              ('i', 't'): 15613,
              ('t', 't'): 20191,
              ('t', 'l'): 10357,
              ('l', 'e_'): 23801,
              ('s', 'o'): 17912,
              ('m', 'a'): 22599,
              ('m', 'o'): 14716,
              ('o', 'r'): 25880,
              ('m', 'e'): 35347,
              ('h', 'i'): 14150,
              ('i', 'n'): 50873,
              ('n', 'g'): 29696,
              ('g', '_'): 21954,
              ('o', 'v'): 12531,
              ('g', 'i'): 7601,
              ('i', 'v'): 13332,
              ('s', 'u'): 10904,
              ('u', 'r'): 19640,
              ('p', 'l'): 14696,
              ('e', 'a'): 68049,
              ('a', 's'): 16059,
              ('s', 'e_'): 29113,
              ('a', 'h'): 4289,
              ('h', '_'): 11948,
              ('a', 'n'): 33306,
              ('l', 'o'): 18209,
              ('o', '_'): 4344,
              ('e', 'f'): 8710,
              ('f', 'o'): 7960,
              ('l', 'p'): 3164,
              ('p', '_'): 7501,
              ('a', 'f'): 4272,
              ('f', 't'): 5498,
              ('h', 'o'): 17990,
              ('p', 'e'): 24925,
              ('e', 'o'): 5384,
              ('o', 'p'): 8563,
              ('f', 'a'): 5854,
              ('a', 't'): 29381,
              ('o', 's'): 9800,
              ('a', 'y'): 4575,
              ('y', 'b'): 3278,
              ('k', 'e'): 14879,
              ('e', 'p'): 10242,
              ('e', 'c'): 16181,
              ('c', 'a'): 14996,
              ('a', 'u'): 6205,
              ('u', 's'): 14720,
              ('o', 't'): 12472,
              ('d', 'e'): 31219,
              ('i', 'f'): 7346,
              ('f', 'e_'): 4436,
              ('o', 'u'): 16785,
              ('r', 's'): 19986,
              ('e', 'w'): 8254,
              ('w', '_'): 6692,
              ('r', 'e'): 58092,
              ('a', 'l'): 17394,
              ('l', 'y'): 11086,
              ('n', 'a'): 7013,
              ('a', 'm'): 12569,
              ('n', 'i'): 9361,
              ('i', 'c'): 14151,
              ('c', 'e_'): 20400,
              ('y', 't'): 2185,
              ('n', 'o'): 8341,
              ('u', 'g'): 3746,
              ('g', 'h'): 5305,
              ('l', 'a'): 13725,
              ('a', 'c'): 12077,
              ('d', 'o'): 7423,
              ('o', 'e'): 5220,
              ('e', 'd'): 55544,
              ('d', '_'): 66492,
              ('m', 'b'): 4010,
              ('y', 'o'): 3482,
              ('l', 'f'): 4636,
              ('f', '_'): 5949,
              ('s', 'n'): 2186,
              ('u', 'n'): 9323,
              ('n', 'd'): 20821,
              ('s', 't'): 32901,
              ('a', 'd'): 14451,
              ('d', 'e_'): 7065,
              ('e', 'i'): 7150,
              ('i', 'r'): 6759,
              ('i', 'e'): 19524,
              ('g', 'r'): 5812,
              ('f', 'e'): 12768,
              ('h', 'r'): 2348,
              ('i', 's'): 14282,
              ('w', 'a'): 5794,
              ('n', 't'): 25533,
              ('m', 'y'): 1963,
              ('y', 's'): 2231,
              ('f', 'r'): 6156,
              ('r', 'i'): 21796,
              ('n', 'c'): 13106,
              ('m', 'i'): 10534,
              ('n', 'u'): 3667,
              ('u', 't'): 7115,
              ('t', 'e_'): 11801,
              ('l', 's'): 3615,
              ('b', 'u'): 3448,
              ('s', 'i'): 13557,
              ('s', 's'): 14674,
              ('r', 'd'): 6868,
              ('f', 'i'): 8490,
              ('p', 'r'): 11880,
              ('t', 'y'): 4505,
              ('w', 'i'): 4558,
              ('q', 'u'): 5471,
              ('u', 'i'): 3569,
              ('p', 'e_'): 2867,
              ('k', 'n'): 2129,
              ('g', 'u'): 3970,
              ('u', 'e'): 4621,
              ('s', 'a'): 6442,
              ('i', 'd'): 8926,
              ('a', '_'): 5823,
              ('u', 'p'): 3301,
              ('p', 'p'): 7660,
              ('p', 'o'): 8274,
              ('a', 'p'): 8921,
              ('i', 'l'): 8988,
              ('t', 'r'): 10852,
              ('r', 'o'): 13521,
              ('u', 'b'): 2350,
              ('b', 'l'): 9517,
              ('e', 'x'): 8613,
              ('x', 't'): 1892,
              ('g', 'o'): 4475,
              ('r', 'r'): 7069,
              ('d', 'y'): 4159,
              ('o', 'l'): 8141,
              ('r', 'g'): 5071,
              ('r', 'h'): 1423,
              ('p', 's'): 1950,
              ('t', 'o'): 6545,
              ('o', 'g'): 2238,
              ('e', 'b'): 2174,
              ('b', 'o'): 4842,
              ('o', 'd'): 4527,
              ('f', 'u'): 4648,
              ('u', 'l'): 5691,
              ('k', 'i'): 3134,
              ('c', 'h'): 15843,
              ('d', 's'): 2958,
              ('s', 'p'): 6161,
              ('k', '_'): 4598,
              ('s', 'l'): 2620,
              ('r', 't'): 9531,
              ('x', 'c'): 2291,
              ('c', 'u'): 2998,
              ('s', 'y'): 1387,
              ('w', 'o'): 4279,
              ('r', 'f'): 2020,
              ('r', 'a'): 14964,
              ('g', 'a'): 4573,
              ('b', 'r'): 5231,
              ('n', 'y'): 2259,
              ('c', 'e'): 10391,
              ('a', 'i'): 4919,
              ('n', 'l'): 1595,
              ('o', 'o'): 4614,
              ('d', 'b'): 788,
              ('b', 'y'): 1366,
              ('y', 'e_'): 1929,
              ('r', 'u'): 2979,
              ('u', 'e_'): 2326,
              ("'", 'e'): 745,
              ('d', 'i'): 11008,
              ('i', 'e_'): 5581,
              ('m', 's'): 2054,
              ('o', 'f'): 3413,
              ('f', 'f'): 4689,
              ('n', 'n'): 4118,
              ('n', 's'): 10856,
              ('e', 'u'): 1831,
              ('g', 'e_'): 7157,
              ('l', 'r'): 760,
              ('s', 'k'): 1616,
              ('o', 'w'): 4598,
              ('j', 'o'): 2161,
              ('o', 'e_'): 965,
              ('l', 'd'): 2958,
              ('d', 'r'): 4978,
              ('s', 'w'): 2648,
              ('e', 'k'): 1828,
              ('t', 's'): 5272,
              ('v', 'i'): 5090,
              ('d', 'a'): 5733,
              ('h', 't'): 2420,
              ('x', 'a'): 1171,
              ('c', 't'): 7553,
              ('c', 'l'): 5163,
              ('r', 'n'): 5183,
              ('u', 'm'): 2373,
              ('m', 'u'): 1913,
              ('w', 'r'): 1424,
              ('x', 'p'): 2388,
              ('t', 'w'): 1121,
              ('e', 'h'): 1893,
              ('y', 'm'): 805,
              ('r', 'l'): 3374,
              ('w', 's'): 1216,
              ('n', 'r'): 723,
              ('i', 'o'): 7396,
              ('a', 'b'): 4262,
              ('p', 'i'): 4106,
              ('t', 'u'): 4974,
              ('p', 'h'): 2456,
              ('p', 't'): 2361,
              ('k', 's'): 925,
              ('o', 'k'): 2426,
              ('p', 'a'): 5888,
              ('j', 'u'): 1382,
              ('u', 'd'): 2042,
              ('d', 'g'): 1563,
              ('s', 'c'): 3609,
              ('c', 'r'): 3794,
              ('c', 'k'): 5673,
              ('g', 'l'): 1936,
              ('i', 'b'): 2715,
              ('d', 'd'): 2412,
              ('l', 'c'): 435,
              ('a', 'g'): 6407,
              ('a', 'j'): 340,
              ('j', 'e'): 2930,
              ('i', 'a'): 2995,
              ('i', 'g'): 5009,
              ('m', 'p'): 4090,
              ('h', 'u'): 1101,
              ('e', 'g'): 4467,
              ('r', 'k'): 1319,
              ('k', 'f'): 298,
              ('l', 't'): 1667,
              ('r', 'p'): 1355,
              ('c', 'i'): 4618,
              ('a', 'e'): 589,
              ('i', 'z'): 1577,
              ('z', 'e_'): 1048,
              ('c', 'y'): 796,
              ('d', 'l'): 1762,
              ('l', 'k'): 679,
              ('r', 'v'): 2516,
              ('y', 'w'): 453,
              ('o', 'b'): 1973,
              ('l', 'u'): 1958,
              ('v', 'o'): 1627,
              ('o', 'i'): 1670,
              ('d', 'u'): 1494,
              ('u', 'k'): 385,
              ('r', 'm'): 2570,
              ('v', 'a'): 2380,
              ('l', 'm'): 692,
              ('t', 'm'): 861,
              ('m', 'm'): 1487,
              ('o', 'c'): 2086,
              ('h', 'n'): 401,
              ('r', 'c'): 2479,
              ('f', 'l'): 1557,
              ('t', 'n'): 631,
              ('d', 'f'): 409,
              ('c', 'c'): 1338,
              ('a', 'w'): 821,
              ('w', 'y'): 297,
              ('s', 'm'): 1279,
              ('d', 'v'): 652,
              ('n', 'm'): 389,
              ('b', 's'): 619,
              ('l', 'v'): 1146,
              ('g', 'n'): 1417,
              ('n', 'j'): 448,
              ('o', 'y'): 1098,
              ('j', 'a'): 1086,
              ('i', 'x'): 466,
              ('x', 'e'): 735,
              ('y', 'p'): 425,
              ('t', 'c'): 1301,
              ('m', 'f'): 192,
              ('g', 'g'): 1840,
              ('g', 's'): 1042,
              ('v', 'y'): 215,
              ('s', 'q'): 364,
              ('u', 'a'): 1417,
              ('g', 't'): 298,
              ('n', 'v'): 1390,
              ('n', 'k'): 1089,
              ("'", 'c'): 149,
              ('d', 'n'): 638,
              ('u', 'c'): 1605,
              ('k', 'o'): 238,
              ('k', 'a'): 760,
              ('b', 'i'): 1432,
              ('b', 'a'): 2945,
              ('b', 'j'): 412,
              ('o', 'z'): 289,
              ('z', 'e'): 1084,
              ('z', 'a'): 395,
              ('i', 'p'): 1510,
              ('p', 'u'): 1251,
              ('k', 'y'): 329,
              ('r', 'w'): 344,
              ('n', 'f'): 1197,
              ('s', 'f'): 291,
              ('z', 'i'): 438,
              ('g', 'f'): 167,
              ('d', 'm'): 333,
              ('m', 'r'): 180,
              ('v', 'l'): 102,
              ('a', 'x'): 300,
              ('x', '_'): 502,
              ('w', 'n'): 373,
              ('l', 'b'): 340,
              ('y', 'l'): 341,
              ('d', 'q'): 89,
              ('h', 'l'): 286,
              ('c', '_'): 785,
              ('u', 'f'): 534,
              ('e', 'q'): 460,
              ('x', 'i'): 400,
              ("'", 'm'): 86,
              ('o', 'a'): 562,
              ('w', 'l'): 267,
              ('y', 'a'): 366,
              ('w', 'd'): 186,
              ('n', "'"): 318,
              ("'", '_'): 732,
              ('r', 'b'): 655,
              ('a', 'o'): 87,
              ('c', 'q'): 234,
              ('h', 'y'): 397,
              ('a', 'z'): 415,
              ('i', 'u'): 210,
              ('h', 'm'): 380,
              ('h', 's'): 170,
              ('y', 'n'): 304,
              ('y', 'c'): 233,
              ('y', 'f'): 130,
              ('b', 't'): 177,
              ('d', 'w'): 258,
              ('g', 'y'): 257,
              ('k', 'r'): 221,
              ('n', 'p'): 170,
              ('p', 'y'): 76,
              ('m', 'c'): 297,
              ('c', 'g'): 105,
              ('d', 'k'): 58,
              ('s', 'g'): 183,
              ('t', 'f'): 157,
              ('u', '_'): 267,
              ('i', '_'): 720,
              ('h', 'c'): 60,
              ('m', 'h'): 69,
              ('k', 'l'): 446,
              ('b', 'b'): 596,
              ('o', 'x'): 176,
              ('c', 'f'): 51,
              ('s', 'd'): 159,
              ('n', 'h'): 339,
              ('h', 'b'): 204,
              ('n', 'w'): 149,
              ('p', 'm'): 118,
              ('n', 'b'): 261,
              ('y', 'i'): 181,
              ('m', 'l'): 99,
              ('g', 'm'): 83,
              ('f', 'y'): 142,
              ('w', 't'): 90,
              ('v', '_'): 124,
              ('o', 'h'): 135,
              ('s', 'b'): 178,
              ('u', 'v'): 149,
              ('c', 'm'): 40,
              ('x', 'h'): 111,
              ('e', 'z'): 366,
              ('z', '_'): 217,
              ('b', '_'): 149,
              ('m', 'n'): 174,
              ('z', 'z'): 144,
              ('y', 'r'): 107,
              ('x', 'q'): 31,
              ('m', 't'): 52,
              ('p', 'n'): 49,
              ("'", 'n'): 60,
              ('l', 'n'): 100,
              ('o', 'q'): 66,
              ("'", 's'): 74,
              ('n', 'q'): 214,
              ('c', 'p'): 28,
              ('z', 'y'): 36,
              ('x', 'y'): 30,
              ('y', 'g'): 52,
              ('t', 'g'): 50,
              ('o', 'j'): 38,
              ('j', 'e_'): 39,
              ('k', 'd'): 32,
              ('t', 'p'): 61,
              ('i', 'i'): 108,
              ('l', 'z'): 47,
              ('z', 'o'): 77,
              ('y', 'd'): 102,
              ('t', 'z'): 124,
              ('t', 'b'): 97,
              ('u', 'o'): 90,
              ('a', 'q'): 33,
              ('p', 'f'): 50,
              ('h', 'w'): 112,
              ('d', 'h'): 107,
              ('n', 'z'): 98,
              ('s', "'"): 275,
              ('f', 'c'): 20,
              ('i', 'q'): 112,
              ('e', 'j'): 142,
              ('c', 'w'): 22,
              ('y', 'u'): 33,
              ('x', 'e_'): 24,
              ('k', 't'): 25,
              ('d', 't'): 69,
              ('w', 'p'): 46,
              ('w', 'b'): 60,
              ('x', 'w'): 17,
              ('p', 'b'): 26,
              ('u', 'x'): 74,
              ('z', 'g'): 19,
              ('c', 'z'): 29,
              ('y', 'z'): 29,
              ('d', 'j'): 30,
              ('f', 'm'): 29,
              ('u', 'j'): 21,
              ('z', 'v'): 15,
              ('c', 's'): 80,
              ('u', 'z'): 91,
              ('s', 'v'): 75,
              ('a', 'e_'): 37,
              ('z', 'l'): 68,
              ('l', 'g'): 124,
              ('v', 'u'): 62,
              ('d', 'c'): 49,
              ('j', 'i'): 80,
              ('k', 'h'): 75,
              ('w', 'c'): 28,
              ('k', 'u'): 48,
              ('t', 'j'): 19,
              ('a', 'a'): 36,
              ('b', 'm'): 24,
              ('x', 'l'): 17,
              ('h', 'q'): 14,
              ('r', 'j'): 43,
              ('l', 'h'): 86,
              ('y', 'v'): 21,
              ('d', 'z'): 14,
              ("'", 'a'): 31,
              ('n', 'x'): 15,
              ("'", 't'): 23,
              ('y', 'h'): 23,
              ('f', 's'): 59,
              ('v', 'v'): 20,
              ('k', 'v'): 15,
              ('l', 'w'): 34,
              ('r', 'z'): 35,
              ('v', 'k'): 9,
              ('g', 'w'): 17,
              ('k', 'k'): 14,
              ('b', 'p'): 9,
              ('y', 'k'): 22,
              ('w', 'u'): 17,
              ('c', 'b'): 14,
              ('x', 'o'): 21,
              ("'", 'y'): 9,
              ('p', 'w'): 18,
              ('f', 'n'): 8,
              ('h', 'd'): 12,
              ('z', 'b'): 7,
              ('w', 'm'): 16,
              ('k', 'b'): 41,
              ('s', 'r'): 42,
              ('u', 'q'): 18,
              ('r', 'q'): 22,
              ('i', 'w'): 16,
              ('z', 'u'): 15,
              ('f', 'j'): 9,
              ("'", 'l'): 18,
              ('k', 'm'): 40,
              ('h', 'j'): 7,
              ('u', 'y'): 26,
              ("'", 'w'): 13,
              ('x', 'u'): 15,
              ('b', 'w'): 6,
              ('v', 'r'): 26,
              ('i', 'j'): 19,
              ('d', 'p'): 24,
              ('e', "'"): 22,
              ('g', "'"): 87,
              ('i', 'h'): 12,
              ('h', 'p'): 14,
              ('j', 'v'): 4,
              ('k', 'p'): 9,
              ('c', 'n'): 7,
              ('s', 'j'): 13,
              ('b', 'd'): 9,
              ('p', 'z'): 4,
              ('v', 'n'): 7,
              ('k', 'w'): 15,
              ('h', 'h'): 17,
              ('z', 'r'): 4,
              ('h', 'f'): 13,
              ('h', 'k'): 9,
              ("'", 'b'): 9,
              ("'", 'i'): 4,
              ('c', 'd'): 7,
              ("'", 'o'): 9,
              ('p', 'k'): 6,
              ('j', '_'): 3,
              ("'", 'h'): 9,
              ('w', 'f'): 6,
              ('g', 'b'): 7,
              ('k', 'c'): 6,
              ('f', 'b'): 3,
              ('u', 'h'): 6,
              ('l', "'"): 4,
              ('b', 'f'): 5,
              ('g', 'k'): 3,
              ('z', 's'): 3,
              ('u', 'w'): 3,
              ('g', 'p'): 9,
              ('m', 'k'): 3,
              ('x', 'n'): 3,
              ('w', 'k'): 10,
              ('y', "'"): 8,
              ("'", 'p'): 8,
              ('m', 'd'): 5,
              ('p', 'g'): 3,
              ('z', 'k'): 9,
              ('t', 'd'): 9,
              ('m', 'w'): 6,
              ('x', 'f'): 3,
              ('y', 'j'): 9,
              ('f', 'h'): 4,
              ('z', 'w'): 7,
              ('h', 'v'): 3,
              ("'", 'f'): 4,
              ('m', 'v'): 4,
              ('g', 'v'): 2,
              ('w', 'g'): 3,
              ('p', 'd'): 4,
              ('q', 'a'): 2,
              ('b', 'h'): 4,
              ('x', 'x'): 2,
              ('b', 'v'): 3,
              ('f', 'v'): 4,
              ('v', 'g'): 2,
              ('v', 'c'): 1,
              ('u', 'u'): 1,
              ('t', 'k'): 4,
              ('r', "'"): 6,
              ('g', 'd'): 2,
              ('w', 'z'): 1,
              ('t', 'v'): 5,
              ('b', 'c'): 2,
              ('l', 'j'): 1,
              ('1', 'c'): 1,
              ('i', 'y'): 3,
              ('z', 'h'): 3,
              ('s', 'z'): 5,
              ('z', 'c'): 1,
              ('v', 't'): 1,
              ('f', 'p'): 1,
              ('p', 'c'): 4,
              ('i', "'"): 1,
              ("'", 'd'): 4,
              ('y', 'y'): 1,
              ('j', 'r'): 1,
              ('q', 'e'): 1,
              ('q', '_'): 2,
              ('f', 'w'): 2,
              ('z', 't'): 2,
              ("'", 'u'): 1,
              ('x', 'b'): 1,
              ('w', "'"): 1,
              ('p', 'v'): 2,
              ("'", 'j'): 1,
              ('t', "'"): 5,

In [547]:
tabset = {'e', 'e_'}
t = time.time()
for _ in range(100):
    func_2(test_vocab2, tabset)
    pass
print(f"{time.time()-t:.2f} seconds")

3.49 seconds

In [511]:
def proc_count(dct, pair):
    dct_proc = {k: v for k, v in dct.items() if set(pair).isdisjoint(k)}
    return dct_proc

In [515]:
dct_proc1 = proc_count(dct_c1, ('e', '_'))
dct_proc1 = dict(sorted(dct_proc1.items(), key=lambda x: x[1], reverse=True))

In [523]:
dct_proc1

{('t', 'h'): 286912,
 ('o', 'u'): 241694,
 ('i', 'n'): 187051,
 ('y', 'o'): 161552,
 ('a', 'n'): 156511,
 ('h', 'a'): 141491,
 ('o', 'n'): 122342,
 ('a', 't'): 120991,
 ('t', 'o'): 108364,
 ('l', 'l'): 104796,
 ('i', 't'): 104719,
 ('n', 'g'): 99478,
 ('o', 'r'): 88425,
 ('h', 'i'): 86574,
 ('n', 'd'): 86449,
 ('i', 's'): 85924,
 ('a', 'r'): 82818,
 ('s', 't'): 78706,
 ('n', 'o'): 77134,
 ('a', 'l'): 61623,
 ('w', 'h'): 61169,
 ('d', 'o'): 60236,
 ('a', 's'): 58861,
 ('o', 'w'): 57751,
 ("'", 's'): 57136,
 ('u', 'r'): 54896,
 ('h', 'o'): 54478,
 ('u', 't'): 53640,
 ('w', 'a'): 53622,
 ('o', 'm'): 51184,
 ('l', 'i'): 50694,
 ("'", 't'): 50517,
 ('o', 't'): 49292,
 ('g', 'o'): 47979,
 ('n', 't'): 47700,
 ('r', 'i'): 47625,
 ('m', 'a'): 47126,
 ('o', 'f'): 46999,
 ('c', 'o'): 45898,
 ('u', 's'): 43270,
 ('c', 'a'): 42797,
 ('t', 'i'): 42341,
 ('r', 'o'): 42178,
 ('o', 'o'): 42081,
 ('l', 'o'): 41988,
 ('s', 'o'): 39673,
 ('f', 'o'): 39473,
 ('a', 'y'): 39460,
 ('g', 'h'): 37912,
 ('w', 'i'): 36661,
 ('t', 'a'): 36642,
 ('i', 'l'): 35803,
 ('s', 'h'): 34641,
 ('c', 'h'): 33317,
 ('r', 'a'): 32061,
 ('a', 'v'): 31966,
 ('i', 'g'): 31932,
 ('l', 'a'): 31705,
 ('l', 'd'): 31148,
 ('i', 'd'): 30571,
 ('a', 'i'): 30544,
 ('h', 't'): 30254,
 ('a', 'd'): 29892,
 ('d', 'i'): 29680,
 ('i', 'm'): 29610,
 ('r', 's'): 29565,
 ('s', 'i'): 29060,
 ('r', 'y'): 28834,
 ('w', 'o'): 28647,
 ('u', 'l'): 28528,
 ('u', 'n'): 28361,
 ('b', 'o'): 27687,
 ('m', 'i'): 25809,
 ('i', 'c'): 25428,
 ('m', 'o'): 25424,
 ('a', 'c'): 25292,
 ('b', 'u'): 24142,
 ('t', 't'): 23677,
 ('o', 'l'): 23644,
 ('l', 'y'): 23512,
 ('s', 's'): 23332,
 ('m', 'y'): 23323,
 ('s', 'a'): 23275,
 ('n', 'i'): 23248,
 ('i', 'r'): 22736,
 ('a', 'm'): 22183,
 ('c', 'k'): 22011,
 ('i', 'f'): 21415,
 ('t', 'r'): 21409,
 ('o', 'd'): 20942,
 ('r', 't'): 20437,
 ('n', 'k'): 20121,
 ("'", 'l'): 20068,
 ('a', 'k'): 19921,
 ('f', 'i'): 18897,
 ('k', 'n'): 18360,
 ('a', 'b'): 18160,
 ('p', 'l'): 18092,
 ('n', 's'): 17802,
 ('d', 'a'): 17622,
 ('o', 's'): 17389,
 ('b', 'a'): 17346,
 ('k', 'i'): 17251,
 ("'", 'm'): 17037,
 ('f', 'r'): 16526,
 ('p', 'a'): 16518,
 ('r', 'r'): 16403,
 ('r', 'd'): 15941,
 ('n', 'c'): 15796,
 ('n', 'y'): 15582,
 ("'", 'r'): 15562,
 ('i', 'o'): 15354,
 ('u', 'p'): 15265,
 ('n', 'a'): 15244,
 ('s', 'u'): 15192,
 ('p', 'o'): 15182,
 ('i', 'v'): 15138,
 ('p', 'r'): 14867,
 ('a', 'p'): 14004,
 ('o', 'p'): 13928,
 ('o', 'k'): 13890,
 ('u', 'g'): 13794,
 ('a', 'g'): 13270,
 ('b', 'l'): 13249,
 ('o', 'v'): 13184,
 ('o', 'i'): 12969,
 ('i', 'k'): 12955,
 ('g', 'i'): 12820,
 ('c', 't'): 12719,
 ('j', 'u'): 12313,
 ('m', 'u'): 12152,
 ('f', 'a'): 12075,
 ('t', 's'): 11837,
 ("'", 'v'): 11583,
 ('o', 'h'): 11402,
 ('g', 'a'): 11225,
 ('t', 'l'): 11083,
 ('n', 'n'): 11083,
 ('d', 'n'): 10734,
 ('r', 'n'): 10594,
 ('d', 'r'): 10366,
 ('v', 'i'): 10260,
 ('u', 'c'): 10232,
 ('p', 'p'): 10213,
 ('b', 'r'): 10186,
 ('f', 'f'): 10034,
 ('m', 'r'): 9956,
 ('a', 'u'): 9823,
 ('d', 'y'): 9791,
 ('t', 'y'): 9687,
 ('w', 'n'): 9593,
 ('g', 'r'): 9588,
 ('t', 'u'): 9527,
 ('r', 'l'): 9430,
 ('y', 's'): 9406,
 ('p', 'i'): 9275,
 ('h', 'y'): 9149,
 ('s', 'p'): 9003,
 ('r', 'u'): 8939,
 ('h', 'u'): 8161,
 ('a', 'w'): 8001,
 ('g', 'u'): 7969,
 ('d', 's'): 7933,
 ('f', 'u'): 7915,
 ("'", 'd'): 7898,
 ('m', 'p'): 7739,
 ('c', 'i'): 7662,
 ('i', 'a'): 7588,
 ('c', 'r'): 7544,
 ('q', 'u'): 7332,
 ('c', 'l'): 7330,
 ('s', 'n'): 7136,
 ('b', 'i'): 7069,
 ('b', 'y'): 6974,
 ('u', 'i'): 6965,
 ('o', 'c'): 6931,
 ('a', 'f'): 6916,
 ('l', 's'): 6748,
 ('k', 's'): 6623,
 ('f', 't'): 6508,
 ('r', 'g'): 6341,
 ('j', 'o'): 6237,
 ('c', 'u'): 6200,
 ('r', 'm'): 6185,
 ('o', 'b'): 6066,
 ('s', 'c'): 6058,
 ('n', 'l'): 6057,
 ('r', 'k'): 6057,
 ('l', 'k'): 5993,
 ('l', 'f'): 5983,
 ('a', 'h'): 5832,
 ('h', 'r'): 5830,
 ('p', 'u'): 5780,
 ('y', 't'): 5522,
 ('m', 'b'): 5282,
 ('l', 'u'): 5234,
 ('u', 'm'): 5228,
 ('o', 'y'): 5158,
 ('s', 'k'): 5103,
 ('g', 's'): 5063,
 ('o', 'a'): 4839,
 ('t', 'w'): 4438,
 ('n', 'u'): 4354,
 ('i', 'p'): 4349,
 ('y', 'i'): 4227,
 ('y', 'b'): 4119,
 ('s', 'l'): 4079,
 ('u', 'b'): 4056,
 ('g', 'l'): 4033,
 ('l', 't'): 4031,
 ('t', 'c'): 3994,
 ('p', 's'): 3953,
 ('o', 'g'): 3938,
 ('v', 'a'): 3919,
 ('p', 't'): 3892,
 ('m', 'm'): 3806,
 ('u', 'd'): 3737,
 ('p', 'h'): 3699,
 ('d', 'd'): 3650,
 ('d', 'u'): 3641,
 ('r', 'c'): 3547,
 ('u', 'a'): 3499,
 ('s', 'w'): 3479,
 ('i', 'b'): 3438,
 ('f', 'l'): 3375,
 ('m', 's'): 3341,
 ('l', 'p'): 3328,
 ('w', 'r'): 3090,
 ('k', 'a'): 2976,
 ('s', 'm'): 2963,
 ('w', 's'): 2835,
 ('r', 'v'): 2717,
 ('j', 'a'): 2657,
 ('d', 'l'): 2616,
 ('s', 'y'): 2567,
 ('v', 'o'): 2555,
 ('l', 'w'): 2527,
 ('u', 'y'): 2395,
 ('x', 'p'): 2388,
 ('c', 'c'): 2368,
 ('g', 'n'): 2361,
 ('g', 'g'): 2311,
 ('x', 'c'): 2298,
 ('0', '0'): 2222,
 ('u', 'h'): 2145,
 ('r', 'f'): 2136,
 ('y', 'a'): 2039,
 ('i', 'z'): 2016,
 ('x', 't'): 1958,
 ('p', 'y'): 1928,
 ('l', 'm'): 1918,
 ('r', 'p'): 1836,
 ('n', 'f'): 1766,
 ('n', 'v'): 1704,
 ('k', 'y'): 1631,
 ('a', 'z'): 1621,
 ('h', 'n'): 1607,
 ('d', 'g'): 1607,
 ('c', 'y'): 1570,
 ('i', 'x'): 1564,
 ('l', 'r'): 1499,
 ('r', 'h'): 1478,
 ('u', 'f'): 1443,
 ('r', 'b'): 1386,
 ('t', 'm'): 1382,
 ('s', 'b'): 1380,
 ('n', "'"): 1315,
 ('l', 'v'): 1307,
 ('b', 'b'): 1298,
 ('y', 'w'): 1297,
 ('b', 's'): 1198,
 ('x', 'a'): 1193,
 ('y', 'm'): 1090,
 ('t', 'n'): 1062,
 ('k', 'l'): 1053,
 ('x', 'i'): 966,
 ('h', 'm'): 945,
 ('z', 'y'): 925,
 ('h', 's'): 897,
 ('z', 'a'): 884,
 ('z', 'i'): 879,
 ('1', '0'): 877,
 ('k', 'o'): 867,
 ('a', 'x'): 843,
 ('d', 'b'): 841,
 ('n', 'r'): 795,
 ('d', 'm'): 795,
 ('j', 'i'): 791,
 ('o', 'x'): 774,
 ('y', 'l'): 722,
 ('w', 'f'): 712,
 ('d', 'v'): 697,
 ('y', 'p'): 696,
 ('y', 'n'): 696,
 ('a', 'j'): 692,
 ('r', 'w'): 660,
 ('l', 'c'): 623,
 ('s', 'q'): 602,
 ('w', 'l'): 599,
 ('g', 'y'): 597,
 ('n', 'j'): 587,
 ("'", 'a'): 584,
 ('n', 'h'): 559,
 ('l', 'b'): 544,
 ('m', 'c'): 542,
 ('2', '0'): 535,
 ('k', 'r'): 534,
 ('w', 'd'): 520,
 ('b', 't'): 514,
 ('d', 'f'): 513,
 ('d', 'w'): 510,
 ('t', 'f'): 498,
 ('i', 'u'): 482,
 ('5', '0'): 476,
 ('u', 'k'): 475,
 ('f', 'y'): 475,
 ('g', 't'): 470,
 ('v', 'y'): 464,
 ('h', 'l'): 462,
 ('s', "'"): 453,
 ('3', '0'): 446,
 ('s', 'f'): 429,
 ('i', 'i'): 418,
 ('n', 'm'): 417,
 ('n', 'b'): 414,
 ('b', 'j'): 413,
 ('m', 'n'): 412,
 ('y', 'c'): 397,
 ('t', 'z'): 394,
 ('w', 'y'): 392,
 ('o', 'z'): 392,
 ('z', 'z'): 390,
 ('c', 's'): 376,
 ('z', 'o'): 369,
 ('k', 'u'): 349,
 ('y', 'r'): 338,
 ('k', 'f'): 331,
 ('k', 'h'): 328,
 ('s', 'd'): 326,
 ('m', 'f'): 321,
 ('1', '5'): 320,
 ('y', 'd'): 318,
 ("'", 'c'): 313,
 ('h', 'b'): 306,
 ('n', 'w'): 289,
 ('1', '2'): 286,
 ('l', 'g'): 286,
 ('c', 'q'): 281,
 ('s', 'g'): 276,
 ('1', '9'): 275,
 ('u', 'z'): 265,
 ('g', "'"): 262,
 ('u', 'o'): 261,
 ("'", 'i'): 257,
 ('h', 'd'): 257,
 ('n', 'q'): 248,
 ('4', '0'): 228,
 ('n', 'p'): 224,
 ('i', 'q'): 223,
 ('h', 'w'): 219,
 ('u', 'v'): 215,
 ('d', 'h'): 196,
 ('t', 'b'): 191,
 ('1', '1'): 190,
 ('a', 'o'): 190,
 ('h', 'h'): 184,
 ('l', 'n'): 179,
 ('g', 'f'): 177,
 ('n', 'z'): 177,
 ('f', 's'): 176,
 ('d', 'p'): 173,
 ('2', '5'): 173,
 ('b', 'v'): 169,
 ('1', '8'): 167,
 ('y', 'f'): 154,
 ('a', 'a'): 154,
 ('n', 'x'): 153,
 ('d', 'c'): 150,
 ('p', 'm'): 149,
 ('w', 'k'): 148,
 ('c', 'g'): 144,
 ('i', 'y'): 142,
 ('y', 'h'): 140,
 ('m', 'l'): 136,
 ("'", 'n'): 134,
 ('z', 'l'): 132,
 ('k', 'm'): 127,
 ('g', 'm'): 127,
 ('u', 'x'): 127,
 ('h', 'f'): 126,
 ('w', 'b'): 126,
 ('v', 'l'): 125,
 ('y', 'g'): 122,
 ('d', 't'): 121,
 ('k', 't'): 120,
 ('g', 'd'): 114,
 ('l', 'h'): 114,
 ('6', '0'): 112,
 ('t', 'p'): 112,
 ('w', 't'): 111,
 ('x', 'h'): 111,
 ('m', 't'): 111,
 ('1', '6'): 109,
 ('t', 'g'): 108,
 ('1', '7'): 107,
 ('h', 'k'): 107,
 ('k', 'w'): 107,
 ('v', 'u'): 106,
 ('s', 'r'): 105,
 ('h', 'c'): 103,
 ('1', '4'): 101,
 ('y', 'u'): 101,
 ('2', '4'): 94,
 ('d', 'q'): 90,
 ("'", 'h'): 90,
 ('i', 'j'): 90,
 ('d', 'j'): 90,
 ('v', 'r'): 89,
 ('1', '3'): 88,
 ('c', 'n'): 86,
 ('g', 'w'): 85,
 ('s', 'v'): 83,
 ('4', '5'): 82,
 ('c', 'f'): 80,
 ('r', 'z'): 78,
 ('m', 'h'): 76,
 ('d', 'k'): 74,
 ('9', '0'): 74,
 ('9', '3'): 73,
 ('c', 'd'): 72,
 ('p', 'k'): 70,
 ('o', 'q'): 69,
 ('l', 'z'): 69,
 ('a', 'q'): 68,
 ('r', 'j'): 68,
 ('z', 'u'): 67,
 ('9', '2'): 65,
 ('3', '5'): 64,
 ('3', '2'): 64,
 ('o', 'j'): 64,
 ('8', '0'): 64,
 ('s', 'z'): 62,
 ('g', 'b'): 62,
 ('x', 'o'): 61,
 ('2', '1'): 60,
 ('7', '0'): 60,
 ('2', '2'): 59,
 ('2', '7'): 59,
 ('k', 'b'): 58,
 ('p', 'n'): 57,
 ('c', 'z'): 56,
 ('b', 'm'): 55,
 ('3', '1'): 55,
 ('p', 'f'): 54,
 ('c', 'm'): 52,
 ('f', 'w'): 51,
 ('p', 'b'): 50,
 ('2', '6'): 49,
 ('w', 'p'): 48,
 ('u', 'j'): 48,
 ('u', 'w'): 47,
 ('9', '4'): 46,
 ('r', 'q'): 45,
 ('2', '9'): 45,
 ('x', 'l'): 44,
 ('x', 'u'): 42,
 ('7', '5'): 42,
 ('0', 't'): 42,
 ('i', 'w'): 42,
 ("'", 'y'): 41,
 ('x', 'y'): 41,
 ('2', '8'): 41,
 ('2', '3'): 41,
 ('4', '8'): 40,
 ('3', '7'): 40,
 ('b', 'd'): 40,
 ('k', 'g'): 39,
 ('p', 'j'): 39,
 ('i', 'h'): 39,
 ('3', '6'): 38,
 ('4', '2'): 38,
 ('5', 't'): 36,
 ('3', '8'): 36,
 ('b', 'w'): 35,
 ('y', 'z'): 35,
 ('p', 'w'): 35,
 ('0', '1'): 35,
 ('t', 'd'): 34,
 ('w', 'u'): 34,
 ('w', 'm'): 34,
 ('9', '1'): 34,
 ('k', 'd'): 33,
 ('6', '5'): 33,
 ("'", 'b'): 33,
 ('4', '1'): 33,
 ('h', 'p'): 33,
 ('f', 'm'): 32,
 ('7', 't'): 32,
 ('k', 'p'): 32,
 ('k', 'k'): 32,
 ('x', 'q'): 31,
 ('w', 'c'): 31,
 ('x', 'f'): 30,
 ('o', "'"): 30,
 ('4', 't'): 30,
 ('t', 'j'): 30,
 ('3', '4'): 30,
 ('8', '8'): 30,
 ('t', "'"): 29,
 ("'", 'w'): 29,
 ('c', 'p'): 28,
 ('2', 'n'): 28,
 ('z', 'k'): 28,
 ('9', '5'): 28,
 ('3', '3'): 28,
 ('j', 'r'): 27,
 ('l', 'j'): 27,
 ('z', 'g'): 27,
 ('8', 't'): 27,
 ('t', 'k'): 27,
 ('y', 'k'): 26,
 ('1', 's'): 26,
 ("'", 'o'): 26,
 ('c', 'w'): 25,
 ('4', '3'): 25,
 ('v', 'v'): 25,
 ('5', '1'): 25,
 ('8', '5'): 24,
 ('y', 'j'): 23,
 ('4', '7'): 23,
 ('f', 'h'): 23,
 ('y', 'v'): 22,
 ('9', '8'): 22,
 ('6', 't'): 22,
 ('5', '2'): 22,
 ('0', '5'): 22,
 ('p', 'c'): 22,
 ('9', '6'): 22,
 ('g', 'k'): 21,
 ('3', '9'): 21,
 ('b', 'c'): 21,
 ('9', 't'): 21,
 ('f', 'j'): 21,
 ('0', '4'): 21,
 ('f', 'c'): 20,
 ('z', 't'): 20,
 ('3', 'r'): 20,
 ('l', "'"): 20,
 ('5', '5'): 20,
 ('9', '9'): 20,
 ('b', 'n'): 20,
 ('7', '1'): 20,
 ('k', 'c'): 19,
 ('4', '4'): 19,
 ('6', '6'): 19,
 ('5', '9'): 19,
 ('x', 'w'): 18,
 ('v', 'g'): 18,
 ('h', 'q'): 18,
 ('h', 'j'): 18,
 ('4', '6'): 18,
 ('u', 'q'): 18,
 ('k', 'v'): 17,
 ('z', 'b'): 17,
 ('0', '8'): 17,
 ('5', '4'): 17,
 ('8', '1'): 17,
 ('y', "'"): 17,
 ('9', '7'): 17,
 ('d', 'z'): 16,
 ('7', '2'): 16,
 ('6', '2'): 16,
 ('7', '3'): 16,
 ('8', '6'): 16,
 ('0', '3'): 16,
 ('z', 'v'): 15,
 ('u', 'u'): 15,
 ('i', "'"): 15,
 ("'", 'u'): 15,
 ('f', 'b'): 15,
 ('4', '9'): 15,
 ('s', 'j'): 15,
 ('7', '7'): 15,
 ('8', '9'): 15,
 ('g', 'p'): 15,
 ('m', 'q'): 14,
 ('3', 't'): 14,
 ('h', 'v'): 14,
 ('c', 'b'): 14,
 ('f', 'n'): 14,
 ('d', "'"): 14,
 ('0', '2'): 14,
 ('0', 's'): 14,
 ('6', '4'): 14,
 ("'", 'p'): 14,
 ('l', 'q'): 13,
 ('t', 'v'): 13,
 ('v', 's'): 13,
 ('5', '6'): 13,
 ('6', '1'): 13,
 ('v', 'n'): 13,
 ('8', '7'): 13,
 ('8', '4'): 13,
 ('5', '7'): 13,
 ('0', '9'): 13,
 ('8', '2'): 13,
 ('w', 'w'): 12,
 ('5', '8'): 12,
 ('5', '3'): 12,
 ('6', '7'): 12,
 ('k', 'j'): 12,
 ('7', '6'): 12,
 ('0', '6'): 11,
 ('m', 'w'): 11,
 ('6', '9'): 11,
 ('7', '4'): 11,
 ('6', '3'): 11,
 ('r', "'"): 11,
 ('u', "'"): 10,
 ('v', 'k'): 10,
 ('b', 'p'): 10,
 ('p', 'g'): 10,
 ('m', 'd'): 10,
 ('z', 'h'): 10,
 ('2', 't'): 9,
 ('m', 'k'): 9,
 ('g', 'c'): 9,
 ('l', '1'): 9,
 ('8', '3'): 9,
 ('b', 'f'): 9,
 ('7', '8'): 9,
 ('6', '8'): 9,
 ('7', '9'): 9,
 ("'", '3'): 9,
 ("'", 'f'): 9,
 ('0', '7'): 8,
 ('b', 'h'): 8,
 ('s', '1'): 7,
 ("'", '2'): 7,
 ('z', 'w'): 7,
 ('p', 'd'): 7,
 ('1', 't'): 6,
 ('r', 'x'): 6,
 ('m', 'g'): 6,
 ('5', 'c'): 6,
 ('w', 'g'): 6,
 ('z', 's'): 6,
 ("'", '1'): 6,
 ('b', 'k'): 5,
 ('r', '1'): 5,
 ('v', 't'): 5,
 ('5', 'o'): 5,
 ('h', "'"): 5,
 ('m', 'z'): 5,
 ('x', 'n'): 5,
 ('m', 'v'): 5,
 ('a', "'"): 5,
 ("'", '4'): 5,
 ('j', 'v'): 4,
 ('2', 'k'): 4,
 ('p', 'z'): 4,
 ('z', 'r'): 4,
 ('x', '4'): 4,
 ("'", 'k'): 4,
 ('k', "'"): 4,
 ('f', 'v'): 4,
 ("'", 'g'): 4,
 ('f', 'g'): 4,
 ('h', 'g'): 3,
 ('6', 'f'): 3,
 ("'", '0'): 3,
 ('0', 'o'): 3,
 ('5', 'p'): 3,
 ('j', 's'): 3,
 ('c', '2'): 3,
 ('2', 'h'): 3,
 ("'", '7'): 3,
 ('x', 'b'): 3,
 ('z', 'p'): 3,
 ('x', 'x'): 3,
 ('p', "'"): 3,
 ('y', 'x'): 3,
 ('y', 'y'): 3,
 ('j', 'p'): 3,
 ('w', "'"): 3,
 ('p', 'v'): 3,
 ('6', 'a'): 2,
 ('m', '4'): 2,
 ('l', 'x'): 2,
 ('x', 'v'): 2,
 ('a', '1'): 2,
 ('w', '9'): 2,
 ('9', 'y'): 2,
 ('2', 'a'): 2,
 ('j', 'm'): 2,
 ('f', 'k'): 2,
 ('g', 'v'): 2,
 ('b', 'z'): 2,
 ('q', 'a'): 2,
 ('v', 'c'): 2,
 ('2', 'o'): 2,
 ('b', 'x'): 2,
 ('z', 'c'): 2,
 ('f', 'p'): 2,
 ('8', 's'): 2,
 ("'", '9'): 2,
 ("'", '5'): 2,
 ('0', 'k'): 2,
 ('4', 'a'): 2,
 ('b', 'g'): 2,
 ("'", 'j'): 2,
 ('h', '2'): 2,
 ('0', 'l'): 2,
 ('j', 'd'): 2,
 ('2', 's'): 2,
 ('j', 'n'): 1,
 ('0', 'r'): 1,
 ('f', "'"): 1,
 ('0', 'm'): 1,
 ('w', 'z'): 1,
 ('g', 'z'): 1,
 ('3', 'o'): 1,
 ('4', 'o'): 1,
 ('6', 'o'): 1,
 ('1', 'c'): 1,
 ('1', 'a'): 1,
 ('g', '9'): 1,
 ('v', 'd'): 1,
 ('m', '2'): 1,
 ('k', '6'): 1,
 ('9', 'a'): 1,
 ('j', 'l'): 1,
 ('z', 'm'): 1,
 ('0', "'"): 1,
 ('l', '2'): 1,
 ('9', 'l'): 1,
 ('l', '5'): 1,
 ('8', 'h'): 1,
 ('4', 'm'): 1,
 ('8', 'p'): 1,
 ('m', '1'): 1,
 ('a', '3'): 1,
 ('4', 'x'): 1,
 ('9', 'b'): 1,
 ('5', 'f'): 1,
 ('4', 's'): 1,
 ('5', 's'): 1,
 ('b', '7'): 1,
 ('o', '0'): 1,
 ('2', 'c'): 1,
 ('w', '7'): 1,
 ('7', 'b'): 1,
 ('8', 'x'): 1,
 ('x', '1'): 1,
 ('0', 'n'): 1,
 ("'", '6'): 1,
 ('r', '5'): 1,
 ('s', '5'): 1,
 ('m', '5'): 1,
 ('0', 'c'): 1,
 ('q', 's'): 1,
 ('9', 's'): 1,
 ('z', 'n'): 1,
 ('m', "'"): 1,
 ('b', "'"): 1,
 ('y', '1'): 1,
 ('5', 'h'): 1,
 ("'", '8'): 1,
 ('k', '4'): 1,
 ('z', 'f'): 1,
 ('7', 'p'): 1,
 ('q', 'v'): 1,
 ('v', 'f'): 1,
 ('6', 's'): 1,
 ('3', 'd'): 1,
 ('x', "'"): 1,
 ('7', 'o'): 1,
 ('8', 'o'): 1,
 ('6', 'l'): 1,
 ('c', 'v'): 1,
 ('x', 'm'): 1,
 ('x', '6'): 1,
 ('0', 'f'): 1,
 ("'", 'q'): 1,
 ('i', '8'): 1,
 ('8', 'n'): 1,
 ('x', 'g'): 1,
 ('d', '2'): 1,
 ('5', 'l'): 1,
 ('8', 'b'): 1,
 ('o', '4'): 1,
 ('z', 'd'): 1,
 ('g', '2'): 1,
 ('p', 'x'): 1,
 ('7', 'h'): 1,
 ('h', '3'): 1}

In [518]:
len(dct_c1), len(dct_c2)

(901, 926)

In [462]:
for key in dct_c1.keys():
    if key not in dct_c2.keys():
        print(key)

('e', '_')
('6', 'e')

In [493]:
ile = 0
for key in dct_c2.keys():
    if key not in dct_c1.keys():
        #print(key)
        ile += 1
print(ile)

27

In [509]:
tab1 = [x for x in dct_c1.keys() if set(pair).isdisjoint(x)]
test_1 = [dct_c1[x] == dct_c2[x] for x in tab1]
print(all(test_1))

True

In [488]:
pair = ('e', '_')
len([x for x in dct_c1.keys() if not set(pair).isdisjoint(x)]), len([x for x in dct_c2.keys() if not set(pair).isdisjoint(x)])

(105, 104)

In [459]:
dct_c1

{('e', '_'): 563767,
 ('.', '_'): 435802,
 ('t', '_'): 405188,
 ('t', 'h'): 286912,
 ('s', '_'): 279133,
 ('h', 'e'): 250516,
 ('o', 'u'): 241694,
 ('n', '_'): 224509,
 ('d', '_'): 199163,
 ('i', 'n'): 187051,
 (',', '_'): 177291,
 ('e', 'r'): 171377,
 ('y', '_'): 170823,
 ('r', '_'): 169575,
 ('y', 'o'): 161552,
 ('o', '_'): 158570,
 ('a', 'n'): 156511,
 ('r', 'e'): 150117,
 ('h', 'a'): 141491,
 ('u', '_'): 135623,
 ('i', '_'): 126232,
 ('o', 'n'): 122342,
 ('a', 't'): 120991,
 ('t', 'o'): 108364,
 ('l', '_'): 107287,
 ('l', 'l'): 104796,
 ('i', 't'): 104719,
 ('n', 'g'): 99478,
 ('m', 'e'): 97781,
 ('v', 'e'): 95608,
 ('g', '_'): 89713,
 ('o', 'r'): 88425,
 ('h', 'i'): 86574,
 ('n', 'd'): 86449,
 ('i', 's'): 85924,
 ('e', 'n'): 85895,
 ('?', '_'): 84640,
 ('a', 'r'): 82818,
 ('a', '_'): 81686,
 ('s', 't'): 78706,
 ('n', 'o'): 77134,
 ('e', 's'): 71709,
 ('s', 'e'): 68448,
 ('t', 'e'): 68429,
 ('e', 'a'): 68049,
 ('l', 'e'): 67832,
 ('h', '_'): 64617,
 ('f', '_'): 63686,
 ('a', 'l'): 61623,
 ('w', 'h'): 61169,
 ('m', '_'): 61166,
 ('n', 'e'): 61163,
 ('d', 'o'): 60236,
 ('b', 'e'): 60120,
 ('e', 'l'): 59120,
 ('a', 's'): 58861,
 ('o', 'w'): 57751,
 ("'", 's'): 57136,
 ('e', 'd'): 55544,
 ('u', 'r'): 54896,
 ('h', 'o'): 54478,
 ('u', 't'): 53640,
 ('w', 'a'): 53622,
 ('e', 't'): 53453,
 ('w', 'e'): 52387,
 ('o', 'm'): 51184,
 ('l', 'i'): 50694,
 ("'", 't'): 50517,
 ('w', '_'): 50017,
 ('k', '_'): 49455,
 ('o', 't'): 49292,
 ('g', 'o'): 47979,
 ('n', 't'): 47700,
 ('r', 'i'): 47625,
 ('m', 'a'): 47126,
 ('o', 'f'): 46999,
 ('c', 'o'): 45898,
 ('e', 'e'): 43610,
 ('u', 's'): 43270,
 ('c', 'a'): 42797,
 ('t', 'i'): 42341,
 ('r', 'o'): 42178,
 ('o', 'o'): 42081,
 ('l', 'o'): 41988,
 ('k', 'e'): 41123,
 ('s', 'o'): 39673,
 ('f', 'o'): 39473,
 ('a', 'y'): 39460,
 ('d', 'e'): 38284,
 ('g', 'h'): 37912,
 ('g', 'e'): 37632,
 ('w', 'i'): 36661,
 ('t', 'a'): 36642,
 ('i', 'l'): 35803,
 ('s', 'h'): 34641,
 ('c', 'h'): 33317,
 ('r', 'a'): 32061,
 ('a', 'v'): 31966,
 ('i', 'g'): 31932,
 ('l', 'a'): 31705,
 ('l', 'd'): 31148,
 ('!', '_'): 30794,
 ('c', 'e'): 30791,
 ('i', 'd'): 30571,
 ('a', 'i'): 30544,
 ('h', 't'): 30254,
 ('a', 'd'): 29892,
 ('d', 'i'): 29680,
 ('i', 'm'): 29610,
 ('r', 's'): 29565,
 ('s', 'i'): 29060,
 ('r', 'y'): 28834,
 ('w', 'o'): 28647,
 ('u', 'l'): 28528,
 ('u', 'n'): 28361,
 ('p', 'e'): 27792,
 ('b', 'o'): 27687,
 ('m', 'i'): 25809,
 ('p', '_'): 25600,
 ('i', 'c'): 25428,
 ('m', 'o'): 25424,
 ('a', 'c'): 25292,
 ('i', 'e'): 25105,
 ('b', 'u'): 24142,
 ('t', 't'): 23677,
 ('o', 'l'): 23644,
 ('l', 'y'): 23512,
 ('s', 's'): 23332,
 ('m', 'y'): 23323,
 ('s', 'a'): 23275,
 ('n', 'i'): 23248,
 ('y', 'e'): 23175,
 ('e', 'v'): 23140,
 ('i', 'r'): 22736,
 ('e', 'y'): 22413,
 ('a', 'm'): 22183,
 ('c', 'k'): 22011,
 ('i', 'f'): 21415,
 ('t', 'r'): 21409,
 ('e', 'm'): 21140,
 ('o', 'd'): 20942,
 ('r', 't'): 20437,
 ('n', 'k'): 20121,
 ("'", 'l'): 20068,
 ('a', 'k'): 19921,
 ('f', 'i'): 18897,
 ('k', 'n'): 18360,
 ('a', 'b'): 18160,
 ('p', 'l'): 18092,
 ('n', 's'): 17802,
 ('d', 'a'): 17622,
 ('o', 's'): 17389,
 ('b', 'a'): 17346,
 ('k', 'i'): 17251,
 ('f', 'e'): 17204,
 ("'", 'm'): 17037,
 ('f', 'r'): 16526,
 ('p', 'a'): 16518,
 ('r', 'r'): 16403,
 ('e', 'c'): 16181,
 ('r', 'd'): 15941,
 ('n', 'c'): 15796,
 ('n', 'y'): 15582,
 ("'", 'r'): 15562,
 ('i', 'o'): 15354,
 ('u', 'p'): 15265,
 ('n', 'a'): 15244,
 ('s', 'u'): 15192,
 ('p', 'o'): 15182,
 ('i', 'v'): 15138,
 ('p', 'r'): 14867,
 ('a', 'p'): 14004,
 ('o', 'p'): 13928,
 ('o', 'k'): 13890,
 ('u', 'g'): 13794,
 ('a', 'g'): 13270,
 ('b', 'l'): 13249,
 ('o', 'v'): 13184,
 ('o', 'i'): 12969,
 ('i', 'k'): 12955,
 ('g', 'i'): 12820,
 ('c', 't'): 12719,
 ('j', 'u'): 12313,
 ('m', 'u'): 12152,
 ('f', 'a'): 12075,
 ('t', 's'): 11837,
 ("'", 'v'): 11583,
 ('o', 'h'): 11402,
 ('g', 'a'): 11225,
 ('t', 'l'): 11083,
 ('n', 'n'): 11083,
 ('d', 'n'): 10734,
 ('r', 'n'): 10594,
 ('d', 'r'): 10366,
 ('v', 'i'): 10260,
 ('e', 'p'): 10242,
 ('u', 'c'): 10232,
 ('p', 'p'): 10213,
 ('b', 'r'): 10186,
 ('f', 'f'): 10034,
 ('m', 'r'): 9956,
 ('a', 'u'): 9823,
 ('d', 'y'): 9791,
 ('t', 'y'): 9687,
 ('w', 'n'): 9593,
 ('g', 'r'): 9588,
 ('t', 'u'): 9527,
 ('r', 'l'): 9430,
 ('y', 's'): 9406,
 ('p', 'i'): 9275,
 ('h', 'y'): 9149,
 ('s', 'p'): 9003,
 ('r', 'u'): 8939,
 ('"', '_'): 8870,
 ('e', 'f'): 8710,
 ('e', 'x'): 8613,
 ('e', 'w'): 8254,
 ('h', 'u'): 8161,
 ('a', 'w'): 8001,
 ('g', 'u'): 7969,
 ('d', 's'): 7933,
 ('f', 'u'): 7915,
 ("'", 'd'): 7898,
 ('-', '_'): 7821,
 ('m', 'p'): 7739,
 ('c', 'i'): 7662,
 ('i', 'a'): 7588,
 ('c', 'r'): 7544,
 ('q', 'u'): 7332,
 ('c', 'l'): 7330,
 ('e', 'i'): 7150,
 ('s', 'n'): 7136,
 ('b', 'i'): 7069,
 ('b', 'y'): 6974,
 ('u', 'i'): 6965,
 ('u', 'e'): 6947,
 ('o', 'c'): 6931,
 ('a', 'f'): 6916,
 ('l', 's'): 6748,
 ('k', 's'): 6623,
 ('f', 't'): 6508,
 ('r', 'g'): 6341,
 ('j', 'o'): 6237,
 ('c', 'u'): 6200,
 ('o', 'e'): 6185,
 ('r', 'm'): 6185,
 ('o', 'b'): 6066,
 ('s', 'c'): 6058,
 ('n', 'l'): 6057,
 ('r', 'k'): 6057,
 ('l', 'k'): 5993,
 ('l', 'f'): 5983,
 ('a', 'h'): 5832,
 ('h', 'r'): 5830,
 ('p', 'u'): 5780,
 ('y', 't'): 5522,
 ('e', 'o'): 5384,
 ('m', 'b'): 5282,
 ('l', 'u'): 5234,
 ('u', 'm'): 5228,
 ('o', 'y'): 5158,
 ('s', 'k'): 5103,
 ('g', 's'): 5063,
 ('o', 'a'): 4839,
 ('e', 'g'): 4467,
 ('t', 'w'): 4438,
 ('n', 'u'): 4354,
 ('i', 'p'): 4349,
 ('y', 'i'): 4227,
 ('y', 'b'): 4119,
 ('s', 'l'): 4079,
 ('u', 'b'): 4056,
 ('g', 'l'): 4033,
 ('l', 't'): 4031,
 ('t', 'c'): 3994,
 ('p', 's'): 3953,
 ('o', 'g'): 3938,
 ('v', 'a'): 3919,
 ('p', 't'): 3892,
 ('m', 'm'): 3806,
 ('u', 'd'): 3737,
 ('0', '_'): 3734,
 ('p', 'h'): 3699,
 ('d', 'd'): 3650,
 ('d', 'u'): 3641,
 ('c', '_'): 3637,
 ('r', 'c'): 3547,
 ('u', 'a'): 3499,
 ('s', 'w'): 3479,
 ('i', 'b'): 3438,
 ('b', '_'): 3407,
 ('f', 'l'): 3375,
 ('m', 's'): 3341,
 ('l', 'p'): 3328,
 ('w', 'r'): 3090,
 ('k', 'a'): 2976,
 ('j', 'e'): 2969,
 ('s', 'm'): 2963,
 ("'", '_'): 2865,
 ('w', 's'): 2835,
 ('r', 'v'): 2717,
 ('j', 'a'): 2657,
 ('d', 'l'): 2616,
 ('s', 'y'): 2567,
 ('v', 'o'): 2555,
 ('l', 'w'): 2527,
 ('u', 'y'): 2395,
 ('x', 'p'): 2388,
 ('c', 'c'): 2368,
 ('g', 'n'): 2361,
 ('g', 'g'): 2311,
 ('x', 'c'): 2298,
 ('x', '_'): 2234,
 ('0', '0'): 2222,
 ('e', 'b'): 2174,
 ('u', 'h'): 2145,
 ('r', 'f'): 2136,
 ('z', 'e'): 2132,
 ('y', 'a'): 2039,
 ('i', 'z'): 2016,
 (':', '_'): 1991,
 ('x', 't'): 1958,
 ('p', 'y'): 1928,
 ('l', 'm'): 1918,
 ('e', 'h'): 1893,
 ('r', 'p'): 1836,
 ('e', 'u'): 1831,
 ('e', 'k'): 1828,
 ('n', 'f'): 1766,
 ('n', 'v'): 1704,
 ('k', 'y'): 1631,
 ('a', 'z'): 1621,
 ('h', 'n'): 1607,
 ('d', 'g'): 1607,
 ('c', 'y'): 1570,
 ('i', 'x'): 1564,
 ('l', 'r'): 1499,
 ('r', 'h'): 1478,
 ('u', 'f'): 1443,
 ('r', 'b'): 1386,
 ('t', 'm'): 1382,
 ('s', 'b'): 1380,
 ('n', "'"): 1315,
 ('l', 'v'): 1307,
 ('b', 'b'): 1298,
 ('y', 'w'): 1297,
 ('b', 's'): 1198,
 ('x', 'a'): 1193,
 ('y', 'm'): 1090,
 ('t', 'n'): 1062,
 ('k', 'l'): 1053,
 ('x', 'i'): 966,
 ('h', 'm'): 945,
 ('z', 'y'): 925,
 ('5', '_'): 904,
 ('h', 's'): 897,
 ('z', 'a'): 884,
 ('z', 'i'): 879,
 ('1', '0'): 877,
 ('k', 'o'): 867,
 ('a', 'x'): 843,
 ('d', 'b'): 841,
 ('n', 'r'): 795,
 ('d', 'm'): 795,
 ('j', 'i'): 791,
 ('o', 'x'): 774,
 ('x', 'e'): 759,
 ("'", 'e'): 746,
 ('y', 'l'): 722,
 ('w', 'f'): 712,
 ('2', '_'): 699,
 ('d', 'v'): 697,
 ('y', 'p'): 696,
 ('y', 'n'): 696,
 ('1', '_'): 694,
 ('a', 'j'): 692,
 ('r', 'w'): 660,
 ('z', '_'): 649,
 ('a', 'e'): 626,
 ('l', 'c'): 623,
 ('s', 'q'): 602,
 ('w', 'l'): 599,
 ('g', 'y'): 597,
 ('n', 'j'): 587,
 ("'", 'a'): 584,
 ('n', 'h'): 559,
 ('l', 'b'): 544,
 ('m', 'c'): 542,
 ('2', '0'): 535,
 ('k', 'r'): 534,
 ('w', 'd'): 520,
 ('b', 't'): 514,
 ('d', 'f'): 513,
 ('d', 'w'): 510,
 ('t', 'f'): 498,
 ('i', 'u'): 482,
 ('5', '0'): 476,
 ('u', 'k'): 475,
 ('f', 'y'): 475,
 ('3', '_'): 474,
 ('g', 't'): 470,
 ('4', '_'): 466,
 ('v', 'y'): 464,
 ('h', 'l'): 462,
 ('e', 'q'): 460,
 ('8', '_'): 454,
 ('s', "'"): 453,
 ('3', '0'): 446,
 ('s', 'f'): 429,
 ('7', '_'): 422,
 ('i', 'i'): 418,
 ('n', 'm'): 417,
 ('n', 'b'): 414,
 ('b', 'j'): 413,
 ('m', 'n'): 412,
 ('y', 'c'): 397,
 ('t', 'z'): 394,
 ('6', '_'): 393,
 ('w', 'y'): 392,
 ('o', 'z'): 392,
 ('z', 'z'): 390,
 ('c', 's'): 376,
 ('z', 'o'): 369,
 ('e', 'z'): 366,
 ('v', '_'): 360,
 ('k', 'u'): 349,
 ('y', 'r'): 338,
 ('k', 'f'): 331,
 ('k', 'h'): 328,
 ('s', 'd'): 326,
 ('m', 'f'): 321,
 ('1', '5'): 320,
 ('y', 'd'): 318,
 ("'", 'c'): 313,
 ('h', 'b'): 306,
 ('n', 'w'): 289,
 ('1', '2'): 286,
 ('9', '_'): 286,
 ('l', 'g'): 286,
 ('c', 'q'): 281,
 ('$', '_'): 280,
 ('s', 'g'): 276,
 ('1', '9'): 275,
 ('u', 'z'): 265,
 ('g', "'"): 262,
 ('u', 'o'): 261,
 ("'", 'i'): 257,
 ('h', 'd'): 257,
 ('n', 'q'): 248,
 ('4', '0'): 228,
 ('n', 'p'): 224,
 ('i', 'q'): 223,
 ('h', 'w'): 219,
 ('u', 'v'): 215,
 ('d', 'h'): 196,
 ('t', 'b'): 191,
 ('1', '1'): 190,
 ('a', 'o'): 190,
 ('h', 'h'): 184,
 ('l', 'n'): 179,
 ('g', 'f'): 177,
 ('n', 'z'): 177,
 ('f', 's'): 176,
 ('d', 'p'): 173,
 ('2', '5'): 173,
 ('b', 'v'): 169,
 ('1', '8'): 167,
 ('y', 'f'): 154,
 ('a', 'a'): 154,
 ('n', 'x'): 153,
 ('d', 'c'): 150,
 ('p', 'm'): 149,
 ('w', 'k'): 148,
 ('c', 'g'): 144,
 ('i', 'y'): 142,
 ('e', 'j'): 142,
 ('y', 'h'): 140,
 ('m', 'l'): 136,
 ("'", 'n'): 134,
 ('z', 'l'): 132,
 ('k', 'm'): 127,
 ('g', 'm'): 127,
 ('u', 'x'): 127,
 ('h', 'f'): 126,
 ('w', 'b'): 126,
 ('v', 'l'): 125,
 ('j', '_'): 123,
 ('y', 'g'): 122,
 ('d', 't'): 121,
 ('k', 't'): 120,
 ('g', 'd'): 114,
 ('l', 'h'): 114,
 ('6', '0'): 112,
 ('t', 'p'): 112,
 ('w', 't'): 111,
 ('x', 'h'): 111,
 ('m', 't'): 111,
 ('1', '6'): 109,
 ('t', 'g'): 108,
 ('1', '7'): 107,
 ('h', 'k'): 107,
 ('k', 'w'): 107,
 ('v', 'u'): 106,
 ('s', 'r'): 105,
 ('h', 'c'): 103,
 ('1', '4'): 101,
 ('y', 'u'): 101,
 ('2', '4'): 94,
 ('d', 'q'): 90,
 ("'", 'h'): 90,
 ('i', 'j'): 90,
 ('d', 'j'): 90,
 ('v', 'r'): 89,
 ('1', '3'): 88,
 ('c', 'n'): 86,
 ('g', 'w'): 85,
 ('s', 'v'): 83,
 ('4', '5'): 82,
 ('c', 'f'): 80,
 ('r', 'z'): 78,
 ('m', 'h'): 76,
 ('d', 'k'): 74,
 ('9', '0'): 74,
 ('9', '3'): 73,
 ('c', 'd'): 72,
 ('p', 'k'): 70,
 ('o', 'q'): 69,
 ('l', 'z'): 69,
 ('a', 'q'): 68,
 ('r', 'j'): 68,
 ('z', 'u'): 67,
 ('9', '2'): 65,
 ('3', '5'): 64,
 ('3', '2'): 64,
 ('o', 'j'): 64,
 ('8', '0'): 64,
 ('s', 'z'): 62,
 ('g', 'b'): 62,
 ('x', 'o'): 61,
 ('2', '1'): 60,
 ('7', '0'): 60,
 ('2', '2'): 59,
 ('2', '7'): 59,
 ('k', 'b'): 58,
 ('%', '_'): 57,
 ('p', 'n'): 57,
 ('c', 'z'): 56,
 ('b', 'm'): 55,
 ('3', '1'): 55,
 ('p', 'f'): 54,
 ('c', 'm'): 52,
 ('f', 'w'): 51,
 ('p', 'b'): 50,
 ('2', '6'): 49,
 ('w', 'p'): 48,
 ('u', 'j'): 48,
 ('[', '_'): 47,
 (']', '_'): 47,
 ('u', 'w'): 47,
 ('9', '4'): 46,
 ('r', 'q'): 45,
 ('2', '9'): 45,
 ('x', 'l'): 44,
 ('x', 'u'): 42,
 ('7', '5'): 42,
 ('0', 't'): 42,
 ('i', 'w'): 42,
 ("'", 'y'): 41,
 ('x', 'y'): 41,
 ('2', '8'): 41,
 ('2', '3'): 41,
 ('/', '_'): 40,
 ('4', '8'): 40,
 ('3', '7'): 40,
 ('b', 'd'): 40,
 ('k', 'g'): 39,
 ('p', 'j'): 39,
 ('i', 'h'): 39,
 ('3', '6'): 38,
 ('4', '2'): 38,
 ('5', 't'): 36,
 ('3', '8'): 36,
 ('b', 'w'): 35,
 ('y', 'z'): 35,
 ('p', 'w'): 35,
 ('0', '1'): 35,
 ('t', 'd'): 34,
 ('w', 'u'): 34,
 ('w', 'm'): 34,
 ('9', '1'): 34,
 ('k', 'd'): 33,
 ('6', '5'): 33,
 ("'", 'b'): 33,
 ('4', '1'): 33,
 ('h', 'p'): 33,
 ('f', 'm'): 32,
 ('7', 't'): 32,
 ('k', 'p'): 32,
 ('k', 'k'): 32,
 ('x', 'q'): 31,
 ('w', 'c'): 31,
 ('x', 'f'): 30,
 ('o', "'"): 30,
 ('4', 't'): 30,
 ('t', 'j'): 30,
 ('3', '4'): 30,
 ('8', '8'): 30,
 ('t', "'"): 29,
 ("'", 'w'): 29,
 ('c', 'p'): 28,
 ('2', 'n'): 28,
 ('z', 'k'): 28,
 ('9', '5'): 28,
 ('3', '3'): 28,
 ('j', 'r'): 27,
 ('l', 'j'): 27,
 ('z', 'g'): 27,
 ('q', '_'): 27,
 ('8', 't'): 27,
 ('t', 'k'): 27,
 ('(', '_'): 26,
 (')', '_'): 26,
 ('y', 'k'): 26,
 ('1', 's'): 26,
 ("'", 'o'): 26,
 ('c', 'w'): 25,
 ('4', '3'): 25,
 ('v', 'v'): 25,
 ('5', '1'): 25,
 ('8', '5'): 24,
 ('y', 'j'): 23,
 ('4', '7'): 23,
 ('f', 'h'): 23,
 ('y', 'v'): 22,
 ('9', '8'): 22,
 ('6', 't'): 22,
 ('5', '2'): 22,
 ('0', '5'): 22,
 ('p', 'c'): 22,
 ('9', '6'): 22,
 ('e', "'"): 22,
 ('g', 'k'): 21,
 ('3', '9'): 21,
 ('b', 'c'): 21,
 ('9', 't'): 21,
 ('f', 'j'): 21,
 ('0', '4'): 21,
 ('f', 'c'): 20,
 ('z', 't'): 20,
 ('3', 'r'): 20,
 ('l', "'"): 20,
 ('5', '5'): 20,
 ('9', '9'): 20,
 ('b', 'n'): 20,
 ('7', '1'): 20,
 ('k', 'c'): 19,
 ('4', '4'): 19,
 ('6', '6'): 19,
 ('5', '9'): 19,
 ('x', 'w'): 18,
 ('v', 'g'): 18,
 ('h', 'q'): 18,
 ('h', 'j'): 18,
 ('4', '6'): 18,
 ('u', 'q'): 18,
 ('k', 'v'): 17,
 ('z', 'b'): 17,
 ('0', '8'): 17,
 ('5', '4'): 17,
 ('8', '1'): 17,
 ('y', "'"): 17,
 ('9', '7'): 17,
 ('d', 'z'): 16,
 ('7', '2'): 16,
 ('6', '2'): 16,
 ('7', '3'): 16,
 ('8', '6'): 16,
 ('0', '3'): 16,
 ('z', 'v'): 15,
 ('u', 'u'): 15,
 ('i', "'"): 15,
 ("'", 'u'): 15,
 ('f', 'b'): 15,
 ('4', '9'): 15,
 ('s', 'j'): 15,
 ('7', '7'): 15,
 ('8', '9'): 15,
 ('g', 'p'): 15,
 ('m', 'q'): 14,
 ('3', 't'): 14,
 ('h', 'v'): 14,
 ('c', 'b'): 14,
 ('f', 'n'): 14,
 ('d', "'"): 14,
 ('0', '2'): 14,
 ('0', 's'): 14,
 ('6', '4'): 14,
 ("'", 'p'): 14,
 ('l', 'q'): 13,
 ('t', 'v'): 13,
 ('v', 's'): 13,
 ('5', '6'): 13,
 ('6', '1'): 13,
 ('v', 'n'): 13,
 ('8', '7'): 13,
 ('8', '4'): 13,
 ('5', '7'): 13,
 ('0', '9'): 13,
 ('8', '2'): 13,
 ('w', 'w'): 12,
 ('5', '8'): 12,
 ('5', '3'): 12,
 ('6', '7'): 12,
 ('k', 'j'): 12,
 ('7', '6'): 12,
 ('0', '6'): 11,
 ('m', 'w'): 11,
 ('6', '9'): 11,
 ('7', '4'): 11,
 ('6', '3'): 11,
 ('r', "'"): 11,
 ('u', "'"): 10,
 ('v', 'k'): 10,
 ('b', 'p'): 10,
 ('p', 'g'): 10,
 ('m', 'd'): 10,
 ('z', 'h'): 10,
 ('2', 't'): 9,
 ('m', 'k'): 9,
 ('g', 'c'): 9,
 ('l', '1'): 9,
 ('8', '3'): 9,
 ('b', 'f'): 9,
 ('7', '8'): 9,
 ('6', '8'): 9,
 ('7', '9'): 9,
 ("'", '3'): 9,
 ("'", 'f'): 9,
 ('0', '7'): 8,
 ('b', 'h'): 8,
 ('s', '1'): 7,
 ("'", '2'): 7,
 ('z', 'w'): 7,
 ('p', 'd'): 7,
 ('1', 't'): 6,
 ('r', 'x'): 6,
 ('m', 'g'): 6,
 ('5', 'c'): 6,
 ('w', 'g'): 6,
 ('z', 's'): 6,
 ("'", '1'): 6,
 ('b', 'k'): 5,
 ('r', '1'): 5,
 ('v', 't'): 5,
 ('5', 'o'): 5,
 ('h', "'"): 5,
 ('m', 'z'): 5,
 ('x', 'n'): 5,
 ('m', 'v'): 5,
 ('a', "'"): 5,
 ("'", '4'): 5,
 ('j', 'v'): 4,
 ('2', 'k'): 4,
 ('p', 'z'): 4,
 ('z', 'r'): 4,
 ('x', '4'): 4,
 ("'", 'k'): 4,
 ('k', "'"): 4,
 ('f', 'v'): 4,
 ("'", 'g'): 4,
 ('f', 'g'): 4,
 ('h', 'g'): 3,
 ('6', 'f'): 3,
 ("'", '0'): 3,
 ('0', 'o'): 3,
 ('5', 'p'): 3,
 ('j', 's'): 3,
 ('c', '2'): 3,
 ('2', 'h'): 3,
 ("'", '7'): 3,
 ('x', 'b'): 3,
 ('z', 'p'): 3,
 ('x', 'x'): 3,
 ('p', "'"): 3,
 ('y', 'x'): 3,
 ('y', 'y'): 3,
 ('j', 'p'): 3,
 ('w', "'"): 3,
 ('p', 'v'): 3,
 ('6', 'a'): 2,
 ('m', '4'): 2,
 ('l', 'x'): 2,
 ('x', 'v'): 2,
 ('a', '1'): 2,
 ('w', '9'): 2,
 ('9', 'y'): 2,
 ('2', 'a'): 2,
 ('j', 'm'): 2,
 ('f', 'k'): 2,
 ('g', 'v'): 2,
 ('b', 'z'): 2,
 ('q', 'a'): 2,
 ('v', 'c'): 2,
 ('2', 'o'): 2,
 ('b', 'x'): 2,
 ('z', 'c'): 2,
 ('f', 'p'): 2,
 ('8', 's'): 2,
 ("'", '9'): 2,
 ("'", '5'): 2,
 ('0', 'k'): 2,
 ('4', 'a'): 2,
 ('b', 'g'): 2,
 ("'", 'j'): 2,
 ('h', '2'): 2,
 ('0', 'l'): 2,
 ('j', 'd'): 2,
 ('2', 's'): 2,
 ('j', 'n'): 1,
 ('0', 'r'): 1,
 ('f', "'"): 1,
 ('0', 'm'): 1,
 ('w', 'z'): 1,
 ('g', 'z'): 1,
 ('3', 'o'): 1,
 ('4', 'o'): 1,
 ('6', 'o'): 1,
 ('1', 'c'): 1,
 ('1', 'a'): 1,
 ('g', '9'): 1,
 ('v', 'd'): 1,
 ('m', '2'): 1,
 ('k', '6'): 1,
 ('9', 'a'): 1,
 ('j', 'l'): 1,
 ('z', 'm'): 1,
 ('0', "'"): 1,
 ('l', '2'): 1,
 ('9', 'l'): 1,
 ('l', '5'): 1,
 ('8', 'h'): 1,
 ('4', 'm'): 1,
 ('8', 'p'): 1,
 ('m', '1'): 1,
 ('a', '3'): 1,
 ('q', 'e'): 1,
 ('4', 'x'): 1,
 ('9', 'b'): 1,
 ('5', 'f'): 1,
 ('4', 's'): 1,
 ('5', 's'): 1,
 ('b', '7'): 1,
 ('o', '0'): 1,
 ('2', 'c'): 1,
 ('w', '7'): 1,
 ('7', 'b'): 1,
 ('8', 'x'): 1,
 ('x', '1'): 1,
 ('0', 'n'): 1,
 ("'", '6'): 1,
 ('r', '5'): 1,
 ('s', '5'): 1,
 ('m', '5'): 1,
 ('0', 'c'): 1,
 ('q', 's'): 1,
 ('9', 's'): 1,
 ('z', 'n'): 1,
 ('m', "'"): 1,
 ('b', "'"): 1,
 ('y', '1'): 1,
 ('5', 'h'): 1,
 ("'", '8'): 1,
 ('k', '4'): 1,
 ('z', 'f'): 1,
 ('7', 'p'): 1,
 ('q', 'v'): 1,
 ('v', 'f'): 1,
 ('6', 's'): 1,
 ('3', 'd'): 1,
 ('x', "'"): 1,
 ('7', 'o'): 1,
 ('8', 'o'): 1,
 ('6', 'l'): 1,
 ('c', 'v'): 1,
 ('x', 'm'): 1,
 ('x', '6'): 1,
 ('0', 'f'): 1,
 ("'", 'q'): 1,
 ('i', '8'): 1,
 ('8', 'n'): 1,
 ('x', 'g'): 1,
 ('d', '2'): 1,
 ('5', 'l'): 1,
 ('8', 'b'): 1,
 ('o', '4'): 1,
 ('z', 'd'): 1,
 ('g', '2'): 1,
 ('p', 'x'): 1,
 ('7', 'h'): 1,
 ('h', '3'): 1,
 ('6', 'e'): 1}

In [460]:
dct_c2

{('.', '_'): 435802,
 ('t', '_'): 405188,
 ('t', 'h'): 286912,
 ('s', '_'): 279133,
 ('o', 'u'): 241694,
 ('n', '_'): 224509,
 ('d', '_'): 199163,
 ('i', 'n'): 187051,
 (',', '_'): 177291,
 ('e', 'r'): 171377,
 ('y', '_'): 170823,
 ('r', '_'): 169575,
 ('y', 'o'): 161552,
 ('o', '_'): 158570,
 ('a', 'n'): 156511,
 ('h', 'a'): 141491,
 ('u', '_'): 135623,
 ('h', 'e_'): 127255,
 ('i', '_'): 126232,
 ('h', 'e'): 123261,
 ('o', 'n'): 122342,
 ('a', 't'): 120991,
 ('t', 'o'): 108364,
 ('l', '_'): 107287,
 ('l', 'l'): 104796,
 ('i', 't'): 104719,
 ('n', 'g'): 99478,
 ('r', 'e_'): 92025,
 ('g', '_'): 89713,
 ('o', 'r'): 88425,
 ('h', 'i'): 86574,
 ('n', 'd'): 86449,
 ('i', 's'): 85924,
 ('e', 'n'): 85895,
 ('?', '_'): 84640,
 ('a', 'r'): 82818,
 ('a', '_'): 81686,
 ('s', 't'): 78706,
 ('n', 'o'): 77134,
 ('e', 's'): 71709,
 ('e', 'a'): 68049,
 ('h', '_'): 64617,
 ('f', '_'): 63686,
 ('m', 'e_'): 62434,
 ('a', 'l'): 61623,
 ('w', 'h'): 61169,
 ('m', '_'): 61166,
 ('d', 'o'): 60236,
 ('e', 'l'): 59120,
 ('a', 's'): 58861,
 ('r', 'e'): 58092,
 ('o', 'w'): 57751,
 ("'", 's'): 57136,
 ('t', 'e'): 56628,
 ('e', 'd'): 55544,
 ('u', 'r'): 54896,
 ('h', 'o'): 54478,
 ('u', 't'): 53640,
 ('w', 'a'): 53622,
 ('e', 't'): 53453,
 ('v', 'e_'): 52048,
 ('o', 'm'): 51184,
 ('l', 'i'): 50694,
 ("'", 't'): 50517,
 ('w', '_'): 50017,
 ('k', '_'): 49455,
 ('o', 't'): 49292,
 ('g', 'o'): 47979,
 ('n', 't'): 47700,
 ('r', 'i'): 47625,
 ('m', 'a'): 47126,
 ('o', 'f'): 46999,
 ('c', 'o'): 45898,
 ('l', 'e'): 44031,
 ('v', 'e'): 43560,
 ('u', 's'): 43270,
 ('c', 'a'): 42797,
 ('t', 'i'): 42341,
 ('r', 'o'): 42178,
 ('o', 'o'): 42081,
 ('l', 'o'): 41988,
 ('s', 'o'): 39673,
 ('f', 'o'): 39473,
 ('a', 'y'): 39460,
 ('s', 'e'): 39335,
 ('g', 'h'): 37912,
 ('b', 'e'): 37217,
 ('w', 'i'): 36661,
 ('t', 'a'): 36642,
 ('n', 'e'): 36388,
 ('i', 'l'): 35803,
 ('m', 'e'): 35347,
 ('s', 'h'): 34641,
 ('c', 'h'): 33317,
 ('r', 'a'): 32061,
 ('a', 'v'): 31966,
 ('i', 'g'): 31932,
 ('l', 'a'): 31705,
 ('d', 'e'): 31219,
 ('l', 'd'): 31148,
 ('!', '_'): 30794,
 ('i', 'd'): 30571,
 ('a', 'i'): 30544,
 ('g', 'e'): 30475,
 ('h', 't'): 30254,
 ('e', 'e'): 29902,
 ('a', 'd'): 29892,
 ('d', 'i'): 29680,
 ('i', 'm'): 29610,
 ('r', 's'): 29565,
 ('s', 'e_'): 29113,
 ('s', 'i'): 29060,
 ('r', 'y'): 28834,
 ('w', 'e'): 28681,
 ('w', 'o'): 28647,
 ('u', 'l'): 28528,
 ('u', 'n'): 28361,
 ('b', 'o'): 27687,
 ('k', 'e_'): 26244,
 ('m', 'i'): 25809,
 ('p', '_'): 25600,
 ('i', 'c'): 25428,
 ('m', 'o'): 25424,
 ('a', 'c'): 25292,
 ('p', 'e'): 24925,
 ('n', 'e_'): 24775,
 ('b', 'u'): 24142,
 ('l', 'e_'): 23801,
 ('w', 'e_'): 23706,
 ('t', 't'): 23677,
 ('o', 'l'): 23644,
 ('l', 'y'): 23512,
 ('s', 's'): 23332,
 ('m', 'y'): 23323,
 ('s', 'a'): 23275,
 ('n', 'i'): 23248,
 ('e', 'v'): 23140,
 ('b', 'e_'): 22903,
 ('i', 'r'): 22736,
 ('e', 'y'): 22413,
 ('a', 'm'): 22183,
 ('c', 'k'): 22011,
 ('i', 'f'): 21415,
 ('t', 'r'): 21409,
 ('y', 'e'): 21246,
 ('e', 'm'): 21140,
 ('o', 'd'): 20942,
 ('r', 't'): 20437,
 ('c', 'e_'): 20400,
 ('n', 'k'): 20121,
 ("'", 'l'): 20068,
 ('a', 'k'): 19921,
 ('i', 'e'): 19524,
 ('f', 'i'): 18897,
 ('k', 'n'): 18360,
 ('a', 'b'): 18160,
 ('p', 'l'): 18092,
 ('n', 's'): 17802,
 ('d', 'a'): 17622,
 ('o', 's'): 17389,
 ('b', 'a'): 17346,
 ('k', 'i'): 17251,
 ("'", 'm'): 17037,
 ('f', 'r'): 16526,
 ('p', 'a'): 16518,
 ('r', 'r'): 16403,
 ('e', 'c'): 16181,
 ('r', 'd'): 15941,
 ('n', 'c'): 15796,
 ('n', 'y'): 15582,
 ("'", 'r'): 15562,
 ('i', 'o'): 15354,
 ('u', 'p'): 15265,
 ('n', 'a'): 15244,
 ('s', 'u'): 15192,
 ('p', 'o'): 15182,
 ('i', 'v'): 15138,
 ('k', 'e'): 14879,
 ('p', 'r'): 14867,
 ('a', 'p'): 14004,
 ('o', 'p'): 13928,
 ('o', 'k'): 13890,
 ('u', 'g'): 13794,
 ('e', 'e_'): 13708,
 ('a', 'g'): 13270,
 ('b', 'l'): 13249,
 ('o', 'v'): 13184,
 ('o', 'i'): 12969,
 ('i', 'k'): 12955,
 ('g', 'i'): 12820,
 ('f', 'e'): 12768,
 ('c', 't'): 12719,
 ('j', 'u'): 12313,
 ('m', 'u'): 12152,
 ('f', 'a'): 12075,
 ('t', 's'): 11837,
 ('t', 'e_'): 11801,
 ("'", 'v'): 11583,
 ('o', 'h'): 11402,
 ('g', 'a'): 11225,
 ('t', 'l'): 11083,
 ('n', 'n'): 11083,
 ('d', 'n'): 10734,
 ('r', 'n'): 10594,
 ('c', 'e'): 10391,
 ('d', 'r'): 10366,
 ('v', 'i'): 10260,
 ('e', 'p'): 10242,
 ('u', 'c'): 10232,
 ('p', 'p'): 10213,
 ('b', 'r'): 10186,
 ('f', 'f'): 10034,
 ('m', 'r'): 9956,
 ('a', 'u'): 9823,
 ('d', 'y'): 9791,
 ('t', 'y'): 9687,
 ('w', 'n'): 9593,
 ('g', 'r'): 9588,
 ('t', 'u'): 9527,
 ('r', 'l'): 9430,
 ('y', 's'): 9406,
 ('p', 'i'): 9275,
 ('h', 'y'): 9149,
 ('s', 'p'): 9003,
 ('r', 'u'): 8939,
 ('"', '_'): 8870,
 ('e', 'f'): 8710,
 ('e', 'x'): 8613,
 ('e', 'w'): 8254,
 ('h', 'u'): 8161,
 ('a', 'w'): 8001,
 ('g', 'u'): 7969,
 ('d', 's'): 7933,
 ('f', 'u'): 7915,
 ("'", 'd'): 7898,
 ('-', '_'): 7821,
 ('m', 'p'): 7739,
 ('c', 'i'): 7662,
 ('i', 'a'): 7588,
 ('c', 'r'): 7544,
 ('q', 'u'): 7332,
 ('c', 'l'): 7330,
 ('g', 'e_'): 7157,
 ('e', 'i'): 7150,
 ('s', 'n'): 7136,
 ('b', 'i'): 7069,
 ('d', 'e_'): 7065,
 ('b', 'y'): 6974,
 ('u', 'i'): 6965,
 ('o', 'c'): 6931,
 ('a', 'f'): 6916,
 ('l', 's'): 6748,
 ('k', 's'): 6623,
 ('f', 't'): 6508,
 ('r', 'g'): 6341,
 ('j', 'o'): 6237,
 ('c', 'u'): 6200,
 ('r', 'm'): 6185,
 ('o', 'b'): 6066,
 ('s', 'c'): 6058,
 ('n', 'l'): 6057,
 ('r', 'k'): 6057,
 ('l', 'k'): 5993,
 ('l', 'f'): 5983,
 ('a', 'h'): 5832,
 ('h', 'r'): 5830,
 ('p', 'u'): 5780,
 ('i', 'e_'): 5581,
 ('y', 't'): 5522,
 ('e', 'o'): 5384,
 ('m', 'b'): 5282,
 ('l', 'u'): 5234,
 ('u', 'm'): 5228,
 ('o', 'e'): 5220,
 ('o', 'y'): 5158,
 ('s', 'k'): 5103,
 ('g', 's'): 5063,
 ('o', 'a'): 4839,
 ('u', 'e'): 4621,
 ('e', 'g'): 4467,
 ('t', 'w'): 4438,
 ('f', 'e_'): 4436,
 ('n', 'u'): 4354,
 ('i', 'p'): 4349,
 ('y', 'i'): 4227,
 ('y', 'b'): 4119,
 ('s', 'l'): 4079,
 ('u', 'b'): 4056,
 ('g', 'l'): 4033,
 ('l', 't'): 4031,
 ('t', 'c'): 3994,
 ('p', 's'): 3953,
 ('o', 'g'): 3938,
 ('v', 'a'): 3919,
 ('p', 't'): 3892,
 ('m', 'm'): 3806,
 ('u', 'd'): 3737,
 ('0', '_'): 3734,
 ('p', 'h'): 3699,
 ('d', 'd'): 3650,
 ('d', 'u'): 3641,
 ('c', '_'): 3637,
 ('r', 'c'): 3547,
 ('u', 'a'): 3499,
 ('s', 'w'): 3479,
 ('i', 'b'): 3438,
 ('b', '_'): 3407,
 ('f', 'l'): 3375,
 ('m', 's'): 3341,
 ('l', 'p'): 3328,
 ('w', 'r'): 3090,
 ('k', 'a'): 2976,
 ('s', 'm'): 2963,
 ('j', 'e'): 2930,
 ('p', 'e_'): 2867,
 ("'", '_'): 2865,
 ('w', 's'): 2835,
 ('r', 'v'): 2717,
 ('j', 'a'): 2657,
 ('d', 'l'): 2616,
 ('s', 'y'): 2567,
 ('v', 'o'): 2555,
 ('l', 'w'): 2527,
 ('u', 'y'): 2395,
 ('x', 'p'): 2388,
 ('c', 'c'): 2368,
 ('g', 'n'): 2361,
 ('u', 'e_'): 2326,
 ('g', 'g'): 2311,
 ('x', 'c'): 2298,
 ('x', '_'): 2234,
 ('0', '0'): 2222,
 ('e', 'b'): 2174,
 ('u', 'h'): 2145,
 ('r', 'f'): 2136,
 ('y', 'a'): 2039,
 ('i', 'z'): 2016,
 (':', '_'): 1991,
 ('x', 't'): 1958,
 ('y', 'e_'): 1929,
 ('p', 'y'): 1928,
 ('l', 'm'): 1918,
 ('e', 'h'): 1893,
 ('r', 'p'): 1836,
 ('e', 'u'): 1831,
 ('e', 'k'): 1828,
 ('n', 'f'): 1766,
 ('n', 'v'): 1704,
 ('k', 'y'): 1631,
 ('a', 'z'): 1621,
 ('h', 'n'): 1607,
 ('d', 'g'): 1607,
 ('c', 'y'): 1570,
 ('i', 'x'): 1564,
 ('l', 'r'): 1499,
 ('r', 'h'): 1478,
 ('u', 'f'): 1443,
 ('r', 'b'): 1386,
 ('t', 'm'): 1382,
 ('s', 'b'): 1380,
 ('n', "'"): 1315,
 ('l', 'v'): 1307,
 ('b', 'b'): 1298,
 ('y', 'w'): 1297,
 ('b', 's'): 1198,
 ('x', 'a'): 1193,
 ('y', 'm'): 1090,
 ('z', 'e'): 1084,
 ('t', 'n'): 1062,
 ('k', 'l'): 1053,
 ('z', 'e_'): 1048,
 ('x', 'i'): 966,
 ('o', 'e_'): 965,
 ('h', 'm'): 945,
 ('z', 'y'): 925,
 ('5', '_'): 904,
 ('h', 's'): 897,
 ('z', 'a'): 884,
 ('z', 'i'): 879,
 ('1', '0'): 877,
 ('k', 'o'): 867,
 ('a', 'x'): 843,
 ('d', 'b'): 841,
 ('n', 'r'): 795,
 ('d', 'm'): 795,
 ('j', 'i'): 791,
 ('o', 'x'): 774,
 ("'", 'e'): 745,
 ('x', 'e'): 735,
 ('y', 'l'): 722,
 ('w', 'f'): 712,
 ('2', '_'): 699,
 ('d', 'v'): 697,
 ('y', 'p'): 696,
 ('y', 'n'): 696,
 ('1', '_'): 694,
 ('a', 'j'): 692,
 ('r', 'w'): 660,
 ('z', '_'): 649,
 ('l', 'c'): 623,
 ('s', 'q'): 602,
 ('w', 'l'): 599,
 ('g', 'y'): 597,
 ('a', 'e'): 589,
 ('n', 'j'): 587,
 ("'", 'a'): 584,
 ('n', 'h'): 559,
 ('l', 'b'): 544,
 ('m', 'c'): 542,
 ('2', '0'): 535,
 ('k', 'r'): 534,
 ('w', 'd'): 520,
 ('b', 't'): 514,
 ('d', 'f'): 513,
 ('d', 'w'): 510,
 ('t', 'f'): 498,
 ('i', 'u'): 482,
 ('5', '0'): 476,
 ('u', 'k'): 475,
 ('f', 'y'): 475,
 ('3', '_'): 474,
 ('g', 't'): 470,
 ('4', '_'): 466,
 ('v', 'y'): 464,
 ('h', 'l'): 462,
 ('e', 'q'): 460,
 ('8', '_'): 454,
 ('s', "'"): 453,
 ('3', '0'): 446,
 ('s', 'f'): 429,
 ('7', '_'): 422,
 ('i', 'i'): 418,
 ('n', 'm'): 417,
 ('n', 'b'): 414,
 ('b', 'j'): 413,
 ('m', 'n'): 412,
 ('y', 'c'): 397,
 ('t', 'z'): 394,
 ('6', '_'): 393,
 ('w', 'y'): 392,
 ('o', 'z'): 392,
 ('z', 'z'): 390,
 ('c', 's'): 376,
 ('z', 'o'): 369,
 ('e', 'z'): 366,
 ('v', '_'): 360,
 ('k', 'u'): 349,
 ('y', 'r'): 338,
 ('k', 'f'): 331,
 ('k', 'h'): 328,
 ('s', 'd'): 326,
 ('m', 'f'): 321,
 ('1', '5'): 320,
 ('y', 'd'): 318,
 ("'", 'c'): 313,
 ('h', 'b'): 306,
 ('n', 'w'): 289,
 ('1', '2'): 286,
 ('9', '_'): 286,
 ('l', 'g'): 286,
 ('c', 'q'): 281,
 ('$', '_'): 280,
 ('s', 'g'): 276,
 ('1', '9'): 275,
 ('u', 'z'): 265,
 ('g', "'"): 262,
 ('u', 'o'): 261,
 ("'", 'i'): 257,
 ('h', 'd'): 257,
 ('n', 'q'): 248,
 ('4', '0'): 228,
 ('n', 'p'): 224,
 ('i', 'q'): 223,
 ('h', 'w'): 219,
 ('u', 'v'): 215,
 ('d', 'h'): 196,
 ('t', 'b'): 191,
 ('1', '1'): 190,
 ('a', 'o'): 190,
 ('h', 'h'): 184,
 ('l', 'n'): 179,
 ('g', 'f'): 177,
 ('n', 'z'): 177,
 ('f', 's'): 176,
 ('d', 'p'): 173,
 ('2', '5'): 173,
 ('b', 'v'): 169,
 ('1', '8'): 167,
 ('y', 'f'): 154,
 ('a', 'a'): 154,
 ('n', 'x'): 153,
 ('d', 'c'): 150,
 ('p', 'm'): 149,
 ('w', 'k'): 148,
 ('c', 'g'): 144,
 ('i', 'y'): 142,
 ('e', 'j'): 142,
 ('y', 'h'): 140,
 ('m', 'l'): 136,
 ("'", 'n'): 134,
 ('z', 'l'): 132,
 ('k', 'm'): 127,
 ('g', 'm'): 127,
 ('u', 'x'): 127,
 ('h', 'f'): 126,
 ('w', 'b'): 126,
 ('v', 'l'): 125,
 ('j', '_'): 123,
 ('y', 'g'): 122,
 ('d', 't'): 121,
 ('k', 't'): 120,
 ('g', 'd'): 114,
 ('l', 'h'): 114,
 ('6', '0'): 112,
 ('t', 'p'): 112,
 ('w', 't'): 111,
 ('x', 'h'): 111,
 ('m', 't'): 111,
 ('1', '6'): 109,
 ('t', 'g'): 108,
 ('1', '7'): 107,
 ('h', 'k'): 107,
 ('k', 'w'): 107,
 ('v', 'u'): 106,
 ('s', 'r'): 105,
 ('h', 'c'): 103,
 ('1', '4'): 101,
 ('y', 'u'): 101,
 ('2', '4'): 94,
 ('d', 'q'): 90,
 ("'", 'h'): 90,
 ('i', 'j'): 90,
 ('d', 'j'): 90,
 ('v', 'r'): 89,
 ('1', '3'): 88,
 ('c', 'n'): 86,
 ('g', 'w'): 85,
 ('s', 'v'): 83,
 ('4', '5'): 82,
 ('c', 'f'): 80,
 ('r', 'z'): 78,
 ('m', 'h'): 76,
 ('d', 'k'): 74,
 ('9', '0'): 74,
 ('9', '3'): 73,
 ('c', 'd'): 72,
 ('p', 'k'): 70,
 ('o', 'q'): 69,
 ('l', 'z'): 69,
 ('a', 'q'): 68,
 ('r', 'j'): 68,
 ('z', 'u'): 67,
 ('9', '2'): 65,
 ('3', '5'): 64,
 ('3', '2'): 64,
 ('o', 'j'): 64,
 ('8', '0'): 64,
 ('s', 'z'): 62,
 ('g', 'b'): 62,
 ('x', 'o'): 61,
 ('2', '1'): 60,
 ('7', '0'): 60,
 ('2', '2'): 59,
 ('2', '7'): 59,
 ('k', 'b'): 58,
 ('%', '_'): 57,
 ('p', 'n'): 57,
 ('c', 'z'): 56,
 ('b', 'm'): 55,
 ('3', '1'): 55,
 ('p', 'f'): 54,
 ('c', 'm'): 52,
 ('f', 'w'): 51,
 ('p', 'b'): 50,
 ('2', '6'): 49,
 ('w', 'p'): 48,
 ('u', 'j'): 48,
 ('[', '_'): 47,
 (']', '_'): 47,
 ('u', 'w'): 47,
 ('9', '4'): 46,
 ('r', 'q'): 45,
 ('2', '9'): 45,
 ('x', 'l'): 44,
 ('x', 'u'): 42,
 ('7', '5'): 42,
 ('0', 't'): 42,
 ('i', 'w'): 42,
 ("'", 'y'): 41,
 ('x', 'y'): 41,
 ('2', '8'): 41,
 ('2', '3'): 41,
 ('/', '_'): 40,
 ('4', '8'): 40,
 ('3', '7'): 40,
 ('b', 'd'): 40,
 ('j', 'e_'): 39,
 ('k', 'g'): 39,
 ('p', 'j'): 39,
 ('i', 'h'): 39,
 ('3', '6'): 38,
 ('4', '2'): 38,
 ('a', 'e_'): 37,
 ('5', 't'): 36,
 ('3', '8'): 36,
 ('b', 'w'): 35,
 ('y', 'z'): 35,
 ('p', 'w'): 35,
 ('0', '1'): 35,
 ('t', 'd'): 34,
 ('w', 'u'): 34,
 ('w', 'm'): 34,
 ('9', '1'): 34,
 ('k', 'd'): 33,
 ('6', '5'): 33,
 ("'", 'b'): 33,
 ('4', '1'): 33,
 ('h', 'p'): 33,
 ('f', 'm'): 32,
 ('7', 't'): 32,
 ('k', 'p'): 32,
 ('k', 'k'): 32,
 ('x', 'q'): 31,
 ('w', 'c'): 31,
 ('x', 'f'): 30,
 ('o', "'"): 30,
 ('4', 't'): 30,
 ('t', 'j'): 30,
 ('3', '4'): 30,
 ('8', '8'): 30,
 ('t', "'"): 29,
 ("'", 'w'): 29,
 ('c', 'p'): 28,
 ('2', 'n'): 28,
 ('z', 'k'): 28,
 ('9', '5'): 28,
 ('3', '3'): 28,
 ('j', 'r'): 27,
 ('l', 'j'): 27,
 ('z', 'g'): 27,
 ('q', '_'): 27,
 ('8', 't'): 27,
 ('t', 'k'): 27,
 ('(', '_'): 26,
 (')', '_'): 26,
 ('y', 'k'): 26,
 ('1', 's'): 26,
 ("'", 'o'): 26,
 ('c', 'w'): 25,
 ('4', '3'): 25,
 ('v', 'v'): 25,
 ('5', '1'): 25,
 ('x', 'e_'): 24,
 ('8', '5'): 24,
 ('y', 'j'): 23,
 ('4', '7'): 23,
 ('f', 'h'): 23,
 ('y', 'v'): 22,
 ('9', '8'): 22,
 ('6', 't'): 22,
 ('5', '2'): 22,
 ('0', '5'): 22,
 ('p', 'c'): 22,
 ('9', '6'): 22,
 ('e', "'"): 22,
 ('g', 'k'): 21,
 ('3', '9'): 21,
 ('b', 'c'): 21,
 ('9', 't'): 21,
 ('f', 'j'): 21,
 ('0', '4'): 21,
 ('f', 'c'): 20,
 ('z', 't'): 20,
 ('3', 'r'): 20,
 ('l', "'"): 20,
 ('5', '5'): 20,
 ('9', '9'): 20,
 ('b', 'n'): 20,
 ('7', '1'): 20,
 ('k', 'c'): 19,
 ('4', '4'): 19,
 ('6', '6'): 19,
 ('5', '9'): 19,
 ('x', 'w'): 18,
 ('v', 'g'): 18,
 ('h', 'q'): 18,
 ('h', 'j'): 18,
 ('4', '6'): 18,
 ('u', 'q'): 18,
 ('k', 'v'): 17,
 ('z', 'b'): 17,
 ('0', '8'): 17,
 ('5', '4'): 17,
 ('8', '1'): 17,
 ('y', "'"): 17,
 ('9', '7'): 17,
 ('d', 'z'): 16,
 ('7', '2'): 16,
 ('6', '2'): 16,
 ('7', '3'): 16,
 ('8', '6'): 16,
 ('0', '3'): 16,
 ('z', 'v'): 15,
 ('u', 'u'): 15,
 ('i', "'"): 15,
 ("'", 'u'): 15,
 ('f', 'b'): 15,
 ('4', '9'): 15,
 ('s', 'j'): 15,
 ('7', '7'): 15,
 ('8', '9'): 15,
 ('g', 'p'): 15,
 ('m', 'q'): 14,
 ('3', 't'): 14,
 ('h', 'v'): 14,
 ('c', 'b'): 14,
 ('f', 'n'): 14,
 ('d', "'"): 14,
 ('0', '2'): 14,
 ('0', 's'): 14,
 ('6', '4'): 14,
 ("'", 'p'): 14,
 ('l', 'q'): 13,
 ('t', 'v'): 13,
 ('v', 's'): 13,
 ('5', '6'): 13,
 ('6', '1'): 13,
 ('v', 'n'): 13,
 ('8', '7'): 13,
 ('8', '4'): 13,
 ('5', '7'): 13,
 ('0', '9'): 13,
 ('8', '2'): 13,
 ('w', 'w'): 12,
 ('5', '8'): 12,
 ('5', '3'): 12,
 ('6', '7'): 12,
 ('k', 'j'): 12,
 ('7', '6'): 12,
 ('0', '6'): 11,
 ('m', 'w'): 11,
 ('6', '9'): 11,
 ('7', '4'): 11,
 ('6', '3'): 11,
 ('r', "'"): 11,
 ('u', "'"): 10,
 ('v', 'k'): 10,
 ('b', 'p'): 10,
 ('p', 'g'): 10,
 ('m', 'd'): 10,
 ('z', 'h'): 10,
 ('2', 't'): 9,
 ('m', 'k'): 9,
 ('g', 'c'): 9,
 ('l', '1'): 9,
 ('8', '3'): 9,
 ('b', 'f'): 9,
 ('7', '8'): 9,
 ('6', '8'): 9,
 ('7', '9'): 9,
 ("'", '3'): 9,
 ("'", 'f'): 9,
 ('0', '7'): 8,
 ('b', 'h'): 8,
 ('s', '1'): 7,
 ("'", '2'): 7,
 ('z', 'w'): 7,
 ('p', 'd'): 7,
 ('1', 't'): 6,
 ('r', 'x'): 6,
 ('m', 'g'): 6,
 ('5', 'c'): 6,
 ('w', 'g'): 6,
 ('z', 's'): 6,
 ("'", '1'): 6,
 ('b', 'k'): 5,
 ('r', '1'): 5,
 ('v', 't'): 5,
 ('5', 'o'): 5,
 ('h', "'"): 5,
 ('m', 'z'): 5,
 ('x', 'n'): 5,
 ('m', 'v'): 5,
 ('a', "'"): 5,
 ("'", '4'): 5,
 ('j', 'v'): 4,
 ('2', 'k'): 4,
 ('p', 'z'): 4,
 ('z', 'r'): 4,
 ('x', '4'): 4,
 ("'", 'k'): 4,
 ('k', "'"): 4,
 ('f', 'v'): 4,
 ("'", 'g'): 4,
 ('f', 'g'): 4,
 ('h', 'g'): 3,
 ('6', 'f'): 3,
 ("'", '0'): 3,
 ('0', 'o'): 3,
 ('5', 'p'): 3,
 ('j', 's'): 3,
 ('c', '2'): 3,
 ('2', 'h'): 3,
 ("'", '7'): 3,
 ('x', 'b'): 3,
 ('z', 'p'): 3,
 ('x', 'x'): 3,
 ('p', "'"): 3,
 ('y', 'x'): 3,
 ('y', 'y'): 3,
 ('j', 'p'): 3,
 ('w', "'"): 3,
 ('p', 'v'): 3,
 ('6', 'a'): 2,
 ('m', '4'): 2,
 ('l', 'x'): 2,
 ('x', 'v'): 2,
 ('a', '1'): 2,
 ('w', '9'): 2,
 ('9', 'y'): 2,
 ('2', 'a'): 2,
 ('j', 'm'): 2,
 ('f', 'k'): 2,
 ('g', 'v'): 2,
 ('b', 'z'): 2,
 ('q', 'a'): 2,
 ('v', 'c'): 2,
 ('2', 'o'): 2,
 ('b', 'x'): 2,
 ('z', 'c'): 2,
 ('f', 'p'): 2,
 ('8', 's'): 2,
 ("'", '9'): 2,
 ("'", '5'): 2,
 ('0', 'k'): 2,
 ('4', 'a'): 2,
 ('b', 'g'): 2,
 ("'", 'j'): 2,
 ('h', '2'): 2,
 ('0', 'l'): 2,
 ('j', 'd'): 2,
 ('2', 's'): 2,
 ('j', 'n'): 1,
 ('0', 'r'): 1,
 ('f', "'"): 1,
 ('0', 'm'): 1,
 ('w', 'z'): 1,
 ('g', 'z'): 1,
 ('3', 'o'): 1,
 ('4', 'o'): 1,
 ('6', 'o'): 1,
 ('1', 'c'): 1,
 ('1', 'a'): 1,
 ('g', '9'): 1,
 ('v', 'd'): 1,
 ('m', '2'): 1,
 ('k', '6'): 1,
 ('9', 'a'): 1,
 ('j', 'l'): 1,
 ('z', 'm'): 1,
 ('0', "'"): 1,
 ('l', '2'): 1,
 ('9', 'l'): 1,
 ('l', '5'): 1,
 ('8', 'h'): 1,
 ('4', 'm'): 1,
 ('8', 'p'): 1,
 ('m', '1'): 1,
 ('a', '3'): 1,
 ('q', 'e'): 1,
 ('4', 'x'): 1,
 ('9', 'b'): 1,
 ('5', 'f'): 1,
 ('4', 's'): 1,
 ('5', 's'): 1,
 ('b', '7'): 1,
 ('o', '0'): 1,
 ('2', 'c'): 1,
 ('w', '7'): 1,
 ('7', 'b'): 1,
 ('8', 'x'): 1,
 ('x', '1'): 1,
 ('0', 'n'): 1,
 ("'", '6'): 1,
 ('r', '5'): 1,
 ('s', '5'): 1,
 ('m', '5'): 1,
 ('0', 'c'): 1,
 ('q', 's'): 1,
 ('9', 's'): 1,
 ('z', 'n'): 1,
 ('m', "'"): 1,
 ('b', "'"): 1,
 ('y', '1'): 1,
 ('5', 'h'): 1,
 ("'", '8'): 1,
 ('k', '4'): 1,
 ('z', 'f'): 1,
 ('7', 'p'): 1,
 ('q', 'v'): 1,
 ('v', 'f'): 1,
 ('6', 's'): 1,
 ('3', 'd'): 1,
 ('x', "'"): 1,
 ('7', 'o'): 1,
 ('8', 'o'): 1,
 ('6', 'l'): 1,
 ('c', 'v'): 1,
 ("'", 'e_'): 1,
 ('x', 'm'): 1,
 ('x', '6'): 1,
 ('0', 'f'): 1,
 ("'", 'q'): 1,
 ('i', '8'): 1,
 ('8', 'n'): 1,
 ('x', 'g'): 1,
 ('d', '2'): 1,
 ('5', 'l'): 1,
 ('8', 'b'): 1,
 ('o', '4'): 1,
 ('z', 'd'): 1,
 ('g', '2'): 1,
 ('p', 'x'): 1,
 ('7', 'h'): 1,
 ('h', '3'): 1,
 ('6', 'e_'): 1}

#### 2.VER -  MOZNA ODEJMOWAC OD TYCH CO ZNALAZLA: ('h', 'e'): 250516 - ('h', 'e_'): 127255 ==> ('h', 'e'): 123261

#### 3.4 BPE Encoder propably should add to the BPE Class Later

In [107]:
test_word = ' '.join(char_factor("running"))
test_word

'r u n n i n g </w>'

In [175]:
# pair = 'g </w>'
pair = '['
sub_pair = lambda x: re.sub('\s+', '', x)
re.sub(rf"( |^){re.escape(pair)}( |$)", rf"\g<1>{sub_pair(pair)}\g<2>", "r u n n i n g </w>")

'r u n n i n g </w>'

In [196]:
def word_encoder(word, vocab):
    word_str = ' '.join(char_factor(word)) #do zmiany uzywanie char_factor spoza funkcji
    sub_key = lambda x: re.sub('\s+', '', x)
    
    for k, v in vocab.items():
        if bool(re.search(rf"( |^){re.escape(k)}( |$)", word_str)):
            print(k, v)
            print(word_str)
            word_str = re.sub(rf"( |^){re.escape(k)}( |$)", rf"\g<1>{sub_key(k)}\g<2>", word_str)
            print(word_str, '\n')
    return word_str

In [218]:
tokenizer_eng.vocab

{'<pad>': 0,
 '<unk>': 1,
 '<eos>': 2,
 '</w>': 3,
 '9': 4,
 'h': 5,
 '4': 6,
 'z': 7,
 '.': 8,
 't': 9,
 '%': 10,
 '1': 11,
 'u': 12,
 'w': 13,
 '7': 14,
 '[': 15,
 '3': 16,
 'c': 17,
 '5': 18,
 'd': 19,
 'i': 20,
 '8': 21,
 '$': 22,
 ']': 23,
 ')': 24,
 'v': 25,
 'l': 26,
 'k': 27,
 ',': 28,
 'm': 29,
 'r': 30,
 'j': 31,
 'q': 32,
 's': 33,
 '"': 34,
 '6': 35,
 'x': 36,
 '?': 37,
 'e': 38,
 'f': 39,
 'y': 40,
 '/': 41,
 '(': 42,
 '-': 43,
 ':': 44,
 'o': 45,
 '2': 46,
 "'": 47,
 '0': 48,
 'g': 49,
 'n': 50,
 'p': 51,
 '!': 52,
 'a': 53,
 'b': 54,
 'e </w>': 55,
 '. </w>': 56,
 't </w>': 57,
 't h': 58,
 's </w>': 59,
 'o u': 60,
 'n </w>': 61,
 'd </w>': 62,
 ', </w>': 63,
 'e r': 64,
 'y </w>': 65,
 'y ou': 66,
 'o </w>': 67,
 'i n': 68,
 'you </w>': 69,
 'i </w>': 70,
 'a n': 71,
 'l </w>': 72,
 'r </w>': 73,
 'th e</w>': 74,
 'g </w>': 75,
 'a t</w>': 76,
 '? </w>': 77,
 'a </w>': 78,
 'l l</w>': 79,
 't o</w>': 80,
 'in g</w>': 81,
 'a r': 82,
 'f </w>': 83,
 'i t</w>': 84,
 'm e</w>': 85,
 'o n</w>': 86,
 'w h': 87,
 'm </w>': 88,
 'o n': 89,
 'o w': 90,
 "' s</w>": 91,
 'i s</w>': 92,
 'v e</w>': 93,
 'o r': 94,
 "' t</w>": 95,
 'e d</w>': 96,
 'k </w>': 97,
 'an d</w>': 98,
 'h a': 99,
 's t': 100,
 'r e': 101,
 'l i': 102,
 'ow </w>': 103,
 'h </w>': 104,
 'e n': 105,
 'o f</w>': 106,
 'w a': 107,
 'e s</w>': 108,
 'h e</w>': 109,
 'r i': 110,
 'l e': 111,
 'w i': 112,
 'g h': 113,
 'g o': 114,
 '! </w>': 115,
 'b e': 116,
 's e</w>': 117,
 't i': 118,
 'gh t</w>': 119,
 'k e</w>': 120,
 'n ow</w>': 121,
 'm a': 122,
 's e': 123,
 'p </w>': 124,
 'c o': 125,
 'r o': 126,
 'd i': 127,
 'b u': 128,
 'a c': 129,
 'f or</w>': 130,
 'th e': 131,
 'l d</w>': 132,
 'w e</w>': 133,
 'h i': 134,
 'l o': 135,
 'n o': 136,
 'ou t</w>': 137,
 'l y</w>': 138,
 'm y</w>': 139,
 's i': 140,
 'e t</w>': 141,
 'h e': 142,
 'you r</w>': 143,
 'd on</w>': 144,
 't a': 145,
 "' ll</w>": 146,
 'ha ve</w>': 147,
 's a': 148,
 'l a': 149,
 'e ll</w>': 150,
 'a ll</w>': 151,
 'e v': 152,
 'd o</w>': 153,
 'm e': 154,
 't t': 155,
 'r a': 156,
 "' m</w>": 157,
 's o': 158,
 'bu t</w>': 159,
 'c e</w>': 160,
 'c a': 161,
 'wa s</w>': 162,
 "' re</w>": 163,
 'wi th</w>': 164,
 'm i': 165,
 'u n': 166,
 'no t</w>': 167,
 't o': 168,
 'd e': 169,
 'u st</w>': 170,
 'g et</w>': 171,
 'a b': 172,
 's u': 173,
 'k now</w>': 174,
 'hi m</w>': 175,
 's s</w>': 176,
 'h o': 177,
 'b o': 178,
 'n e': 179,
 'w ell</w>': 180,
 'i f</w>': 181,
 'f i': 182,
 'a l': 183,
 'the y</w>': 184,
 'y es</w>': 185,
 'd o': 186,
 "' ve</w>": 187,
 'c h</w>': 188,
 'r y</w>': 189,
 'li ke</w>': 190,
 'co me</w>': 191,
 'o d</w>': 192,
 'ri ght</w>': 193,
 't e</w>': 194,
 'd a': 195,
 's he</w>': 196,
 'p o': 197,
 'u p</w>': 198,
 'p e': 199,
 'g i': 200,
 'd n</w>': 201,
 'o h</w>': 202,
 'a s</w>': 203,
 'wi ll</w>': 204,
 'j ust</w>': 205,
 'se e</w>': 206,
 'n i': 207,
 't s</w>': 208,
 'go od</w>': 209,
 'f e': 210,
 'd y</w>': 211,
 'go t</w>': 212,
 'w or': 213,
 'le a': 214,
 '" </w>': 215,
 'wa y</w>': 216,
 'm o': 217,
 'lo o': 218,
 't e': 219,
 'u r': 220,
 'w </w>': 221,
 "' d</w>": 222,
 '- </w>': 223,
 'wan t</w>': 224,
 'k ing</w>': 225,
 'thin k</w>': 226,
 'wh y</w>': 227,
 're a': 228,
 'p a': 229,
 'so me': 230,
 'm r</w>': 231,
 'w ou': 232,
 'q u': 233,
 'g a': 234,
 'd s</w>': 235,
 'f a': 236,
 'g e</w>': 237,
 'y s</w>': 238,
 'go ing</w>': 239,
 'di d</w>': 240,
 'i d</w>': 241,
 'c k</w>': 242,
 'y e': 243,
 'ta ke</w>': 244,
 'g e': 245,
 'the m</w>': 246,
 'f ro': 247,
 't y</w>': 248,
 'e x': 249,
 'be en</w>': 250,
 'an y': 251,
 'fro m</w>': 252,
 'he l': 253,
 'c i': 254,
 'p i': 255,
 'u s</w>': 256,
 'k s</w>': 257,
 's n</w>': 258,
 'sa y</w>': 259,
 'w e': 260,
 'm u': 261,
 'f u': 262,
 'a d</w>': 263,
 'ti on</w>': 264,
 'g u': 265,
 'ti me</w>': 266,
 'f or': 267,
 'v ery</w>': 268,
 'b ack</w>': 269,
 'r u': 270,
 'a s': 271,
 'tt le</w>': 272,
 'a f': 273,
 'k i': 274,
 'loo k</w>': 275,
 'v er</w>': 276,
 'p ro': 277,
 'k e': 278,
 'o f': 279,
 'to o</w>': 280,
 'ha p': 281,
 'se l': 282,
 'wou ld</w>': 283,
 'v i': 284,
 'j o': 285,
 'da y</w>': 286,
 'n a': 287,
 'di dn</w>': 288,
 'b i': 289,
 'si r</w>': 290,
 'p u': 291,
 'li ttle</w>': 292,
 'g s</w>': 293,
 'b y</w>': 294,
 'c u': 295,
 'p re': 296,
 'dow n</w>': 297,
 'gi ve</w>': 298,
 'l dn</w>': 299,
 'ma ke</w>': 300,
 'sel f</w>': 301,
 'on ly</w>': 302,
 'a h</w>': 303,
 's h</w>': 304,
 'h u': 305,
 'l u': 306,
 'cou ld</w>': 307,
 'y ing</w>': 308,
 'some thing</w>': 309,
 'than k</w>': 310,
 'o ver</w>': 311,
 'c e': 312,
 'ni ght</w>': 313,
 'bo dy</w>': 314,
 'fu l</w>': 315,
 'p le</w>': 316,
 'w on</w>': 317,
 'mu ch</w>': 318,
 'e p</w>': 319,
 'a m</w>': 320,
 '0 </w>': 321,
 'a ga': 322,
 'u se</w>': 323,
 'p lease</w>': 324,
 'co m': 325,
 'qu i': 326,
 's hou': 327,
 'b le</w>': 328,
 'ne w</w>': 329,
 'i r</w>': 330,
 'f o': 331,
 'be tter</w>': 332,
 'ev er': 333,
 'ever y': 334,
 'ye ah</w>': 335,
 'w o': 336,
 'no thing</w>': 337,
 'f ri': 338,
 'men t</w>': 339,
 'c </w>': 340,
 'l s</w>': 341,
 'any thing</w>': 342,
 'of f</w>': 343,
 'a way</w>': 344,
 't wo</w>': 345,
 'r s</w>': 346,
 'me an</w>': 347,
 'o ld</w>': 348,
 'lo ve</w>': 349,
 'd u': 350,
 'hel lo</w>': 351,
 'lon g</w>': 352,
 's pe': 353,
 'b </w>': 354,
 'e l</w>': 355,
 'mi ss</w>': 356,
 'be fore</w>': 357,
 'ro o': 358,
 'sa id</w>': 359,
 'aga in</w>': 360,
 "' </w>": 361,
 'fin d</w>': 362,
 'c hi': 363,
 'v en</w>': 364,
 'shou ld</w>': 365,
 'p la': 366,
 'i sn</w>': 367,
 'fa ther</w>': 368,
 'ar d</w>': 369,
 'fi r': 370,
 'sor ry</w>': 371,
 'hel p</w>': 372,
 'fri en': 373,
 'wa ys</w>': 374,
 'm ber</w>': 375,
 'af ter</w>': 376,
 'ca use</w>': 377,
 're e</w>': 378,
 'thou ght</w>': 379,
 'c han': 380,
 'pu t</w>': 381,
 'ho me</w>': 382,
 't ra': 383,
 'ma y': 384,
 's ho': 385,
 'o ple</w>': 386,
 'fir st</w>': 387,
 'pe ople</w>': 388,
 'gi r': 389,
 'min d</w>': 390,
 'thin gs</w>': 391,
 'e l': 392,
 'al ways</w>': 393,
 'tho se</w>': 394,
 'c t</w>': 395,
 'may be</w>': 396,
 'ke ep</w>': 397,
 'tal k</w>': 398,
 'in to</w>': 399,
 'j e': 400,
 'gon na</w>': 401,
 'm rs</w>': 402,
 'wa it</w>': 403,
 'a in</w>': 404,
 't ry</w>': 405,
 'be cause</w>': 406,
 'v es</w>': 407,
 'm s</w>': 408,
 'lea ve</w>': 409,
 's si': 410,
 't ri': 411,
 'the se</w>': 412,
 'o ther</w>': 413,
 'de ar</w>': 414,
 't ch</w>': 415,
 'li fe</w>': 416,
 'aroun d</w>': 417,
 'cour se</w>': 418,
 'a u': 419,
 'mone y</w>': 420,
 't ur': 421,
 'wou ldn</w>': 422,
 'i m': 423,
 'a d': 424,
 'min u': 425,
 'mor ning</w>': 426,
 'un der': 427,
 'on s</w>': 428,
 'c k': 429,
 'real ly</w>': 430,
 'p ri': 431,
 'wor k</w>': 432,
 'na me</w>': 433,
 'ni ce</w>': 434,
 'ma tter</w>': 435,
 'roo m</w>': 436,
 'c he': 437,
 'every thing</w>': 438,
 'mi ght</w>': 439,
 'o k</w>': 440,
 'n y</w>': 441,
 'ha ven</w>': 442,
 'sti ll</w>': 443,
 'j u': 444,
 'c har': 445,
 'su p': 446,
 ': </w>': 447,
 'enou gh</w>': 448,
 'gir l</w>': 449,
 'f t</w>': 450,
 'v ed</w>': 451,
 'x </w>': 452,
 'c lo': 453,
 'c tor</w>': 454,
 'do ing</w>': 455,
 'do es</w>': 456,
 're me': 457,
 'he ad</w>': 458,
 'than ks</w>': 459,
 'ca me</w>': 460,
 'he y</w>': 461,
 'ne ed</w>': 462,
 'sta y</w>': 463,
 'rou gh</w>': 464,
 't ru': 465,
 'se e': 466,
 't u': 467,
 'sto p</w>': 468,
 'mo st</w>': 469,
 'p y</w>': 470,
 'bo y</w>': 471,
 't le': 472,
 'ra id</w>': 473,
 'b a': 474,
 'reme mber</w>': 475,
 'ye ars</w>': 476,
 'as k</w>': 477,
 'm y': 478,
 'he ar</w>': 479,
 'th rough</w>': 480,
 'your self</w>': 481,
 'af raid</w>': 482,
 't ly</w>': 483,
 'do e': 484,
 'doe sn</w>': 485,
 's c': 486,
 'under stand</w>': 487,
 'v er': 488,
 'the ir</w>': 489,
 'k a': 490,
 'bi g</w>': 491,
 'gu e': 492,
 'si de</w>': 493,
 'beli eve</w>': 494,
 'g reat</w>': 495,
 'le ft</w>': 496,
 'fe el</w>': 497,
 'r ying</w>': 498,
 's hall</w>': 499,
 '0 0</w>': 500,
 'i l</w>': 501,
 'kin d</w>': 502,
 'p t</w>': 503,
 'cou ldn</w>': 504,
 'ri ed</w>': 505,
 'p s</w>': 506,
 'sup po': 507,
 'g ra': 508,
 'gen tle': 509,
 'lo t</w>': 510,
 'wo man</w>': 511,
 's hi': 512,
 'ow n</w>': 513,
 'th ree</w>': 514,
 'frien d</w>': 515,
 'ron g</w>': 516,
 'c h': 517,
 'l ly</w>': 518,
 'f ran': 519,
 'd rin': 520,
 'i de': 521,
 'fo o': 522,
 'dar ling</w>': 523,
 'li sten</w>': 524,
 'do ctor</w>': 525,
 'wan ted</w>': 526,
 'qu e': 527,
 'my self</w>': 528,
 'bu sine': 529,
 'l li': 530,
 'on ce</w>': 531,
 'minu te</w>': 532,
 'he ard</w>': 533,
 'el se</w>': 534,
 'wa i': 535,
 'po li': 536,
 'wor ld</w>': 537,
 'we e': 538,
 'busine ss</w>': 539,
 'mor row</w>': 540,
 'o d': 541,
 'su ch</w>': 542,
 'be au': 543,
 'to morrow</w>': 544,
 'pre tty</w>': 545,
 'd r</w>': 546,
 'le y</w>': 547,
 't rou': 548,
 'ho pe</w>': 549,
 'b rea': 550,
 'wi fe</w>': 551,
 'a p': 552,
 'qui te</w>': 553,
 'hap py</w>': 554,
 'youn g</w>': 555,
 'whi le</w>': 556,
 'ge tting</w>': 557,
 'de ad</w>': 558,
 'b ring</w>': 559,
 'k new</w>': 560,
 'sa me</w>': 561,
 'sa w</w>': 562,
 's le': 563,
 'wi thout</w>': 564,
 'l t</w>': 565,
 'gue ss</w>': 566,
 'wi sh</w>': 567,
 'li ve</w>': 568,
 'be ing</w>': 569,
 'f f</w>': 570,
 's pi': 571,
 'ide a</w>': 572,
 'ti ons</w>': 573,
 'd re': 574,
 'loo king</w>': 575,
 'w rong</w>': 576,
 'suppo se</w>': 577,
 'hap pened</w>': 578,
 'bo ys</w>': 579,
 'di e</w>': 580,
 'a k</w>': 581,
 'l led</w>': 582,
 'of fi': 583,
 'b ye</w>': 584,
 'an s</w>': 585,
 'jo h': 586,
 'tur n</w>': 587,
 're st</w>': 588,
 'so on</w>': 589,
 'wen t</w>': 590,
 'di f': 591,
 'foun d</w>': 592,
 'drin k</w>': 593,
 'ar t</w>': 594,
 'fo l': 595,
 'c y</w>': 596,
 'gu y</w>': 597,
 'da ys</w>': 598,
 'trou ble</w>': 599,
 'sen t</w>': 600,
 'nex t</w>': 601,
 'ne ss</w>': 602,
 'g re': 603,
 'be st</w>': 604,
 'u h</w>': 605,
 'un til</w>': 606,
 'gentle men</w>': 607,
 'fe w</w>': 608,
 'sin ce</w>': 609,
 'mar ried</w>': 610,
 'g lad</w>': 611,
 'jo b</w>': 612,
 'w ri': 613,
 'ka y</w>': 614,
 'who le</w>': 615,
 'go od': 616,
 't rying</w>': 617,
 'tal king</w>': 618,
 'e ar': 619,
 'ta in': 620,
 'v e': 621,
 'wai ting</w>': 622,
 'd ri': 623,
 'z e</w>': 624,
 'le ss</w>': 625,
 'for get</w>': 626,
 'per haps</w>': 627,
 'la te</w>': 628,
 'n u': 629,
 'beau ti': 630,
 'cap tain</w>': 631,
 'sa ys</w>': 632,
 's y</w>': 633,
 'to ge': 634,
 'ki ll</w>': 635,
 'toge ther</w>': 636,
 'wor d</w>': 637,
 'b ri': 638,
 'v o': 639,
 'li e</w>': 640,
 'whi ch</w>': 641,
 'o kay</w>': 642,
 'pla y</w>': 643,
 'c ra': 644,
 'me et</w>': 645,
 'd ge</w>': 646,
 'o pen</w>': 647,
 'si g': 648,
 'hu s': 649,
 'u sed</w>': 650,
 'a th</w>': 651,
 'sen d</w>': 652,
 'wan ts</w>': 653,
 'a go</w>': 654,
 'some body</w>': 655,
 'poli ce</w>': 656,
 'beauti ful</w>': 657,
 'pa y</w>': 658,
 'ex pe': 659,
 'e i': 660,
 'to ok</w>': 661,
 'wor ry</w>': 662,
 'ki lled</w>': 663,
 'wa ter</w>': 664,
 'b ro': 665,
 'do or</w>': 666,
 'hus band</w>': 667,
 'shi p</w>': 668,
 'in t</w>': 669,
 'z y</w>': 670,
 'chan ce</w>': 671,
 'm p': 672,
 'no body</w>': 673,
 '5 </w>': 674,
 'po or</w>': 675,
 'an t</w>': 676,
 'hur ry</w>': 677,
 'ti ve</w>': 678,
 'frien ds</w>': 679,
 's sed</w>': 680,
 'dif feren': 681,
 'k now': 682,
 'i l': 683,
 'la ter</w>': 684,
 'spe ak</w>': 685,
 'f re': 686,
 'j a': 687,
 'sle ep</w>': 688,
 'bo th</w>': 689,
 'won der': 690,
 'han ds</w>': 691,
 's po': 692,
 'st re': 693,
 'some one</w>': 694,
 'fi ve</w>': 695,
 'ou t': 696,
 'ck y</w>': 697,
 'ex cuse</w>': 698,
 'a ge</w>': 699,
 'coun try</w>': 700,
 'every body</w>': 701,
 'e asy</w>': 702,
 'wonder ful</w>': 703,
 'de ath</w>': 704,
 'o t</w>': 705,
 'e m</w>': 706,
 'pro mi': 707,
 'gh ter</w>': 708,
 'mo ment</w>': 709,
 'c tion</w>': 710,
 'aga in': 711,
 'li ght</w>': 712,
 'again st</w>': 713,
 'ne w': 714,
 'ho l': 715,
 'loo ks</w>': 716,
 'y a</w>': 717,
 'hal f</w>': 718,
 'thin king</w>': 719,
 'ga ve</w>': 720,
 'an s': 721,
 'know s</w>': 722,
 'ra ther</w>': 723,
 'wa tch</w>': 724,
 'e yes</w>': 725,
 'ge or': 726,
 'any body</w>': 727,
 'lo st</w>': 728,
 'hur t</w>': 729,
 'ou ght</w>': 730,
 'cer tain': 731,
 's hed</w>': 732,
 'he a': 733,
 'fi ght</w>': 734,
 'ro ss</w>': 735,
 'si e': 736,
 'any one</w>': 737,
 'certain ly</w>': 738,
 'ch ri': 739,
 'a w': 740,
 'c le</w>': 741,
 'p ped</w>': 742,
 'good bye</w>': 743,
 'd ro': 744,
 'e ach</w>': 745,
 'o b': 746,
 'ter ri': 747,
 'e f</w>': 748,
 'hap pen</w>': 749,
 'en d</w>': 750,
 'tru e</w>': 751,
 'mar ry</w>': 752,
 'p hone</w>': 753,
 'c re': 754,
 'in tere': 755,
 'chan ge</w>': 756,
 'o l</w>': 757,
 'e at</w>': 758,
 'd ly</w>': 759,
 'd le</w>': 760,
 "' em</w>": 761,
 'any way</w>': 762,
 'a head</w>': 763,
 'si ster</w>': 764,
 'a meri': 765,
 'ma kes</w>': 766,
 'pi c': 767,
 'see ms</w>': 768,
 'ta king</w>': 769,
 's hu': 770,
 'offi ce</w>': 771,
 'minu tes</w>': 772,
 '2 </w>': 773,
 'b ra': 774,
 'en g': 775,
 '1 </w>': 776,
 'din ner</w>': 777,
 'v a': 778,
 'wo men</w>': 779,
 'fun ny</w>': 780,
 'i rs</w>': 781,
 'sie ur</w>': 782,
 'th y</w>': 783,
 'mon sieur</w>': 784,
 'go es</w>': 785,
 'ssi on</w>': 786,
 'al ready</w>': 787,
 'cra zy</w>': 788,
 'as ked</w>': 789,
 'geor ge</w>': 790,
 'ha ving</w>': 791,
 'impor tant</w>': 792,
 'qui et</w>': 793,
 'ne e': 794,
 'fel low</w>': 795,
 'go tta</w>': 796,
 'jo e</w>': 797,
 'lu ck</w>': 798,
 'gh ts</w>': 799,
 'ci ty</w>': 800,
 'z </w>': 801,
 'mo ve</w>': 802,
 'p len': 803,
 'i ce</w>': 804,
 't ment</w>': 805,
 '1 0</w>': 806,
 'chil dren</w>': 807,
 'af ter': 808,
 'bu y</w>': 809,
 'cu t</w>': 810,
 'wal k</w>': 811,
 'sen se</w>': 812,
 'di s': 813,
 'cen t</w>': 814,
 'sor t</w>': 815,
 'dau ghter</w>': 816,
 'ge ts</w>': 817,
 'ans wer</w>': 818,
 'wee k</w>': 819,
 'bo at</w>': 820,
 'no on</w>': 821,
 'th s</w>': 822,
 'joh n': 823,
 's y': 824,
 'me ans</w>': 825,
 'gran d': 826,
 'te st</w>': 827,
 'c ted</w>': 828,
 'ce pt</w>': 829,
 'ti red</w>': 830,
 'ha te</w>': 831,
 'lor d</w>': 832,
 'lea ving</w>': 833,
 'co l': 834,
 'dan ce</w>': 835,
 'ke y</w>': 836,
 'al most</w>': 837,
 'u p': 838,
 'me di': 839,
 'hor se</w>': 840,
 's sor</w>': 841,
 'en ce</w>': 842,
 'fa mily</w>': 843,
 'i ts</w>': 844,
 'ssi ble</w>': 845,
 'c lu': 846,
 'fu lly</w>': 847,
 'shou ldn</w>': 848,
 'e d': 849,
 'probab ly</w>': 850,
 'shu t</w>': 851,
 'bi r': 852,
 'him self</w>': 853,
 'be t': 854,
 'ex ac': 855,
 's h': 856,
 'le tter</w>': 857,
 'm my</w>': 858,
 'profe ssor</w>': 859,
 'wan na</w>': 860,
 'ma king</w>': 861,
 'exac tly</w>': 862,
 'ei ther</w>': 863,
 'c la': 864,
 '0 00</w>': 865,
 'thou gh</w>': 866,
 'clo se</w>': 867,
 'mada me</w>': 868,
 'ho tel</w>': 869,
 'fu ll</w>': 870,
 'dre ss</w>': 871,
 'par ty</w>': 872,
 'lo vely</w>': 873,
 'coun t</w>': 874,
 'wa t': 875,
 'un cle</w>': 876,
 'to m</w>': 877,
 'do g</w>': 878,
 'in di': 879,
 'spe ci': 880,
 'n s</w>': 881,
 'after noon</w>': 882,
 'tru th</w>': 883,
 'b la': 884,
 'si x</w>': 885,
 'nu mber</w>': 886,
 'hone y</w>': 887,
 'mur der</w>': 888,
 'pi e': 889,
 'y or': 890,
 'g le</w>': 891,
 'k y</w>': 892,
 'or der</w>': 893,
 'par don</w>': 894,
 'b li': 895,
 'sta irs</w>': 896,
 'roun d</w>': 897,
 'sa ying</w>': 898,
 'sa ve</w>': 899,
 'wri te</w>': 900,
 'l y': 901,
 'sur pri': 902,
 'so l': 903,
 'se con': 904,
 'yor k</w>': 905,
 'per fe': 906,
 'expe ct</w>': 907,
 'ta ken</w>': 908,
 'al right</w>': 909,
 'mon ths</w>': 910,
 'bo ok</w>': 911,
 'john ny</w>': 912,
 'e h</w>': 913,
 'bo o': 914,
 'bet ween</w>': 915,
 'por t</w>': 916,
 'bo ss</w>': 917,
 'differen t</w>': 918,
 'j im</w>': 919,
 'g ry</w>': 920,
 'm m</w>': 921,
 'wor th</w>': 922,
 'b lood</w>': 923,
 'qui ck</w>': 924,
 'c lear</w>': 925,
 'si ck</w>': 926,
 'mu si': 927,
 'hin d</w>': 928,
 'ro ad</w>': 929,
 'wor king</w>': 930,
 'di ed</w>': 931,
 'ni e</w>': 932,
 'ti c</w>': 933,
 'fran k</w>': 934,
 'i se</w>': 935,
 'out side</w>': 936,
 'b ly</w>': 937,
 'ti es</w>': 938,
 'be hind</w>': 939,
 'plen ty</w>': 940,
 'po int</w>': 941,
 'vi si': 942,
 'any more</w>': 943,
 'ca tch</w>': 944,
 'hi gh</w>': 945,
 'li ving</w>': 946,
 'char les</w>': 947,
 '3 </w>': 948,
 'some times</w>': 949,
 'en t</w>': 950,
 'o thers</w>': 951,
 'sho ot</w>': 952,
 'gir ls</w>': 953,
 'i r': 954,
 'po si': 955,
 'for give</w>': 956,
 'fron t</w>': 957,
 'new s</w>': 958,
 'stre et</w>': 959,
 '4 </w>': 960,
 'care ful</w>': 961,
 'al so</w>': 962,
 'clo thes</w>': 963,
 'lo se</w>': 964,
 'li sh</w>': 965,
 'gentle man</w>': 966,
 'e g': 967,
 'm c': 968,
 'hen ry</w>': 969,
 'que stion</w>': 970,
 '8 </w>': 971,
 's weet</w>': 972,
 'de al</w>': 973,
 'fa ir</w>': 974,
 'lon ger</w>': 975,
 'run ning</w>': 976,
 'pre sent</w>': 977,
 'star ted</w>': 978,
 'stran ge</w>': 979,
 'i s': 980,
 'secon d</w>': 981,
 'do c</w>': 982,
 'men ts</w>': 983,
 'ni ck</w>': 984,
 'whi te</w>': 985,
 'sel ves</w>': 986,
 'scho ol</w>': 987,
 'do l': 988,
 'g ge': 989,
 'stu ff</w>': 990,
 'pic ture</w>': 991,
 'go ver': 992,
 'stra i': 993,
 'o ver': 994,
 'gu ys</w>': 995,
 'e u': 996,
 'v y</w>': 997,
 'wor ds</w>': 998,
 's mi': 999,
 ...}

In [333]:
def encode_word(word, vocab):
    word_str = ' '.join(word)
    sub_key = lambda x: re.sub('\s+', '', x)
    for key in vocab.keys():
        pat = ' ' + key + ' '
        if pat in word_str:
            print(key)
            print(word_str, '\n')
            word_str = word_str.replace(key, sub_key(key))
            # print(key)
            # print(word_str, '\n')
    return word_str

In [336]:
encode_word(char_factor(' running '), tokenizer_eng.vocab)

n
  r u n n i n g   </w>

g
  r u n n i n g   </w>

r
  r u n n i n g   </w>

u
  r u n n i n g   </w>

i
  r u n n i n g   </w>

i n
  r u n n i n g   </w>

u n
  r u n n in g   </w>

'  r un n in g   </w>'

In [269]:
test_snt = "Yesterday I visited zoo with my family, it was super fun!"
test_snt_split = tokenize_eng(test_snt)
print(test_snt_split)

['yesterday', 'i', 'visited', 'zoo', 'with', 'my', 'family', ',', 'it', 'was', 'super', 'fun', '!']

In [270]:
[[x for x in word] + ['</w>'] for word in test_snt_split]

[['y', 'e', 's', 't', 'e', 'r', 'd', 'a', 'y', '</w>'],
 ['i', '</w>'],
 ['v', 'i', 's', 'i', 't', 'e', 'd', '</w>'],
 ['z', 'o', 'o', '</w>'],
 ['w', 'i', 't', 'h', '</w>'],
 ['m', 'y', '</w>'],
 ['f', 'a', 'm', 'i', 'l', 'y', '</w>'],
 [',', '</w>'],
 ['i', 't', '</w>'],
 ['w', 'a', 's', '</w>'],
 ['s', 'u', 'p', 'e', 'r', '</w>'],
 ['f', 'u', 'n', '</w>'],
 ['!', '</w>']]

In [135]:
def connect_pairs(vocab_chars, pair):
    vocab_proc = vocab_chars.copy()
    pair_con = re.sub('\s+', '', pair)
    for i, (toks, _) in enumerate(vocab_proc):
        toks = " ".join(toks).replace(pair, pair_con).split()
        vocab_proc[i][0] = toks
    return vocab_proc

In [221]:
def most_common_pair(vocab_chars):
    pair_counts = Counter()
    for toks, freq in vocab_chars:
        for pair in map(' '.join, zip(toks, toks[1:])):
            pair_counts[pair] += freq
    return pair_counts.most_common(1)[0][0]

In [226]:
vocab_chars_eng

[[['.', '</w>'], 435802],
 [[',', '</w>'], 177291],
 [['y', 'o', 'u', '</w>'], 134548],
 [['i', '</w>'], 122767],
 [['t', 'h', 'e', '</w>'], 89859],
 [['?', '</w>'], 84640],
 [['t', 'o', '</w>'], 73192],
 [['a', '</w>'], 61661],
 [["'", 's', '</w>'], 57045],
 [['i', 't', '</w>'], 55074],
 [["'", 't', '</w>'], 50411],
 [['t', 'h', 'a', 't', '</w>'], 43020],
 [['a', 'n', 'd', '</w>'], 41124],
 [['o', 'f', '</w>'], 39514],
 [['i', 'n', '</w>'], 32142],
 [['!', '</w>'], 30794],
 [['m', 'e', '</w>'], 29977],
 [['w', 'h', 'a', 't', '</w>'], 26868],
 [['i', 's', '</w>'], 26378],
 [['h', 'e', '</w>'], 26149],
 [['f', 'o', 'r', '</w>'], 23935],
 [['w', 'e', '</w>'], 23370],
 [['t', 'h', 'i', 's', '</w>'], 20366],
 [['y', 'o', 'u', 'r', '</w>'], 20158],
 [['b', 'e', '</w>'], 20137],
 [['m', 'y', '</w>'], 20105],
 [["'", 'l', 'l', '</w>'], 20011],
 [['h', 'a', 'v', 'e', '</w>'], 19830],
 [['d', 'o', 'n', '</w>'], 18888],
 [['d', 'o', '</w>'], 18663],
 [['o', 'n', '</w>'], 18052],
 [['n', 'o', '</w>'], 17694],
 [["'", 'm', '</w>'], 16935],
 [['a', 'l', 'l', '</w>'], 16776],
 [['b', 'u', 't', '</w>'], 16067],
 [['w', 'a', 's', '</w>'], 15781],
 [["'", 'r', 'e', '</w>'], 15483],
 [['w', 'i', 't', 'h', '</w>'], 15435],
 [['c', 'a', 'n', '</w>'], 15365],
 [['h', 'e', 'r', 'e', '</w>'], 15059],
 [['n', 'o', 't', '</w>'], 14896],
 [['a', 'r', 'e', '</w>'], 14431],
 [['k', 'n', 'o', 'w', '</w>'], 14310],
 [['t', 'h', 'e', 'r', 'e', '</w>'], 14310],
 [['h', 'i', 'm', '</w>'], 14193],
 [['g', 'e', 't', '</w>'], 13469],
 [['i', 'f', '</w>'], 12400],
 [['w', 'e', 'l', 'l', '</w>'], 12155],
 [['t', 'h', 'e', 'y', '</w>'], 11807],
 [['n', 'o', 'w', '</w>'], 11736],
 [["'", 'v', 'e', '</w>'], 11579],
 [['l', 'i', 'k', 'e', '</w>'], 11372],
 [['y', 'e', 's', '</w>'], 10842],
 [['o', 'u', 't', '</w>'], 10839],
 [['s', 'h', 'e', '</w>'], 10741],
 [['c', 'o', 'm', 'e', '</w>'], 10653],
 [['g', 'o', '</w>'], 10570],
 [['r', 'i', 'g', 'h', 't', '</w>'], 10414],
 [['s', 'o', '</w>'], 10352],
 [['a', 'b', 'o', 'u', 't', '</w>'], 10349],
 [['a', 't', '</w>'], 10100],
 [['u', 'p', '</w>'], 9851],
 [['o', 'h', '</w>'], 9750],
 [['w', 'i', 'l', 'l', '</w>'], 9685],
 [['j', 'u', 's', 't', '</w>'], 9650],
 [['s', 'e', 'e', '</w>'], 9619],
 [['g', 'o', 'o', 'd', '</w>'], 9404],
 [['h', 'e', 'r', '</w>'], 9170],
 [['a', 's', '</w>'], 9044],
 [['"', '</w>'], 8870],
 [['o', 'n', 'e', '</w>'], 8831],
 [['g', 'o', 't', '</w>'], 8827],
 [['h', 'o', 'w', '</w>'], 8698],
 [["'", 'd', '</w>'], 7878],
 [['-', '</w>'], 7821],
 [['w', 'a', 'n', 't', '</w>'], 7783],
 [['t', 'h', 'i', 'n', 'k', '</w>'], 7743],
 [['w', 'h', 'y', '</w>'], 7726],
 [['h', 'i', 's', '</w>'], 7396],
 [['m', 'r', '</w>'], 7390],
 [['g', 'o', 'i', 'n', 'g', '</w>'], 7023],
 [['d', 'i', 'd', '</w>'], 6784],
 [['t', 'a', 'k', 'e', '</w>'], 6657],
 [['t', 'h', 'e', 'm', '</w>'], 6612],
 [['b', 'e', 'e', 'n', '</w>'], 6579],
 [['w', 'h', 'e', 'n', '</w>'], 6444],
 [['f', 'r', 'o', 'm', '</w>'], 6437],
 [['l', 'e', 't', '</w>'], 6379],
 [['t', 'e', 'l', 'l', '</w>'], 6330],
 [['w', 'h', 'o', '</w>'], 6283],
 [['w', 'h', 'e', 'r', 'e', '</w>'], 6175],
 [['s', 'a', 'y', '</w>'], 6142],
 [['v', 'e', 'r', 'y', '</w>'], 5833],
 [['b', 'a', 'c', 'k', '</w>'], 5736],
 [['m', 'a', 'n', '</w>'], 5539],
 [['t', 'i', 'm', 'e', '</w>'], 5538],
 [['l', 'o', 'o', 'k', '</w>'], 5465],
 [['a', 'n', '</w>'], 5437],
 [['h', 'a', 'd', '</w>'], 5395],
 [['t', 'o', 'o', '</w>'], 5297],
 [['u', 's', '</w>'], 5228],
 [['w', 'o', 'u', 'l', 'd', '</w>'], 5165],
 [['n', 'e', 'v', 'e', 'r', '</w>'], 5037],
 [['d', 'i', 'd', 'n', '</w>'], 4959],
 [['w', 'e', 'r', 'e', '</w>'], 4912],
 [['s', 'i', 'r', '</w>'], 4907],
 [['l', 'i', 't', 't', 'l', 'e', '</w>'], 4764],
 [['w', 'a', 'y', '</w>'], 4572],
 [['o', 'r', '</w>'], 4571],
 [['t', 'h', 'e', 'n', '</w>'], 4556],
 [['s', 'o', 'm', 'e', '</w>'], 4544],
 [['d', 'o', 'w', 'n', '</w>'], 4510],
 [['m', 'u', 's', 't', '</w>'], 4353],
 [['a', 'n', 'y', '</w>'], 4343],
 [['m', 'a', 'k', 'e', '</w>'], 4312],
 [['o', 'n', 'l', 'y', '</w>'], 4213],
 [['c', 'o', 'u', 'l', 'd', '</w>'], 4125],
 [['m', 'o', 'r', 'e', '</w>'], 4078],
 [['b', 'y', '</w>'], 4064],
 [['h', 'a', 's', '</w>'], 4035],
 [['s', 'o', 'm', 'e', 't', 'h', 'i', 'n', 'g', '</w>'], 4018],
 [['t', 'h', 'a', 'n', 'k', '</w>'], 3991],
 [['o', 'u', 'r', '</w>'], 3987],
 [['o', 'v', 'e', 'r', '</w>'], 3933],
 [['g', 'i', 'v', 'e', '</w>'], 3923],
 [['w', 'o', 'n', '</w>'], 3826],
 [['m', 'u', 'c', 'h', '</w>'], 3806],
 [['s', 'u', 'r', 'e', '</w>'], 3682],
 [['p', 'l', 'e', 'a', 's', 'e', '</w>'], 3634],
 [['n', 'i', 'g', 'h', 't', '</w>'], 3541],
 [['b', 'e', 't', 't', 'e', 'r', '</w>'], 3447],
 [['y', 'e', 'a', 'h', '</w>'], 3404],
 [['n', 'o', 't', 'h', 'i', 'n', 'g', '</w>'], 3379],
 [['a', 'n', 'y', 't', 'h', 'i', 'n', 'g', '</w>'], 3219],
 [['a', 'w', 'a', 'y', '</w>'], 3136],
 [['t', 'w', 'o', '</w>'], 3114],
 [['m', 'e', 'a', 'n', '</w>'], 3060],
 [['o', 'l', 'd', '</w>'], 3053],
 [['o', 'f', 'f', '</w>'], 3035],
 [['l', 'o', 'v', 'e', '</w>'], 3028],
 [['h', 'e', 'l', 'l', 'o', '</w>'], 3018],
 [['a', 'm', '</w>'], 2934],
 [['m', 'i', 's', 's', '</w>'], 2929],
 [['b', 'e', 'f', 'o', 'r', 'e', '</w>'], 2916],
 [['s', 'a', 'i', 'd', '</w>'], 2882],
 [['a', 'g', 'a', 'i', 'n', '</w>'], 2882],
 [['f', 'i', 'n', 'd', '</w>'], 2839],
 [['s', 'h', 'o', 'u', 'l', 'd', '</w>'], 2800],
 [['l', 'o', 'n', 'g', '</w>'], 2767],
 [['i', 's', 'n', '</w>'], 2738],
 [['t', 'h', 'i', 'n', 'g', '</w>'], 2720],
 [['s', 'o', 'r', 'r', 'y', '</w>'], 2676],
 [['h', 'e', 'l', 'p', '</w>'], 2667],
 [['a', 'f', 't', 'e', 'r', '</w>'], 2623],
 [['t', 'h', 'o', 'u', 'g', 'h', 't', '</w>'], 2600],
 [['p', 'u', 't', '</w>'], 2573],
 [['h', 'o', 'm', 'e', '</w>'], 2550],
 [['t', 'h', 'a', 'n', '</w>'], 2528],
 [['e', 'v', 'e', 'r', '</w>'], 2525],
 [['f', 'i', 'r', 's', 't', '</w>'], 2521],
 [['p', 'e', 'o', 'p', 'l', 'e', '</w>'], 2514],
 [['f', 'a', 't', 'h', 'e', 'r', '</w>'], 2502],
 [['t', 'h', 'i', 'n', 'g', 's', '</w>'], 2447],
 [['a', 'l', 'w', 'a', 'y', 's', '</w>'], 2424],
 [['t', 'h', 'o', 's', 'e', '</w>'], 2422],
 [['m', 'a', 'y', 'b', 'e', '</w>'], 2417],
 [['d', 'a', 'y', '</w>'], 2410],
 [['k', 'e', 'e', 'p', '</w>'], 2393],
 [['t', 'a', 'l', 'k', '</w>'], 2389],
 [['i', 'n', 't', 'o', '</w>'], 2380],
 [['g', 'o', 'n', 'n', 'a', '</w>'], 2372],
 [['m', 'r', 's', '</w>'], 2366],
 [['t', 'o', 'l', 'd', '</w>'], 2360],
 [['w', 'a', 'i', 't', '</w>'], 2348],
 [['m', 'i', 'n', 'd', '</w>'], 2339],
 [['a', 'i', 'n', '</w>'], 2336],
 [['b', 'e', 'c', 'a', 'u', 's', 'e', '</w>'], 2327],
 [['l', 'a', 's', 't', '</w>'], 2314],
 [['m', 'a', 'y', '</w>'], 2299],
 [['l', 'e', 'a', 'v', 'e', '</w>'], 2297],
 [['t', 'h', 'e', 's', 'e', '</w>'], 2289],
 [['o', 't', 'h', 'e', 'r', '</w>'], 2277],
 [['d', 'e', 'a', 'r', '</w>'], 2255],
 [['a', 'r', 'o', 'u', 'n', 'd', '</w>'], 2245],
 [['l', 'i', 'f', 'e', '</w>'], 2245],
 [['e', 'v', 'e', 'n', '</w>'], 2242],
 [['c', 'o', 'u', 'r', 's', 'e', '</w>'], 2213],
 [['m', 'o', 'n', 'e', 'y', '</w>'], 2207],
 [['w', 'o', 'u', 'l', 'd', 'n', '</w>'], 2160],
 [['n', 'e', 'w', '</w>'], 2154],
 [['m', 'o', 'r', 'n', 'i', 'n', 'g', '</w>'], 2147],
 [['r', 'e', 'a', 'l', 'l', 'y', '</w>'], 2098],
 [['n', 'a', 'm', 'e', '</w>'], 2067],
 [['n', 'i', 'c', 'e', '</w>'], 2061],
 [['m', 'a', 't', 't', 'e', 'r', '</w>'], 2051],
 [['e', 'v', 'e', 'r', 'y', 't', 'h', 'i', 'n', 'g', '</w>'], 2034],
 [['m', 'i', 'g', 'h', 't', '</w>'], 2030],
 [['w', 'o', 'r', 'k', '</w>'], 2029],
 [['h', 'a', 'v', 'e', 'n', '</w>'], 2015],
 [['s', 't', 'i', 'l', 'l', '</w>'], 2010],
 [[':', '</w>'], 1991],
 [['e', 'n', 'o', 'u', 'g', 'h', '</w>'], 1989],
 [['p', 'l', 'a', 'c', 'e', '</w>'], 1966],
 [['g', 'i', 'r', 'l', '</w>'], 1956],
 [['m', 'e', 'n', '</w>'], 1953],
 [['d', 'o', 'i', 'n', 'g', '</w>'], 1934],
 [['d', 'o', 'e', 's', '</w>'], 1933],
 [['c', 'a', 'l', 'l', '</w>'], 1911],
 [['t', 'h', 'a', 'n', 'k', 's', '</w>'], 1896],
 [['h', 'e', 'y', '</w>'], 1882],
 [['n', 'e', 'e', 'd', '</w>'], 1876],
 [['s', 't', 'a', 'y', '</w>'], 1861],
 [['s', 't', 'o', 'p', '</w>'], 1823],
 [['h', 'o', 'u', 's', 'e', '</w>'], 1787],
 [['c', 'a', 'm', 'e', '</w>'], 1777],
 [['r', 'e', 'm', 'e', 'm', 'b', 'e', 'r', '</w>'], 1771],
 [['y', 'e', 'a', 'r', 's', '</w>'], 1757],
 [['a', 's', 'k', '</w>'], 1757],
 [['a', 'n', 'o', 't', 'h', 'e', 'r', '</w>'], 1757],
 [['r', 'o', 'o', 'm', '</w>'], 1751],
 [['h', 'e', 'a', 'r', '</w>'], 1737],
 [['y', 'o', 'u', 'r', 's', 'e', 'l', 'f', '</w>'], 1734],
 [['t', 'h', 'r', 'o', 'u', 'g', 'h', '</w>'], 1734],
 [['b', 'o', 'y', '</w>'], 1733],
 [['a', 'f', 'r', 'a', 'i', 'd', '</w>'], 1721],
 [['d', 'o', 'e', 's', 'n', '</w>'], 1714],
 [['u', 'n', 'd', 'e', 'r', 's', 't', 'a', 'n', 'd', '</w>'], 1690],
 [['m', 'a', 'd', 'e', '</w>'], 1681],
 [['d', 'o', 'n', 'e', '</w>'], 1673],
 [['t', 'h', 'e', 'i', 'r', '</w>'], 1670],
 [['b', 'i', 'g', '</w>'], 1668],
 [['c', 'o', 'm', 'i', 'n', 'g', '</w>'], 1659],
 [['b', 'e', 'l', 'i', 'e', 'v', 'e', '</w>'], 1656],
 [['g', 'r', 'e', 'a', 't', '</w>'], 1653],
 [['m', 'o', 't', 'h', 'e', 'r', '</w>'], 1653],
 [['l', 'e', 'f', 't', '</w>'], 1651],
 [['f', 'e', 'e', 'l', '</w>'], 1647],
 [['t', 'o', 'n', 'i', 'g', 'h', 't', '</w>'], 1646],
 [['e', 'v', 'e', 'r', 'y', '</w>'], 1620],
 [['c', 'o', 'u', 'l', 'd', 'n', '</w>'], 1609],
 [['s', 'h', 'a', 'l', 'l', '</w>'], 1607],
 [['b', 'a', 'd', '</w>'], 1605],
 [['k', 'i', 'n', 'd', '</w>'], 1582],
 [['o', 'w', 'n', '</w>'], 1565],
 [['t', 'h', 'r', 'e', 'e', '</w>'], 1553],
 [['w', 'o', 'm', 'a', 'n', '</w>'], 1527],
 [['c', 'a', 'r', 'e', '</w>'], 1511],
 [['d', 'a', 'r', 'l', 'i', 'n', 'g', '</w>'], 1498],
 [['l', 'i', 's', 't', 'e', 'n', '</w>'], 1496],
 [['d', 'o', 'c', 't', 'o', 'r', '</w>'], 1493],
 [['w', 'a', 'n', 't', 'e', 'd', '</w>'], 1492],
 [['m', 'y', 's', 'e', 'l', 'f', '</w>'], 1484],
 [['f', 'r', 'i', 'e', 'n', 'd', '</w>'], 1474],
 [['l', 'o', 't', '</w>'], 1456],
 [['s', 'e', 'e', 'n', '</w>'], 1455],
 [['o', 'n', 'c', 'e', '</w>'], 1446],
 [['m', 'i', 'n', 'u', 't', 'e', '</w>'], 1438],
 [['e', 'l', 's', 'e', '</w>'], 1430],
 [['w', 'o', 'r', 'l', 'd', '</w>'], 1412],
 [['b', 'u', 's', 'i', 'n', 'e', 's', 's', '</w>'], 1411],
 [['h', 'e', 'a', 'r', 'd', '</w>'], 1410],
 [['s', 'u', 'c', 'h', '</w>'], 1395],
 [['f', 'i', 'n', 'e', '</w>'], 1394],
 [['t', 'o', 'm', 'o', 'r', 'r', 'o', 'w', '</w>'], 1389],
 [['p', 'r', 'e', 't', 't', 'y', '</w>'], 1388],
 [['d', 'r', '</w>'], 1385],
 [['s', 'i', 't', '</w>'], 1383],
 [['s', 'h', 'o', 'w', '</w>'], 1372],
 [['l', 'a', 'd', 'y', '</w>'], 1363],
 [['w', 'i', 'f', 'e', '</w>'], 1361],
 [['t', 'r', 'y', '</w>'], 1354],
 [['a', 'l', 'o', 'n', 'e', '</w>'], 1343],
 [['q', 'u', 'i', 't', 'e', '</w>'], 1341],
 [['h', 'o', 'p', 'e', '</w>'], 1335],
 [['y', 'o', 'u', 'n', 'g', '</w>'], 1328],
 [['b', 'r', 'i', 'n', 'g', '</w>'], 1313],
 [['d', 'e', 'a', 'd', '</w>'], 1312],
 [['w', 'a', 's', 'n', '</w>'], 1303],
 [['k', 'n', 'e', 'w', '</w>'], 1299],
 [['y', 'e', 't', '</w>'], 1295],
 [['w', 'i', 't', 'h', 'o', 'u', 't', '</w>'], 1287],
 [['g', 'u', 'e', 's', 's', '</w>'], 1284],
 [['s', 'a', 'm', 'e', '</w>'], 1282],
 [['b', 'e', 'i', 'n', 'g', '</w>'], 1270],
 [['g', 'e', 't', 't', 'i', 'n', 'g', '</w>'], 1264],
 [['i', 'd', 'e', 'a', '</w>'], 1260],
 [['l', 'i', 'v', 'e', '</w>'], 1252],
 [['l', 'o', 'o', 'k', 'i', 'n', 'g', '</w>'], 1236],
 [['w', 'r', 'o', 'n', 'g', '</w>'], 1236],
 [['s', 'u', 'p', 'p', 'o', 's', 'e', '</w>'], 1234],
 [['w', 'i', 's', 'h', '</w>'], 1231],
 [['h', 'a', 'p', 'p', 'e', 'n', 'e', 'd', '</w>'], 1229],
 [['w', 'h', 'i', 'l', 'e', '</w>'], 1227],
 [['h', 'a', 'p', 'p', 'y', '</w>'], 1224],
 [['s', 'a', 'w', '</w>'], 1218],
 [['b', 'o', 'y', 's', '</w>'], 1213],
 [['a', 'l', 'o', 'n', 'g', '</w>'], 1201],
 [['m', 'o', 's', 't', '</w>'], 1192],
 [['w', 'e', 'n', 't', '</w>'], 1188],
 [['s', 'o', 'o', 'n', '</w>'], 1187],
 [['d', 'r', 'i', 'n', 'k', '</w>'], 1172],
 [['f', 'o', 'u', 'n', 'd', '</w>'], 1165],
 [['g', 'u', 'y', '</w>'], 1156],
 [['t', 'r', 'o', 'u', 'b', 'l', 'e', '</w>'], 1153],
 [['n', 'e', 'x', 't', '</w>'], 1141],
 [['g', 'o', 'n', 'e', '</w>'], 1138],
 [['b', 'e', 's', 't', '</w>'], 1125],
 [['u', 'h', '</w>'], 1121],
 [['u', 'n', 't', 'i', 'l', '</w>'], 1115],
 [['g', 'e', 'n', 't', 'l', 'e', 'm', 'e', 'n', '</w>'], 1115],
 [['t', 'o', 'w', 'n', '</w>'], 1112],
 [['h', 'e', 'a', 'd', '</w>'], 1109],
 [['d', 'a', 'y', 's', '</w>'], 1107],
 [['s', 'i', 'n', 'c', 'e', '</w>'], 1104],
 [['f', 'e', 'w', '</w>'], 1104],
 [['g', 'l', 'a', 'd', '</w>'], 1102],
 [['t', 'o', 'd', 'a', 'y', '</w>'], 1097],
 [['j', 'o', 'b', '</w>'], 1096],
 [['m', 'a', 'n', 'y', '</w>'], 1095],
 [['m', 'a', 'r', 'r', 'i', 'e', 'd', '</w>'], 1092],
 [['r', 'e', 'a', 'd', 'y', '</w>'], 1087],
 [['w', 'h', 'o', 'l', 'e', '</w>'], 1083],
 [['t', 'r', 'y', 'i', 'n', 'g', '</w>'], 1077],
 [['h', 'o', 'l', 'd', '</w>'], 1076],
 [['t', 'a', 'l', 'k', 'i', 'n', 'g', '</w>'], 1070],
 [['r', 'u', 'n', '</w>'], 1068],
 [['f', 'o', 'r', 'g', 'e', 't', '</w>'], 1041],
 [['p', 'e', 'r', 'h', 'a', 'p', 's', '</w>'], 1038],
 [['h', 'a', 'n', 'd', '</w>'], 1033],
 [['w', 'a', 'i', 't', 'i', 'n', 'g', '</w>'], 1030],
 [['u', 's', 'e', '</w>'], 1029],
 [['s', 't', 'a', 'n', 'd', '</w>'], 1023],
 [['c', 'a', 'p', 't', 'a', 'i', 'n', '</w>'], 1019],
 [['s', 'a', 'y', 's', '</w>'], 1018],
 [['m', 'i', 'n', 'e', '</w>'], 1016],
 [['k', 'i', 'l', 'l', '</w>'], 996],
 [['w', 'h', 'i', 'c', 'h', '</w>'], 994],
 [['o', 'k', 'a', 'y', '</w>'], 993],
 [['m', 'e', 'e', 't', '</w>'], 992],
 [['e', 'v', 'e', 'n', 'i', 'n', 'g', '</w>'], 984],
 [['o', 'p', 'e', 'n', '</w>'], 981],
 [['u', 's', 'e', 'd', '</w>'], 973],
 [['t', 'o', 'g', 'e', 't', 'h', 'e', 'r', '</w>'], 968],
 [['h', 'u', 'h', '</w>'], 967],
 [['w', 'a', 'n', 't', 's', '</w>'], 963],
 [['p', 'l', 'a', 'y', '</w>'], 961],
 [['a', 'g', 'o', '</w>'], 957],
 [['s', 'o', 'm', 'e', 'b', 'o', 'd', 'y', '</w>'], 956],
 [['p', 'o', 'l', 'i', 'c', 'e', '</w>'], 954],
 [['b', 'e', 'a', 'u', 't', 'i', 'f', 'u', 'l', '</w>'], 952],
 [['c', 'a', 's', 'e', '</w>'], 944],
 [['s', 'e', 'n', 'd', '</w>'], 944],
 [['a', 'r', 'e', 'n', '</w>'], 943],
 [['w', 'o', 'r', 'r', 'y', '</w>'], 927],
 [['h', 'u', 's', 'b', 'a', 'n', 'd', '</w>'], 924],
 [['t', 'o', 'o', 'k', '</w>'], 924],
 [['k', 'i', 'l', 'l', 'e', 'd', '</w>'], 921],
 [['p', 'a', 'y', '</w>'], 918],
 [['c', 'h', 'a', 'n', 'c', 'e', '</w>'], 918],
 [['d', 'o', 'o', 'r', '</w>'], 913],
 [['n', 'o', 'b', 'o', 'd', 'y', '</w>'], 906],
 [['p', 'o', 'o', 'r', '</w>'], 903],
 [['h', 'u', 'r', 'r', 'y', '</w>'], 898],
 [['w', 'a', 't', 'e', 'r', '</w>'], 896],
 [['u', 'n', 'd', 'e', 'r', '</w>'], 892],
 [['s', 'o', 'n', '</w>'], 890],
 [['f', 'r', 'i', 'e', 'n', 'd', 's', '</w>'], 883],
 [['l', 'a', 't', 'e', 'r', '</w>'], 879],
 [['t', 'u', 'r', 'n', '</w>'], 875],
 [['w', 'o', 'r', 'd', '</w>'], 871],
 [['s', 'p', 'e', 'a', 'k', '</w>'], 869],
 [['s', 'l', 'e', 'e', 'p', '</w>'], 861],
 [['s', 't', 'a', 'r', 't', '</w>'], 860],
 [['b', 'o', 't', 'h', '</w>'], 858],
 [['l', 'a', 't', 'e', '</w>'], 855],
 [['s', 'o', 'm', 'e', 'o', 'n', 'e', '</w>'], 853],
 [['h', 'a', 'n', 'd', 's', '</w>'], 852],
 [['f', 'i', 'v', 'e', '</w>'], 852],
 [['y', 'o', 'u', 'r', 's', '</w>'], 844],
 [['f', 'a', 'c', 'e', '</w>'], 835],
 [['h', 'e', 'a', 'r', 't', '</w>'], 835],
 [['e', 'x', 'c', 'u', 's', 'e', '</w>'], 835],
 [['c', 'o', 'u', 'n', 't', 'r', 'y', '</w>'], 830],
 [['e', 'v', 'e', 'r', 'y', 'b', 'o', 'd', 'y', '</w>'], 830],
 [['e', 'a', 's', 'y', '</w>'], 829],
 [['w', 'o', 'n', 'd', 'e', 'r', 'f', 'u', 'l', '</w>'], 829],
 [['f', 'a', 'r', '</w>'], 826],
 [['d', 'e', 'a', 't', 'h', '</w>'], 822],
 [['r', 'e', 's', 't', '</w>'], 819],
 [['m', 'o', 'm', 'e', 'n', 't', '</w>'], 811],
 [['b', 'a', 'b', 'y', '</w>'], 809],
 [['c', 'a', 'r', '</w>'], 807],
 [['a', 'g', 'a', 'i', 'n', 's', 't', '</w>'], 807],
 [['l', 'o', 'o', 'k', 's', '</w>'], 803],
 [['c', 'o', 'm', 'e', 's', '</w>'], 803],
 [['t', 'h', 'i', 'n', 'k', 'i', 'n', 'g', '</w>'], 800],
 [['w', 'a', 'r', '</w>'], 795],
 [['k', 'n', 'o', 'w', 's', '</w>'], 793],
 [['r', 'a', 't', 'h', 'e', 'r', '</w>'], 791],
 [['g', 'a', 'v', 'e', '</w>'], 790],
 [['h', 'a', 'r', 'd', '</w>'], 788],
 [['e', 'y', 'e', 's', '</w>'], 788],
 [['a', 'n', 'y', 'b', 'o', 'd', 'y', '</w>'], 787],
 [['r', 'e', 'a', 'd', '</w>'], 787],
 [['l', 'o', 's', 't', '</w>'], 783],
 [['w', 'a', 't', 'c', 'h', '</w>'], 782],
 [['h', 'u', 'r', 't', '</w>'], 780],
 [['b', 'r', 'o', 't', 'h', 'e', 'r', '</w>'], 777],
 [['o', 'u', 'g', 'h', 't', '</w>'], 775],
 [['b', 'e', 'd', '</w>'], 774],
 [['a', 'n', 'y', 'o', 'n', 'e', '</w>'], 765],
 [['c', 'e', 'r', 't', 'a', 'i', 'n', 'l', 'y', '</w>'], 765],
 [['f', 'i', 'g', 'h', 't', '</w>'], 763],
 [['b', 'i', 't', '</w>'], 763],
 [['g', 'o', 'd', '</w>'], 760],
 [['c', 'h', 'i', 'l', 'd', '</w>'], 759],
 [['h', 'a', 'l', 'f', '</w>'], 755],
 [['k', 'i', 'd', '</w>'], 755],
 [['g', 'o', 'o', 'd', 'b', 'y', 'e', '</w>'], 752],
 [['e', 'a', 'c', 'h', '</w>'], 751],
 [['t', 'i', 'l', 'l', '</w>'], 750],
 [['h', 'a', 'p', 'p', 'e', 'n', '</w>'], 743],
 [['y', 'e', 'a', 'r', '</w>'], 737],
 [['m', 'a', 'r', 'r', 'y', '</w>'], 734],
 [['t', 'r', 'u', 'e', '</w>'], 733],
 [['e', 'a', 't', '</w>'], 726],
 [["'", 'e', 'm', '</w>'], 718],
 [['d', 'i', 'e', '</w>'], 717],
 [['a', 'n', 'y', 'w', 'a', 'y', '</w>'], 717],
 [['a', 'h', 'e', 'a', 'd', '</w>'], 717],
 [['s', 'i', 's', 't', 'e', 'r', '</w>'], 715],
 [['m', 'a', 'k', 'e', 's', '</w>'], 713],
 [['g', 'u', 'n', '</w>'], 712],
 [['b', 'r', 'o', 'u', 'g', 'h', 't', '</w>'], 706],
 [['s', 'e', 'e', 'm', 's', '</w>'], 705],
 [['e', 'n', 'd', '</w>'], 700],
 [['o', 'f', 'f', 'i', 'c', 'e', '</w>'], 700],
 [['m', 'i', 'n', 'u', 't', 'e', 's', '</w>'], 700],
 [['l', '</w>'], 699],
 [['f', 'o', 'u', 'r', '</w>'], 695],
 [['t', 'a', 'k', 'i', 'n', 'g', '</w>'], 692],
 [['d', 'i', 'n', 'n', 'e', 'r', '</w>'], 691],
 [['t', 'r', 'a', 'i', 'n', '</w>'], 690],
 [['m', 'a', '</w>'], 688],
 [['w', 'o', 'm', 'e', 'n', '</w>'], 687],
 [['f', 'u', 'n', 'n', 'y', '</w>'], 685],
 [['f', 'i', 'r', 'e', '</w>'], 685],
 [['m', 'o', 'n', 's', 'i', 'e', 'u', 'r', '</w>'], 683],
 [['f', 'o', 'o', 'l', '</w>'], 681],
 [['c', 'h', 'a', 'n', 'g', 'e', '</w>'], 681],
 [['g', 'o', 'e', 's', '</w>'], 679],
 [['a', 'l', 'r', 'e', 'a', 'd', 'y', '</w>'], 678],
 [['c', 'r', 'a', 'z', 'y', '</w>'], 676],
 [['a', 's', 'k', 'e', 'd', '</w>'], 672],
 [['g', 'e', 'o', 'r', 'g', 'e', '</w>'], 670],
 [['i', 'm', 'p', 'o', 'r', 't', 'a', 'n', 't', '</w>'], 668],
 [['q', 'u', 'i', 'e', 't', '</w>'], 667],
 [['g', 'o', 't', 't', 'a', '</w>'], 662],
 [['f', 'e', 'l', 'l', 'o', 'w', '</w>'], 660],
 [['j', 'o', 'e', '</w>'], 660],
 [['b', 'e', 't', '</w>'], 659],
 [['c', 'a', 'l', 'l', 'e', 'd', '</w>'], 645],
 [['l', 'u', 'c', 'k', '</w>'], 642],
 [["'", '</w>'], 642],
 [['s', 't', 'o', 'r', 'y', '</w>'], 641],
 [['b', 'r', 'e', 'a', 'k', '</w>'], 637],
 [['h', 'o', 'u', 'r', '</w>'], 636],
 [['b', 'u', 'y', '</w>'], 635],
 [['h', 'a', 'v', 'i', 'n', 'g', '</w>'], 633],
 [['l', 'a', 'w', '</w>'], 631],
 [['o', '</w>'], 629],
 [['s', 'e', 'n', 't', '</w>'], 629],
 [['c', 'h', 'i', 'l', 'd', 'r', 'e', 'n', '</w>'], 627],
 [['m', 'e', 't', '</w>'], 626],
 [['1', '0', '</w>'], 626],
 [['s', 'h', 'o', 't', '</w>'], 626],
 [['a', 'n', 's', 'w', 'e', 'r', '</w>'], 624],
 [['w', 'e', 'e', 'k', '</w>'], 622],
 [['s', 'o', 'r', 't', '</w>'], 621],
 [['w', 'a', 'l', 'k', '</w>'], 619],
 [['k', 'i', 'n', 'g', '</w>'], 618],
 [['m', 'e', 'a', 'n', 's', '</w>'], 617],
 [['r', 'e', 'a', 'l', '</w>'], 615],
 [['t', 'r', 'i', 'e', 'd', '</w>'], 609],
 [['h', 'a', 't', 'e', '</w>'], 603],
 [['g', 'e', 't', 's', '</w>'], 600],
 [['l', 'e', 'a', 'v', 'i', 'n', 'g', '</w>'], 600],
 [['d', 'a', 'u', 'g', 'h', 't', 'e', 'r', '</w>'], 598],
 [['b', 'i', 'l', 'l', '</w>'], 598],
 [['t', 'i', 'm', 'e', 's', '</w>'], 597],

In [102]:
def most_common_pair(vocab_chars):
    freq_pair = defaultdict(int)
    for toks, freq in vocab_chars:
        toks_pairs = [" ".join(pair) for pair in zip(toks, toks[1:])]
        for pair in toks_pairs:
            freq_pair[pair] += freq
    return max(freq_pair.items(), key=lambda x: x[1])[0]

In [190]:
pair_counts = Counter()
pair_counts[('t','h')] += 10
pair_counts[('t','h')] += 10
pair_counts.most_common(1)

[(('t', 'h'), 20)]

In [394]:
vocab_chars_eng2 = [[char_factor(k), v] for k, v in uniq_freq_eng.most_common()]
tokenizer_eng_test = BPETokenizer(vocab_chars_eng2, 100, False)
t = time.time()
tokenizer_eng_test.train_bpe()
print(f"{time.time()-t:.2f} seconds")

4.49 seconds