## 04. scratchpad

### 1. Data Upload

In [1]:
import pandas as pd
import os
from collections import defaultdict 
import re

In [2]:
def upload_to_dataframe(root, files, num_lines):
    path_eng, path_pol = [root+f for f in files]
    data = defaultdict(list)
    
    with open (path_eng, encoding="utf_8") as f_eng, open (path_pol, encoding="utf_8") as f_pol:
        for _ in range(num_lines):
            data['eng_text'].append(f_eng.readline().strip())
            data['pol_text'].append(f_pol.readline().strip())
    return pd.DataFrame(data)

In [3]:
root = "../data/opus_opensub/en-pl.txt/"
files = ('OpenSubtitles.en-pl.en', '/OpenSubtitles.en-pl.pl')
df = upload_to_dataframe(root, files, 600000)

### 2. EDA & Sanitazation

#### 2.1 English Non-Ascii Sentences

In [4]:
def nonascii_list(df_series, is_pol):
    if is_pol:
        pl_chars = set("ąęćłńóśźżĄĘĆŁŃÓŚŹŻ")
        requir = lambda x: x.isascii() or x in pl_chars
    else:
        requir = lambda x: x.isascii()
        
    text_all = ''.join(df_series)
    unique_dct = {x for x in text_all if not requir(x)}
    return sorted(list(unique_dct))

In [5]:
print(nonascii_list(df['eng_text'], False))

['\x80', '\x81', '\x82', '\x83', '\x84', '\x85', '\x88', '\x8b', '\x8c', '\x8e', '\x8f', '\x91', '\x94', '\x96', '\x98', '\x99', '\x9c', '\x9d', '\xa0', '¡', '¢', '£', '¤', '¥', '¦', '§', '¨', '©', 'ª', '¬', '\xad', '°', '±', '²', '³', '´', 'µ', '¶', '·', '¸', '¹', 'º', '¼', '½', '¾', '¿', 'Á', 'Â', 'Ã', 'Ä', 'Å', 'Ç', 'É', 'Ê', 'Ì', 'Ï', 'Ð', 'Ñ', 'Ô', 'Ö', 'Ø', 'Ü', 'Ý', 'Þ', 'ß', 'à', 'á', 'â', 'ã', 'ä', 'å', 'ç', 'è', 'é', 'ê', 'ì', 'í', 'î', 'ï', 'ð', 'ñ', 'ó', 'ô', 'ö', 'ù', 'ú', 'û', 'ü', 'ý', 'þ', 'Ă', 'ď', 'ę', 'Ł', 'ń', 'ő', 'œ', 'ś', 'Š', 'š', 'Ј', 'С', 'й', '،', 'أ', 'إ', 'ئ', 'ا', 'ب', 'ة', 'ت', 'ح', 'ر', 'س', 'ش', 'ع', 'غ', 'ف', 'ك', 'ل', 'م', 'ن', 'و', 'ي', 'َ', 'ُ', 'ِ', 'ّ', 'ْ', '\u200b', '‒', '–', '—', '‚', '€', '™', '─', '☻', '♥', '♪', '慹', '拢', '檛', '鈥', 'ﬁ', 'ﬂ']

In [6]:
is_ascii = lambda text: text.isascii()
maska = df['eng_text'].apply(is_ascii)
df_non_ascii = df[~maska].copy().reset_index(drop=True)
print(df_non_ascii.shape)
df_non_ascii.head()

(4595, 2)

,eng_text,pol_text
0,¿You had never seen A crab suedes? Them there ...,- Nigdy wcześniej nie widziałaś raków?
1,"He hears ¿, where you live?",Nigdy wcześniej nie byłam w lesie.
2,"Boys ¿, they are there?",Jesteście tam chłopaki?
3,- Te atrapé. - No es gracioso. Your he catches...,- Ale twoje mina była.
4,"Your also ¿, it is not like that?","- Tak, niezła jest"

In [7]:
df_2 = df[maska].reset_index(drop=True)
df_2.shape

(595405, 2)

#### 2.2 Polish Non-Ascii Sentences

In [8]:
pl_chars = set("ąęćłńóśźżĄĘĆŁŃÓŚŹŻ")
requir = lambda let: not let.isascii() and let not in pl_chars
maska = df_2['pol_text'].apply(lambda snt: any([requir(let) for let in snt]))
df_non_ascii = df_2[maska].copy().reset_index(drop=True)
print(df_non_ascii.shape)
df_non_ascii.sample(10)

(1227, 2)

,eng_text,pol_text
328,"Laughing, happy.",Šmieja sie. Ciesza sie.
99,Death!,...jest mi ¶mierci±!
811,Are we going to let a man like that throw mud ...,"POWSTRZYMAC SMITHA Pozwolimy, by ktoš taki obr..."
143,He was going to send for you As soon as you go...,Zamierzał po ciebie posłać jak ​​tylko stąd wy...
951,There is a legend he can drink two bottles of ...,"Istnieje legenda, że ​​może wypić dwie butelki..."
157,The JurgenStrasse isn't it.,"To jest JürgenStrasse, prawda?"
724,Every aspect of this matter was dealt with in ...,Wszystkie sporne kwestie zostaly wyjašnione na...
767,- I've seen filibustering...,PAINE'A - Widzialem juž takie filipiki.
319,"Come on, boss.","Šmialo, szefuniu."
46,This is blasphemy.,BluĽnisz przeciw Bogu.

In [9]:
df_3 = df_2[~maska].reset_index(drop=True)
print(df_3.shape)
df_3.sample(5)

(594178, 2)

,eng_text,pol_text
460399,"Whenever there's trouble, you're always on the...",Proszę wejść.
422385,You talk as if you wanted to see her tried for...,"Mówi pan, jakby chciał ją zobaczyć sądzoną za ..."
116876,"Ask me anything else, anything!","Proszę. Proś mnie, o co zechcesz."
42758,And I'm going to take you in my arms now and h...,I zaraz wezmę cię w ramiona i przytulę mocno! ...
33941,It's Elizabeth!,To Elizabeth!

In [10]:
print(nonascii_list(df_3['eng_text'], False))
print(nonascii_list(df_3['pol_text'], True))

[]
[]

In [11]:
df_3.iloc[74182]['eng_text']

'The next time I...'

In [12]:
df_3.iloc[74182]['pol_text']

'Następnym razem...'

#### 2.3 Short Or Empty Examples

In [13]:
mask1 = df_3['eng_text'].str.len() >= 3
mask2 = df_3['pol_text'].str.len() >= 3

In [14]:
df_4 = df_3[mask1 & mask2].reset_index(drop=True)
df_4.head()

,eng_text,pol_text
0,"Previously on ""The Blacklist""...",/W poprzednich odcinkach: /
1,- You want to call your daddy?,- Chcesz zadzwonić do taty?
2,"- Yeah, I want to tell him I'm okay.","- Tak, powiem, że wszystko w porządku."
3,Okay.,Dobrze.
4,Lizzy... Be careful of your husband.,"Lizzy, uważaj na męża."

In [15]:
df_4.shape

(593894, 2)

#### 2.4 Dialog like sentences [starts with - ]

In [16]:
is_dialog = lambda snt: bool(re.match(r"^ *- *", snt))
mask = df_4['eng_text'].apply(is_dialog) | df_4['pol_text'].apply(is_dialog)
df_dialogs = df_4[mask].copy().reset_index(drop=True)
df_dialogs.head()

,eng_text,pol_text
0,- You want to call your daddy?,- Chcesz zadzwonić do taty?
1,"- Yeah, I want to tell him I'm okay.","- Tak, powiem, że wszystko w porządku."
2,- 45 seconds.,Szybciej! 45 sekund.
3,It's okay. It's okay. It's okay.,- Już dobrze.
4,It's okay. You're okay. You're okay.,- Odpoczywaj.

In [17]:
def fix_dialog(snt):
    return re.sub(r"^ *- *", "", snt)

df_4['eng_text'] = df_4['eng_text'].apply(fix_dialog).reset_index(drop=True)
df_4['pol_text'] = df_4['pol_text'].apply(fix_dialog).reset_index(drop=True)
df_4.sample(30)

,eng_text,pol_text
313445,So you and the old boy cross swords?,Więc posprzeczałeś się ze staruszkiem?
139898,See you all later,Do zobaczenia.
171937,Love is a strange thing.,Miłość to dziwna rzecz.
445872,What about the poorhouse?,A przytulisko?
223879,Halt!,Stać!
531417,I'll get rid of them.,Dlaczego nie mogę?
1364,"Yes, of course.","Tak, oczywiście."
163491,Try and come to an understanding with the boss.,Spróbuj się porozumieć z szefową.
31358,You're not going to see some young lieutenant ...,Nie masz dziś w planach randki z jakimś młodym...
136937,I couldn't marry a dead man.,Nie mogę wyjść za nieboszczyka.
534334,"""For I'm foolish.""","""Bo jestem głupia."""
412608,Hollywood caught up with you?,Załapałeś się w Hollywoodzie?
11628,"""No, no, anything but that!""","""Nie, wszystko tylko nie to!"""
79175,"Gee, it's warm in here.","Rany, ale tu jest gorąco."
442093,"Darling, you are the song","Kochanie, jesteś piosenką"
218031,I wasn't thinking of that.,Nie o tym myślałem.
509772,"Have to get it yourself, mister.",Musi pan wziąć sam.
380890,"ONE ""B.""",Zabierasz ze sobą lunch?
585265,This lady I've been telling you about.,"Ta dama, o której mówiłam."
580837,We'll bunk in it.,Będziemy tam nocować.
530655,Sorry about you two. Kathy told my wife this m...,"Przykro mi, że się wam nie ułożyło."
16178,Director:,Reżyseria:
320964,"They are men too, like us.",Są takimi samymi ludźmi jak my.
112447,I wasn't sleeping.,Nie spałem. Byłem...
386065,There you are Donald.,Tu jesteś Donald.
30257,"Boss, I'm sorry. I should have been with you.","Przepraszam, powinienem być z tobą."
197660,"That's Aunt Hedwige, the head of the family.","To ciocia Hedwige, głowa rodu."
94274,That's me.,To ja.
29895,Just because...,Przyjdzie...
326922,It's a good game.,To dobra gra.

#### 2.5 Broken Dialog like sentences [somehwere has -]

In [18]:
broken_dialog = lambda snt: bool(re.match(r".* +- +.*", snt))
mask1 = df_4['eng_text'].apply(broken_dialog)
mask2 = df_4['pol_text'].apply(broken_dialog)

In [19]:
df_4[mask1 | mask2].sample(5)

,eng_text,pol_text
407931,Get back!,Wracać. - Ewakuacja!
508312,Would you take a note in for me? - When he buz...,Zaniosłabyś mu liścik ode mnie?
492639,He's coming. - Who?,Kto?
127576,"She's gone, sir. - Gone?","Wyjechała, proszę pana."
329368,"And maybe in a flash, like a bolt of lightning...","Nie przetrwałby bez korzeni, które sięgają głe..."

In [20]:
df_5 = df_4[~mask1 & ~mask2].reset_index(drop=True)

In [21]:
broken_dialog = lambda snt: bool(re.match(r".*-.*", snt))

In [22]:
df_5.sample(50)

,eng_text,pol_text
424250,"Oh, how I do hate living in a London flat.",Jak ja nienawidzę mieszkać w londyńskim mieszk...
203754,I can't.,Nie mogę.
368225,HeilHitler.,Heil Hitler.
428530,"There's a $10,000 reward out for just the kind...",Jest 10 tysięcy nagrody za ten rodzaj informac...
565153,Yes. Is there something I can do?,Jestem jego żoną.
301504,"Yes, yes, I'll do it.","Tak, tak, zrobię to."
537393,German victory is inevitable.,Zwycięstwo Niemiec jest pewne.
391344,You hear that?,Słyszałeś to?
504670,"Furthermore, she knew precisely how to guide m...",Pomogła mi wyjść tylnymi drzwiami.
51847,He's probably under one.,Baravelli do mnie.
380754,Mrs Walden.,Pani Walden.
6708,"""Good evening, Mr. Hull!""","Dzień dobry, panie Hull!"
215020,Let's sit down.,Usiądźmy.
125821,"Oh please, Andre.","Błagam, Andre!"
219179,And you're irritable because your nerves are a...,"Jest pani rozdrażniona, bo ma napięte nerwy."
543714,"This isn't a country for glory, Owen.",To nie jest kraj gdzie można zdobyć chwałę.
504995,In these things we'd be spotted right away.,W tych ciuchach zaraz nas namierzą.
109051,Beasts.,Bestie.
154091,It's got the Falins' smell on it.,Ma na sobie zapach Falinów.
40814,"No, he wouldn't!",Tak myślisz?
23942,You can't be serious.,Pan raczy żartować!
151982,Meet Mr. Hawkins.,To pan Hawkins.
564898,"How dare you? Who are you, anyway?",Kim jesteś?
322593,"Mommy, you're a heroine.","Mamo, jesteś bohaterką."
30082,I am Dracula.,Jestem... Dracula.
356293,I'm afraid Bananas is only used to forecastles.,"Obawiam się, że Bananowi brak trochę ogłady."
348245,Where are you going?,Dokąd idziesz?
356140,You found your anchor?,Wciągaj kotwicę.
84587,What?,Co?
372183,"I love you, Sam.","Kocham cię, Sam."
70431,She's been put In solitary.,Wzięli ją do izolatki.
338582,"Now, you've got to listen to me.",Posłuchaj mnie.
380662,"Come on, honey, and sit down.",Usiądź słoneczko.
21430,"Exactly, nothing elaborate.","Miejsce, które można nazwać domem a żonie powi..."
530794,Who are they eh?,Kim oni są?
98945,MacCaulay? I can't believe it!,Nie do wiary!
76355,"Alright, I'll leave in five minutes.","Dobra, wyjdę za pięć minut."
411328,"No, thanks.",Nie.
529721,"Hello, Grannie.","Cześć, babciu."
374186,"Worse than that, there was a strike at the fac...","Co gorsza, w fabryce był strajk, a ja, kierown..."
299982,Twenty years?,Dwadzieścia lat?
513647,Seem any easier?,Trochę lepiej?
371360,"I mean, Mrs. Craig.","Znaczy, pani Craig."
198291,It was my way of making him happy.,Tak mogłam go uszczęśliwić.
325315,It's a waste of time. If you want to get sore ...,"Jeśli cię irytuję, to normalne., wszystkim dzi..."
34868,"Well, I'm sorry I wasted your time, Mr. Taylor.",No to przykro mi. Zmarnowałem twój czas panie ...
575191,"What's he ke, Nor ko?","Jaki on jest, Noriko?"
108537,Clear deck!,Opuścić pokład!
43771,SHE'S DEAD.,Ona nie żyje.
505094,We never saw him before.,Widzimy go pierwszy raz.

#### 2.6 Different Last Case

In [23]:
mask = df_5['eng_text'].str[-1] != df_5['pol_text'].str[-1]
mask.sum()

57558

In [24]:
df_6 = df_5[~mask].reset_index(drop=True)

#### 2.7 Text length difference

In [25]:
mask = df_6['eng_text'].str.split
df_6['len_ratio'] = df_6['eng_text'].str.split().str.len() / df_6['pol_text'].str.split().str.len()
df_6.head()

,eng_text,pol_text,len_ratio
0,You want to call your daddy?,Chcesz zadzwonić do taty?,1.500000
1,"Yeah, I want to tell him I'm okay.","Tak, powiem, że wszystko w porządku.",1.333333
2,Okay.,Dobrze.,1.000000
3,Lizzy... Be careful of your husband.,"Lizzy, uważaj na męża.",1.500000
4,I can only lead you to the truth.,/Mogę naprowadzić cię na prawdę.,1.600000

In [26]:
thres_left = df_6["len_ratio"].quantile(0.05)
thres_right = df_6["len_ratio"].quantile(0.95)
thres_left, thres_right

(0.75, 2.5)

In [27]:
mask = (df_6["len_ratio"] >= thres_left) & (df_6["len_ratio"] <= thres_right)
mask.sum()

472209

In [28]:
df_7 = df_6[mask].reset_index(drop=True)
df_7.sample(20)

,eng_text,pol_text,len_ratio
255829,I've got about $500 left.,Zostało mi 500 dolarów.,1.250000
375607,Sorry.,Przepraszam.,1.000000
115059,Mr. Waldemar!,Panie Waldemar!,1.000000
149747,Hurry.,Szybko.,1.000000
273679,I see.,Rozumiem.,2.000000
339633,Even if it is about Hitler?,Nawet jeżeli dotyczy Hitlera?,1.500000
139800,You'd never sell your old stock.,Nigdy nie sprzedałaby pani starego towaru.,1.000000
12781,Look. My family.,Moja rodzina.,1.500000
414887,You see me climb in? Sure. Or I wouldn't sugge...,Inaczej nie zachęcałbym cię do wyjścia.,2.333333
276094,I saw the tunnel that my pal Lefty Matson dug ...,Widziałem ten tunel co mój kumpel Lefty Matson...,1.153846
40716,"We could wait here a few minutes, and say that...","Poczekajmy tu parę minut, potem zejdźmy i powi...",1.083333
93320,Stand by to go aloft!,Przygotować się do wejścia na maszt!,0.833333
124075,Certainly.,Oczywiście.,1.000000
152776,Yeah. Yeah.,Pewnie.,2.000000
282714,"Is Vin still a vege... ""Vegetenarian,"" mother?",On ciągle jest wegetarianinem?,1.750000
225470,"Oh, speaking of that Zorro, could you provide ...","A co do tego Zorro, ekscelencjo... zapewnisz m...",1.181818
22248,I can't get it out of my mind.,Nie mogę tego wyrzucić z umysłu.,1.333333
217741,I've been looking for you tramps.,"Szukałam was, dranie.",2.000000
219594,He promised me money and a good position if I ...,"Obiecał mi pieniądze i dobrą posadę, jeśli nic...",1.400000
324553,Have your own elderberry bushes?,Macie panie własne krzewy bzu?,1.000000

In [29]:
df_7.sample(50)

,eng_text,pol_text,len_ratio
173037,Twice I've seen you dead in my dreams.,Dwa razy widziałem cię martwego w moich snach.,1.000000
284328,It was pretty sweet of him to come from New Yo...,"I to miłe z jego strony, że zechciał przyjecha...",0.866667
162221,Reverend Ethan Wilkins! Reverend Wilkins has c...,Wielebny Ethan Wilkins który przybył z Marylan...,1.600000
160195,Right.,Dobrze.,1.000000
106869,Ferryboat.,Prom.,1.000000
86412,"If it was anybody else but you, I'd chuck you ...","Gdyby to był ktoś niż ty, wyrzuciłbym za burtę.",1.222222
365955,Shut up. You're a cheap crook and you killed him.,Jesteś oszustem i go zabiłeś.,2.000000
200980,They can fall out of love.,Mogą się odkochać.,2.000000
427879,"Well, there is some ale in the kitchen if you ...","Mamy w kuchni trochę piwa, jeśli chcecie...",2.000000
295928,"Remember that, Tokyo.",Pamiętaj Tokyo.,1.500000
69092,What are you so nervous about?,Co się tak stresujesz?,1.500000
282284,Amen.,Amen.,1.000000
131375,"Yes, sir, but...","Tak, proszę pana, aIe...",0.750000
320756,"Yes, it bows in sorrow.","Tak, pochyla się ze smutku.",1.000000
317388,That's got nothing to do with it.,To nie ma nic do rzeczy.,1.166667
80208,"A draper, a greengrocer, someone humble fit to...","Sukiennika, handlarza, kogoś pokornego, pasują...",1.250000
100196,He never did love me.,. Nigdy nie kochał mnie.,1.000000
394856,But I can't!,Ale nie mogę!,1.000000
333920,"Yes, thank you.","Tak, dziękuję.",1.500000
286358,"And to cinch it, I'll give him 50 percent.",Dla pewności dam mu 50.,1.800000
161537,One would be enough.,Wystarczyłby jeden.,2.000000
342785,"At your age, you best not be lifting things so...","W twoim wieku, nie powinieneś dźwigać takich c...",1.375000
205200,"We'll go wildcatting, huh?",Czy zrobimy dzikie wiercenie?,1.000000
35707,Thought you'd gone to bed.,"Myślałem, że poszłaś do łóżka.",1.000000
355234,"Please sit, we'll say hello later.","Siadajcie, później się przywitamy.",1.500000
136211,You can live like a great lord!,Możesz żyć jak wielki pan!,1.400000
55793,Come on.,Chodźcie.,2.000000
275039,I seem to have put my big foot in it.,Nie powinnam była się w to mieszać.,1.428571
343229,"You should be ashamed, throwing yourself at a ...","Wstydź się, rzucać się na takiego faceta.",1.571429
379554,"Come here, belle.","Chodź tu, Belle.",1.000000
16362,I got some surprise for you!,Mam dla ciebie niespodziankę!,1.500000
170558,Put the musket balls aside.,połóż je z boku.,1.250000
410483,I don't hear anything jingle.,Nie słyszę żadnego brzęczenia.,1.250000
353471,What a dumb town!,Co za głupie miasto!,1.000000
340538,The third remains.,Trzeci jeszcze nie.,1.000000
153637,The fight is over.,Walka skończona.,2.000000
469971,What's that supposed to mean?,Jak to?,2.500000
57371,How are you?,Jak się masz?,1.000000
375107,"You're not going to commit a second murder, Dr...","Dr Mercheson, nie zamierzasz chyba popełnić dr...",1.250000
135754,"Stay right where you are, countess.","Zostań tam, gdzie jesteś, hrabino.",1.200000
35493,I want you to give Dr. X full credit for trapp...,"Chcę, żebyś dał Doktorowi X, pełne uznanie za ...",1.200000
21003,Tell me.,Powiedz mi.,1.000000
56163,"Yes. When I was called, the girl had been dead...","Gdy mnie wezwano, dziewczyna była martwa 3, 4 ...",1.777778
61614,I finally found the coal man.,W końcu znalazłem dostawcę węgla.,1.200000
24169,"You're a man of the world, and you know that t...",Dokładnie tak. Jesteś człowiekiem światowym i ...,1.523810
216478,Just a few dissenters.,Kilku buntowników.,2.000000
25955,Women?,Kobiety?,1.000000
212461,"I mean, where are you sleeping?","To znaczy, gdzie śpisz?",1.500000
26492,Are you sure she's all right?,"Jesteś pewien, że wszystko w porządku?",1.000000
241279,Thank you.,Dziękuję.,2.000000

#### 2.8 Sentences starting with * fix

In [30]:
fix_star = lambda snt: re.sub(r"^ *[*].*", "", snt)
df_7['eng_text'] = df_7['eng_text'].apply(fix_star)
df_7['pol_text'] = df_7['pol_text'].apply(fix_star)

#### 2.9 Action Comments

In [31]:
def mask_distinct(df, col1, col2, chars):
    chars_escaped = "".join(re.escape(c) for c in chars)
    templ = f"[{chars_escaped}]"

    m1 = df[col1].str.contains(templ, regex=True, na=False)
    m2 = df[col2].str.contains(templ, regex=True, na=False)

    return m1 ^ m2

chars = '[]()/\*+#$"️'
mask = mask_distinct(df_7, "eng_text", "pol_text", chars)

df_8 = df_7[~mask].reset_index(drop=True)
df_8.shape

(467550, 3)

In [32]:
df_8.sample(50)

,eng_text,pol_text,len_ratio
198320,I know.,Wiem.,2.000000
4018,"It was very good advice, indeed.",Ta twoja rada doskonale się sprawdziła.,1.000000
421037,Truffles and champagne.,Trufle i szampan.,1.000000
89116,You sent for a manicurist?,Zamawiano tutaj manicure?,1.666667
107639,Please.,Proszę.,1.000000
301349,Where do we go?,Dokąd idziemy?,2.000000
67230,"That's a short jerky movement, like this.",To taki gwałtowny ruch.,1.750000
416361,"What's the matter, Mortimer?","o co chodzi, Mortimer?",1.000000
401008,Come on.,Wstawaj.,2.000000
464452,They said I'd never do it alone.,"Mówili, że nigdy nie zrobię tego sam.",1.000000
223787,Tell them which rooms they're to have.,Pani Imbrie i panu Connorowi. Musicie im przyd...,0.777778
297878,You must have observed him for months.,Musiał pan go obserwować od kilku miesięcy.,1.000000
107890,"Pass the sugar, lover.","Podaj cukier, kochany.",1.333333
425603,! -Two!,Dwa!,2.000000
316423,"Franz Gruber, first violin in the first stater...","Franz Gruber, pierwszy skrzypek w I klasie na ...",1.200000
427810,"How old are you, Alfred?","Ile masz lat, Alfred?",1.250000
5674,Take Gunther's form and break Brunhild's iron ...,Przybierz postać Gunthera i złam żelazną wolę ...,1.000000
362245,I'm not a murderer.,Nie jestem mordercą.,1.333333
203418,Hi.,Cześć.,1.000000
139140,"""This is not according to form.","""To wbrew normalnej praktyce.",1.500000
132363,Oh.,Och.,1.000000
317096,And it's women and children first!,"A to oznacza, że wpierw kobiety i dzieci!",0.750000
405875,Breaks a glass.,Tłuką szkło.,1.500000
439494,"Oh, I don't know.",Sama nie wiem.,1.333333
129191,"Ahoy there, on the mud scow.","Ahoj, załogo zakichanej łodzi.",1.500000
184486,Hiding on the moor ever since.,Od tego czasu ukrywał się na wrzosowiskach.,0.857143
345293,Come in.,Proszę wejść.,1.000000
275192,"Oh, I don't know, he didn't leave word.","Nie wiem, nie powiedział ani słowa.",1.333333
344431,"No, seriously, Pam.",Bądź poważna.,1.500000
227416,"This way, sir.","Tędy, sir.",1.500000
259237,Shall I call the police?,Może zadzwonimy na policję?,1.250000
155962,"In life, I was your partner, Jacob Marley.","Za życia byłem twoim wspólnikiem, Jakubem Marl...",1.142857
199563,"Miriam, how's matrimony? Still making a go of it?","Miriam, wciąż bawi cię małżeństwo?",1.800000
282332,"Be good. Say your prayers, Camille.","Do zobaczenia, Camille.",2.000000
141872,In all sorts of ways.,Na różne sposoby.,1.666667
55820,I'm celebrating.,Świętuję.,2.000000
323101,And right then it came over me that I hadn't w...,"W pewnej chwili dotarło do mnie, że niczego ta...",1.347826
119508,"Nothing very hopeful, Chief.","Nic napawającego otuchą, szefie.",1.000000
254659,He's a terrible example of places like Marysport.,Jest okropnym przykładem miejsc takich jak Mar...,1.142857
157738,You needn't have asked.,Nie musisz o to prosić.,0.800000
404247,You've been driving almost 10 hours.,Prowadzisz prawie od 10 godzin.,1.200000
184340,Jack has some theory about them.,Jack ma na ten temat teorię.,1.000000
441215,Have it sounded.,Proszę zagrać.,1.500000
363111,Good.,Dobrze.,1.000000
467040,"I want to take you with me, now that I know wh...","Teraz, gdy cię poznałem, chcę zabrać cię ze sobą.",1.555556
232453,But I don't want to get it by double-crossing ...,Ale nie mogę zawieść Joe.,2.000000
150982,Give him the dough.,"Daj mu forsę, powiedziałem.",1.000000
160502,"Perfectly, and thank you very much, gentlemen.",Oczywiście. Dziękuję bardzo.,2.333333
131010,"We're just terribly hurt, that's all.",Bardzo nas zraniono.,2.000000
298417,MAYBE IF WE GOT A PILE OF FEATHERS AND MADE HI...,Może gdybyśmy mieli mnóstwo piór... i sprawili...,1.636364

#### 2.10  " ` " ---> " ' " & del " ~ "

In [87]:
wanted_case = '`'
mask = df_8["eng_text"].apply(lambda x: wanted_case in x)
df_8[mask]

,eng_text,pol_text,len_ratio
214145,"Revolution had broken out, her diplomats sued ...","Rewolucja na tyłach frontu, dąży do zawarcia p...",1.277778
214152,We`ll examine it.,Zbadajmy go.,1.500000
214157,What do you think you`re doing?,Wstawaj! Co ty robisz?,1.500000
214161,Where`s your hand grenade?,Gdzie masz swój granat?,1.000000
214163,Let `em have it!,Niech je poczują!,1.333333
...,...,...,...
214943,We don`t want to hate one another.,Bez nienawiści ani pogardy.,1.750000
214944,There`s room for everyone.,Każdy ma swe miejsce.,1.000000
214947,"Greed has poisoned men`s souls, has barricaded...","Chciwość zatruła nasze dusze, wzniosła mury ni...",1.333333
214963,You don`t hate.,Przestańcie nienawidzieć.,1.500000
214965,"Soldiers, don`t fight for slavery, fight for l...","Nie walczcie o niewolę, lecz o wolność!",1.142857

In [88]:
df_8["eng_text"] = df_8["eng_text"].str.replace("`", "'", regex=False)
df_8["pol_text"] = df_8["pol_text"].str.replace("`", "'", regex=False)

In [95]:
df_8["eng_text"] = df_8["eng_text"].str.replace("~", "", regex=False)
df_8["pol_text"] = df_8["pol_text"].str.replace("~", "", regex=False)

#### 2.11 Del rows with specific case

In [184]:
def del_row_with_char(df, eng_col, pol_col, chars):
    df_proc = df.copy()
    for char in chars:
        mask1 = df_proc[eng_col].apply(lambda x: char in x)
        mask2 = df_proc[pol_col].apply(lambda x: char in x)
        df_proc = df_proc[~(mask1 | mask2)].reset_index(drop=True)
    return df_proc
    

chars = "=+*@#;|_}{"
df_data = del_row_with_char(df_8, "eng_text", "pol_text", chars)

#### 3. Data Tokenization

In [33]:
test_snt = "That's good, right?"
test_snt

"That's good, right?"

In [185]:
uniq_cases = set("".join(df_data["eng_text"].astype(str)))
print(sorted(list(uniq_cases), reverse=True))

['z', 'y', 'x', 'w', 'v', 'u', 't', 's', 'r', 'q', 'p', 'o', 'n', 'm', 'l', 'k', 'j', 'i', 'h', 'g', 'f', 'e', 'd', 'c', 'b', 'a', ']', '[', 'Z', 'Y', 'X', 'W', 'V', 'U', 'T', 'S', 'R', 'Q', 'P', 'O', 'N', 'M', 'L', 'K', 'J', 'I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'A', '?', ':', '9', '8', '7', '6', '5', '4', '3', '2', '1', '0', '/', '.', '-', ',', ')', '(', "'", '%', '$', '"', '!', ' ']

In [186]:
uniq_cases = set("".join(df_data["pol_text"].astype(str)))
print(sorted(list(uniq_cases), reverse=True))

['ż', 'Ż', 'ź', 'Ź', 'ś', 'Ś', 'ń', 'Ń', 'ł', 'Ł', 'ę', 'Ę', 'ć', 'Ć', 'ą', 'Ą', 'ó', 'Ó', 'z', 'y', 'x', 'w', 'v', 'u', 't', 's', 'r', 'q', 'p', 'o', 'n', 'm', 'l', 'k', 'j', 'i', 'h', 'g', 'f', 'e', 'd', 'c', 'b', 'a', ']', '[', 'Z', 'Y', 'X', 'W', 'V', 'U', 'T', 'S', 'R', 'Q', 'P', 'O', 'N', 'M', 'L', 'K', 'J', 'I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'A', '?', ':', '9', '8', '7', '6', '5', '4', '3', '2', '1', '0', '/', '.', '-', ',', ')', '(', "'", '%', '$', '"', '!', ' ']

In [183]:
wanted_case = '/'
mask = df_data["pol_text"].apply(lambda x: wanted_case in x)
df_data[mask]

,eng_text,pol_text,len_ratio
494,I will be to this generation a second Mohammed...,"/Będę dla naszego pokolenia /drugim Mahometem,...",1.312500
791,"""with its accompanying name, sign or penalty.",/kapłaństwa imienia i kar.,1.750000
1633,The congress member Evan Baxter tomorrow he/sh...,"/Człowiek z telewizji, Evan Baxter, /obejmuje ...",0.769231
1847,HE/SHE REQUESTS AND YOU WILL RECEIVE.,"/Proś, a będzie ci dane.",1.200000
1858,I thought that he/she would fall you well with...,"/Pomyślałem, że będzie pasować /do brody i wło...",1.333333
1880,He/she returns to work.,/Wracaj do pracy.,1.333333
4487,Lil Dagover An usher/clerk,Lil Dagover Prowadzący / urzędnik,0.800000
30139,"HE WEARS BROAD-TOED SHOES, SIZE 101/2.","Nosi buty z szerokim czubkiem, rozmiar 101/2.",0.857143
31074,2 1/2 YEARS IN A STONE CELL WON'T HELP HER LOO...,"2 1/2 roku w kamiennej celi, nie wpłynie dobrz...",1.000000
46924,Rumors Abound It's Being Auctioned On The Inte...,"/Mówi się, że został wystawiony /na aukcji w i...",1.666667
51870,"One cup of sugar, 1/4 teaspoonful Of salt, One...","Jedna szklanka cukru, 1/4 łyżeczki soli, jedna...",1.384615
73423,She's with a servant/secretary.,Towarzyszy jej służący/sekretarz.,1.333333
73495,You know. An American German/American.,"No, wiesz, amerykański Niemiec/Amerykanin.",1.250000
210274,"But Tom, I've got it down to one/one hundred t...","Ale Tom, już sprowadziłem to do jednej/sto tys...",1.555556
262721,I mean splitting 50/50 on this job and .. On o...,Mam na myśli podział 50/50 na tę pracę i... na...,1.071429
262740,50/50?,50/50?,1.000000
280369,"I got 85""%"" on the test and a week's leave on ...",Dostałem z egzaminu 85/100 i w nagrodę tydzień...,1.666667
288454,You understand that in no way must your action...,"Musisz zrozumieć, że twoje zachowanie nie może...",1.538462
288456,"As a matter of fact, there is you and/or the G...","Prawdę mówiąc, tak ty i/lub niemiecka armia.",1.714286
316392,Some icebergs are miles long and 7 /8 of them ...,Niektóre góry lodowe mierzą milę i 7/8 z nich ...,1.000000
323795,We have succeeded in identifying him as one Ni...,Udało nam się go zidentyfikować jako Nina Zach...,1.130435
331768,"""love and desire and hate.","/miłość, pożądanie, nienawiść.",1.666667
346932,"At the same time, World Enterprises Incorporat...",/Równocześnie /World Enterprises Inc. /zaofero...,1.045455
348284,They were given 1/12th of a loaf of bread and ...,Dzienna racja to 1/12 bochenka chleba i trochę...,1.400000
361678,"""I can't believe that you're in love with me""","/""Nie mogę uwierzyć, /że jesteś we mnie zakoch...",1.125000
361775,"But me from now on, I'll take my education i...","/Chyba jednak wolę studiować, /być samoukiem /...",2.500000
361876,You're going to tell me you don't believe my s...,"/Masz zamiar mi powiedzieć, że nie wierzysz /w...",1.130435
361906,The first thing I found out was that I had $768.,"/Po pierwsze, okazało się, /że miałem 768 dola...",1.375000
362040,"Vera wasn't kidding with that ""Siamese twins"" ...","/Vera nie żartowała z tymi /""bliźniętami syjam...",1.142857
364271,I made it 3/4 yesterday and wasn't a bit tired.,Wczoraj przepłynąłem 3/4 długości.,2.500000
364508,He swam 3/4 the day before and he was sure he ...,"Wcześniej przepłynął 3/4 jeziora. Był pewny, ż...",1.166667
370510,"""Police believe the impostor who escaped from ...","/""Policja uważa, że oszust który uciekł z Gree...",1.250000
370794,"He said, ""That makes 21.","/On powiedział: ""Mam 21, wygrałem"".",1.000000
370866,[J.B. 's Voice] It was something in my childhood.,/To było coś w moim dzieciństwie.,1.500000
370928,[Murchison's Voice] I knew Edwardes only sligh...,/Znałem tylko odrobinę Edwardesa... /Nigdy go ...,1.625000
374891,22nd July 1944 S1504 for 23/7,"22 lipca 1944 r., S1504 dla 23/7",0.857143
391495,Miss Ingeborg is a piano teacher and lets a ro...,/Panna Ingeborg uczy gry na pianinie. /Wynajmu...,1.470588
425144,"1547 45/38, R. Ekberg, for military service.",R. Ekberg 1547 45/38 powołany do służby wojsko...,0.875000

In [ ]:
to_del = "~=@+*;"

In [94]:
re.sub("~", "", "~~~ pronounce you man and wife.")

' pronounce you man and wife.'

In [65]:
# Change '`' to '

In [49]:
df_8[mask]

,eng_text,pol_text,len_ratio
3262,One hour and forty~ four paints later.,Godzinę i 22 litry później.,1.400000
3270,~~~ pronounce you man and wife.,ogłaszam was mężem i żoną.,1.200000
280187,"I tell you, ~Father... when I think of the cla...",Kiedy myślę o systemie klasowym w tym kraju...,2.125000
280281,"~For you, Miss Beldon.","Dla pani, panno Beldon.",1.000000
280321,~For long?,Na długo?,1.000000
280331,~For you too?,Dla ciebie też?,1.000000
280332,"~For me too, Vin.","Tak, Vin.",2.000000
280364,And that stove the man only come ~Friday to lo...,"I ten piec... Był ten spec w zeszły piątek, al...",1.266667
280409,The RA~F for me.,Ja służyłbym w RAF-ie.,1.000000
280419,"Not half, she ain't. ~Full dress inspection kit.","Nie, dobrane jak należy.",2.000000
280440,After a terrific row with Mr. ~Foley my grandm...,Po straszliwej awanturze z panem Foley'em... b...,1.250000
280469,You're in league with wretched ~Foley.,Jesteś w zmowie z tym wstrętnym Foley'em.,0.857143
280477,It's ~Foley giving a false alarm.,To pewnie ten Foley zrobił fałszywy alarm.,0.857143
280494,"Hello, ~Foley.","Cześć, Foley.",1.000000
280499,"Oh, gosh. This way, ~Foley.",Chodź ze mną.,1.666667
280542,Did you get that ~Fritz?,Złapaliście tego Fritza?,1.666667
280595,Gladys joined the WAA~Fs. She's off to Aldershot.,Gladys wstąpiła do ŻSP.,2.000000
280596,What's a WAA~F?,Co to ŻSP?,1.000000
280597,Women's Auxiliary Air ~Force.,Żeńska Służba Pomocnicza.,1.333333
280629,Some job or other. You don't ask why in the Ai...,W lotnictwie nie zadaje się takich pytań.,1.714286
280652,Shoot down some Jerries and ~Fritzes.,Zastrzel paru Szwabów.,2.000000
280693,"~Fill her up, Dixon.",Nalej do pełna.,1.333333
280728,~Funny how the sound carries with this east wind.,Jak ten wschodni wiatr niesie dźwięk.,1.500000
280746,~Food.,Jeść.,1.000000
280748,"~Food, quick.","Jeść, szybko.",1.000000
281013,"~Fine, Mr. Miniver. Just fine.",W porządku.,2.500000
281096,"~First prize, Miss Alice Lovedean.",Panna Alice Lovedean.,1.666667
281113,"Not now, ~Foley.",Nie teraz.,1.500000
281122,~Foley here says there's a chance of air raide...,"Foley mówi, że powinniśmy liczyć się z nalotem.",1.500000
281127,~Foley's seen to that.,Foley o to zadbał.,1.000000
281147,Do you think the ~Foley girl will take the chi...,"Myślisz, że Foley zabrał je do schronu?",1.857143
281223,"~Fight it, then.",Więc walczmy.,1.500000

#### fask;ldjfha;lskjdhfas;dkljfhas