## 04. scratchpad

### 1. Data Upload

In [54]:
import pandas as pd
import os
from collections import defaultdict, Counter
import re
import time

In [2]:
def upload_to_dataframe(root, files, num_lines):
    path_eng, path_pol = [root+f for f in files]
    data = defaultdict(list)
    
    with open (path_eng, encoding="utf_8") as f_eng, open (path_pol, encoding="utf_8") as f_pol:
        for _ in range(num_lines):
            data['eng_text'].append(f_eng.readline().strip())
            data['pol_text'].append(f_pol.readline().strip())
    return pd.DataFrame(data)

In [3]:
root = "../data/opus_opensub/en-pl.txt/"
files = ('OpenSubtitles.en-pl.en', '/OpenSubtitles.en-pl.pl')
df = upload_to_dataframe(root, files, 600000)

### 2. EDA & Sanitazation

#### 2.1 English Non-Ascii Sentences

In [4]:
def nonascii_list(df_series, is_pol):
    if is_pol:
        pl_chars = set("ąęćłńóśźżĄĘĆŁŃÓŚŹŻ")
        requir = lambda x: x.isascii() or x in pl_chars
    else:
        requir = lambda x: x.isascii()
        
    text_all = ''.join(df_series)
    unique_dct = {x for x in text_all if not requir(x)}
    return sorted(list(unique_dct))

In [5]:
print(nonascii_list(df['eng_text'], False))

['\x80', '\x81', '\x82', '\x83', '\x84', '\x85', '\x88', '\x8b', '\x8c', '\x8e', '\x8f', '\x91', '\x94', '\x96', '\x98', '\x99', '\x9c', '\x9d', '\xa0', '¡', '¢', '£', '¤', '¥', '¦', '§', '¨', '©', 'ª', '¬', '\xad', '°', '±', '²', '³', '´', 'µ', '¶', '·', '¸', '¹', 'º', '¼', '½', '¾', '¿', 'Á', 'Â', 'Ã', 'Ä', 'Å', 'Ç', 'É', 'Ê', 'Ì', 'Ï', 'Ð', 'Ñ', 'Ô', 'Ö', 'Ø', 'Ü', 'Ý', 'Þ', 'ß', 'à', 'á', 'â', 'ã', 'ä', 'å', 'ç', 'è', 'é', 'ê', 'ì', 'í', 'î', 'ï', 'ð', 'ñ', 'ó', 'ô', 'ö', 'ù', 'ú', 'û', 'ü', 'ý', 'þ', 'Ă', 'ď', 'ę', 'Ł', 'ń', 'ő', 'œ', 'ś', 'Š', 'š', 'Ј', 'С', 'й', '،', 'أ', 'إ', 'ئ', 'ا', 'ب', 'ة', 'ت', 'ح', 'ر', 'س', 'ش', 'ع', 'غ', 'ف', 'ك', 'ل', 'م', 'ن', 'و', 'ي', 'َ', 'ُ', 'ِ', 'ّ', 'ْ', '\u200b', '‒', '–', '—', '‚', '€', '™', '─', '☻', '♥', '♪', '慹', '拢', '檛', '鈥', 'ﬁ', 'ﬂ']

In [6]:
is_ascii = lambda text: text.isascii()
maska = df['eng_text'].apply(is_ascii)
df_non_ascii = df[~maska].copy().reset_index(drop=True)
print(df_non_ascii.shape)
df_non_ascii.head()

(4595, 2)

,eng_text,pol_text
0,¿You had never seen A crab suedes? Them there ...,- Nigdy wcześniej nie widziałaś raków?
1,"He hears ¿, where you live?",Nigdy wcześniej nie byłam w lesie.
2,"Boys ¿, they are there?",Jesteście tam chłopaki?
3,- Te atrapé. - No es gracioso. Your he catches...,- Ale twoje mina była.
4,"Your also ¿, it is not like that?","- Tak, niezła jest"

In [7]:
df_2 = df[maska].reset_index(drop=True)
df_2.shape

(595405, 2)

#### 2.2 Polish Non-Ascii Sentences

In [8]:
pl_chars = set("ąęćłńóśźżĄĘĆŁŃÓŚŹŻ")
requir = lambda let: not let.isascii() and let not in pl_chars
maska = df_2['pol_text'].apply(lambda snt: any([requir(let) for let in snt]))
df_non_ascii = df_2[maska].copy().reset_index(drop=True)
print(df_non_ascii.shape)
df_non_ascii.sample(10)

(1227, 2)

,eng_text,pol_text
701,Your friend Mr Lincoln had his Taylors and Pai...,"Twój przyjaciel, pan Lincoln, tež mial swoich ..."
453,Big as life. Sparkling away under the old sun.,"Naturalnej wielkošci, polyskujaca w sloncu."
287,- It's nothing at all.,– Niezupełnie.
944,My Fuhrer!,Meine führer!
1220,Hotel de Paris.,W Hôtel de Paris.
525,Finally they think it's quite a bill.,"Wreszcie uznaja, že projekt jest šwietny."
410,"Some wealthy, influential citizen merely to cu...","Jakiemuš wplywowemu bogaczowi, by kupic jego l..."
550,Much better.,Dužo lepiej.
91,So you still believe that you are sent by the ...,"Ci±gle wierzysz, jakoby posyłał cię Bóg?"
1088,Glad to see the skies of blue Have turned into...,"¶ Cieszę się, gdy widzę jak błekitne niebo ¶ Z..."

In [9]:
df_3 = df_2[~maska].reset_index(drop=True)
print(df_3.shape)
df_3.sample(5)

(594178, 2)

,eng_text,pol_text
271116,We're gonna give you $500.,Damy ci 500 dolarów.
79266,These are all friends.,Tu wszyscy są przyjaciółmi.
41221,What?,Co?
415021,"Come, Mr. Cameron. Take this man away!",Niech pan zabierze tego człowieka!
379609,"Oh, yes, London.","Ach tak, Londyn."

In [10]:
print(nonascii_list(df_3['eng_text'], False))
print(nonascii_list(df_3['pol_text'], True))

[]
[]

In [11]:
df_3.iloc[74182]['eng_text']

'The next time I...'

In [12]:
df_3.iloc[74182]['pol_text']

'Następnym razem...'

#### 2.3 Short Or Empty Examples

In [13]:
mask1 = df_3['eng_text'].str.len() >= 3
mask2 = df_3['pol_text'].str.len() >= 3

In [14]:
df_4 = df_3[mask1 & mask2].reset_index(drop=True)
df_4.head()

,eng_text,pol_text
0,"Previously on ""The Blacklist""...",/W poprzednich odcinkach: /
1,- You want to call your daddy?,- Chcesz zadzwonić do taty?
2,"- Yeah, I want to tell him I'm okay.","- Tak, powiem, że wszystko w porządku."
3,Okay.,Dobrze.
4,Lizzy... Be careful of your husband.,"Lizzy, uważaj na męża."

In [15]:
df_4.shape

(593894, 2)

#### 2.4 Dialog like sentences [starts with - ]

In [16]:
is_dialog = lambda snt: bool(re.match(r"^ *- *", snt))
mask = df_4['eng_text'].apply(is_dialog) | df_4['pol_text'].apply(is_dialog)
df_dialogs = df_4[mask].copy().reset_index(drop=True)
df_dialogs.head()

,eng_text,pol_text
0,- You want to call your daddy?,- Chcesz zadzwonić do taty?
1,"- Yeah, I want to tell him I'm okay.","- Tak, powiem, że wszystko w porządku."
2,- 45 seconds.,Szybciej! 45 sekund.
3,It's okay. It's okay. It's okay.,- Już dobrze.
4,It's okay. You're okay. You're okay.,- Odpoczywaj.

In [17]:
def fix_dialog(snt):
    return re.sub(r"^ *- *", "", snt)

df_4['eng_text'] = df_4['eng_text'].apply(fix_dialog).reset_index(drop=True)
df_4['pol_text'] = df_4['pol_text'].apply(fix_dialog).reset_index(drop=True)
df_4.sample(5)

,eng_text,pol_text
543540,You must have faith in him.,Musisz w nim pokładać wiarę.
336391,I do.,Tak.
549006,I'll pay Ivey back for this if it's the last t...,Odpłacę Ivey'emu.
226664,Why not?,Czemu nie.
74830,"If I' m not mistaken, that's blood.","Jeśli się nie mylę, to jest krew."

#### 2.5 Broken Dialog like sentences [somehwere has -]

# Do naprawy (lepszy re przed tokenziacja)

In [18]:
broken_dialog = lambda snt: bool(re.match(r".* +- +.*", snt))
mask1 = df_4['eng_text'].apply(broken_dialog)
mask2 = df_4['pol_text'].apply(broken_dialog)

In [19]:
df_4[mask1 | mask2].sample(5)

,eng_text,pol_text
433552,A special brand? - Yes.,Wykonane na zamówienie?
285113,"Well, I did catch a glimpse of her some time ago.",Ujrzałem ją przez moment jakiś czas temu. - I...
439588,I wonder if we could tell him that... - That i...,"Mogę powiedzieć że nie powiodło się, i nie dzi..."
503723,And I've got to be this way just once to fix i...,Popełniłam w życiu wielki błąd i muszę to zrob...
113700,You're smart enough to hide that note.,"Czego chcesz? - Jesteś sprytna, ukryłaś banknot."

In [20]:
df_5 = df_4[~mask1 & ~mask2].reset_index(drop=True)

In [21]:
broken_dialog = lambda snt: bool(re.match(r".*-.*", snt))

In [22]:
df_5.sample(5)

,eng_text,pol_text
552966,Willie Garzah.,Willie Garzah.
513234,"Oh, maybe.",Może.
175889,It wouldn't be considered good manners to take...,"Uznano by za niestosowne pragnąć kobiety, któr..."
105915,I was told beware my wedding night.,Ostrzegano mnie przed dniem mego ślubu..
322414,He told me Whitey was dead before he took me h...,"Powiedział mi, że Whitey nie żyje jeszcze zani..."

#### 2.6 Different Last Case

In [23]:
mask = df_5['eng_text'].str[-1] != df_5['pol_text'].str[-1]
mask.sum()

57558

In [24]:
df_6 = df_5[~mask].reset_index(drop=True)

#### 2.7 Text length difference

In [25]:
mask = df_6['eng_text'].str.split
df_6['len_ratio'] = df_6['eng_text'].str.split().str.len() / df_6['pol_text'].str.split().str.len()
df_6.head()

,eng_text,pol_text,len_ratio
0,You want to call your daddy?,Chcesz zadzwonić do taty?,1.500000
1,"Yeah, I want to tell him I'm okay.","Tak, powiem, że wszystko w porządku.",1.333333
2,Okay.,Dobrze.,1.000000
3,Lizzy... Be careful of your husband.,"Lizzy, uważaj na męża.",1.500000
4,I can only lead you to the truth.,/Mogę naprowadzić cię na prawdę.,1.600000

In [26]:
thres_left = df_6["len_ratio"].quantile(0.05)
thres_right = df_6["len_ratio"].quantile(0.95)
thres_left, thres_right

(0.75, 2.5)

In [27]:
mask = (df_6["len_ratio"] >= thres_left) & (df_6["len_ratio"] <= thres_right)
mask.sum()

472209

In [28]:
df_7 = df_6[mask].reset_index(drop=True)
df_7.sample(5)

,eng_text,pol_text,len_ratio
120221,"If you're not shot by the time you're 50, you ...","Jeśli nie zginiesz przed piećdziesiatką, skońc...",1.666667
21732,I shouldn't like that.,Nie powinnam była tego mówić.,0.800000
408066,"Oh, sure.",Jasne.,2.000000
304036,Just level off and head straight for home.,Wyrównaj poziom i leć prosto do domu.,1.142857
349903,"It's been such fun, Jim. Yes.","To była świetna zabawa, Jim.",1.200000

In [29]:
df_7.sample(5)

,eng_text,pol_text,len_ratio
252661,Roy?,Roy?,1.0
330928,At least I think so.,"Ja jestem pewien, że tak.",1.0
147819,He doesn't look like a criminal.,Nie wygląda na przestępcę.,1.5
464938,Any kind...,Obojętnie...,2.0
235062,"Oh, uh...hello.",Cześć.,2.0

#### 2.8 Sentences starting with * fix

In [30]:
fix_star = lambda snt: re.sub(r"^ *[*].*", "", snt)
df_7['eng_text'] = df_7['eng_text'].apply(fix_star)
df_7['pol_text'] = df_7['pol_text'].apply(fix_star)

#### 2.9 Action Comments

In [31]:
def mask_distinct(df, col1, col2, chars):
    chars_escaped = "".join(re.escape(c) for c in chars)
    templ = f"[{chars_escaped}]"

    m1 = df[col1].str.contains(templ, regex=True, na=False)
    m2 = df[col2].str.contains(templ, regex=True, na=False)

    return m1 ^ m2

chars = '[]()/\*+#$"️'
mask = mask_distinct(df_7, "eng_text", "pol_text", chars)

df_8 = df_7[~mask].reset_index(drop=True)
df_8.shape

(467550, 3)

In [32]:
df_8.sample(5)

,eng_text,pol_text,len_ratio
321923,"Doctor, Teddy, signature...","Lekarz, Teddy, podpis...",1.000000
267632,"Who, from this hour forth, can ask anything in...","Który od tej pory może prosić o wszystko, co w...",1.083333
343646,What about your passengers?,A co z pasażerami?,1.000000
317472,She is difficult.,Jest trudna.,1.500000
258187,He's getting more like his father every day.,Coraz bardziej przypomina ojca.,2.000000

#### 2.10  " ` " ---> " ' " & del " ~ "

In [33]:
wanted_case = '`'
mask = df_8["eng_text"].apply(lambda x: wanted_case in x)
df_8[mask]

,eng_text,pol_text,len_ratio
214145,"Revolution had broken out, her diplomats sued ...","Rewolucja na tyłach frontu, dąży do zawarcia p...",1.277778
214152,We`ll examine it.,Zbadajmy go.,1.500000
214157,What do you think you`re doing?,Wstawaj! Co ty robisz?,1.500000
214161,Where`s your hand grenade?,Gdzie masz swój granat?,1.000000
214163,Let `em have it!,Niech je poczują!,1.333333
...,...,...,...
214943,We don`t want to hate one another.,Bez nienawiści ani pogardy.,1.750000
214944,There`s room for everyone.,Każdy ma swe miejsce.,1.000000
214947,"Greed has poisoned men`s souls, has barricaded...","Chciwość zatruła nasze dusze, wzniosła mury ni...",1.333333
214963,You don`t hate.,Przestańcie nienawidzieć.,1.500000
214965,"Soldiers, don`t fight for slavery, fight for l...","Nie walczcie o niewolę, lecz o wolność!",1.142857

In [34]:
df_8["eng_text"] = df_8["eng_text"].str.replace("`", "'", regex=False)
df_8["pol_text"] = df_8["pol_text"].str.replace("`", "'", regex=False)

In [35]:
df_8["eng_text"] = df_8["eng_text"].str.replace("~", "", regex=False)
df_8["pol_text"] = df_8["pol_text"].str.replace("~", "", regex=False)

#### 2.11 Del rows with specific case

In [36]:
def del_row_with_char(df, eng_col, pol_col, chars):
    df_proc = df.copy()
    for char in chars:
        mask1 = df_proc[eng_col].apply(lambda x: char in x)
        mask2 = df_proc[pol_col].apply(lambda x: char in x)
        df_proc = df_proc[~(mask1 | mask2)].reset_index(drop=True)
    return df_proc
    

chars = "=+*@#;|_}{"
df_9 = del_row_with_char(df_8, "eng_text", "pol_text", chars)

#### 2.12 Del rows with dialog -

In [37]:
mask1 = df_9["eng_text"].apply(lambda x: bool(re.search(r' +-[^ ]+', x)))
mask2 = df_9["pol_text"].apply(lambda x: bool(re.search(r' +-[^ ]+', x)))
df_data = df_9[~(mask1 | mask2)].reset_index(drop=True)

#### 3. Data Tokenization

In [38]:
uniq_cases = set("".join(df_data["eng_text"].astype(str)))
tab1 = sorted(list(uniq_cases), reverse=True)
print(tab1)

['z', 'y', 'x', 'w', 'v', 'u', 't', 's', 'r', 'q', 'p', 'o', 'n', 'm', 'l', 'k', 'j', 'i', 'h', 'g', 'f', 'e', 'd', 'c', 'b', 'a', ']', '[', 'Z', 'Y', 'X', 'W', 'V', 'U', 'T', 'S', 'R', 'Q', 'P', 'O', 'N', 'M', 'L', 'K', 'J', 'I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'A', '?', ':', '9', '8', '7', '6', '5', '4', '3', '2', '1', '0', '/', '.', '-', ',', ')', '(', "'", '%', '$', '"', '!', ' ']

In [39]:
uniq_cases = set("".join(df_data["pol_text"].astype(str)))
tab2 = sorted(list(uniq_cases), reverse=True)
print(tab2)

['ż', 'Ż', 'ź', 'Ź', 'ś', 'Ś', 'ń', 'Ń', 'ł', 'Ł', 'ę', 'Ę', 'ć', 'Ć', 'ą', 'Ą', 'ó', 'Ó', 'z', 'y', 'x', 'w', 'v', 'u', 't', 's', 'r', 'q', 'p', 'o', 'n', 'm', 'l', 'k', 'j', 'i', 'h', 'g', 'f', 'e', 'd', 'c', 'b', 'a', ']', '[', 'Z', 'Y', 'X', 'W', 'V', 'U', 'T', 'S', 'R', 'Q', 'P', 'O', 'N', 'M', 'L', 'K', 'J', 'I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'A', '?', ':', '9', '8', '7', '6', '5', '4', '3', '2', '1', '0', '/', '.', '-', ',', ')', '(', "'", '%', '$', '"', '!', ' ']

In [40]:
def tokenize_eng(snt):
    snt = snt.lower()
    snt = re.sub("(?<! )'(?! )", r" '", snt)
    snt = re.sub(r"""([\]?:)\[(/\.\-,%\$"!])""", r" \1 ", snt)
    snt = re.sub(r"\s+", " ", snt).strip()
    return re.split(r'\s+', snt.strip())

In [41]:
def tokenize_pol(snt):
    snt = snt.lower()
    snt = re.sub(r"""([\]?:)\[(/\.\-,%\$"!])""", r" \1 ", snt)
    snt = re.sub(r"\s+", " ", snt).strip()
    return re.split(r'\s+', snt.strip())

In [42]:
df_data = df_data.drop(['len_ratio'], axis=1)

#### 3.1 Splitting and trimming on quantile

In [43]:
df_data['eng_split'] = df_data['eng_text'].apply(tokenize_eng)
df_data['pol_split'] = df_data['pol_text'].apply(tokenize_pol)
df_data.sample(10)

,eng_text,pol_text,eng_split,pol_split
207261,"The hot-tempered young fool must carry a gun, ...","Ten młody wariat chce nosić broń, bo w okolicy...","[the, hot, -, tempered, young, fool, must, car...","[ten, młody, wariat, chce, nosić, broń, ,, bo,..."
4263,"""Bare your body, Brother!""","""Obnaż swoje ciało, bracie!""","["", bare, your, body, ,, brother, !, ""]","["", obnaż, swoje, ciało, ,, bracie, !, ""]"
432673,Mr. Gagin!,Panie Gagin!,"[mr, ., gagin, !]","[panie, gagin, !]"
34104,"Say, you want to draw another paycheck, don't ...","Chcesz dostać kolejną wypłatę, prawda?","[say, ,, you, want, to, draw, another, paychec...","[chcesz, dostać, kolejną, wypłatę, ,, prawda, ?]"
45450,"A, I got A.",Dostałem piątkę.,"[a, ,, i, got, a, .]","[dostałem, piątkę, .]"
335069,Really?,Naprawdę?,"[really, ?]","[naprawdę, ?]"
399162,Do I know you?,Znam pana?,"[do, i, know, you, ?]","[znam, pana, ?]"
267746,Bambi!,Bambi!,"[bambi, !]","[bambi, !]"
60068,As my own child.,Jak na swoje własne dziecko.,"[as, my, own, child, .]","[jak, na, swoje, własne, dziecko, .]"
209403,I've got it.,Są. Będą na pewno.,"[i, 've, got, it, .]","[są, ., będą, na, pewno, .]"

In [44]:
thres1 = df_data['eng_split'].str.len().quantile(0.99)
mask1 = df_data['eng_split'].str.len() > thres1

thres2 = df_data['pol_split'].str.len().quantile(0.99)
mask2 = df_data['pol_split'].str.len() > thres2
print(mask1.sum(), mask2.sum(), (mask1 | mask2).sum())

df_data = df_data[~(mask1 | mask2)].reset_index(drop=True)

4113 3960 5510

#### 3.2 BPE Init. Uniq_freq & Rozklad chars

In [45]:
uniq_freq_eng = Counter(df_data['eng_split'].explode())
uniq_freq_pol = Counter(df_data['pol_split'].explode())

In [46]:
len(uniq_freq_eng), len(uniq_freq_pol)

(40087, 113603)

In [455]:
char_factor = lambda word: [x for x in word] + ['</w>']
vocab_chars_eng = [[char_factor(k), v] for k, v in uniq_freq_eng.most_common()]
vocab_chars_pol = [[char_factor(k), v] for k, v in uniq_freq_pol.most_common()]
print(len(vocab_chars_eng), vocab_chars_eng[:5], '\n')
print(len(vocab_chars_pol), vocab_chars_pol[:5])

40087 [[['.', '</w>'], 435802], [[',', '</w>'], 177291], [['y', 'o', 'u', '</w>'], 134548], [['i', '</w>'], 122767], [['t', 'h', 'e', '</w>'], 89859]]

113603 [[['.', '</w>'], 413780], [[',', '</w>'], 183948], [['?', '</w>'], 83444], [['n', 'i', 'e', '</w>'], 82694], [['t', 'o', '</w>'], 53190]]

#### 3.3 BPE Tokenizer most common pairs

In [450]:
# class BPETokenizer():
#     def __init__(self, vocab_chrs, vocab_size, is_tgt):
#         self.vocab_chrs = vocab_chrs
#         self.vocab_size = vocab_size
#         self.vocab = self.vocab_init(vocab_chrs, is_tgt)
#         self.base_size = len(self.vocab)

#     def vocab_init(self, vocab_chrs, is_tgt):
#         vocab = {'<pad>': 0, '<unk>': 1, '<eos>': 2, '</w>': 3}
#         if is_tgt:
#             vocab['<bos>'] = 4
            
#         uniq_toks = {tok for toks, _ in vocab_chrs for tok in toks}
#         uniq_toks.remove('</w>')
#         for i, tok in enumerate(uniq_toks, len(vocab)):
#             vocab[tok] = i
#         return vocab                

#     def train_bpe(self):
#         for i in range(self.base_size, self.vocab_size):
#             pair = self.most_common_pair()
#             self.vocab[pair] = i
#             pair_con = re.sub('\s+', '', pair)
#             self.replace_pairs(pair, pair_con)

#     def most_common_pair(self):
#         pair_counts = Counter()
#         for toks, freq in self.vocab_chrs:
#             for pair in map(' '.join, zip(toks, toks[1:])):
#                 pair_counts[pair] += freq
#         return pair_counts.most_common(1)[0][0]

#     def replace_pairs(self, pair, pair_con):
#         for i, (toks, _) in enumerate(self.vocab_chrs):
#             self.vocab_chrs[i][0] = ' '.join(toks).replace(pair, pair_con).split()

In [454]:
class BPETokenizer():
    def __init__(self, vocab_chrs, vocab_size, is_tgt):
        self.vocab_chrs = vocab_chrs
        self.vocab_size = vocab_size
        self.vocab = self.vocab_init(vocab_chrs, is_tgt)
        self.base_size = len(self.vocab)

    def vocab_init(self, vocab_chrs, is_tgt):
        vocab = {'<pad>': 0, '<unk>': 1, '<eos>': 2, '</w>': 3}
        if is_tgt:
            vocab['<bos>'] = 4
            
        uniq_toks = {tok for toks, _ in vocab_chrs for tok in toks}
        uniq_toks.remove('</w>')
        for i, tok in enumerate(uniq_toks, len(vocab)):
            vocab[tok] = i
        return vocab                

    def train_bpe(self):
        for i in range(self.base_size, self.vocab_size):
            pair = self.most_common_pair()
            pair_spc, pair_con = ' '.join(pair), ''.join(pair)
            self.vocab[pair_spc] = i
            self.replace_pairs(pair, pair_spc, pair_con)

    def most_common_pair(self):
        pair_counts = defaultdict(int)
        for toks, freq in self.vocab_chrs:
            for pair in zip(toks, toks[1:]):
                pair_counts[pair] += freq
        return max(pair_counts, key=pair_counts.get)

    def replace_pairs(self, pair, pair_spc, pair_con):
        for i, (toks, _) in enumerate(self.vocab_chrs):
            if pair in zip(toks, toks[1:]):
                self.vocab_chrs[i][0] = ' '.join(toks).replace(pair_spc, pair_con).split()

In [456]:
tokenizer_eng = BPETokenizer(vocab_chars_eng, 8000, False)
t = time.time()
tokenizer_eng.train_bpe()
print(f"{time.time()-t:.2f} seconds")

498.02 seconds

In [461]:
tab = ['a', 'b', 'r', 'a', 'c', 'a', 'd', 'a', 'br', 'a', '</w>']
print(list(zip(tab, tab[1:])))
if ('a', 'b') in zip(tab, tab[1:]):
    print(' '.join(tab).replace('a b', 'ab').split())

[('a', 'b'), ('b', 'r'), ('r', 'a'), ('a', 'c'), ('c', 'a'), ('a', 'd'), ('d', 'a'), ('a', 'br'), ('br', 'a'), ('a', '</w>')]
['ab', 'r', 'a', 'c', 'a', 'd', 'abr', 'a', '</w>']

In [471]:
tab2 = list(zip(tab, tab[1:]))
print(tab2)

[('a', 'b'), ('b', 'r'), ('r', 'a'), ('a', 'c'), ('c', 'a'), ('a', 'd'), ('d', 'a'), ('a', 'br'), ('br', 'a'), ('a', '</w>')]

## edytuj liste z tuplami i trzymaj tupla w slowniku

In [472]:
tab2.index(('a', 'b'))

0

In [458]:
[[char_factor(k), v] for k, v in uniq_freq_eng.most_common()]

[[['.', '</w>'], 435802],
 [[',', '</w>'], 177291],
 [['y', 'o', 'u', '</w>'], 134548],
 [['i', '</w>'], 122767],
 [['t', 'h', 'e', '</w>'], 89859],
 [['?', '</w>'], 84640],
 [['t', 'o', '</w>'], 73192],
 [['a', '</w>'], 61661],
 [["'", 's', '</w>'], 57045],
 [['i', 't', '</w>'], 55074],
 [["'", 't', '</w>'], 50411],
 [['t', 'h', 'a', 't', '</w>'], 43020],
 [['a', 'n', 'd', '</w>'], 41124],
 [['o', 'f', '</w>'], 39514],
 [['i', 'n', '</w>'], 32142],
 [['!', '</w>'], 30794],
 [['m', 'e', '</w>'], 29977],
 [['w', 'h', 'a', 't', '</w>'], 26868],
 [['i', 's', '</w>'], 26378],
 [['h', 'e', '</w>'], 26149],
 [['f', 'o', 'r', '</w>'], 23935],
 [['w', 'e', '</w>'], 23370],
 [['t', 'h', 'i', 's', '</w>'], 20366],
 [['y', 'o', 'u', 'r', '</w>'], 20158],
 [['b', 'e', '</w>'], 20137],
 [['m', 'y', '</w>'], 20105],
 [["'", 'l', 'l', '</w>'], 20011],
 [['h', 'a', 'v', 'e', '</w>'], 19830],
 [['d', 'o', 'n', '</w>'], 18888],
 [['d', 'o', '</w>'], 18663],
 [['o', 'n', '</w>'], 18052],
 [['n', 'o', '</w>'], 17694],
 [["'", 'm', '</w>'], 16935],
 [['a', 'l', 'l', '</w>'], 16776],
 [['b', 'u', 't', '</w>'], 16067],
 [['w', 'a', 's', '</w>'], 15781],
 [["'", 'r', 'e', '</w>'], 15483],
 [['w', 'i', 't', 'h', '</w>'], 15435],
 [['c', 'a', 'n', '</w>'], 15365],
 [['h', 'e', 'r', 'e', '</w>'], 15059],
 [['n', 'o', 't', '</w>'], 14896],
 [['a', 'r', 'e', '</w>'], 14431],
 [['k', 'n', 'o', 'w', '</w>'], 14310],
 [['t', 'h', 'e', 'r', 'e', '</w>'], 14310],
 [['h', 'i', 'm', '</w>'], 14193],
 [['g', 'e', 't', '</w>'], 13469],
 [['i', 'f', '</w>'], 12400],
 [['w', 'e', 'l', 'l', '</w>'], 12155],
 [['t', 'h', 'e', 'y', '</w>'], 11807],
 [['n', 'o', 'w', '</w>'], 11736],
 [["'", 'v', 'e', '</w>'], 11579],
 [['l', 'i', 'k', 'e', '</w>'], 11372],
 [['y', 'e', 's', '</w>'], 10842],
 [['o', 'u', 't', '</w>'], 10839],
 [['s', 'h', 'e', '</w>'], 10741],
 [['c', 'o', 'm', 'e', '</w>'], 10653],
 [['g', 'o', '</w>'], 10570],
 [['r', 'i', 'g', 'h', 't', '</w>'], 10414],
 [['s', 'o', '</w>'], 10352],
 [['a', 'b', 'o', 'u', 't', '</w>'], 10349],
 [['a', 't', '</w>'], 10100],
 [['u', 'p', '</w>'], 9851],
 [['o', 'h', '</w>'], 9750],
 [['w', 'i', 'l', 'l', '</w>'], 9685],
 [['j', 'u', 's', 't', '</w>'], 9650],
 [['s', 'e', 'e', '</w>'], 9619],
 [['g', 'o', 'o', 'd', '</w>'], 9404],
 [['h', 'e', 'r', '</w>'], 9170],
 [['a', 's', '</w>'], 9044],
 [['"', '</w>'], 8870],
 [['o', 'n', 'e', '</w>'], 8831],
 [['g', 'o', 't', '</w>'], 8827],
 [['h', 'o', 'w', '</w>'], 8698],
 [["'", 'd', '</w>'], 7878],
 [['-', '</w>'], 7821],
 [['w', 'a', 'n', 't', '</w>'], 7783],
 [['t', 'h', 'i', 'n', 'k', '</w>'], 7743],
 [['w', 'h', 'y', '</w>'], 7726],
 [['h', 'i', 's', '</w>'], 7396],
 [['m', 'r', '</w>'], 7390],
 [['g', 'o', 'i', 'n', 'g', '</w>'], 7023],
 [['d', 'i', 'd', '</w>'], 6784],
 [['t', 'a', 'k', 'e', '</w>'], 6657],
 [['t', 'h', 'e', 'm', '</w>'], 6612],
 [['b', 'e', 'e', 'n', '</w>'], 6579],
 [['w', 'h', 'e', 'n', '</w>'], 6444],
 [['f', 'r', 'o', 'm', '</w>'], 6437],
 [['l', 'e', 't', '</w>'], 6379],
 [['t', 'e', 'l', 'l', '</w>'], 6330],
 [['w', 'h', 'o', '</w>'], 6283],
 [['w', 'h', 'e', 'r', 'e', '</w>'], 6175],
 [['s', 'a', 'y', '</w>'], 6142],
 [['v', 'e', 'r', 'y', '</w>'], 5833],
 [['b', 'a', 'c', 'k', '</w>'], 5736],
 [['m', 'a', 'n', '</w>'], 5539],
 [['t', 'i', 'm', 'e', '</w>'], 5538],
 [['l', 'o', 'o', 'k', '</w>'], 5465],
 [['a', 'n', '</w>'], 5437],
 [['h', 'a', 'd', '</w>'], 5395],
 [['t', 'o', 'o', '</w>'], 5297],
 [['u', 's', '</w>'], 5228],
 [['w', 'o', 'u', 'l', 'd', '</w>'], 5165],
 [['n', 'e', 'v', 'e', 'r', '</w>'], 5037],
 [['d', 'i', 'd', 'n', '</w>'], 4959],
 [['w', 'e', 'r', 'e', '</w>'], 4912],
 [['s', 'i', 'r', '</w>'], 4907],
 [['l', 'i', 't', 't', 'l', 'e', '</w>'], 4764],
 [['w', 'a', 'y', '</w>'], 4572],
 [['o', 'r', '</w>'], 4571],
 [['t', 'h', 'e', 'n', '</w>'], 4556],
 [['s', 'o', 'm', 'e', '</w>'], 4544],
 [['d', 'o', 'w', 'n', '</w>'], 4510],
 [['m', 'u', 's', 't', '</w>'], 4353],
 [['a', 'n', 'y', '</w>'], 4343],
 [['m', 'a', 'k', 'e', '</w>'], 4312],
 [['o', 'n', 'l', 'y', '</w>'], 4213],
 [['c', 'o', 'u', 'l', 'd', '</w>'], 4125],
 [['m', 'o', 'r', 'e', '</w>'], 4078],
 [['b', 'y', '</w>'], 4064],
 [['h', 'a', 's', '</w>'], 4035],
 [['s', 'o', 'm', 'e', 't', 'h', 'i', 'n', 'g', '</w>'], 4018],
 [['t', 'h', 'a', 'n', 'k', '</w>'], 3991],
 [['o', 'u', 'r', '</w>'], 3987],
 [['o', 'v', 'e', 'r', '</w>'], 3933],
 [['g', 'i', 'v', 'e', '</w>'], 3923],
 [['w', 'o', 'n', '</w>'], 3826],
 [['m', 'u', 'c', 'h', '</w>'], 3806],
 [['s', 'u', 'r', 'e', '</w>'], 3682],
 [['p', 'l', 'e', 'a', 's', 'e', '</w>'], 3634],
 [['n', 'i', 'g', 'h', 't', '</w>'], 3541],
 [['b', 'e', 't', 't', 'e', 'r', '</w>'], 3447],
 [['y', 'e', 'a', 'h', '</w>'], 3404],
 [['n', 'o', 't', 'h', 'i', 'n', 'g', '</w>'], 3379],
 [['a', 'n', 'y', 't', 'h', 'i', 'n', 'g', '</w>'], 3219],
 [['a', 'w', 'a', 'y', '</w>'], 3136],
 [['t', 'w', 'o', '</w>'], 3114],
 [['m', 'e', 'a', 'n', '</w>'], 3060],
 [['o', 'l', 'd', '</w>'], 3053],
 [['o', 'f', 'f', '</w>'], 3035],
 [['l', 'o', 'v', 'e', '</w>'], 3028],
 [['h', 'e', 'l', 'l', 'o', '</w>'], 3018],
 [['a', 'm', '</w>'], 2934],
 [['m', 'i', 's', 's', '</w>'], 2929],
 [['b', 'e', 'f', 'o', 'r', 'e', '</w>'], 2916],
 [['s', 'a', 'i', 'd', '</w>'], 2882],
 [['a', 'g', 'a', 'i', 'n', '</w>'], 2882],
 [['f', 'i', 'n', 'd', '</w>'], 2839],
 [['s', 'h', 'o', 'u', 'l', 'd', '</w>'], 2800],
 [['l', 'o', 'n', 'g', '</w>'], 2767],
 [['i', 's', 'n', '</w>'], 2738],
 [['t', 'h', 'i', 'n', 'g', '</w>'], 2720],
 [['s', 'o', 'r', 'r', 'y', '</w>'], 2676],
 [['h', 'e', 'l', 'p', '</w>'], 2667],
 [['a', 'f', 't', 'e', 'r', '</w>'], 2623],
 [['t', 'h', 'o', 'u', 'g', 'h', 't', '</w>'], 2600],
 [['p', 'u', 't', '</w>'], 2573],
 [['h', 'o', 'm', 'e', '</w>'], 2550],
 [['t', 'h', 'a', 'n', '</w>'], 2528],
 [['e', 'v', 'e', 'r', '</w>'], 2525],
 [['f', 'i', 'r', 's', 't', '</w>'], 2521],
 [['p', 'e', 'o', 'p', 'l', 'e', '</w>'], 2514],
 [['f', 'a', 't', 'h', 'e', 'r', '</w>'], 2502],
 [['t', 'h', 'i', 'n', 'g', 's', '</w>'], 2447],
 [['a', 'l', 'w', 'a', 'y', 's', '</w>'], 2424],
 [['t', 'h', 'o', 's', 'e', '</w>'], 2422],
 [['m', 'a', 'y', 'b', 'e', '</w>'], 2417],
 [['d', 'a', 'y', '</w>'], 2410],
 [['k', 'e', 'e', 'p', '</w>'], 2393],
 [['t', 'a', 'l', 'k', '</w>'], 2389],
 [['i', 'n', 't', 'o', '</w>'], 2380],
 [['g', 'o', 'n', 'n', 'a', '</w>'], 2372],
 [['m', 'r', 's', '</w>'], 2366],
 [['t', 'o', 'l', 'd', '</w>'], 2360],
 [['w', 'a', 'i', 't', '</w>'], 2348],
 [['m', 'i', 'n', 'd', '</w>'], 2339],
 [['a', 'i', 'n', '</w>'], 2336],
 [['b', 'e', 'c', 'a', 'u', 's', 'e', '</w>'], 2327],
 [['l', 'a', 's', 't', '</w>'], 2314],
 [['m', 'a', 'y', '</w>'], 2299],
 [['l', 'e', 'a', 'v', 'e', '</w>'], 2297],
 [['t', 'h', 'e', 's', 'e', '</w>'], 2289],
 [['o', 't', 'h', 'e', 'r', '</w>'], 2277],
 [['d', 'e', 'a', 'r', '</w>'], 2255],
 [['a', 'r', 'o', 'u', 'n', 'd', '</w>'], 2245],
 [['l', 'i', 'f', 'e', '</w>'], 2245],
 [['e', 'v', 'e', 'n', '</w>'], 2242],
 [['c', 'o', 'u', 'r', 's', 'e', '</w>'], 2213],
 [['m', 'o', 'n', 'e', 'y', '</w>'], 2207],
 [['w', 'o', 'u', 'l', 'd', 'n', '</w>'], 2160],
 [['n', 'e', 'w', '</w>'], 2154],
 [['m', 'o', 'r', 'n', 'i', 'n', 'g', '</w>'], 2147],
 [['r', 'e', 'a', 'l', 'l', 'y', '</w>'], 2098],
 [['n', 'a', 'm', 'e', '</w>'], 2067],
 [['n', 'i', 'c', 'e', '</w>'], 2061],
 [['m', 'a', 't', 't', 'e', 'r', '</w>'], 2051],
 [['e', 'v', 'e', 'r', 'y', 't', 'h', 'i', 'n', 'g', '</w>'], 2034],
 [['m', 'i', 'g', 'h', 't', '</w>'], 2030],
 [['w', 'o', 'r', 'k', '</w>'], 2029],
 [['h', 'a', 'v', 'e', 'n', '</w>'], 2015],
 [['s', 't', 'i', 'l', 'l', '</w>'], 2010],
 [[':', '</w>'], 1991],
 [['e', 'n', 'o', 'u', 'g', 'h', '</w>'], 1989],
 [['p', 'l', 'a', 'c', 'e', '</w>'], 1966],
 [['g', 'i', 'r', 'l', '</w>'], 1956],
 [['m', 'e', 'n', '</w>'], 1953],
 [['d', 'o', 'i', 'n', 'g', '</w>'], 1934],
 [['d', 'o', 'e', 's', '</w>'], 1933],
 [['c', 'a', 'l', 'l', '</w>'], 1911],
 [['t', 'h', 'a', 'n', 'k', 's', '</w>'], 1896],
 [['h', 'e', 'y', '</w>'], 1882],
 [['n', 'e', 'e', 'd', '</w>'], 1876],
 [['s', 't', 'a', 'y', '</w>'], 1861],
 [['s', 't', 'o', 'p', '</w>'], 1823],
 [['h', 'o', 'u', 's', 'e', '</w>'], 1787],
 [['c', 'a', 'm', 'e', '</w>'], 1777],
 [['r', 'e', 'm', 'e', 'm', 'b', 'e', 'r', '</w>'], 1771],
 [['y', 'e', 'a', 'r', 's', '</w>'], 1757],
 [['a', 's', 'k', '</w>'], 1757],
 [['a', 'n', 'o', 't', 'h', 'e', 'r', '</w>'], 1757],
 [['r', 'o', 'o', 'm', '</w>'], 1751],
 [['h', 'e', 'a', 'r', '</w>'], 1737],
 [['y', 'o', 'u', 'r', 's', 'e', 'l', 'f', '</w>'], 1734],
 [['t', 'h', 'r', 'o', 'u', 'g', 'h', '</w>'], 1734],
 [['b', 'o', 'y', '</w>'], 1733],
 [['a', 'f', 'r', 'a', 'i', 'd', '</w>'], 1721],
 [['d', 'o', 'e', 's', 'n', '</w>'], 1714],
 [['u', 'n', 'd', 'e', 'r', 's', 't', 'a', 'n', 'd', '</w>'], 1690],
 [['m', 'a', 'd', 'e', '</w>'], 1681],
 [['d', 'o', 'n', 'e', '</w>'], 1673],
 [['t', 'h', 'e', 'i', 'r', '</w>'], 1670],
 [['b', 'i', 'g', '</w>'], 1668],
 [['c', 'o', 'm', 'i', 'n', 'g', '</w>'], 1659],
 [['b', 'e', 'l', 'i', 'e', 'v', 'e', '</w>'], 1656],
 [['g', 'r', 'e', 'a', 't', '</w>'], 1653],
 [['m', 'o', 't', 'h', 'e', 'r', '</w>'], 1653],
 [['l', 'e', 'f', 't', '</w>'], 1651],
 [['f', 'e', 'e', 'l', '</w>'], 1647],
 [['t', 'o', 'n', 'i', 'g', 'h', 't', '</w>'], 1646],
 [['e', 'v', 'e', 'r', 'y', '</w>'], 1620],
 [['c', 'o', 'u', 'l', 'd', 'n', '</w>'], 1609],
 [['s', 'h', 'a', 'l', 'l', '</w>'], 1607],
 [['b', 'a', 'd', '</w>'], 1605],
 [['k', 'i', 'n', 'd', '</w>'], 1582],
 [['o', 'w', 'n', '</w>'], 1565],
 [['t', 'h', 'r', 'e', 'e', '</w>'], 1553],
 [['w', 'o', 'm', 'a', 'n', '</w>'], 1527],
 [['c', 'a', 'r', 'e', '</w>'], 1511],
 [['d', 'a', 'r', 'l', 'i', 'n', 'g', '</w>'], 1498],
 [['l', 'i', 's', 't', 'e', 'n', '</w>'], 1496],
 [['d', 'o', 'c', 't', 'o', 'r', '</w>'], 1493],
 [['w', 'a', 'n', 't', 'e', 'd', '</w>'], 1492],
 [['m', 'y', 's', 'e', 'l', 'f', '</w>'], 1484],
 [['f', 'r', 'i', 'e', 'n', 'd', '</w>'], 1474],
 [['l', 'o', 't', '</w>'], 1456],
 [['s', 'e', 'e', 'n', '</w>'], 1455],
 [['o', 'n', 'c', 'e', '</w>'], 1446],
 [['m', 'i', 'n', 'u', 't', 'e', '</w>'], 1438],
 [['e', 'l', 's', 'e', '</w>'], 1430],
 [['w', 'o', 'r', 'l', 'd', '</w>'], 1412],
 [['b', 'u', 's', 'i', 'n', 'e', 's', 's', '</w>'], 1411],
 [['h', 'e', 'a', 'r', 'd', '</w>'], 1410],
 [['s', 'u', 'c', 'h', '</w>'], 1395],
 [['f', 'i', 'n', 'e', '</w>'], 1394],
 [['t', 'o', 'm', 'o', 'r', 'r', 'o', 'w', '</w>'], 1389],
 [['p', 'r', 'e', 't', 't', 'y', '</w>'], 1388],
 [['d', 'r', '</w>'], 1385],
 [['s', 'i', 't', '</w>'], 1383],
 [['s', 'h', 'o', 'w', '</w>'], 1372],
 [['l', 'a', 'd', 'y', '</w>'], 1363],
 [['w', 'i', 'f', 'e', '</w>'], 1361],
 [['t', 'r', 'y', '</w>'], 1354],
 [['a', 'l', 'o', 'n', 'e', '</w>'], 1343],
 [['q', 'u', 'i', 't', 'e', '</w>'], 1341],
 [['h', 'o', 'p', 'e', '</w>'], 1335],
 [['y', 'o', 'u', 'n', 'g', '</w>'], 1328],
 [['b', 'r', 'i', 'n', 'g', '</w>'], 1313],
 [['d', 'e', 'a', 'd', '</w>'], 1312],
 [['w', 'a', 's', 'n', '</w>'], 1303],
 [['k', 'n', 'e', 'w', '</w>'], 1299],
 [['y', 'e', 't', '</w>'], 1295],
 [['w', 'i', 't', 'h', 'o', 'u', 't', '</w>'], 1287],
 [['g', 'u', 'e', 's', 's', '</w>'], 1284],
 [['s', 'a', 'm', 'e', '</w>'], 1282],
 [['b', 'e', 'i', 'n', 'g', '</w>'], 1270],
 [['g', 'e', 't', 't', 'i', 'n', 'g', '</w>'], 1264],
 [['i', 'd', 'e', 'a', '</w>'], 1260],
 [['l', 'i', 'v', 'e', '</w>'], 1252],
 [['l', 'o', 'o', 'k', 'i', 'n', 'g', '</w>'], 1236],
 [['w', 'r', 'o', 'n', 'g', '</w>'], 1236],
 [['s', 'u', 'p', 'p', 'o', 's', 'e', '</w>'], 1234],
 [['w', 'i', 's', 'h', '</w>'], 1231],
 [['h', 'a', 'p', 'p', 'e', 'n', 'e', 'd', '</w>'], 1229],
 [['w', 'h', 'i', 'l', 'e', '</w>'], 1227],
 [['h', 'a', 'p', 'p', 'y', '</w>'], 1224],
 [['s', 'a', 'w', '</w>'], 1218],
 [['b', 'o', 'y', 's', '</w>'], 1213],
 [['a', 'l', 'o', 'n', 'g', '</w>'], 1201],
 [['m', 'o', 's', 't', '</w>'], 1192],
 [['w', 'e', 'n', 't', '</w>'], 1188],
 [['s', 'o', 'o', 'n', '</w>'], 1187],
 [['d', 'r', 'i', 'n', 'k', '</w>'], 1172],
 [['f', 'o', 'u', 'n', 'd', '</w>'], 1165],
 [['g', 'u', 'y', '</w>'], 1156],
 [['t', 'r', 'o', 'u', 'b', 'l', 'e', '</w>'], 1153],
 [['n', 'e', 'x', 't', '</w>'], 1141],
 [['g', 'o', 'n', 'e', '</w>'], 1138],
 [['b', 'e', 's', 't', '</w>'], 1125],
 [['u', 'h', '</w>'], 1121],
 [['u', 'n', 't', 'i', 'l', '</w>'], 1115],
 [['g', 'e', 'n', 't', 'l', 'e', 'm', 'e', 'n', '</w>'], 1115],
 [['t', 'o', 'w', 'n', '</w>'], 1112],
 [['h', 'e', 'a', 'd', '</w>'], 1109],
 [['d', 'a', 'y', 's', '</w>'], 1107],
 [['s', 'i', 'n', 'c', 'e', '</w>'], 1104],
 [['f', 'e', 'w', '</w>'], 1104],
 [['g', 'l', 'a', 'd', '</w>'], 1102],
 [['t', 'o', 'd', 'a', 'y', '</w>'], 1097],
 [['j', 'o', 'b', '</w>'], 1096],
 [['m', 'a', 'n', 'y', '</w>'], 1095],
 [['m', 'a', 'r', 'r', 'i', 'e', 'd', '</w>'], 1092],
 [['r', 'e', 'a', 'd', 'y', '</w>'], 1087],
 [['w', 'h', 'o', 'l', 'e', '</w>'], 1083],
 [['t', 'r', 'y', 'i', 'n', 'g', '</w>'], 1077],
 [['h', 'o', 'l', 'd', '</w>'], 1076],
 [['t', 'a', 'l', 'k', 'i', 'n', 'g', '</w>'], 1070],
 [['r', 'u', 'n', '</w>'], 1068],
 [['f', 'o', 'r', 'g', 'e', 't', '</w>'], 1041],
 [['p', 'e', 'r', 'h', 'a', 'p', 's', '</w>'], 1038],
 [['h', 'a', 'n', 'd', '</w>'], 1033],
 [['w', 'a', 'i', 't', 'i', 'n', 'g', '</w>'], 1030],
 [['u', 's', 'e', '</w>'], 1029],
 [['s', 't', 'a', 'n', 'd', '</w>'], 1023],
 [['c', 'a', 'p', 't', 'a', 'i', 'n', '</w>'], 1019],
 [['s', 'a', 'y', 's', '</w>'], 1018],
 [['m', 'i', 'n', 'e', '</w>'], 1016],
 [['k', 'i', 'l', 'l', '</w>'], 996],
 [['w', 'h', 'i', 'c', 'h', '</w>'], 994],
 [['o', 'k', 'a', 'y', '</w>'], 993],
 [['m', 'e', 'e', 't', '</w>'], 992],
 [['e', 'v', 'e', 'n', 'i', 'n', 'g', '</w>'], 984],
 [['o', 'p', 'e', 'n', '</w>'], 981],
 [['u', 's', 'e', 'd', '</w>'], 973],
 [['t', 'o', 'g', 'e', 't', 'h', 'e', 'r', '</w>'], 968],
 [['h', 'u', 'h', '</w>'], 967],
 [['w', 'a', 'n', 't', 's', '</w>'], 963],
 [['p', 'l', 'a', 'y', '</w>'], 961],
 [['a', 'g', 'o', '</w>'], 957],
 [['s', 'o', 'm', 'e', 'b', 'o', 'd', 'y', '</w>'], 956],
 [['p', 'o', 'l', 'i', 'c', 'e', '</w>'], 954],
 [['b', 'e', 'a', 'u', 't', 'i', 'f', 'u', 'l', '</w>'], 952],
 [['c', 'a', 's', 'e', '</w>'], 944],
 [['s', 'e', 'n', 'd', '</w>'], 944],
 [['a', 'r', 'e', 'n', '</w>'], 943],
 [['w', 'o', 'r', 'r', 'y', '</w>'], 927],
 [['h', 'u', 's', 'b', 'a', 'n', 'd', '</w>'], 924],
 [['t', 'o', 'o', 'k', '</w>'], 924],
 [['k', 'i', 'l', 'l', 'e', 'd', '</w>'], 921],
 [['p', 'a', 'y', '</w>'], 918],
 [['c', 'h', 'a', 'n', 'c', 'e', '</w>'], 918],
 [['d', 'o', 'o', 'r', '</w>'], 913],
 [['n', 'o', 'b', 'o', 'd', 'y', '</w>'], 906],
 [['p', 'o', 'o', 'r', '</w>'], 903],
 [['h', 'u', 'r', 'r', 'y', '</w>'], 898],
 [['w', 'a', 't', 'e', 'r', '</w>'], 896],
 [['u', 'n', 'd', 'e', 'r', '</w>'], 892],
 [['s', 'o', 'n', '</w>'], 890],
 [['f', 'r', 'i', 'e', 'n', 'd', 's', '</w>'], 883],
 [['l', 'a', 't', 'e', 'r', '</w>'], 879],
 [['t', 'u', 'r', 'n', '</w>'], 875],
 [['w', 'o', 'r', 'd', '</w>'], 871],
 [['s', 'p', 'e', 'a', 'k', '</w>'], 869],
 [['s', 'l', 'e', 'e', 'p', '</w>'], 861],
 [['s', 't', 'a', 'r', 't', '</w>'], 860],
 [['b', 'o', 't', 'h', '</w>'], 858],
 [['l', 'a', 't', 'e', '</w>'], 855],
 [['s', 'o', 'm', 'e', 'o', 'n', 'e', '</w>'], 853],
 [['h', 'a', 'n', 'd', 's', '</w>'], 852],
 [['f', 'i', 'v', 'e', '</w>'], 852],
 [['y', 'o', 'u', 'r', 's', '</w>'], 844],
 [['f', 'a', 'c', 'e', '</w>'], 835],
 [['h', 'e', 'a', 'r', 't', '</w>'], 835],
 [['e', 'x', 'c', 'u', 's', 'e', '</w>'], 835],
 [['c', 'o', 'u', 'n', 't', 'r', 'y', '</w>'], 830],
 [['e', 'v', 'e', 'r', 'y', 'b', 'o', 'd', 'y', '</w>'], 830],
 [['e', 'a', 's', 'y', '</w>'], 829],
 [['w', 'o', 'n', 'd', 'e', 'r', 'f', 'u', 'l', '</w>'], 829],
 [['f', 'a', 'r', '</w>'], 826],
 [['d', 'e', 'a', 't', 'h', '</w>'], 822],
 [['r', 'e', 's', 't', '</w>'], 819],
 [['m', 'o', 'm', 'e', 'n', 't', '</w>'], 811],
 [['b', 'a', 'b', 'y', '</w>'], 809],
 [['c', 'a', 'r', '</w>'], 807],
 [['a', 'g', 'a', 'i', 'n', 's', 't', '</w>'], 807],
 [['l', 'o', 'o', 'k', 's', '</w>'], 803],
 [['c', 'o', 'm', 'e', 's', '</w>'], 803],
 [['t', 'h', 'i', 'n', 'k', 'i', 'n', 'g', '</w>'], 800],
 [['w', 'a', 'r', '</w>'], 795],
 [['k', 'n', 'o', 'w', 's', '</w>'], 793],
 [['r', 'a', 't', 'h', 'e', 'r', '</w>'], 791],
 [['g', 'a', 'v', 'e', '</w>'], 790],
 [['h', 'a', 'r', 'd', '</w>'], 788],
 [['e', 'y', 'e', 's', '</w>'], 788],
 [['a', 'n', 'y', 'b', 'o', 'd', 'y', '</w>'], 787],
 [['r', 'e', 'a', 'd', '</w>'], 787],
 [['l', 'o', 's', 't', '</w>'], 783],
 [['w', 'a', 't', 'c', 'h', '</w>'], 782],
 [['h', 'u', 'r', 't', '</w>'], 780],
 [['b', 'r', 'o', 't', 'h', 'e', 'r', '</w>'], 777],
 [['o', 'u', 'g', 'h', 't', '</w>'], 775],
 [['b', 'e', 'd', '</w>'], 774],
 [['a', 'n', 'y', 'o', 'n', 'e', '</w>'], 765],
 [['c', 'e', 'r', 't', 'a', 'i', 'n', 'l', 'y', '</w>'], 765],
 [['f', 'i', 'g', 'h', 't', '</w>'], 763],
 [['b', 'i', 't', '</w>'], 763],
 [['g', 'o', 'd', '</w>'], 760],
 [['c', 'h', 'i', 'l', 'd', '</w>'], 759],
 [['h', 'a', 'l', 'f', '</w>'], 755],
 [['k', 'i', 'd', '</w>'], 755],
 [['g', 'o', 'o', 'd', 'b', 'y', 'e', '</w>'], 752],
 [['e', 'a', 'c', 'h', '</w>'], 751],
 [['t', 'i', 'l', 'l', '</w>'], 750],
 [['h', 'a', 'p', 'p', 'e', 'n', '</w>'], 743],
 [['y', 'e', 'a', 'r', '</w>'], 737],
 [['m', 'a', 'r', 'r', 'y', '</w>'], 734],
 [['t', 'r', 'u', 'e', '</w>'], 733],
 [['e', 'a', 't', '</w>'], 726],
 [["'", 'e', 'm', '</w>'], 718],
 [['d', 'i', 'e', '</w>'], 717],
 [['a', 'n', 'y', 'w', 'a', 'y', '</w>'], 717],
 [['a', 'h', 'e', 'a', 'd', '</w>'], 717],
 [['s', 'i', 's', 't', 'e', 'r', '</w>'], 715],
 [['m', 'a', 'k', 'e', 's', '</w>'], 713],
 [['g', 'u', 'n', '</w>'], 712],
 [['b', 'r', 'o', 'u', 'g', 'h', 't', '</w>'], 706],
 [['s', 'e', 'e', 'm', 's', '</w>'], 705],
 [['e', 'n', 'd', '</w>'], 700],
 [['o', 'f', 'f', 'i', 'c', 'e', '</w>'], 700],
 [['m', 'i', 'n', 'u', 't', 'e', 's', '</w>'], 700],
 [['l', '</w>'], 699],
 [['f', 'o', 'u', 'r', '</w>'], 695],
 [['t', 'a', 'k', 'i', 'n', 'g', '</w>'], 692],
 [['d', 'i', 'n', 'n', 'e', 'r', '</w>'], 691],
 [['t', 'r', 'a', 'i', 'n', '</w>'], 690],
 [['m', 'a', '</w>'], 688],
 [['w', 'o', 'm', 'e', 'n', '</w>'], 687],
 [['f', 'u', 'n', 'n', 'y', '</w>'], 685],
 [['f', 'i', 'r', 'e', '</w>'], 685],
 [['m', 'o', 'n', 's', 'i', 'e', 'u', 'r', '</w>'], 683],
 [['f', 'o', 'o', 'l', '</w>'], 681],
 [['c', 'h', 'a', 'n', 'g', 'e', '</w>'], 681],
 [['g', 'o', 'e', 's', '</w>'], 679],
 [['a', 'l', 'r', 'e', 'a', 'd', 'y', '</w>'], 678],
 [['c', 'r', 'a', 'z', 'y', '</w>'], 676],
 [['a', 's', 'k', 'e', 'd', '</w>'], 672],
 [['g', 'e', 'o', 'r', 'g', 'e', '</w>'], 670],
 [['i', 'm', 'p', 'o', 'r', 't', 'a', 'n', 't', '</w>'], 668],
 [['q', 'u', 'i', 'e', 't', '</w>'], 667],
 [['g', 'o', 't', 't', 'a', '</w>'], 662],
 [['f', 'e', 'l', 'l', 'o', 'w', '</w>'], 660],
 [['j', 'o', 'e', '</w>'], 660],
 [['b', 'e', 't', '</w>'], 659],
 [['c', 'a', 'l', 'l', 'e', 'd', '</w>'], 645],
 [['l', 'u', 'c', 'k', '</w>'], 642],
 [["'", '</w>'], 642],
 [['s', 't', 'o', 'r', 'y', '</w>'], 641],
 [['b', 'r', 'e', 'a', 'k', '</w>'], 637],
 [['h', 'o', 'u', 'r', '</w>'], 636],
 [['b', 'u', 'y', '</w>'], 635],
 [['h', 'a', 'v', 'i', 'n', 'g', '</w>'], 633],
 [['l', 'a', 'w', '</w>'], 631],
 [['o', '</w>'], 629],
 [['s', 'e', 'n', 't', '</w>'], 629],
 [['c', 'h', 'i', 'l', 'd', 'r', 'e', 'n', '</w>'], 627],
 [['m', 'e', 't', '</w>'], 626],
 [['1', '0', '</w>'], 626],
 [['s', 'h', 'o', 't', '</w>'], 626],
 [['a', 'n', 's', 'w', 'e', 'r', '</w>'], 624],
 [['w', 'e', 'e', 'k', '</w>'], 622],
 [['s', 'o', 'r', 't', '</w>'], 621],
 [['w', 'a', 'l', 'k', '</w>'], 619],
 [['k', 'i', 'n', 'g', '</w>'], 618],
 [['m', 'e', 'a', 'n', 's', '</w>'], 617],
 [['r', 'e', 'a', 'l', '</w>'], 615],
 [['t', 'r', 'i', 'e', 'd', '</w>'], 609],
 [['h', 'a', 't', 'e', '</w>'], 603],
 [['g', 'e', 't', 's', '</w>'], 600],
 [['l', 'e', 'a', 'v', 'i', 'n', 'g', '</w>'], 600],
 [['d', 'a', 'u', 'g', 'h', 't', 'e', 'r', '</w>'], 598],
 [['b', 'i', 'l', 'l', '</w>'], 598],
 [['t', 'i', 'm', 'e', 's', '</w>'], 597],

In [457]:
tokenizer_eng.vocab

{'<pad>': 0,
 '<unk>': 1,
 '<eos>': 2,
 '</w>': 3,
 '9': 4,
 'h': 5,
 '4': 6,
 'z': 7,
 '.': 8,
 't': 9,
 '%': 10,
 '1': 11,
 'u': 12,
 'w': 13,
 '7': 14,
 '[': 15,
 '3': 16,
 'c': 17,
 '5': 18,
 'd': 19,
 'i': 20,
 '8': 21,
 '$': 22,
 ']': 23,
 ')': 24,
 'v': 25,
 'l': 26,
 'k': 27,
 ',': 28,
 'm': 29,
 'r': 30,
 'j': 31,
 'q': 32,
 's': 33,
 '"': 34,
 '6': 35,
 'x': 36,
 '?': 37,
 'e': 38,
 'f': 39,
 'y': 40,
 '/': 41,
 '(': 42,
 '-': 43,
 ':': 44,
 'o': 45,
 '2': 46,
 "'": 47,
 '0': 48,
 'g': 49,
 'n': 50,
 'p': 51,
 '!': 52,
 'a': 53,
 'b': 54,
 'e </w>': 55,
 '. </w>': 56,
 't </w>': 57,
 't h': 58,
 's </w>': 59,
 'o u': 60,
 'n </w>': 61,
 'd </w>': 62,
 ', </w>': 63,
 'e r': 64,
 'y </w>': 65,
 'y ou': 66,
 'o </w>': 67,
 'i n': 68,
 'you </w>': 69,
 'i </w>': 70,
 'a n': 71,
 'l </w>': 72,
 'r </w>': 73,
 'th e</w>': 74,
 'g </w>': 75,
 'a t</w>': 76,
 '? </w>': 77,
 'a </w>': 78,
 'l l</w>': 79,
 't o</w>': 80,
 'in g</w>': 81,
 'er </w>': 82,
 'a r': 83,
 'f </w>': 84,
 'i t</w>': 85,
 'm e</w>': 86,
 'o n</w>': 87,
 'w h': 88,
 'm </w>': 89,
 'o n': 90,
 'o w': 91,
 "' s</w>": 92,
 'i s</w>': 93,
 'v e</w>': 94,
 'e a': 95,
 'o r': 96,
 "' t</w>": 97,
 'e d</w>': 98,
 'k </w>': 99,
 'an d</w>': 100,
 'h a': 101,
 'i n</w>': 102,
 's t': 103,
 'e n': 104,
 'th at</w>': 105,
 'l i': 106,
 'ow </w>': 107,
 'h </w>': 108,
 'er e</w>': 109,
 'e n</w>': 110,
 'o f</w>': 111,
 'w a': 112,
 'e s</w>': 113,
 'o r</w>': 114,
 'h e</w>': 115,
 'a n</w>': 116,
 'r i': 117,
 'w i': 118,
 's t</w>': 119,
 'g h': 120,
 'g o': 121,
 '! </w>': 122,
 'e t</w>': 123,
 'r e': 124,
 's e</w>': 125,
 'e l': 126,
 't i': 127,
 'wh at</w>': 128,
 'gh t</w>': 129,
 'k e</w>': 130,
 'm a': 131,
 'n ow</w>': 132,
 'b e': 133,
 'p </w>': 134,
 'c o': 135,
 'r o': 136,
 'd i': 137,
 'b u': 138,
 'r e</w>': 139,
 'l a': 140,
 'f or</w>': 141,
 'l e</w>': 142,
 'w e</w>': 143,
 'h i': 144,
 'th e': 145,
 'n o': 146,
 'l o': 147,
 'b e</w>': 148,
 'l d</w>': 149,
 'ou t</w>': 150,
 'th </w>': 151,
 't t': 152,
 'm y</w>': 153,
 's i': 154,
 'e v': 155,
 'e ll</w>': 156,
 'c e</w>': 157,
 'th is</w>': 158,
 's a': 159,
 'you r</w>': 160,
 't a': 161,
 'd on</w>': 162,
 "' ll</w>": 163,
 'ha ve</w>': 164,
 'l y</w>': 165,
 'a ll</w>': 166,
 'r a': 167,
 'd o</w>': 168,
 's e': 169,
 'n o</w>': 170,
 'ar e</w>': 171,
 'c a': 172,
 "' m</w>": 173,
 'on e</w>': 174,
 's o': 175,
 'bu t</w>': 176,
 'c an</w>': 177,
 'wa s</w>': 178,
 "' re</w>": 179,
 'th ing</w>': 180,
 'wi th</w>': 181,
 'm i': 182,
 'u n': 183,
 'no t</w>': 184,
 't o': 185,
 'c h': 186,
 'a b': 187,
 'h ere</w>': 188,
 'l e': 189,
 's u': 190,
 'u st</w>': 191,
 'm e': 192,
 'g et</w>': 193,
 'c k</w>': 194,
 'th ere</w>': 195,
 'k now</w>': 196,
 'hi m</w>': 197,
 's h': 198,
 's s</w>': 199,
 'b o': 200,
 'th er</w>': 201,
 'a l': 202,
 'c h</w>': 203,
 'w ell</w>': 204,
 'i f</w>': 205,
 'n e': 206,
 'f i': 207,
 'g o</w>': 208,
 'ou ld</w>': 209,
 'the y</w>': 210,
 'y es</w>': 211,
 'd o': 212,
 "' ve</w>": 213,
 'li ke</w>': 214,
 'th in': 215,
 'r y</w>': 216,
 'co me</w>': 217,
 'r ea': 218,
 'd a': 219,
 'o d</w>': 220,
 'ri ght</w>': 221,
 'w an': 222,
 't e</w>': 223,
 'b a': 224,
 's o</w>': 225,
 's he</w>': 226,
 'p o': 227,
 'ab out</w>': 228,
 'u p</w>': 229,
 'h o': 230,
 'g i': 231,
 'f a': 232,
 'd n</w>': 233,
 'o h</w>': 234,
 'l ea': 235,
 'wi ll</w>': 236,
 'j ust</w>': 237,
 'se e</w>': 238,
 'n i': 239,
 'u r': 240,
 't s</w>': 241,
 'a s</w>': 242,
 'f or': 243,
 'm or': 244,
 'go od</w>': 245,
 'en t</w>': 246,
 'm an</w>': 247,
 'h er</w>': 248,
 'd y</w>': 249,
 'go t</w>': 250,
 'd e': 251,
 'w or': 252,
 'h ow</w>': 253,
 'ev er</w>': 254,
 'p a': 255,
 '" </w>': 256,
 'wa y</w>': 257,
 'ow n</w>': 258,
 'm o': 259,
 'ou n': 260,
 'lo o': 261,
 'v er': 262,
 'p p': 263,
 'w </w>': 264,
 'g a': 265,
 "' d</w>": 266,
 'in d</w>': 267,
 '- </w>': 268,
 'wan t</w>': 269,
 'k ing</w>': 270,
 'thin k</w>': 271,
 'wh y</w>': 272,
 's p': 273,
 'so me': 274,
 'h is</w>': 275,
 't er</w>': 276,
 'm r</w>': 277,
 'q u': 278,
 'd s</w>': 279,
 'g e</w>': 280,
 'g u': 281,
 'y s</w>': 282,
 'c k': 283,
 'e e': 284,
 'go ing</w>': 285,
 'wh ere</w>': 286,
 'di d</w>': 287,
 'r u': 288,
 'el l': 289,
 'i d</w>': 290,
 'd e</w>': 291,
 'e x': 292,
 'l et</w>': 293,
 'f u': 294,
 'ta ke</w>': 295,
 'e ar': 296,
 'the m</w>': 297,
 'c i': 298,
 'f ro': 299,
 't y</w>': 300,
 'be en</w>': 301,
 'an y': 302,
 'ea r</w>': 303,
 'tt er</w>': 304,
 'wh en</w>': 305,
 'fro m</w>': 306,
 'l l': 307,
 'co m': 308,
 'er s</w>': 309,
 'on g</w>': 310,
 't ell</w>': 311,
 'g e': 312,
 'm ar': 313,
 'wh o</w>': 314,
 's n</w>': 315,
 'm u': 316,
 'sa y</w>': 317,
 't ed</w>': 318,
 'u s</w>': 319,
 'g h</w>': 320,
 'an y</w>': 321,
 'ti on</w>': 322,
 'e y</w>': 323,
 'ti me</w>': 324,
 'th an': 325,
 'ver y</w>': 326,
 'c on': 327,
 'ba ck</w>': 328,
 'ou r</w>': 329,
 'st a': 330,
 'tt le</w>': 331,
 'c ou': 332,
 'a f': 333,
 'in e</w>': 334,
 'loo k</w>': 335,
 'v er</w>': 336,
 'o f': 337,
 'm on': 338,
 'n a': 339,
 'ha d</w>': 340,
 'k s</w>': 341,
 's el': 342,
 'ev er': 343,
 'p e': 344,
 'to o</w>': 345,
 'o p': 346,
 'c t': 347,
 'f e': 348,
 'v i': 349,
 'p la': 350,
 'c u': 351,
 'p ro': 352,
 'w ould</w>': 353,
 'k i': 354,
 'r an': 355,
 'j o': 356,
 'ou gh</w>': 357,
 'n ever</w>': 358,
 'da y</w>': 359,
 'b i': 360,
 'p u': 361,
 'd er': 362,
 'di dn</w>': 363,
 's h</w>': 364,
 'w ere</w>': 365,
 'si r</w>': 366,
 'p i': 367,
 'so me</w>': 368,
 'li ttle</w>': 369,
 'st i': 370,
 'g s</w>': 371,
 'b y</w>': 372,
 's s': 373,
 'mor e</w>': 374,
 'm b': 375,
 'r s</w>': 376,
 'p ar': 377,
 'oun d</w>': 378,
 'd own</w>': 379,
 'th en</w>': 380,
 'p er': 381,
 'p re': 382,
 'ou ght</w>': 383,
 'p lea': 384,
 'f e</w>': 385,
 'gi ve</w>': 386,
 's on</w>': 387,
 'su re</w>': 388,
 'm ust</w>': 389,
 'l dn</w>': 390,
 'ma ke</w>': 391,
 'b le</w>': 392,
 'l ly</w>': 393,
 't er': 394,
 'en d</w>': 395,
 'sel f</w>': 396,
 'on ly</w>': 397,
 't e': 398,
 'ta l': 399,
 'm en</w>': 400,
 'd er</w>': 401,
 'ha pp': 402,
 't ing</w>': 403,
 'c ould</w>': 404,
 'l u': 405,
 'a s': 406,
 't w': 407,
 'ha s</w>': 408,
 'o ther</w>': 409,
 'y ing</w>': 410,
 'some thing</w>': 411,
 'than k</w>': 412,
 'c ar': 413,
 'o ver</w>': 414,
 'bo dy</w>': 415,
 'ni ght</w>': 416,
 'e ss</w>': 417,
 'fu l</w>': 418,
 'a l</w>': 419,
 'w on</w>': 420,
 'mu ch</w>': 421,
 '0 </w>': 422,
 'a ga': 423,
 'u se</w>': 424,
 'ar d</w>': 425,
 's or': 426,
 'n ing</w>': 427,
 't r': 428,
 'st o': 429,
 'c </w>': 430,
 'plea se</w>': 431,
 'a m</w>': 432,
 'h ea': 433,
 'qu i': 434,
 'c t</w>': 435,
 'wh i': 436,
 'h el': 437,
 'm in': 438,
 'i r</w>': 439,
 'ne w</w>': 440,
 's in': 441,
 'ea n</w>': 442,
 'f o': 443,
 'be tter</w>': 444,
 'm p': 445,
 'ever y': 446,
 'y ea': 447,
 'yea h</w>': 448,
 'n a</w>': 449,
 'no thing</w>': 450,
 'w o': 451,
 'f ri': 452,
 'd r': 453,
 'm ent</w>': 454,
 't ra': 455,
 'of f</w>': 456,
 'any thing</w>': 457,
 'h u': 458,
 'a way</w>': 459,
 'o ld</w>': 460,
 'tw o</w>': 461,
 'd ea': 462,
 'd u': 463,
 'd ing</w>': 464,
 'm ean</w>': 465,
 'lo ve</w>': 466,
 'ell o</w>': 467,
 'g re': 468,
 'an t</w>': 469,
 'ou s</w>': 470,
 'b r': 471,
 'h ello</w>': 472,
 's ed</w>': 473,
 'for e</w>': 474,
 'g en': 475,
 'mi ss</w>': 476,
 't u': 477,
 'l ing</w>': 478,
 'c hi': 479,
 'fi r': 480,
 'be fore</w>': 481,
 'sa id</w>': 482,
 'aga in</w>': 483,
 'o se</w>': 484,
 'b </w>': 485,
 "' </w>": 486,
 'v ing</w>': 487,
 'f ind</w>': 488,
 'k ee': 489,
 's ha': 490,
 'v en</w>': 491,
 'on s</w>': 492,
 'sh ould</w>': 493,
 'ro o': 494,
 'p e</w>': 495,
 'l ong</w>': 496,
 'st and</w>': 497,
 'cou r': 498,
 'h ear': 499,
 'ou ldn</w>': 500,
 'h an': 501,
 'i sn</w>': 502,
 'fa ther</w>': 503,
 'h ou': 504,
 'ch an': 505,
 'sor ry</w>': 506,
 'hel p</w>': 507,
 's er': 508,
 'st er</w>': 509,
 'wa ys</w>': 510,
 'mb er</w>': 511,
 'th an</w>': 512,
 'af ter</w>': 513,
 'ca use</w>': 514,
 'th ought</w>': 515,
 'a c': 516,
 'el y</w>': 517,
 'c e': 518,
 'pu t</w>': 519,
 'g ra': 520,
 'ev en</w>': 521,
 'ho me</w>': 522,
 'op le</w>': 523,
 'ma y': 524,
 'fir st</w>': 525,
 'pe ople</w>': 526,
 'gi r': 527,
 't ur': 528,
 'k ed</w>': 529,
 'g on': 530,
 'sh o': 531,
 's si': 532,
 'm ind</w>': 533,
 'thin gs</w>': 534,
 'th r': 535,
 'al ways</w>': 536,
 'th ose</w>': 537,
 'may be</w>': 538,
 'i ght</w>': 539,
 'l es</w>': 540,
 'in to</w>': 541,
 'kee p</w>': 542,
 'tal k</w>': 543,
 'la st</w>': 544,
 'gon na</w>': 545,
 'a in</w>': 546,
 'm rs</w>': 547,
 'wa it</w>': 548,
 'to ld</w>': 549,
 're e</w>': 550,
 't ry</w>': 551,
 'ri ed</w>': 552,
 'be cause</w>': 553,
 'ma y</w>': 554,
 'v es</w>': 555,
 'p s</w>': 556,
 'm s</w>': 557,
 'lea ve</w>': 558,
 'e st': 559,
 'f t</w>': 560,
 'the se</w>': 561,
 'ch ar': 562,
 'li e': 563,
 'd ar': 564,
 'un der': 565,
 'd ear</w>': 566,
 't ch</w>': 567,
 'ar ound</w>': 568,
 'li fe</w>': 569,
 'tt ing</w>': 570,
 's w': 571,
 'cour se</w>': 572,
 'j u': 573,
 'mon ey</w>': 574,
 'pla ce</w>': 575,
 'i l</w>': 576,
 'ear s</w>': 577,
 'w ouldn</w>': 578,
 'l an': 579,
 'g er</w>': 580,
 'i l': 581,
 'min u': 582,
 'en ce</w>': 583,
 'mor ning</w>': 584,
 'c oun': 585,
 'x </w>': 586,
 'p ri': 587,
 't on': 588,
 'm an': 589,
 'rea lly</w>': 590,
 'wor k</w>': 591,
 'na me</w>': 592,
 'ni ce</w>': 593,
 'a d': 594,
 'ma tter</w>': 595,
 'ct or</w>': 596,
 'roo m</w>': 597,
 'every thing</w>': 598,
 'mi ght</w>': 599,
 'b ea': 600,
 'st ar': 601,
 'h ar': 602,
 'o k</w>': 603,
 'n y</w>': 604,
 'ha ven</w>': 605,
 'sti ll</w>': 606,
 'd an': 607,
 'e st</w>': 608,
 ': </w>': 609,
 'en ough</w>': 610,
 'gir l</w>': 611,
 'c lo': 612,
 'v ed</w>': 613,
 'h ur': 614,
 'c all</w>': 615,
 'r ow</w>': 616,
 'hou se</w>': 617,
 'f in': 618,
 'do ing</w>': 619,
 'j a': 620,
 'do es</w>': 621,
 'h on': 622,
 'y e</w>': 623,
 're me': 624,
 'hea d</w>': 625,
 'p po': 626,
 'than ks</w>': 627,
 'ca me</w>': 628,
 'ee l</w>': 629,
 'h ey</w>': 630,
 'a t': 631,
 'll ed</w>': 632,
 'ne ed</w>': 633,
 'c ha': 634,
 'sta y</w>': 635,
 'f f': 636,
 'you r': 637,
 't ru': 638,
 'se e': 639,
 'e l</w>': 640,
 'm er': 641,
 's c': 642,
 's en': 643,
 'sto p</w>': 644,
 'mo st</w>': 645,
 'bo y</w>': 646,
 'tt y</w>': 647,
 't le': 648,
 'li st': 649,
 'com ing</w>': 650,
 'ra id</w>': 651,
 'reme mber</w>': 652,
 'mo ther</w>': 653,
 'l on': 654,
 'li ve</w>': 655,
 'rea dy</w>': 656,
 'en ed</w>': 657,
 'y ears</w>': 658,
 'as k</w>': 659,
 'an other</w>': 660,
 's y</w>': 661,
 'm y': 662,
 'st u': 663,
 'h ear</w>': 664,
 'si de</w>': 665,
 'thr ough</w>': 666,
 'your self</w>': 667,
 's hi': 668,
 'under stand</w>': 669,
 'af raid</w>': 670,
 'do e': 671,
 'b ro': 672,
 'doe sn</w>': 673,
 'r ed</w>': 674,
 'k n': 675,
 'be lie': 676,
 'ma de</w>': 677,
 'd one</w>': 678,
 'k es</w>': 679,
 'g la': 680,
 's it</w>': 681,
 'b er': 682,
 'the ir</w>': 683,
 'w on': 684,
 'bi g</w>': 685,
 'belie ve</w>': 686,
 'c er': 687,
 'k a': 688,
 'gre at</w>': 689,
 'le ft</w>': 690,
 'e p</w>': 691,
 'c or': 692,
 'f eel</w>': 693,
 'ton ight</w>': 694,
 'sha ll</w>': 695,
 'n er</w>': 696,
 '0 0</w>': 697,
 'wa l': 698,
 'k ind</w>': 699,
 'ever y</w>': 700,
 'ba d</w>': 701,
 'ta in</w>': 702,
 'i r': 703,
 'cou ldn</w>': 704,
 'h or': 705,
 'ow s</w>': 706,
 'n ed</w>': 707,
 'su ppo': 708,
 'b ab': 709,
 'j e': 710,
 'gen tle': 711,
 'lo t</w>': 712,
 'wo man</w>': 713,
 'wh o': 714,
 'ca p': 715,
 'th ree</w>': 716,
 'fri end</w>': 717,
 'r ong</w>': 718,
 't ri': 719,
 'b rea': 720,
 'sp e': 721,
 't es</w>': 722,
 'o l</w>': 723,
 'wi th': 724,
 'o d': 725,
 'b ar': 726,
 'c are</w>': 727,
 'e d': 728,
 'f ran': 729,
 'dr in': 730,
 'c ra': 731,
 'l li': 732,
 'dar ling</w>': 733,
 'list en</w>': 734,
 'do ctor</w>': 735,
 'wan ted</w>': 736,
 'p h': 737,
 'b la': 738,
 'my self</w>': 739,
 'st or': 740,
 'i m': 741,
 'm es</w>': 742,
 'se en</w>': 743,
 'la dy</w>': 744,
 'you n': 745,
 'bu sin': 746,
 'l s</w>': 747,
 'w ar': 748,
 'on ce</w>': 749,
 'in ter': 750,
 'minu te</w>': 751,
 'hear d</w>': 752,
 'f f</w>': 753,
 'el se</w>': 754,
 'wa i': 755,
 'po li': 756,
 'ab le</w>': 757,
 'ch e': 758,
 'wor ld</w>': 759,
 'g ar': 760,
 'en ing</w>': 761,
 'le y</w>': 762,
 'busin ess</w>': 763,
 'ou ble</w>': 764,
 'f ine</w>': 765,
 't ch': 766,
 'l or': 767,
 'mor row</w>': 768,
 'an s</w>': 769,
 'su ch</w>': 770,
 'bea u': 771,
 'to morrow</w>': 772,
 'pre tty</w>': 773,
 'd r</w>': 774,
 'd in': 775,
 'sh ow</w>': 776,
 'p t</w>': 777,
 'ho pe</w>': 778,
 'g ed</w>': 779,
 'wi fe</w>': 780,
 'l and</w>': 781,
 'd ed</w>': 782,
 'al one</w>': 783,
 'qui te</w>': 784,
 'c y</w>': 785,
 'd re': 786,
 'happ y</w>': 787,
 'youn g</w>': 788,
 'whi le</w>': 789,
 'ge tting</w>': 790,
 'dea d</w>': 791,
 'br ing</w>': 792,
 's es</w>': 793,
 'wa sn</w>': 794,
 'm en': 795,
 'k new</w>': 796,
 'y et</w>': 797,
 'sa me</w>': 798,
 'sa w</w>': 799,
 's le': 800,
 'with out</w>': 801,
 'gu ess</w>': 802,
 'in s</w>': 803,
 'wi sh</w>': 804,
 'm ur': 805,
 's ing</w>': 806,
 's k': 807,
 'el e': 808,
 'be ing</w>': 809,
 'i de': 810,
 'm a</w>': 811,
 'l t</w>': 812,
 'm ed</w>': 813,
 'com p': 814,
 'ar y</w>': 815,
 'ide a</w>': 816,
 'di e</w>': 817,
 'c an': 818,
 'st e': 819,
 'ti ons</w>': 820,
 'qu e': 821,
 'c es</w>': 822,
 'loo king</w>': 823,
 'ch o': 824,
 'w rong</w>': 825,
 'suppo se</w>': 826,
 'happ ened</w>': 827,
 'bo ys</w>': 828,
 'p or': 829,
 'l f</w>': 830,
 'sp ea': 831,
 'b or': 832,
 'of fi': 833,
 'en g': 834,
 'b ye</w>': 835,
 'jo h': 836,
 'al ong</w>': 837,
 'da ys</w>': 838,
 'h un': 839,
 'g r': 840,
 'a ge</w>': 841,
 'a tt': 842,
 're st</w>': 843,
 'p r': 844,
 'f ound</w>': 845,
 'tur n</w>': 846,
 'st an': 847,
 'un ti': 848,
 'so on</w>': 849,
 't own</w>': 850,
 'w ent</w>': 851,
 'b el': 852,
 'w ee': 853,
 'g one</w>': 854,
 'b ri': 855,
 'm any</w>': 856,
 'di s': 857,
 'in g': 858,
 'ho ld</w>': 859,
 'f ell': 860,
 'b ra': 861,
 'drin k</w>': 862,
 'ck ed</w>': 863,
 'v o': 864,
 'en ds</w>': 865,
 'g er': 866,
 'gu y</w>': 867,
 'a pp': 868,
 'tr ouble</w>': 869,
 's ent</w>': 870,
 'x t</w>': 871,
 'gh t': 872,
 'bu r': 873,
 'w in': 874,
 'ne xt</w>': 875,
 'ne ss</w>': 876,
 'al ly</w>': 877,
 'be st</w>': 878,
 'v a': 879,
 'o t</w>': 880,
 'u h</w>': 881,
 'd ge</w>': 882,
 'unti l</w>': 883,
 'gentle men</w>': 884,
 'fe w</w>': 885,
 'su r': 886,
 'k e': 887,
 'sin ce</w>': 888,
 'mar ried</w>': 889,
 'gla d</w>': 890,
 'jo b</w>': 891,
 'm ine</w>': 892,
 'w ri': 893,
 'le ss</w>': 894,
 'to day</w>': 895,
 'e i': 896,
 'ka y</w>': 897,
 'in t</w>': 898,
 'd ri': 899,
 'an i': 900,
 'who le</w>': 901,
 'un i': 902,
 'ff er': 903,
 'tr ying</w>': 904,
 'go od': 905,
 'k en</w>': 906,
 'ti mes</w>': 907,
 'ru n</w>': 908,
 'ss ed</w>': 909,
 'tal king</w>': 910,
 'c la': 911,
 'won der': 912,
 "in '</w>": 913,
 'h and</w>': 914,
 'sp i': 915,
 'go tt': 916,
 'u sed</w>': 917,
 'wai ting</w>': 918,
 'si g': 919,
 'b ed</w>': 920,
 'li e</w>': 921,
 'z e</w>': 922,
 't on</w>': 923,
 'for get</w>': 924,
 'per ha': 925,
 'perha ps</w>': 926,
 'la te</w>': 927,
 'beau ti': 928,
 'cap tain</w>': 929,
 's b': 930,
 'sa ys</w>': 931,
 'c ti': 932,
 'to ge': 933,
 'ca se</w>': 934,
 'n u': 935,
 'ki ll</w>': 936,
 'toge ther</w>': 937,
 'wor d</w>': 938,
 'c r': 939,
 's on': 940,
 't en': 941,
 'ex pe': 942,
 'f r': 943,
 'whi ch</w>': 944,
 'o kay</w>': 945,
 'me et</w>': 946,
 'l ed</w>': 947,
 'a ct': 948,
 'd d': 949,
 'u gh': 950,
 'op en</w>': 951,
 'ev ening</w>': 952,
 'p lan': 953,
 'hu h</w>': 954,
 'pla y</w>': 955,
 'e u': 956,
 'ar en</w>': 957,
 'ea ch</w>': 958,
 't t</w>': 959,
 'p l': 960,
 's end</w>': 961,
 'ck s</w>': 962,
 'wan ts</w>': 963,
 'a go</w>': 964,
 'un der</w>': 965,
 'ca r</w>': 966,
 'd a</w>': 967,
 'hu sb': 968,
 'some body</w>': 969,
 'sh ed</w>': 970,
 'poli ce</w>': 971,
 'beauti ful</w>': 972,
 'or t': 973,
 'ma da': 974,
 'pa y</w>': 975,
 'm p</w>': 976,
 'ta in': 977,
 'al l': 978,
 'ou s': 979,
 'pa p': 980,
 'pp ed</w>': 981,
 'g ran': 982,
 'to ok</w>': 983,
 'b it</w>': 984,
 'u p': 985,
 'wor ry</w>': 986,
 'ki lled</w>': 987,
 'd ly</w>': 988,
 'do or</w>': 989,
 'v en': 990,
 'husb and</w>': 991,
 'shi p</w>': 992,
 'chan ce</w>': 993,
 'z y</w>': 994,
 'wa ter</w>': 995,
 'ou t': 996,
 'a d</w>': 997,
 's ou': 998,
 'no body</w>': 999,
 ...}

#### 3.4 BPE Encoder propably should add to the BPE Class Later

In [107]:
test_word = ' '.join(char_factor("running"))
test_word

'r u n n i n g </w>'

In [175]:
# pair = 'g </w>'
pair = '['
sub_pair = lambda x: re.sub('\s+', '', x)
re.sub(rf"( |^){re.escape(pair)}( |$)", rf"\g<1>{sub_pair(pair)}\g<2>", "r u n n i n g </w>")

'r u n n i n g </w>'

In [196]:
def word_encoder(word, vocab):
    word_str = ' '.join(char_factor(word)) #do zmiany uzywanie char_factor spoza funkcji
    sub_key = lambda x: re.sub('\s+', '', x)
    
    for k, v in vocab.items():
        if bool(re.search(rf"( |^){re.escape(k)}( |$)", word_str)):
            print(k, v)
            print(word_str)
            word_str = re.sub(rf"( |^){re.escape(k)}( |$)", rf"\g<1>{sub_key(k)}\g<2>", word_str)
            print(word_str, '\n')
    return word_str

In [218]:
tokenizer_eng.vocab

{'<pad>': 0,
 '<unk>': 1,
 '<eos>': 2,
 '</w>': 3,
 '9': 4,
 'h': 5,
 '4': 6,
 'z': 7,
 '.': 8,
 't': 9,
 '%': 10,
 '1': 11,
 'u': 12,
 'w': 13,
 '7': 14,
 '[': 15,
 '3': 16,
 'c': 17,
 '5': 18,
 'd': 19,
 'i': 20,
 '8': 21,
 '$': 22,
 ']': 23,
 ')': 24,
 'v': 25,
 'l': 26,
 'k': 27,
 ',': 28,
 'm': 29,
 'r': 30,
 'j': 31,
 'q': 32,
 's': 33,
 '"': 34,
 '6': 35,
 'x': 36,
 '?': 37,
 'e': 38,
 'f': 39,
 'y': 40,
 '/': 41,
 '(': 42,
 '-': 43,
 ':': 44,
 'o': 45,
 '2': 46,
 "'": 47,
 '0': 48,
 'g': 49,
 'n': 50,
 'p': 51,
 '!': 52,
 'a': 53,
 'b': 54,
 'e </w>': 55,
 '. </w>': 56,
 't </w>': 57,
 't h': 58,
 's </w>': 59,
 'o u': 60,
 'n </w>': 61,
 'd </w>': 62,
 ', </w>': 63,
 'e r': 64,
 'y </w>': 65,
 'y ou': 66,
 'o </w>': 67,
 'i n': 68,
 'you </w>': 69,
 'i </w>': 70,
 'a n': 71,
 'l </w>': 72,
 'r </w>': 73,
 'th e</w>': 74,
 'g </w>': 75,
 'a t</w>': 76,
 '? </w>': 77,
 'a </w>': 78,
 'l l</w>': 79,
 't o</w>': 80,
 'in g</w>': 81,
 'a r': 82,
 'f </w>': 83,
 'i t</w>': 84,
 'm e</w>': 85,
 'o n</w>': 86,
 'w h': 87,
 'm </w>': 88,
 'o n': 89,
 'o w': 90,
 "' s</w>": 91,
 'i s</w>': 92,
 'v e</w>': 93,
 'o r': 94,
 "' t</w>": 95,
 'e d</w>': 96,
 'k </w>': 97,
 'an d</w>': 98,
 'h a': 99,
 's t': 100,
 'r e': 101,
 'l i': 102,
 'ow </w>': 103,
 'h </w>': 104,
 'e n': 105,
 'o f</w>': 106,
 'w a': 107,
 'e s</w>': 108,
 'h e</w>': 109,
 'r i': 110,
 'l e': 111,
 'w i': 112,
 'g h': 113,
 'g o': 114,
 '! </w>': 115,
 'b e': 116,
 's e</w>': 117,
 't i': 118,
 'gh t</w>': 119,
 'k e</w>': 120,
 'n ow</w>': 121,
 'm a': 122,
 's e': 123,
 'p </w>': 124,
 'c o': 125,
 'r o': 126,
 'd i': 127,
 'b u': 128,
 'a c': 129,
 'f or</w>': 130,
 'th e': 131,
 'l d</w>': 132,
 'w e</w>': 133,
 'h i': 134,
 'l o': 135,
 'n o': 136,
 'ou t</w>': 137,
 'l y</w>': 138,
 'm y</w>': 139,
 's i': 140,
 'e t</w>': 141,
 'h e': 142,
 'you r</w>': 143,
 'd on</w>': 144,
 't a': 145,
 "' ll</w>": 146,
 'ha ve</w>': 147,
 's a': 148,
 'l a': 149,
 'e ll</w>': 150,
 'a ll</w>': 151,
 'e v': 152,
 'd o</w>': 153,
 'm e': 154,
 't t': 155,
 'r a': 156,
 "' m</w>": 157,
 's o': 158,
 'bu t</w>': 159,
 'c e</w>': 160,
 'c a': 161,
 'wa s</w>': 162,
 "' re</w>": 163,
 'wi th</w>': 164,
 'm i': 165,
 'u n': 166,
 'no t</w>': 167,
 't o': 168,
 'd e': 169,
 'u st</w>': 170,
 'g et</w>': 171,
 'a b': 172,
 's u': 173,
 'k now</w>': 174,
 'hi m</w>': 175,
 's s</w>': 176,
 'h o': 177,
 'b o': 178,
 'n e': 179,
 'w ell</w>': 180,
 'i f</w>': 181,
 'f i': 182,
 'a l': 183,
 'the y</w>': 184,
 'y es</w>': 185,
 'd o': 186,
 "' ve</w>": 187,
 'c h</w>': 188,
 'r y</w>': 189,
 'li ke</w>': 190,
 'co me</w>': 191,
 'o d</w>': 192,
 'ri ght</w>': 193,
 't e</w>': 194,
 'd a': 195,
 's he</w>': 196,
 'p o': 197,
 'u p</w>': 198,
 'p e': 199,
 'g i': 200,
 'd n</w>': 201,
 'o h</w>': 202,
 'a s</w>': 203,
 'wi ll</w>': 204,
 'j ust</w>': 205,
 'se e</w>': 206,
 'n i': 207,
 't s</w>': 208,
 'go od</w>': 209,
 'f e': 210,
 'd y</w>': 211,
 'go t</w>': 212,
 'w or': 213,
 'le a': 214,
 '" </w>': 215,
 'wa y</w>': 216,
 'm o': 217,
 'lo o': 218,
 't e': 219,
 'u r': 220,
 'w </w>': 221,
 "' d</w>": 222,
 '- </w>': 223,
 'wan t</w>': 224,
 'k ing</w>': 225,
 'thin k</w>': 226,
 'wh y</w>': 227,
 're a': 228,
 'p a': 229,
 'so me': 230,
 'm r</w>': 231,
 'w ou': 232,
 'q u': 233,
 'g a': 234,
 'd s</w>': 235,
 'f a': 236,
 'g e</w>': 237,
 'y s</w>': 238,
 'go ing</w>': 239,
 'di d</w>': 240,
 'i d</w>': 241,
 'c k</w>': 242,
 'y e': 243,
 'ta ke</w>': 244,
 'g e': 245,
 'the m</w>': 246,
 'f ro': 247,
 't y</w>': 248,
 'e x': 249,
 'be en</w>': 250,
 'an y': 251,
 'fro m</w>': 252,
 'he l': 253,
 'c i': 254,
 'p i': 255,
 'u s</w>': 256,
 'k s</w>': 257,
 's n</w>': 258,
 'sa y</w>': 259,
 'w e': 260,
 'm u': 261,
 'f u': 262,
 'a d</w>': 263,
 'ti on</w>': 264,
 'g u': 265,
 'ti me</w>': 266,
 'f or': 267,
 'v ery</w>': 268,
 'b ack</w>': 269,
 'r u': 270,
 'a s': 271,
 'tt le</w>': 272,
 'a f': 273,
 'k i': 274,
 'loo k</w>': 275,
 'v er</w>': 276,
 'p ro': 277,
 'k e': 278,
 'o f': 279,
 'to o</w>': 280,
 'ha p': 281,
 'se l': 282,
 'wou ld</w>': 283,
 'v i': 284,
 'j o': 285,
 'da y</w>': 286,
 'n a': 287,
 'di dn</w>': 288,
 'b i': 289,
 'si r</w>': 290,
 'p u': 291,
 'li ttle</w>': 292,
 'g s</w>': 293,
 'b y</w>': 294,
 'c u': 295,
 'p re': 296,
 'dow n</w>': 297,
 'gi ve</w>': 298,
 'l dn</w>': 299,
 'ma ke</w>': 300,
 'sel f</w>': 301,
 'on ly</w>': 302,
 'a h</w>': 303,
 's h</w>': 304,
 'h u': 305,
 'l u': 306,
 'cou ld</w>': 307,
 'y ing</w>': 308,
 'some thing</w>': 309,
 'than k</w>': 310,
 'o ver</w>': 311,
 'c e': 312,
 'ni ght</w>': 313,
 'bo dy</w>': 314,
 'fu l</w>': 315,
 'p le</w>': 316,
 'w on</w>': 317,
 'mu ch</w>': 318,
 'e p</w>': 319,
 'a m</w>': 320,
 '0 </w>': 321,
 'a ga': 322,
 'u se</w>': 323,
 'p lease</w>': 324,
 'co m': 325,
 'qu i': 326,
 's hou': 327,
 'b le</w>': 328,
 'ne w</w>': 329,
 'i r</w>': 330,
 'f o': 331,
 'be tter</w>': 332,
 'ev er': 333,
 'ever y': 334,
 'ye ah</w>': 335,
 'w o': 336,
 'no thing</w>': 337,
 'f ri': 338,
 'men t</w>': 339,
 'c </w>': 340,
 'l s</w>': 341,
 'any thing</w>': 342,
 'of f</w>': 343,
 'a way</w>': 344,
 't wo</w>': 345,
 'r s</w>': 346,
 'me an</w>': 347,
 'o ld</w>': 348,
 'lo ve</w>': 349,
 'd u': 350,
 'hel lo</w>': 351,
 'lon g</w>': 352,
 's pe': 353,
 'b </w>': 354,
 'e l</w>': 355,
 'mi ss</w>': 356,
 'be fore</w>': 357,
 'ro o': 358,
 'sa id</w>': 359,
 'aga in</w>': 360,
 "' </w>": 361,
 'fin d</w>': 362,
 'c hi': 363,
 'v en</w>': 364,
 'shou ld</w>': 365,
 'p la': 366,
 'i sn</w>': 367,
 'fa ther</w>': 368,
 'ar d</w>': 369,
 'fi r': 370,
 'sor ry</w>': 371,
 'hel p</w>': 372,
 'fri en': 373,
 'wa ys</w>': 374,
 'm ber</w>': 375,
 'af ter</w>': 376,
 'ca use</w>': 377,
 're e</w>': 378,
 'thou ght</w>': 379,
 'c han': 380,
 'pu t</w>': 381,
 'ho me</w>': 382,
 't ra': 383,
 'ma y': 384,
 's ho': 385,
 'o ple</w>': 386,
 'fir st</w>': 387,
 'pe ople</w>': 388,
 'gi r': 389,
 'min d</w>': 390,
 'thin gs</w>': 391,
 'e l': 392,
 'al ways</w>': 393,
 'tho se</w>': 394,
 'c t</w>': 395,
 'may be</w>': 396,
 'ke ep</w>': 397,
 'tal k</w>': 398,
 'in to</w>': 399,
 'j e': 400,
 'gon na</w>': 401,
 'm rs</w>': 402,
 'wa it</w>': 403,
 'a in</w>': 404,
 't ry</w>': 405,
 'be cause</w>': 406,
 'v es</w>': 407,
 'm s</w>': 408,
 'lea ve</w>': 409,
 's si': 410,
 't ri': 411,
 'the se</w>': 412,
 'o ther</w>': 413,
 'de ar</w>': 414,
 't ch</w>': 415,
 'li fe</w>': 416,
 'aroun d</w>': 417,
 'cour se</w>': 418,
 'a u': 419,
 'mone y</w>': 420,
 't ur': 421,
 'wou ldn</w>': 422,
 'i m': 423,
 'a d': 424,
 'min u': 425,
 'mor ning</w>': 426,
 'un der': 427,
 'on s</w>': 428,
 'c k': 429,
 'real ly</w>': 430,
 'p ri': 431,
 'wor k</w>': 432,
 'na me</w>': 433,
 'ni ce</w>': 434,
 'ma tter</w>': 435,
 'roo m</w>': 436,
 'c he': 437,
 'every thing</w>': 438,
 'mi ght</w>': 439,
 'o k</w>': 440,
 'n y</w>': 441,
 'ha ven</w>': 442,
 'sti ll</w>': 443,
 'j u': 444,
 'c har': 445,
 'su p': 446,
 ': </w>': 447,
 'enou gh</w>': 448,
 'gir l</w>': 449,
 'f t</w>': 450,
 'v ed</w>': 451,
 'x </w>': 452,
 'c lo': 453,
 'c tor</w>': 454,
 'do ing</w>': 455,
 'do es</w>': 456,
 're me': 457,
 'he ad</w>': 458,
 'than ks</w>': 459,
 'ca me</w>': 460,
 'he y</w>': 461,
 'ne ed</w>': 462,
 'sta y</w>': 463,
 'rou gh</w>': 464,
 't ru': 465,
 'se e': 466,
 't u': 467,
 'sto p</w>': 468,
 'mo st</w>': 469,
 'p y</w>': 470,
 'bo y</w>': 471,
 't le': 472,
 'ra id</w>': 473,
 'b a': 474,
 'reme mber</w>': 475,
 'ye ars</w>': 476,
 'as k</w>': 477,
 'm y': 478,
 'he ar</w>': 479,
 'th rough</w>': 480,
 'your self</w>': 481,
 'af raid</w>': 482,
 't ly</w>': 483,
 'do e': 484,
 'doe sn</w>': 485,
 's c': 486,
 'under stand</w>': 487,
 'v er': 488,
 'the ir</w>': 489,
 'k a': 490,
 'bi g</w>': 491,
 'gu e': 492,
 'si de</w>': 493,
 'beli eve</w>': 494,
 'g reat</w>': 495,
 'le ft</w>': 496,
 'fe el</w>': 497,
 'r ying</w>': 498,
 's hall</w>': 499,
 '0 0</w>': 500,
 'i l</w>': 501,
 'kin d</w>': 502,
 'p t</w>': 503,
 'cou ldn</w>': 504,
 'ri ed</w>': 505,
 'p s</w>': 506,
 'sup po': 507,
 'g ra': 508,
 'gen tle': 509,
 'lo t</w>': 510,
 'wo man</w>': 511,
 's hi': 512,
 'ow n</w>': 513,
 'th ree</w>': 514,
 'frien d</w>': 515,
 'ron g</w>': 516,
 'c h': 517,
 'l ly</w>': 518,
 'f ran': 519,
 'd rin': 520,
 'i de': 521,
 'fo o': 522,
 'dar ling</w>': 523,
 'li sten</w>': 524,
 'do ctor</w>': 525,
 'wan ted</w>': 526,
 'qu e': 527,
 'my self</w>': 528,
 'bu sine': 529,
 'l li': 530,
 'on ce</w>': 531,
 'minu te</w>': 532,
 'he ard</w>': 533,
 'el se</w>': 534,
 'wa i': 535,
 'po li': 536,
 'wor ld</w>': 537,
 'we e': 538,
 'busine ss</w>': 539,
 'mor row</w>': 540,
 'o d': 541,
 'su ch</w>': 542,
 'be au': 543,
 'to morrow</w>': 544,
 'pre tty</w>': 545,
 'd r</w>': 546,
 'le y</w>': 547,
 't rou': 548,
 'ho pe</w>': 549,
 'b rea': 550,
 'wi fe</w>': 551,
 'a p': 552,
 'qui te</w>': 553,
 'hap py</w>': 554,
 'youn g</w>': 555,
 'whi le</w>': 556,
 'ge tting</w>': 557,
 'de ad</w>': 558,
 'b ring</w>': 559,
 'k new</w>': 560,
 'sa me</w>': 561,
 'sa w</w>': 562,
 's le': 563,
 'wi thout</w>': 564,
 'l t</w>': 565,
 'gue ss</w>': 566,
 'wi sh</w>': 567,
 'li ve</w>': 568,
 'be ing</w>': 569,
 'f f</w>': 570,
 's pi': 571,
 'ide a</w>': 572,
 'ti ons</w>': 573,
 'd re': 574,
 'loo king</w>': 575,
 'w rong</w>': 576,
 'suppo se</w>': 577,
 'hap pened</w>': 578,
 'bo ys</w>': 579,
 'di e</w>': 580,
 'a k</w>': 581,
 'l led</w>': 582,
 'of fi': 583,
 'b ye</w>': 584,
 'an s</w>': 585,
 'jo h': 586,
 'tur n</w>': 587,
 're st</w>': 588,
 'so on</w>': 589,
 'wen t</w>': 590,
 'di f': 591,
 'foun d</w>': 592,
 'drin k</w>': 593,
 'ar t</w>': 594,
 'fo l': 595,
 'c y</w>': 596,
 'gu y</w>': 597,
 'da ys</w>': 598,
 'trou ble</w>': 599,
 'sen t</w>': 600,
 'nex t</w>': 601,
 'ne ss</w>': 602,
 'g re': 603,
 'be st</w>': 604,
 'u h</w>': 605,
 'un til</w>': 606,
 'gentle men</w>': 607,
 'fe w</w>': 608,
 'sin ce</w>': 609,
 'mar ried</w>': 610,
 'g lad</w>': 611,
 'jo b</w>': 612,
 'w ri': 613,
 'ka y</w>': 614,
 'who le</w>': 615,
 'go od': 616,
 't rying</w>': 617,
 'tal king</w>': 618,
 'e ar': 619,
 'ta in': 620,
 'v e': 621,
 'wai ting</w>': 622,
 'd ri': 623,
 'z e</w>': 624,
 'le ss</w>': 625,
 'for get</w>': 626,
 'per haps</w>': 627,
 'la te</w>': 628,
 'n u': 629,
 'beau ti': 630,
 'cap tain</w>': 631,
 'sa ys</w>': 632,
 's y</w>': 633,
 'to ge': 634,
 'ki ll</w>': 635,
 'toge ther</w>': 636,
 'wor d</w>': 637,
 'b ri': 638,
 'v o': 639,
 'li e</w>': 640,
 'whi ch</w>': 641,
 'o kay</w>': 642,
 'pla y</w>': 643,
 'c ra': 644,
 'me et</w>': 645,
 'd ge</w>': 646,
 'o pen</w>': 647,
 'si g': 648,
 'hu s': 649,
 'u sed</w>': 650,
 'a th</w>': 651,
 'sen d</w>': 652,
 'wan ts</w>': 653,
 'a go</w>': 654,
 'some body</w>': 655,
 'poli ce</w>': 656,
 'beauti ful</w>': 657,
 'pa y</w>': 658,
 'ex pe': 659,
 'e i': 660,
 'to ok</w>': 661,
 'wor ry</w>': 662,
 'ki lled</w>': 663,
 'wa ter</w>': 664,
 'b ro': 665,
 'do or</w>': 666,
 'hus band</w>': 667,
 'shi p</w>': 668,
 'in t</w>': 669,
 'z y</w>': 670,
 'chan ce</w>': 671,
 'm p': 672,
 'no body</w>': 673,
 '5 </w>': 674,
 'po or</w>': 675,
 'an t</w>': 676,
 'hur ry</w>': 677,
 'ti ve</w>': 678,
 'frien ds</w>': 679,
 's sed</w>': 680,
 'dif feren': 681,
 'k now': 682,
 'i l': 683,
 'la ter</w>': 684,
 'spe ak</w>': 685,
 'f re': 686,
 'j a': 687,
 'sle ep</w>': 688,
 'bo th</w>': 689,
 'won der': 690,
 'han ds</w>': 691,
 's po': 692,
 'st re': 693,
 'some one</w>': 694,
 'fi ve</w>': 695,
 'ou t': 696,
 'ck y</w>': 697,
 'ex cuse</w>': 698,
 'a ge</w>': 699,
 'coun try</w>': 700,
 'every body</w>': 701,
 'e asy</w>': 702,
 'wonder ful</w>': 703,
 'de ath</w>': 704,
 'o t</w>': 705,
 'e m</w>': 706,
 'pro mi': 707,
 'gh ter</w>': 708,
 'mo ment</w>': 709,
 'c tion</w>': 710,
 'aga in': 711,
 'li ght</w>': 712,
 'again st</w>': 713,
 'ne w': 714,
 'ho l': 715,
 'loo ks</w>': 716,
 'y a</w>': 717,
 'hal f</w>': 718,
 'thin king</w>': 719,
 'ga ve</w>': 720,
 'an s': 721,
 'know s</w>': 722,
 'ra ther</w>': 723,
 'wa tch</w>': 724,
 'e yes</w>': 725,
 'ge or': 726,
 'any body</w>': 727,
 'lo st</w>': 728,
 'hur t</w>': 729,
 'ou ght</w>': 730,
 'cer tain': 731,
 's hed</w>': 732,
 'he a': 733,
 'fi ght</w>': 734,
 'ro ss</w>': 735,
 'si e': 736,
 'any one</w>': 737,
 'certain ly</w>': 738,
 'ch ri': 739,
 'a w': 740,
 'c le</w>': 741,
 'p ped</w>': 742,
 'good bye</w>': 743,
 'd ro': 744,
 'e ach</w>': 745,
 'o b': 746,
 'ter ri': 747,
 'e f</w>': 748,
 'hap pen</w>': 749,
 'en d</w>': 750,
 'tru e</w>': 751,
 'mar ry</w>': 752,
 'p hone</w>': 753,
 'c re': 754,
 'in tere': 755,
 'chan ge</w>': 756,
 'o l</w>': 757,
 'e at</w>': 758,
 'd ly</w>': 759,
 'd le</w>': 760,
 "' em</w>": 761,
 'any way</w>': 762,
 'a head</w>': 763,
 'si ster</w>': 764,
 'a meri': 765,
 'ma kes</w>': 766,
 'pi c': 767,
 'see ms</w>': 768,
 'ta king</w>': 769,
 's hu': 770,
 'offi ce</w>': 771,
 'minu tes</w>': 772,
 '2 </w>': 773,
 'b ra': 774,
 'en g': 775,
 '1 </w>': 776,
 'din ner</w>': 777,
 'v a': 778,
 'wo men</w>': 779,
 'fun ny</w>': 780,
 'i rs</w>': 781,
 'sie ur</w>': 782,
 'th y</w>': 783,
 'mon sieur</w>': 784,
 'go es</w>': 785,
 'ssi on</w>': 786,
 'al ready</w>': 787,
 'cra zy</w>': 788,
 'as ked</w>': 789,
 'geor ge</w>': 790,
 'ha ving</w>': 791,
 'impor tant</w>': 792,
 'qui et</w>': 793,
 'ne e': 794,
 'fel low</w>': 795,
 'go tta</w>': 796,
 'jo e</w>': 797,
 'lu ck</w>': 798,
 'gh ts</w>': 799,
 'ci ty</w>': 800,
 'z </w>': 801,
 'mo ve</w>': 802,
 'p len': 803,
 'i ce</w>': 804,
 't ment</w>': 805,
 '1 0</w>': 806,
 'chil dren</w>': 807,
 'af ter': 808,
 'bu y</w>': 809,
 'cu t</w>': 810,
 'wal k</w>': 811,
 'sen se</w>': 812,
 'di s': 813,
 'cen t</w>': 814,
 'sor t</w>': 815,
 'dau ghter</w>': 816,
 'ge ts</w>': 817,
 'ans wer</w>': 818,
 'wee k</w>': 819,
 'bo at</w>': 820,
 'no on</w>': 821,
 'th s</w>': 822,
 'joh n': 823,
 's y': 824,
 'me ans</w>': 825,
 'gran d': 826,
 'te st</w>': 827,
 'c ted</w>': 828,
 'ce pt</w>': 829,
 'ti red</w>': 830,
 'ha te</w>': 831,
 'lor d</w>': 832,
 'lea ving</w>': 833,
 'co l': 834,
 'dan ce</w>': 835,
 'ke y</w>': 836,
 'al most</w>': 837,
 'u p': 838,
 'me di': 839,
 'hor se</w>': 840,
 's sor</w>': 841,
 'en ce</w>': 842,
 'fa mily</w>': 843,
 'i ts</w>': 844,
 'ssi ble</w>': 845,
 'c lu': 846,
 'fu lly</w>': 847,
 'shou ldn</w>': 848,
 'e d': 849,
 'probab ly</w>': 850,
 'shu t</w>': 851,
 'bi r': 852,
 'him self</w>': 853,
 'be t': 854,
 'ex ac': 855,
 's h': 856,
 'le tter</w>': 857,
 'm my</w>': 858,
 'profe ssor</w>': 859,
 'wan na</w>': 860,
 'ma king</w>': 861,
 'exac tly</w>': 862,
 'ei ther</w>': 863,
 'c la': 864,
 '0 00</w>': 865,
 'thou gh</w>': 866,
 'clo se</w>': 867,
 'mada me</w>': 868,
 'ho tel</w>': 869,
 'fu ll</w>': 870,
 'dre ss</w>': 871,
 'par ty</w>': 872,
 'lo vely</w>': 873,
 'coun t</w>': 874,
 'wa t': 875,
 'un cle</w>': 876,
 'to m</w>': 877,
 'do g</w>': 878,
 'in di': 879,
 'spe ci': 880,
 'n s</w>': 881,
 'after noon</w>': 882,
 'tru th</w>': 883,
 'b la': 884,
 'si x</w>': 885,
 'nu mber</w>': 886,
 'hone y</w>': 887,
 'mur der</w>': 888,
 'pi e': 889,
 'y or': 890,
 'g le</w>': 891,
 'k y</w>': 892,
 'or der</w>': 893,
 'par don</w>': 894,
 'b li': 895,
 'sta irs</w>': 896,
 'roun d</w>': 897,
 'sa ying</w>': 898,
 'sa ve</w>': 899,
 'wri te</w>': 900,
 'l y': 901,
 'sur pri': 902,
 'so l': 903,
 'se con': 904,
 'yor k</w>': 905,
 'per fe': 906,
 'expe ct</w>': 907,
 'ta ken</w>': 908,
 'al right</w>': 909,
 'mon ths</w>': 910,
 'bo ok</w>': 911,
 'john ny</w>': 912,
 'e h</w>': 913,
 'bo o': 914,
 'bet ween</w>': 915,
 'por t</w>': 916,
 'bo ss</w>': 917,
 'differen t</w>': 918,
 'j im</w>': 919,
 'g ry</w>': 920,
 'm m</w>': 921,
 'wor th</w>': 922,
 'b lood</w>': 923,
 'qui ck</w>': 924,
 'c lear</w>': 925,
 'si ck</w>': 926,
 'mu si': 927,
 'hin d</w>': 928,
 'ro ad</w>': 929,
 'wor king</w>': 930,
 'di ed</w>': 931,
 'ni e</w>': 932,
 'ti c</w>': 933,
 'fran k</w>': 934,
 'i se</w>': 935,
 'out side</w>': 936,
 'b ly</w>': 937,
 'ti es</w>': 938,
 'be hind</w>': 939,
 'plen ty</w>': 940,
 'po int</w>': 941,
 'vi si': 942,
 'any more</w>': 943,
 'ca tch</w>': 944,
 'hi gh</w>': 945,
 'li ving</w>': 946,
 'char les</w>': 947,
 '3 </w>': 948,
 'some times</w>': 949,
 'en t</w>': 950,
 'o thers</w>': 951,
 'sho ot</w>': 952,
 'gir ls</w>': 953,
 'i r': 954,
 'po si': 955,
 'for give</w>': 956,
 'fron t</w>': 957,
 'new s</w>': 958,
 'stre et</w>': 959,
 '4 </w>': 960,
 'care ful</w>': 961,
 'al so</w>': 962,
 'clo thes</w>': 963,
 'lo se</w>': 964,
 'li sh</w>': 965,
 'gentle man</w>': 966,
 'e g': 967,
 'm c': 968,
 'hen ry</w>': 969,
 'que stion</w>': 970,
 '8 </w>': 971,
 's weet</w>': 972,
 'de al</w>': 973,
 'fa ir</w>': 974,
 'lon ger</w>': 975,
 'run ning</w>': 976,
 'pre sent</w>': 977,
 'star ted</w>': 978,
 'stran ge</w>': 979,
 'i s': 980,
 'secon d</w>': 981,
 'do c</w>': 982,
 'men ts</w>': 983,
 'ni ck</w>': 984,
 'whi te</w>': 985,
 'sel ves</w>': 986,
 'scho ol</w>': 987,
 'do l': 988,
 'g ge': 989,
 'stu ff</w>': 990,
 'pic ture</w>': 991,
 'go ver': 992,
 'stra i': 993,
 'o ver': 994,
 'gu ys</w>': 995,
 'e u': 996,
 'v y</w>': 997,
 'wor ds</w>': 998,
 's mi': 999,
 ...}

In [333]:
def encode_word(word, vocab):
    word_str = ' '.join(word)
    sub_key = lambda x: re.sub('\s+', '', x)
    for key in vocab.keys():
        pat = ' ' + key + ' '
        if pat in word_str:
            print(key)
            print(word_str, '\n')
            word_str = word_str.replace(key, sub_key(key))
            # print(key)
            # print(word_str, '\n')
    return word_str

In [336]:
encode_word(char_factor(' running '), tokenizer_eng.vocab)

n
  r u n n i n g   </w>

g
  r u n n i n g   </w>

r
  r u n n i n g   </w>

u
  r u n n i n g   </w>

i
  r u n n i n g   </w>

i n
  r u n n i n g   </w>

u n
  r u n n in g   </w>

'  r un n in g   </w>'

In [269]:
test_snt = "Yesterday I visited zoo with my family, it was super fun!"
test_snt_split = tokenize_eng(test_snt)
print(test_snt_split)

['yesterday', 'i', 'visited', 'zoo', 'with', 'my', 'family', ',', 'it', 'was', 'super', 'fun', '!']

In [270]:
[[x for x in word] + ['</w>'] for word in test_snt_split]

[['y', 'e', 's', 't', 'e', 'r', 'd', 'a', 'y', '</w>'],
 ['i', '</w>'],
 ['v', 'i', 's', 'i', 't', 'e', 'd', '</w>'],
 ['z', 'o', 'o', '</w>'],
 ['w', 'i', 't', 'h', '</w>'],
 ['m', 'y', '</w>'],
 ['f', 'a', 'm', 'i', 'l', 'y', '</w>'],
 [',', '</w>'],
 ['i', 't', '</w>'],
 ['w', 'a', 's', '</w>'],
 ['s', 'u', 'p', 'e', 'r', '</w>'],
 ['f', 'u', 'n', '</w>'],
 ['!', '</w>']]

In [135]:
def connect_pairs(vocab_chars, pair):
    vocab_proc = vocab_chars.copy()
    pair_con = re.sub('\s+', '', pair)
    for i, (toks, _) in enumerate(vocab_proc):
        toks = " ".join(toks).replace(pair, pair_con).split()
        vocab_proc[i][0] = toks
    return vocab_proc

In [221]:
def most_common_pair(vocab_chars):
    pair_counts = Counter()
    for toks, freq in vocab_chars:
        for pair in map(' '.join, zip(toks, toks[1:])):
            pair_counts[pair] += freq
    return pair_counts.most_common(1)[0][0]

In [226]:
vocab_chars_eng

[[['.', '</w>'], 435802],
 [[',', '</w>'], 177291],
 [['y', 'o', 'u', '</w>'], 134548],
 [['i', '</w>'], 122767],
 [['t', 'h', 'e', '</w>'], 89859],
 [['?', '</w>'], 84640],
 [['t', 'o', '</w>'], 73192],
 [['a', '</w>'], 61661],
 [["'", 's', '</w>'], 57045],
 [['i', 't', '</w>'], 55074],
 [["'", 't', '</w>'], 50411],
 [['t', 'h', 'a', 't', '</w>'], 43020],
 [['a', 'n', 'd', '</w>'], 41124],
 [['o', 'f', '</w>'], 39514],
 [['i', 'n', '</w>'], 32142],
 [['!', '</w>'], 30794],
 [['m', 'e', '</w>'], 29977],
 [['w', 'h', 'a', 't', '</w>'], 26868],
 [['i', 's', '</w>'], 26378],
 [['h', 'e', '</w>'], 26149],
 [['f', 'o', 'r', '</w>'], 23935],
 [['w', 'e', '</w>'], 23370],
 [['t', 'h', 'i', 's', '</w>'], 20366],
 [['y', 'o', 'u', 'r', '</w>'], 20158],
 [['b', 'e', '</w>'], 20137],
 [['m', 'y', '</w>'], 20105],
 [["'", 'l', 'l', '</w>'], 20011],
 [['h', 'a', 'v', 'e', '</w>'], 19830],
 [['d', 'o', 'n', '</w>'], 18888],
 [['d', 'o', '</w>'], 18663],
 [['o', 'n', '</w>'], 18052],
 [['n', 'o', '</w>'], 17694],
 [["'", 'm', '</w>'], 16935],
 [['a', 'l', 'l', '</w>'], 16776],
 [['b', 'u', 't', '</w>'], 16067],
 [['w', 'a', 's', '</w>'], 15781],
 [["'", 'r', 'e', '</w>'], 15483],
 [['w', 'i', 't', 'h', '</w>'], 15435],
 [['c', 'a', 'n', '</w>'], 15365],
 [['h', 'e', 'r', 'e', '</w>'], 15059],
 [['n', 'o', 't', '</w>'], 14896],
 [['a', 'r', 'e', '</w>'], 14431],
 [['k', 'n', 'o', 'w', '</w>'], 14310],
 [['t', 'h', 'e', 'r', 'e', '</w>'], 14310],
 [['h', 'i', 'm', '</w>'], 14193],
 [['g', 'e', 't', '</w>'], 13469],
 [['i', 'f', '</w>'], 12400],
 [['w', 'e', 'l', 'l', '</w>'], 12155],
 [['t', 'h', 'e', 'y', '</w>'], 11807],
 [['n', 'o', 'w', '</w>'], 11736],
 [["'", 'v', 'e', '</w>'], 11579],
 [['l', 'i', 'k', 'e', '</w>'], 11372],
 [['y', 'e', 's', '</w>'], 10842],
 [['o', 'u', 't', '</w>'], 10839],
 [['s', 'h', 'e', '</w>'], 10741],
 [['c', 'o', 'm', 'e', '</w>'], 10653],
 [['g', 'o', '</w>'], 10570],
 [['r', 'i', 'g', 'h', 't', '</w>'], 10414],
 [['s', 'o', '</w>'], 10352],
 [['a', 'b', 'o', 'u', 't', '</w>'], 10349],
 [['a', 't', '</w>'], 10100],
 [['u', 'p', '</w>'], 9851],
 [['o', 'h', '</w>'], 9750],
 [['w', 'i', 'l', 'l', '</w>'], 9685],
 [['j', 'u', 's', 't', '</w>'], 9650],
 [['s', 'e', 'e', '</w>'], 9619],
 [['g', 'o', 'o', 'd', '</w>'], 9404],
 [['h', 'e', 'r', '</w>'], 9170],
 [['a', 's', '</w>'], 9044],
 [['"', '</w>'], 8870],
 [['o', 'n', 'e', '</w>'], 8831],
 [['g', 'o', 't', '</w>'], 8827],
 [['h', 'o', 'w', '</w>'], 8698],
 [["'", 'd', '</w>'], 7878],
 [['-', '</w>'], 7821],
 [['w', 'a', 'n', 't', '</w>'], 7783],
 [['t', 'h', 'i', 'n', 'k', '</w>'], 7743],
 [['w', 'h', 'y', '</w>'], 7726],
 [['h', 'i', 's', '</w>'], 7396],
 [['m', 'r', '</w>'], 7390],
 [['g', 'o', 'i', 'n', 'g', '</w>'], 7023],
 [['d', 'i', 'd', '</w>'], 6784],
 [['t', 'a', 'k', 'e', '</w>'], 6657],
 [['t', 'h', 'e', 'm', '</w>'], 6612],
 [['b', 'e', 'e', 'n', '</w>'], 6579],
 [['w', 'h', 'e', 'n', '</w>'], 6444],
 [['f', 'r', 'o', 'm', '</w>'], 6437],
 [['l', 'e', 't', '</w>'], 6379],
 [['t', 'e', 'l', 'l', '</w>'], 6330],
 [['w', 'h', 'o', '</w>'], 6283],
 [['w', 'h', 'e', 'r', 'e', '</w>'], 6175],
 [['s', 'a', 'y', '</w>'], 6142],
 [['v', 'e', 'r', 'y', '</w>'], 5833],
 [['b', 'a', 'c', 'k', '</w>'], 5736],
 [['m', 'a', 'n', '</w>'], 5539],
 [['t', 'i', 'm', 'e', '</w>'], 5538],
 [['l', 'o', 'o', 'k', '</w>'], 5465],
 [['a', 'n', '</w>'], 5437],
 [['h', 'a', 'd', '</w>'], 5395],
 [['t', 'o', 'o', '</w>'], 5297],
 [['u', 's', '</w>'], 5228],
 [['w', 'o', 'u', 'l', 'd', '</w>'], 5165],
 [['n', 'e', 'v', 'e', 'r', '</w>'], 5037],
 [['d', 'i', 'd', 'n', '</w>'], 4959],
 [['w', 'e', 'r', 'e', '</w>'], 4912],
 [['s', 'i', 'r', '</w>'], 4907],
 [['l', 'i', 't', 't', 'l', 'e', '</w>'], 4764],
 [['w', 'a', 'y', '</w>'], 4572],
 [['o', 'r', '</w>'], 4571],
 [['t', 'h', 'e', 'n', '</w>'], 4556],
 [['s', 'o', 'm', 'e', '</w>'], 4544],
 [['d', 'o', 'w', 'n', '</w>'], 4510],
 [['m', 'u', 's', 't', '</w>'], 4353],
 [['a', 'n', 'y', '</w>'], 4343],
 [['m', 'a', 'k', 'e', '</w>'], 4312],
 [['o', 'n', 'l', 'y', '</w>'], 4213],
 [['c', 'o', 'u', 'l', 'd', '</w>'], 4125],
 [['m', 'o', 'r', 'e', '</w>'], 4078],
 [['b', 'y', '</w>'], 4064],
 [['h', 'a', 's', '</w>'], 4035],
 [['s', 'o', 'm', 'e', 't', 'h', 'i', 'n', 'g', '</w>'], 4018],
 [['t', 'h', 'a', 'n', 'k', '</w>'], 3991],
 [['o', 'u', 'r', '</w>'], 3987],
 [['o', 'v', 'e', 'r', '</w>'], 3933],
 [['g', 'i', 'v', 'e', '</w>'], 3923],
 [['w', 'o', 'n', '</w>'], 3826],
 [['m', 'u', 'c', 'h', '</w>'], 3806],
 [['s', 'u', 'r', 'e', '</w>'], 3682],
 [['p', 'l', 'e', 'a', 's', 'e', '</w>'], 3634],
 [['n', 'i', 'g', 'h', 't', '</w>'], 3541],
 [['b', 'e', 't', 't', 'e', 'r', '</w>'], 3447],
 [['y', 'e', 'a', 'h', '</w>'], 3404],
 [['n', 'o', 't', 'h', 'i', 'n', 'g', '</w>'], 3379],
 [['a', 'n', 'y', 't', 'h', 'i', 'n', 'g', '</w>'], 3219],
 [['a', 'w', 'a', 'y', '</w>'], 3136],
 [['t', 'w', 'o', '</w>'], 3114],
 [['m', 'e', 'a', 'n', '</w>'], 3060],
 [['o', 'l', 'd', '</w>'], 3053],
 [['o', 'f', 'f', '</w>'], 3035],
 [['l', 'o', 'v', 'e', '</w>'], 3028],
 [['h', 'e', 'l', 'l', 'o', '</w>'], 3018],
 [['a', 'm', '</w>'], 2934],
 [['m', 'i', 's', 's', '</w>'], 2929],
 [['b', 'e', 'f', 'o', 'r', 'e', '</w>'], 2916],
 [['s', 'a', 'i', 'd', '</w>'], 2882],
 [['a', 'g', 'a', 'i', 'n', '</w>'], 2882],
 [['f', 'i', 'n', 'd', '</w>'], 2839],
 [['s', 'h', 'o', 'u', 'l', 'd', '</w>'], 2800],
 [['l', 'o', 'n', 'g', '</w>'], 2767],
 [['i', 's', 'n', '</w>'], 2738],
 [['t', 'h', 'i', 'n', 'g', '</w>'], 2720],
 [['s', 'o', 'r', 'r', 'y', '</w>'], 2676],
 [['h', 'e', 'l', 'p', '</w>'], 2667],
 [['a', 'f', 't', 'e', 'r', '</w>'], 2623],
 [['t', 'h', 'o', 'u', 'g', 'h', 't', '</w>'], 2600],
 [['p', 'u', 't', '</w>'], 2573],
 [['h', 'o', 'm', 'e', '</w>'], 2550],
 [['t', 'h', 'a', 'n', '</w>'], 2528],
 [['e', 'v', 'e', 'r', '</w>'], 2525],
 [['f', 'i', 'r', 's', 't', '</w>'], 2521],
 [['p', 'e', 'o', 'p', 'l', 'e', '</w>'], 2514],
 [['f', 'a', 't', 'h', 'e', 'r', '</w>'], 2502],
 [['t', 'h', 'i', 'n', 'g', 's', '</w>'], 2447],
 [['a', 'l', 'w', 'a', 'y', 's', '</w>'], 2424],
 [['t', 'h', 'o', 's', 'e', '</w>'], 2422],
 [['m', 'a', 'y', 'b', 'e', '</w>'], 2417],
 [['d', 'a', 'y', '</w>'], 2410],
 [['k', 'e', 'e', 'p', '</w>'], 2393],
 [['t', 'a', 'l', 'k', '</w>'], 2389],
 [['i', 'n', 't', 'o', '</w>'], 2380],
 [['g', 'o', 'n', 'n', 'a', '</w>'], 2372],
 [['m', 'r', 's', '</w>'], 2366],
 [['t', 'o', 'l', 'd', '</w>'], 2360],
 [['w', 'a', 'i', 't', '</w>'], 2348],
 [['m', 'i', 'n', 'd', '</w>'], 2339],
 [['a', 'i', 'n', '</w>'], 2336],
 [['b', 'e', 'c', 'a', 'u', 's', 'e', '</w>'], 2327],
 [['l', 'a', 's', 't', '</w>'], 2314],
 [['m', 'a', 'y', '</w>'], 2299],
 [['l', 'e', 'a', 'v', 'e', '</w>'], 2297],
 [['t', 'h', 'e', 's', 'e', '</w>'], 2289],
 [['o', 't', 'h', 'e', 'r', '</w>'], 2277],
 [['d', 'e', 'a', 'r', '</w>'], 2255],
 [['a', 'r', 'o', 'u', 'n', 'd', '</w>'], 2245],
 [['l', 'i', 'f', 'e', '</w>'], 2245],
 [['e', 'v', 'e', 'n', '</w>'], 2242],
 [['c', 'o', 'u', 'r', 's', 'e', '</w>'], 2213],
 [['m', 'o', 'n', 'e', 'y', '</w>'], 2207],
 [['w', 'o', 'u', 'l', 'd', 'n', '</w>'], 2160],
 [['n', 'e', 'w', '</w>'], 2154],
 [['m', 'o', 'r', 'n', 'i', 'n', 'g', '</w>'], 2147],
 [['r', 'e', 'a', 'l', 'l', 'y', '</w>'], 2098],
 [['n', 'a', 'm', 'e', '</w>'], 2067],
 [['n', 'i', 'c', 'e', '</w>'], 2061],
 [['m', 'a', 't', 't', 'e', 'r', '</w>'], 2051],
 [['e', 'v', 'e', 'r', 'y', 't', 'h', 'i', 'n', 'g', '</w>'], 2034],
 [['m', 'i', 'g', 'h', 't', '</w>'], 2030],
 [['w', 'o', 'r', 'k', '</w>'], 2029],
 [['h', 'a', 'v', 'e', 'n', '</w>'], 2015],
 [['s', 't', 'i', 'l', 'l', '</w>'], 2010],
 [[':', '</w>'], 1991],
 [['e', 'n', 'o', 'u', 'g', 'h', '</w>'], 1989],
 [['p', 'l', 'a', 'c', 'e', '</w>'], 1966],
 [['g', 'i', 'r', 'l', '</w>'], 1956],
 [['m', 'e', 'n', '</w>'], 1953],
 [['d', 'o', 'i', 'n', 'g', '</w>'], 1934],
 [['d', 'o', 'e', 's', '</w>'], 1933],
 [['c', 'a', 'l', 'l', '</w>'], 1911],
 [['t', 'h', 'a', 'n', 'k', 's', '</w>'], 1896],
 [['h', 'e', 'y', '</w>'], 1882],
 [['n', 'e', 'e', 'd', '</w>'], 1876],
 [['s', 't', 'a', 'y', '</w>'], 1861],
 [['s', 't', 'o', 'p', '</w>'], 1823],
 [['h', 'o', 'u', 's', 'e', '</w>'], 1787],
 [['c', 'a', 'm', 'e', '</w>'], 1777],
 [['r', 'e', 'm', 'e', 'm', 'b', 'e', 'r', '</w>'], 1771],
 [['y', 'e', 'a', 'r', 's', '</w>'], 1757],
 [['a', 's', 'k', '</w>'], 1757],
 [['a', 'n', 'o', 't', 'h', 'e', 'r', '</w>'], 1757],
 [['r', 'o', 'o', 'm', '</w>'], 1751],
 [['h', 'e', 'a', 'r', '</w>'], 1737],
 [['y', 'o', 'u', 'r', 's', 'e', 'l', 'f', '</w>'], 1734],
 [['t', 'h', 'r', 'o', 'u', 'g', 'h', '</w>'], 1734],
 [['b', 'o', 'y', '</w>'], 1733],
 [['a', 'f', 'r', 'a', 'i', 'd', '</w>'], 1721],
 [['d', 'o', 'e', 's', 'n', '</w>'], 1714],
 [['u', 'n', 'd', 'e', 'r', 's', 't', 'a', 'n', 'd', '</w>'], 1690],
 [['m', 'a', 'd', 'e', '</w>'], 1681],
 [['d', 'o', 'n', 'e', '</w>'], 1673],
 [['t', 'h', 'e', 'i', 'r', '</w>'], 1670],
 [['b', 'i', 'g', '</w>'], 1668],
 [['c', 'o', 'm', 'i', 'n', 'g', '</w>'], 1659],
 [['b', 'e', 'l', 'i', 'e', 'v', 'e', '</w>'], 1656],
 [['g', 'r', 'e', 'a', 't', '</w>'], 1653],
 [['m', 'o', 't', 'h', 'e', 'r', '</w>'], 1653],
 [['l', 'e', 'f', 't', '</w>'], 1651],
 [['f', 'e', 'e', 'l', '</w>'], 1647],
 [['t', 'o', 'n', 'i', 'g', 'h', 't', '</w>'], 1646],
 [['e', 'v', 'e', 'r', 'y', '</w>'], 1620],
 [['c', 'o', 'u', 'l', 'd', 'n', '</w>'], 1609],
 [['s', 'h', 'a', 'l', 'l', '</w>'], 1607],
 [['b', 'a', 'd', '</w>'], 1605],
 [['k', 'i', 'n', 'd', '</w>'], 1582],
 [['o', 'w', 'n', '</w>'], 1565],
 [['t', 'h', 'r', 'e', 'e', '</w>'], 1553],
 [['w', 'o', 'm', 'a', 'n', '</w>'], 1527],
 [['c', 'a', 'r', 'e', '</w>'], 1511],
 [['d', 'a', 'r', 'l', 'i', 'n', 'g', '</w>'], 1498],
 [['l', 'i', 's', 't', 'e', 'n', '</w>'], 1496],
 [['d', 'o', 'c', 't', 'o', 'r', '</w>'], 1493],
 [['w', 'a', 'n', 't', 'e', 'd', '</w>'], 1492],
 [['m', 'y', 's', 'e', 'l', 'f', '</w>'], 1484],
 [['f', 'r', 'i', 'e', 'n', 'd', '</w>'], 1474],
 [['l', 'o', 't', '</w>'], 1456],
 [['s', 'e', 'e', 'n', '</w>'], 1455],
 [['o', 'n', 'c', 'e', '</w>'], 1446],
 [['m', 'i', 'n', 'u', 't', 'e', '</w>'], 1438],
 [['e', 'l', 's', 'e', '</w>'], 1430],
 [['w', 'o', 'r', 'l', 'd', '</w>'], 1412],
 [['b', 'u', 's', 'i', 'n', 'e', 's', 's', '</w>'], 1411],
 [['h', 'e', 'a', 'r', 'd', '</w>'], 1410],
 [['s', 'u', 'c', 'h', '</w>'], 1395],
 [['f', 'i', 'n', 'e', '</w>'], 1394],
 [['t', 'o', 'm', 'o', 'r', 'r', 'o', 'w', '</w>'], 1389],
 [['p', 'r', 'e', 't', 't', 'y', '</w>'], 1388],
 [['d', 'r', '</w>'], 1385],
 [['s', 'i', 't', '</w>'], 1383],
 [['s', 'h', 'o', 'w', '</w>'], 1372],
 [['l', 'a', 'd', 'y', '</w>'], 1363],
 [['w', 'i', 'f', 'e', '</w>'], 1361],
 [['t', 'r', 'y', '</w>'], 1354],
 [['a', 'l', 'o', 'n', 'e', '</w>'], 1343],
 [['q', 'u', 'i', 't', 'e', '</w>'], 1341],
 [['h', 'o', 'p', 'e', '</w>'], 1335],
 [['y', 'o', 'u', 'n', 'g', '</w>'], 1328],
 [['b', 'r', 'i', 'n', 'g', '</w>'], 1313],
 [['d', 'e', 'a', 'd', '</w>'], 1312],
 [['w', 'a', 's', 'n', '</w>'], 1303],
 [['k', 'n', 'e', 'w', '</w>'], 1299],
 [['y', 'e', 't', '</w>'], 1295],
 [['w', 'i', 't', 'h', 'o', 'u', 't', '</w>'], 1287],
 [['g', 'u', 'e', 's', 's', '</w>'], 1284],
 [['s', 'a', 'm', 'e', '</w>'], 1282],
 [['b', 'e', 'i', 'n', 'g', '</w>'], 1270],
 [['g', 'e', 't', 't', 'i', 'n', 'g', '</w>'], 1264],
 [['i', 'd', 'e', 'a', '</w>'], 1260],
 [['l', 'i', 'v', 'e', '</w>'], 1252],
 [['l', 'o', 'o', 'k', 'i', 'n', 'g', '</w>'], 1236],
 [['w', 'r', 'o', 'n', 'g', '</w>'], 1236],
 [['s', 'u', 'p', 'p', 'o', 's', 'e', '</w>'], 1234],
 [['w', 'i', 's', 'h', '</w>'], 1231],
 [['h', 'a', 'p', 'p', 'e', 'n', 'e', 'd', '</w>'], 1229],
 [['w', 'h', 'i', 'l', 'e', '</w>'], 1227],
 [['h', 'a', 'p', 'p', 'y', '</w>'], 1224],
 [['s', 'a', 'w', '</w>'], 1218],
 [['b', 'o', 'y', 's', '</w>'], 1213],
 [['a', 'l', 'o', 'n', 'g', '</w>'], 1201],
 [['m', 'o', 's', 't', '</w>'], 1192],
 [['w', 'e', 'n', 't', '</w>'], 1188],
 [['s', 'o', 'o', 'n', '</w>'], 1187],
 [['d', 'r', 'i', 'n', 'k', '</w>'], 1172],
 [['f', 'o', 'u', 'n', 'd', '</w>'], 1165],
 [['g', 'u', 'y', '</w>'], 1156],
 [['t', 'r', 'o', 'u', 'b', 'l', 'e', '</w>'], 1153],
 [['n', 'e', 'x', 't', '</w>'], 1141],
 [['g', 'o', 'n', 'e', '</w>'], 1138],
 [['b', 'e', 's', 't', '</w>'], 1125],
 [['u', 'h', '</w>'], 1121],
 [['u', 'n', 't', 'i', 'l', '</w>'], 1115],
 [['g', 'e', 'n', 't', 'l', 'e', 'm', 'e', 'n', '</w>'], 1115],
 [['t', 'o', 'w', 'n', '</w>'], 1112],
 [['h', 'e', 'a', 'd', '</w>'], 1109],
 [['d', 'a', 'y', 's', '</w>'], 1107],
 [['s', 'i', 'n', 'c', 'e', '</w>'], 1104],
 [['f', 'e', 'w', '</w>'], 1104],
 [['g', 'l', 'a', 'd', '</w>'], 1102],
 [['t', 'o', 'd', 'a', 'y', '</w>'], 1097],
 [['j', 'o', 'b', '</w>'], 1096],
 [['m', 'a', 'n', 'y', '</w>'], 1095],
 [['m', 'a', 'r', 'r', 'i', 'e', 'd', '</w>'], 1092],
 [['r', 'e', 'a', 'd', 'y', '</w>'], 1087],
 [['w', 'h', 'o', 'l', 'e', '</w>'], 1083],
 [['t', 'r', 'y', 'i', 'n', 'g', '</w>'], 1077],
 [['h', 'o', 'l', 'd', '</w>'], 1076],
 [['t', 'a', 'l', 'k', 'i', 'n', 'g', '</w>'], 1070],
 [['r', 'u', 'n', '</w>'], 1068],
 [['f', 'o', 'r', 'g', 'e', 't', '</w>'], 1041],
 [['p', 'e', 'r', 'h', 'a', 'p', 's', '</w>'], 1038],
 [['h', 'a', 'n', 'd', '</w>'], 1033],
 [['w', 'a', 'i', 't', 'i', 'n', 'g', '</w>'], 1030],
 [['u', 's', 'e', '</w>'], 1029],
 [['s', 't', 'a', 'n', 'd', '</w>'], 1023],
 [['c', 'a', 'p', 't', 'a', 'i', 'n', '</w>'], 1019],
 [['s', 'a', 'y', 's', '</w>'], 1018],
 [['m', 'i', 'n', 'e', '</w>'], 1016],
 [['k', 'i', 'l', 'l', '</w>'], 996],
 [['w', 'h', 'i', 'c', 'h', '</w>'], 994],
 [['o', 'k', 'a', 'y', '</w>'], 993],
 [['m', 'e', 'e', 't', '</w>'], 992],
 [['e', 'v', 'e', 'n', 'i', 'n', 'g', '</w>'], 984],
 [['o', 'p', 'e', 'n', '</w>'], 981],
 [['u', 's', 'e', 'd', '</w>'], 973],
 [['t', 'o', 'g', 'e', 't', 'h', 'e', 'r', '</w>'], 968],
 [['h', 'u', 'h', '</w>'], 967],
 [['w', 'a', 'n', 't', 's', '</w>'], 963],
 [['p', 'l', 'a', 'y', '</w>'], 961],
 [['a', 'g', 'o', '</w>'], 957],
 [['s', 'o', 'm', 'e', 'b', 'o', 'd', 'y', '</w>'], 956],
 [['p', 'o', 'l', 'i', 'c', 'e', '</w>'], 954],
 [['b', 'e', 'a', 'u', 't', 'i', 'f', 'u', 'l', '</w>'], 952],
 [['c', 'a', 's', 'e', '</w>'], 944],
 [['s', 'e', 'n', 'd', '</w>'], 944],
 [['a', 'r', 'e', 'n', '</w>'], 943],
 [['w', 'o', 'r', 'r', 'y', '</w>'], 927],
 [['h', 'u', 's', 'b', 'a', 'n', 'd', '</w>'], 924],
 [['t', 'o', 'o', 'k', '</w>'], 924],
 [['k', 'i', 'l', 'l', 'e', 'd', '</w>'], 921],
 [['p', 'a', 'y', '</w>'], 918],
 [['c', 'h', 'a', 'n', 'c', 'e', '</w>'], 918],
 [['d', 'o', 'o', 'r', '</w>'], 913],
 [['n', 'o', 'b', 'o', 'd', 'y', '</w>'], 906],
 [['p', 'o', 'o', 'r', '</w>'], 903],
 [['h', 'u', 'r', 'r', 'y', '</w>'], 898],
 [['w', 'a', 't', 'e', 'r', '</w>'], 896],
 [['u', 'n', 'd', 'e', 'r', '</w>'], 892],
 [['s', 'o', 'n', '</w>'], 890],
 [['f', 'r', 'i', 'e', 'n', 'd', 's', '</w>'], 883],
 [['l', 'a', 't', 'e', 'r', '</w>'], 879],
 [['t', 'u', 'r', 'n', '</w>'], 875],
 [['w', 'o', 'r', 'd', '</w>'], 871],
 [['s', 'p', 'e', 'a', 'k', '</w>'], 869],
 [['s', 'l', 'e', 'e', 'p', '</w>'], 861],
 [['s', 't', 'a', 'r', 't', '</w>'], 860],
 [['b', 'o', 't', 'h', '</w>'], 858],
 [['l', 'a', 't', 'e', '</w>'], 855],
 [['s', 'o', 'm', 'e', 'o', 'n', 'e', '</w>'], 853],
 [['h', 'a', 'n', 'd', 's', '</w>'], 852],
 [['f', 'i', 'v', 'e', '</w>'], 852],
 [['y', 'o', 'u', 'r', 's', '</w>'], 844],
 [['f', 'a', 'c', 'e', '</w>'], 835],
 [['h', 'e', 'a', 'r', 't', '</w>'], 835],
 [['e', 'x', 'c', 'u', 's', 'e', '</w>'], 835],
 [['c', 'o', 'u', 'n', 't', 'r', 'y', '</w>'], 830],
 [['e', 'v', 'e', 'r', 'y', 'b', 'o', 'd', 'y', '</w>'], 830],
 [['e', 'a', 's', 'y', '</w>'], 829],
 [['w', 'o', 'n', 'd', 'e', 'r', 'f', 'u', 'l', '</w>'], 829],
 [['f', 'a', 'r', '</w>'], 826],
 [['d', 'e', 'a', 't', 'h', '</w>'], 822],
 [['r', 'e', 's', 't', '</w>'], 819],
 [['m', 'o', 'm', 'e', 'n', 't', '</w>'], 811],
 [['b', 'a', 'b', 'y', '</w>'], 809],
 [['c', 'a', 'r', '</w>'], 807],
 [['a', 'g', 'a', 'i', 'n', 's', 't', '</w>'], 807],
 [['l', 'o', 'o', 'k', 's', '</w>'], 803],
 [['c', 'o', 'm', 'e', 's', '</w>'], 803],
 [['t', 'h', 'i', 'n', 'k', 'i', 'n', 'g', '</w>'], 800],
 [['w', 'a', 'r', '</w>'], 795],
 [['k', 'n', 'o', 'w', 's', '</w>'], 793],
 [['r', 'a', 't', 'h', 'e', 'r', '</w>'], 791],
 [['g', 'a', 'v', 'e', '</w>'], 790],
 [['h', 'a', 'r', 'd', '</w>'], 788],
 [['e', 'y', 'e', 's', '</w>'], 788],
 [['a', 'n', 'y', 'b', 'o', 'd', 'y', '</w>'], 787],
 [['r', 'e', 'a', 'd', '</w>'], 787],
 [['l', 'o', 's', 't', '</w>'], 783],
 [['w', 'a', 't', 'c', 'h', '</w>'], 782],
 [['h', 'u', 'r', 't', '</w>'], 780],
 [['b', 'r', 'o', 't', 'h', 'e', 'r', '</w>'], 777],
 [['o', 'u', 'g', 'h', 't', '</w>'], 775],
 [['b', 'e', 'd', '</w>'], 774],
 [['a', 'n', 'y', 'o', 'n', 'e', '</w>'], 765],
 [['c', 'e', 'r', 't', 'a', 'i', 'n', 'l', 'y', '</w>'], 765],
 [['f', 'i', 'g', 'h', 't', '</w>'], 763],
 [['b', 'i', 't', '</w>'], 763],
 [['g', 'o', 'd', '</w>'], 760],
 [['c', 'h', 'i', 'l', 'd', '</w>'], 759],
 [['h', 'a', 'l', 'f', '</w>'], 755],
 [['k', 'i', 'd', '</w>'], 755],
 [['g', 'o', 'o', 'd', 'b', 'y', 'e', '</w>'], 752],
 [['e', 'a', 'c', 'h', '</w>'], 751],
 [['t', 'i', 'l', 'l', '</w>'], 750],
 [['h', 'a', 'p', 'p', 'e', 'n', '</w>'], 743],
 [['y', 'e', 'a', 'r', '</w>'], 737],
 [['m', 'a', 'r', 'r', 'y', '</w>'], 734],
 [['t', 'r', 'u', 'e', '</w>'], 733],
 [['e', 'a', 't', '</w>'], 726],
 [["'", 'e', 'm', '</w>'], 718],
 [['d', 'i', 'e', '</w>'], 717],
 [['a', 'n', 'y', 'w', 'a', 'y', '</w>'], 717],
 [['a', 'h', 'e', 'a', 'd', '</w>'], 717],
 [['s', 'i', 's', 't', 'e', 'r', '</w>'], 715],
 [['m', 'a', 'k', 'e', 's', '</w>'], 713],
 [['g', 'u', 'n', '</w>'], 712],
 [['b', 'r', 'o', 'u', 'g', 'h', 't', '</w>'], 706],
 [['s', 'e', 'e', 'm', 's', '</w>'], 705],
 [['e', 'n', 'd', '</w>'], 700],
 [['o', 'f', 'f', 'i', 'c', 'e', '</w>'], 700],
 [['m', 'i', 'n', 'u', 't', 'e', 's', '</w>'], 700],
 [['l', '</w>'], 699],
 [['f', 'o', 'u', 'r', '</w>'], 695],
 [['t', 'a', 'k', 'i', 'n', 'g', '</w>'], 692],
 [['d', 'i', 'n', 'n', 'e', 'r', '</w>'], 691],
 [['t', 'r', 'a', 'i', 'n', '</w>'], 690],
 [['m', 'a', '</w>'], 688],
 [['w', 'o', 'm', 'e', 'n', '</w>'], 687],
 [['f', 'u', 'n', 'n', 'y', '</w>'], 685],
 [['f', 'i', 'r', 'e', '</w>'], 685],
 [['m', 'o', 'n', 's', 'i', 'e', 'u', 'r', '</w>'], 683],
 [['f', 'o', 'o', 'l', '</w>'], 681],
 [['c', 'h', 'a', 'n', 'g', 'e', '</w>'], 681],
 [['g', 'o', 'e', 's', '</w>'], 679],
 [['a', 'l', 'r', 'e', 'a', 'd', 'y', '</w>'], 678],
 [['c', 'r', 'a', 'z', 'y', '</w>'], 676],
 [['a', 's', 'k', 'e', 'd', '</w>'], 672],
 [['g', 'e', 'o', 'r', 'g', 'e', '</w>'], 670],
 [['i', 'm', 'p', 'o', 'r', 't', 'a', 'n', 't', '</w>'], 668],
 [['q', 'u', 'i', 'e', 't', '</w>'], 667],
 [['g', 'o', 't', 't', 'a', '</w>'], 662],
 [['f', 'e', 'l', 'l', 'o', 'w', '</w>'], 660],
 [['j', 'o', 'e', '</w>'], 660],
 [['b', 'e', 't', '</w>'], 659],
 [['c', 'a', 'l', 'l', 'e', 'd', '</w>'], 645],
 [['l', 'u', 'c', 'k', '</w>'], 642],
 [["'", '</w>'], 642],
 [['s', 't', 'o', 'r', 'y', '</w>'], 641],
 [['b', 'r', 'e', 'a', 'k', '</w>'], 637],
 [['h', 'o', 'u', 'r', '</w>'], 636],
 [['b', 'u', 'y', '</w>'], 635],
 [['h', 'a', 'v', 'i', 'n', 'g', '</w>'], 633],
 [['l', 'a', 'w', '</w>'], 631],
 [['o', '</w>'], 629],
 [['s', 'e', 'n', 't', '</w>'], 629],
 [['c', 'h', 'i', 'l', 'd', 'r', 'e', 'n', '</w>'], 627],
 [['m', 'e', 't', '</w>'], 626],
 [['1', '0', '</w>'], 626],
 [['s', 'h', 'o', 't', '</w>'], 626],
 [['a', 'n', 's', 'w', 'e', 'r', '</w>'], 624],
 [['w', 'e', 'e', 'k', '</w>'], 622],
 [['s', 'o', 'r', 't', '</w>'], 621],
 [['w', 'a', 'l', 'k', '</w>'], 619],
 [['k', 'i', 'n', 'g', '</w>'], 618],
 [['m', 'e', 'a', 'n', 's', '</w>'], 617],
 [['r', 'e', 'a', 'l', '</w>'], 615],
 [['t', 'r', 'i', 'e', 'd', '</w>'], 609],
 [['h', 'a', 't', 'e', '</w>'], 603],
 [['g', 'e', 't', 's', '</w>'], 600],
 [['l', 'e', 'a', 'v', 'i', 'n', 'g', '</w>'], 600],
 [['d', 'a', 'u', 'g', 'h', 't', 'e', 'r', '</w>'], 598],
 [['b', 'i', 'l', 'l', '</w>'], 598],
 [['t', 'i', 'm', 'e', 's', '</w>'], 597],

In [102]:
def most_common_pair(vocab_chars):
    freq_pair = defaultdict(int)
    for toks, freq in vocab_chars:
        toks_pairs = [" ".join(pair) for pair in zip(toks, toks[1:])]
        for pair in toks_pairs:
            freq_pair[pair] += freq
    return max(freq_pair.items(), key=lambda x: x[1])[0]

In [190]:
pair_counts = Counter()
pair_counts[('t','h')] += 10
pair_counts[('t','h')] += 10
pair_counts.most_common(1)

[(('t', 'h'), 20)]

In [394]:
vocab_chars_eng2 = [[char_factor(k), v] for k, v in uniq_freq_eng.most_common()]
tokenizer_eng_test = BPETokenizer(vocab_chars_eng2, 100, False)
t = time.time()
tokenizer_eng_test.train_bpe()
print(f"{time.time()-t:.2f} seconds")

4.49 seconds